PROMPT Starting Alter_Add_Location_Type_Columns.sql

-- Execute as inventory owner
-- Add container and plate location type columns

alter table INV_COMPOUNDS add (
	LOCATION_TYPE_ID_FK number(4,0),
	 CONSTRAINT "INV_COMP_LOC_TYPES_FK" 
		FOREIGN KEY("LOCATION_TYPE_ID_FK") 
		REFERENCES "INV_LOCATION_TYPES"("LOCATION_TYPE_ID") 
);
ALTER TABLE INV_CONTAINERS ADD (LOCATION_TYPE_ID_FK NUMBER(4));

ALTER TABLE INV_CONTAINERS ADD CONSTRAINT INV_CONTAINERS_LOC_TYPE_FK
  FOREIGN KEY (LOCATION_TYPE_ID_FK)
  REFERENCES INV_LOCATION_TYPES(LOCATION_TYPE_ID);

ALTER TABLE INV_PLATES ADD (LOCATION_TYPE_ID_FK NUMBER(4));

ALTER TABLE INV_PLATES ADD CONSTRAINT INV_PLATES_LOC_TYPE_FK
  FOREIGN KEY (LOCATION_TYPE_ID_FK)
  REFERENCES INV_LOCATION_TYPES(LOCATION_TYPE_ID);
