alter table INV_COMPOUNDS add (
	LOCATION_TYPE_ID_FK number(4,0),
	 CONSTRAINT "INV_COMP_LOC_TYPES_FK" 
		FOREIGN KEY("LOCATION_TYPE_ID_FK") 
		REFERENCES "INV_LOCATION_TYPES"("LOCATION_TYPE_ID") 
);
