DEFINE SCHEMANAME = CHEMINVDB2
@f_UpdateNonnullContainerFields.sql
GRANT EXECUTE ON CHEMINVDB2.UpdateNonnullContainerFields TO INV_CHEMIST;
GRANT EXECUTE ON CHEMINVDB2.UpdateNonnullContainerFields TO INV_FINANCE;
GRANT EXECUTE ON CHEMINVDB2.UpdateNonnullContainerFields TO INV_RECEIVING;
GRANT EXECUTE ON CHEMINVDB2.UpdateNonnullContainerFields TO INV_ADMIN;
GRANT EXECUTE ON CHEMINVDB2.UpdateNonnullContainerFields TO COEDB WITH GRANT OPTION;
GRANT EXECUTE ON CHEMINVDB2.UpdateNonnullContainerFields TO INV_ADMIN;
