CREATE TABLE "INV_GRAPHICS"(
	"GRAPHIC_ID" NUMBER NOT NULL,
	"GRAPHIC_NAME" VARCHAR2(50),
	"GRAPHIC_TYPE_ID_FK" NUMBER(4),
	"GRAPHIC_WIDTH" NUMBER(4),
	"GRAPHIC_HEIGHT" NUMBER(4),
	"GRAPHIC_ALT" VARCHAR2(50),
	"URL_ACTIVE" VARCHAR(100),
	"URL_INACTIVE" VARCHAR(100),
    CONSTRAINT "INV_GRAPHIC_PK"
		PRIMARY KEY("GRAPHIC_ID") USING INDEX TABLESPACE &&indexTableSpaceName,
	CONSTRAINT "INV_GRAPHIC_TYPE_ID_FK" 
		FOREIGN KEY ("GRAPHIC_TYPE_ID_FK")
		REFERENCES "INV_GRAPHIC_TYPES" ("GRAPHIC_TYPE_ID")
	);
	
CREATE SEQUENCE SEQ_INV_GRAPHICS INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER "TRG_INV_GRAPHICS_ID"
    BEFORE INSERT
    ON "INV_GRAPHICS"
    FOR EACH ROW
BEGIN
	if :new.graphic_id is null then
		select SEQ_INV_GRAPHICS.nextval into :new.graphic_id from dual;
	end if;
END;
/
	