--Copyright 1999-2003 CambridgeSoft Corporation. All rights reserved

-- This file provides the mapping between CS_SECURITY Privileges and Oracle
-- Object Privileges.  

-- CSS_LOGIN PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_LOGIN', 'EXECUTE', 'CS_SECURITY', 'LOGIN');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_LOGIN', 'EXECUTE', 'CS_SECURITY', 'MANAGE_ROLES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_LOGIN', 'EXECUTE', 'CS_SECURITY', 'MANAGE_USERS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_LOGIN', 'SELECT', 'CS_SECURITY', 'PEOPLE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_LOGIN', 'SELECT', 'CS_SECURITY', 'PRIVILEGE_TABLES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_LOGIN', 'SELECT', 'CS_SECURITY', 'SITES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_LOGIN', 'SELECT', 'CS_SECURITY', 'SECURITY_ROLES');

-- CSS_CREATE_USER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_CREATE_USER', 'EXECUTE', 'CS_SECURITY', 'CREATEUSER');

-- CSS_EDIT_USER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_EDIT_USER', 'EXECUTE', 'CS_SECURITY', 'UPDATEUSER');

-- CSS_DELETE_USER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_DELETE_USER', 'EXECUTE', 'CS_SECURITY', 'DELETEUSER');

-- CSS_CREATE_ROLE PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_CREATE_ROLE', 'EXECUTE', 'CS_SECURITY', 'CREATEROLE');

-- CSS_EDIT_ROLE PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_EDIT_ROLE', 'EXECUTE', 'CS_SECURITY', 'UPDATEROLE');

-- CSS_DELETE_ROLE PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_DELETE_ROLE', 'EXECUTE', 'CS_SECURITY', 'DELETEROLE');

-- CSS_CHANGE_PASSWORD PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('CSS_CHANGE_PASSWORD', 'EXECUTE', 'CS_SECURITY', 'CHANGEPWD');


-- CSS_CREATE_WORKGRP PRIVS

-- CSS_UPDATE_WORKGRP PRIVS

-- CSS_DELETE_WORKGRP PRIVS

