--Copyright 1999-2003 CambridgeSoft Corporation. All rights reserved


CREATE TABLE PEOPLE (
	PERSON_ID NUMBER(8,0) not null,
	USER_CODE VARCHAR2(50) null,
	USER_ID VARCHAR2(50) null,
	SUPERVISOR_INTERNAL_ID NUMBER(8,0) null,
	TITLE VARCHAR2(50) null,	
	FIRST_NAME VARCHAR2(50) null,
	MIDDLE_NAME VARCHAR2(50) null,
	LAST_NAME VARCHAR2(50) null,
	SITE_ID NUMBER(8,0) null,
	DEPARTMENT VARCHAR2(50) null,	
	INT_ADDRESS VARCHAR2(50) null,	
	TELEPHONE VARCHAR2(50) null,
	EMAIL VARCHAR2(50) null,
	ACTIVE NUMBER(1,0) null, 
	"RID" NUMBER(10) NOT NULL, 
	"CREATOR" VARCHAR2(30) DEFAULT RTRIM(user) NOT NULL, 
	"TIMESTAMP" DATE DEFAULT sysdate NOT NULL,   
	CONSTRAINT PEOPLE_PK 
		primary key (PERSON_ID)USING INDEX TABLESPACE &&indexTableSpaceName,
	CONSTRAINT PEOPLE_USER_CODE_UK 
		UNIQUE (USER_CODE) USING INDEX TABLESPACE &&indexTableSpaceName
	)
;


CREATE TABLE SITES (
	SITE_ID NUMBER(8,0) not null,
	SITE_CODE VARCHAR2(50) null,
	SITE_NAME VARCHAR2(250) null,
	ACTIVE NUMBER(1,0) null,
	CONSTRAINT SITES_PK primary key (SITE_ID) USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

CREATE TABLE PRIVILEGE_TABLES (
	PRIVILEGE_TABLE_ID NUMBER(8,0) not null,
	PRIVILEGE_TABLE_NAME VARCHAR2(50) not null,
	APP_NAME VARCHAR2(50) not null,
	APP_URL VARCHAR2(250) null,
	TABLE_SPACE VARCHAR2(100) not null, 
	CONSTRAINT PRIVILEGE_TABLE_PK 
		primary key (PRIVILEGE_TABLE_ID) USING INDEX TABLESPACE &&indexTableSpaceName 
	) 
;

CREATE TABLE SECURITY_ROLES (
	ROLE_ID NUMBER(8,0) not null,
	PRIVILEGE_TABLE_INT_ID NUMBER(8,0) null,
	ROLE_NAME VARCHAR2(120) null, 
	"RID" NUMBER(10) NOT NULL, 
	"CREATOR" VARCHAR2(30) DEFAULT RTRIM(user) NOT NULL, 
	"TIMESTAMP" DATE DEFAULT sysdate NOT NULL,   
	CONSTRAINT SECURITY_ROLES_PK 
		primary key (ROLE_ID) USING INDEX TABLESPACE &&indexTableSpaceName,
	CONSTRAINT SECURITYROLES_PRIVILEGETABLES 
		foreign key (PRIVILEGE_TABLE_INT_ID)
		REFERENCES PRIVILEGE_TABLES (PRIVILEGE_TABLE_ID)	  
	) 
;



--#########################################################
--CREATE SEQUENCES AND TRIGGERS
--#########################################################

CREATE SEQUENCE SITES_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE PEOPLE_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SECURITY_ROLES_SEQ INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE PRIVILEGE_TABLES_seq INCREMENT BY 1 START WITH 1;


CREATE TRIGGER SITES_TRIG
BEFORE INSERT ON SITES
FOR EACH ROW
BEGIN
SELECT SITES_SEQ.NEXTVAL
INTO :NEW.SITE_ID
FROM DUAL;
END;
/

CREATE TRIGGER CS_SECURITY.PEOPLE_TRIG BEFORE
INSERT ON CS_SECURITY.PEOPLE 
FOR EACH ROW WHEN (NEW.PERSON_ID IS NULL) 
BEGIN
SELECT PEOPLE_SEQ.NEXTVAL INTO :NEW.PERSON_ID FROM DUAL;
END;
/

CREATE TRIGGER SECURITY_ROLES_TRIG
BEFORE INSERT ON SECURITY_ROLES
FOR EACH ROW
BEGIN
SELECT SECURITY_ROLES_SEQ.NEXTVAL
INTO :NEW.ROLE_ID
FROM DUAL;
END;
/

CREATE TRIGGER PRIVILEGE_TABLES_TRIG
BEFORE INSERT ON PRIVILEGE_TABLES
FOR EACH ROW
BEGIN
SELECT PRIVILEGE_TABLES_SEQ.NEXTVAL
INTO :NEW.PRIVILEGE_TABLE_ID
FROM DUAL;
END;
/

--#########################################################
--CREATE INDICES
--#########################################################

CREATE INDEX PRIVILEGE_TABLE_INT_ID 
	ON SECURITY_ROLES (PRIVILEGE_TABLE_INT_ID ASC) TABLESPACE &&indexTableSpaceName
; 

CREATE INDEX DBMS_ID ON 
	PEOPLE (USER_ID ASC) TABLESPACE &&indexTableSpaceName
; 

CREATE INDEX LAST_NAME ON 
	PEOPLE (LAST_NAME ASC) TABLESPACE &&indexTableSpaceName
; 

CREATE INDEX SUPERVISOR_INTERNAL_ID 
	ON PEOPLE (SUPERVISOR_INTERNAL_ID ASC) TABLESPACE &&indexTableSpaceName
; 


commit;



