<%@ LANGUAGE="VBScript" %>
<%'Copyright 1998-2001 CambridgeSoft Corporation All Rights Reserved
'DO NOT EDIT THIS FILE%>
<html>
<head>
<!--#INCLUDE VIRTUAL = "/cfserverasp/source/cows_func_vbs.asp" -->
<!--#INCLUDE VIRTUAL = "/cfserverasp/source/upload.asp"-->
<!--#INCLUDE VIRTUAL = "/biosar_browser/reports/reports_app_js.js"-->
<!--#INCLUDE VIRTUAL = "/biosar_browser/reports/ReportUtils.asp"-->



<script language = "javascript">
var readFile =  ""
function dosubmit(){
if (document.formx.browsefile.value.length > 0){
	
	document.formx.submit()
	}else{
		alert("please enter a full path before clicking the Load File button.")
	}
}



</script>

<%Dim fieldname
Function SaveUploadAsFile(Fields)
	dim Field
	For Each Field In Fields.Items
		If Field.FileName <> "" Then 'This field is uploaded file. Save the file in temp directory
			fileName = Field.FileName
			
			fullfilename = Application("ReportLogoPath") & fileName 
			
			Field.Value.SaveAs fullfilename
			
		End If
	Next
	SaveUploadAsFile=fileName
End Function

'after the submit button is click the this will be picked up and run. It gets the file name and reads the lines
'each line is added to a variable to create a comma delimeted string


If Request.ServerVariables("REQUEST_METHOD") = "POST" Then

	'filename = request.form("browsefile")
	
	Dim Upload
	Set Upload = GetUpload() 'function in upload.asp
	
	filename = SaveUploadAsFile(Upload)
	if filename <> "" then
		Getbiosar_browserSettingsConnection
		Set RS = Server.CreateObject("adodb.recordset")
		Set RS2 = Server.CreateObject("adodb.recordset")
		Set Cmd = Server.CreateObject("ADODB.COMMAND")
		Cmd.ActiveConnection = RptConn
		Cmd.CommandType=adCmdText
		sql = "select * from  RptSettingLkup where value = '" & filename & "'"
		Cmd.CommandText = sql
		RS2.Open cmd
		if Not (RS2.EOF and RS2.BOF) then
			bUsed = true
			RS2.Close
		else
			bUsed = false
		end if
		
		if bUsed = true then%>
		<script language = "javascript">
			alert("Logo already exists.")
		</script>
		<% else
			if not (instr(UCase(filename), ".GIF")>0 or instr(UCase(filename), ".JPG")>0 or instr(UCase(filename), ".PNG")>0) then%>
			<script language = "javascript">
				alert("File must be *.gif, *.jpg or *.png")
			</script><%
		
			else
				RS.Open "RptSettingLkup", RptConn, adOpenKeyset,  adLockOptimistic, adCmdTable 
				
				RS.AddNew
				RS("Lkup_name")="RptLogo"
				
				RS("Description")=filename
				RS("Value") = filename
				RS.Update
				RS.Close%>
				<script language = "javascript">
					doClose()
				</script><%
			end if
		end if%>
		
		
	<%
	else
		response.Write "file failed to upload"
	end if
	%>
	
	
<%end if%>
</head>
<BODY >


<form name = "formx" action="upload_logos.asp" method="post"  ENCTYPE="multipart/form-data">
Enter a file path or click browse to select a logo file in *.png, *.gif or *.jpg format. Click Add Logo to complete addition.
<table border = "1"><tr>
			<td><input type="file" name="browsefile" size = "30"><input type="button" value="Add Logo" onClick="dosubmit()" ></td>
			<input type="hidden" value="dbname" value = "<%=dbkey%>" ID="Text1" NAME="Text1">
			
			</td></tr></table>
</form>



<%Function detectIE6()
	IEBrowser = false

	UserAgent = Request.ServerVariables("HTTP_USER_AGENT")
			'response.write UserAgent

		If InStr(UCASE(UserAgent), "MSIE")>0 then
			If InStr(UCASE(UserAgent), "6.")>0 then
				IEBrowser = true
			end if
		end if
		'IEBrowser = false
	detectIE6 = IEBrowser
End Function

Function detectNetscape()
	Netscape = false

	UserAgent = Request.ServerVariables("HTTP_USER_AGENT")

		If NOT InStr(UCASE(UserAgent), "MSIE")>0 then
			Netscape = true
		end if
		
	detectNetscape = Netscape
End Function

Function ReadFile(filename)
   Const ForReading = 1, ForWriting = 2
   Dim fso, MyFile
   Set fso = CreateObject("Scripting.FileSystemObject")
   Set MyFile = fso.OpenTextFile(filename, ForReading, True)
   Do While MyFile.AtEndOfStream <> True
   currentLine = myFile.ReadLine
		if finalRead <> "" then
			finalRead = finalRead & "," & Trim(currentLine)
		else
			finalRead = Trim(currentLine)
		end if
	loop
	
	finalRead = replace(finalRead, ",,", ",")
	finalRead = replace(finalRead, " ", "")
	rightmost_char = Right(finalRead,1)
	if rightmost_char = "," then
		string_len = Len(finalRead)
		finalRead = Mid(finalRead,1,string_len-1)
	end if
	ReadFile =finalRead

End Function
%>
</body>
</html>