CREATE TABLE "INV_LPR_DEFINITION"(
	"LPR_DEFINITION_ID" NUMBER(9) NOT NULL,
	"HEADER_FILENAME" VARCHAR2(200) NULL,
	"LABEL_FILENAME" VARCHAR2(200) NOT NULL,
	"FOOTER_FILENAME" VARCHAR2(200) NULL,
	CONSTRAINT "INV_LPR_DEFINITION_PK"
		PRIMARY KEY("LPR_DEFINITION_ID") USING INDEX TABLESPACE &&indexTableSpaceName	
);

CREATE SEQUENCE SEQ_INV_LPR_DEFINITION_VALUES INCREMENT BY 1 START WITH 1000 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE;

CREATE OR REPLACE TRIGGER "TRG_INV_LPR_DEFINITION_VALUES"
    BEFORE INSERT
    ON "INV_LPR_DEFINITION"
    FOR EACH ROW
    begin
        if :new.LPR_DEFINITION_ID is null then
            select SEQ_INV_LPR_DEFINITION_VALUES.nextval into :new.LPR_DEFINITION_ID from dual;
        end if;
    end;
/
