CREATE OR REPLACE VIEW CHEMINVDB2.VIEW_INV_CUSTOM_FIELDS
    ( CUSTOM_FIELD_ID,CUSTOM_FIELD_NAME,CUSTOM_FIELD_GROUP_ID_FK,READONLY )
  AS SELECT CUSTOM_FIELD_ID,CUSTOM_FIELD_NAME,CUSTOM_FIELD_GROUP_ID_FK,READONLY
  FROM CHEMINVDB2.INV_CUSTOM_FIELDS
  WHERE PICKLIST_TYPE_ID_FK = 1;

CREATE OR REPLACE TRIGGER CHEMINVDB2.TRG_VIEW_INV_CUSTOM_FIELDS
  INSTEAD OF INSERT ON CHEMINVDB2.VIEW_INV_CUSTOM_FIELDS
  FOR EACH ROW
  BEGIN
    INSERT INTO CHEMINVDB2.INV_CUSTOM_FIELDS
      (CUSTOM_FIELD_NAME,CUSTOM_FIELD_GROUP_ID_FK,READONLY,PICKLIST_TYPE_ID_FK,NULL_PICKLIST_ID_FK)
    VALUES (:new.CUSTOM_FIELD_NAME, :new.CUSTOM_FIELD_GROUP_ID_FK, :new.READONLY, 1, 1);
  END;
/
