CREATE TABLE TRANSACTION_RECORD
(
INTERNAL_SEQ_NUM NUMBER(10),
SEQUENCE_NUMBER number(10),
LOCATION_BARCODE VARCHAR2(50),
NDC VARCHAR2(15),
BDPP VARCHAR2(255),
PROTOCOL_ID VARCHAR2(255),
MRN VARCHAR2(2000),
PI  VARCHAR2(2000),
LOT_NUM VARCHAR2(50),
CONTAINER_ID NUMBER(9),
QTY NUMBER,
DOSE varchar2(200),
DISPENSING_PHARMACIST VARCHAR2(100),
TRANSACTION_TYPE VARCHAR2(10),
TRANSACTION_INPUT VARCHAR2(2000),
TRANSACTION_STATUS INTEGER DEFAULT 0,
TRANSACTION_DATE DATE DEFAULT SYSDATE,
ERROR VARCHAR2(200)
);
create sequence SEQ_TRANSACTION_RECORD INCREMENT BY 1 START WITH 1;

CREATE UNIQUE INDEX INTERNAL_SEQ_NUM_IDX ON TRANSACTION_RECORD(INTERNAL_SEQ_NUM) TABLESPACE &&indexTableSpaceName;