<%'Copyright 1999-2003 CambridgeSoft Corporation. All rights reserved

'DO NOT EDIT THIS FILE%>

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<html>

<head>

<title>Get Duplicate Record Action</title>
<%'SYAN modified on 11/29/2006 to fix CSBR-73397
'dbkey = Request.QueryString("dbname")
dbkey="reg"
'End of SYAN modification
%>
<script language="javascript">
//var totalrecords = ""
theOpener = opener
var okhelpstr = "submit record request"
var cancelhelpstr = "close window"
var buttonGifPath = theOpener.button_gif_path 
var okbutton = buttonGifPath + "ok.gif"
var cancelbutton = buttonGifPath + "Cancel.gif"
function getButtons() {
	outputval = ""

	outputval = '<A HREF = "javascript:getDuplicateAction();" onMouseOver="window.status=&quot;' + okhelpstr + '&quot;; return true;"><IMG SRC="' +  okbutton + '" BORDER="0"></A>'
	outputval = outputval + '<A HREF = "javascript:window.close();" onMouseOver="window.status=&quot;' + cancelhelpstr + '&quot;; return true;"><IMG SRC="' +  cancelbutton + '" BORDER="0"></A>'	

	document.write (outputval)
	}


function getDuplicateAction(){
	for (i=0;i<document.forms[0].elements.length;i++){
		if (document.forms[0].elements[i].checked){
			theOpener.document.cows_input_form.duplicate_processing.value=document.forms[0].elements[i].value
		}
	}
	theOpener.document.cows_input_form.temp_sort_by.value=document.forms[0].elements["TempTableSort"].options[document.forms[0].elements["TempTableSort"].selectedIndex].value
	theOpener.document.cows_input_form.temp_sort_by_direction.value=document.forms[0].elements["TempTableSortDirection"].options[document.forms[0].elements["TempTableSortDirection"].selectedIndex].value

	theOpener.doRegAllSubmit()
	window.close()
}

function buildTempTableSelectBox(){
	var thestring = "<%=Application("TempTableDisplayFields")%>"
		document.write ('<select name="TempTableSort" size = "0">')
		if(!thestring == ""){
			temp = thestring.split(";")
			for (i=0;i<temp.length;i++){
				theItems = temp[i].split(":")
				document.write ("<option value=" + theItems[1] + ">")
				document.write (theItems[0])
				document.write ("</option>")
			}
		}
		document.write ("</select>")
}

function buildTempTableSortSelectBox(){
	
		document.write ('<select name="TempTableSortDirection" size = "0">')
		document.write ("<option value=" + "ASC" + ">")
		document.write ("ASCENDING")
		document.write ("</option>")
		document.write ("<option value=" + "DESC" + ">")
		document.write ("DESCENDING")
		document.write ("</option>")
		document.write ("</select>")
}
</script>
</head>

<body>
<form>
  <script language="javascript">getButtons()</script>
<table border="0" width="100%">
    <tr>
      <td><small><strong><font face="Arial" size = "2">Please Select Duplicate Action</font></strong> </small></td>
</tr>    <tr>
<td><small><font face="Arial"> <input type="radio" name="DupAction" value=""  checked>Leave Duplicate In Temp Table</td></tr>

      <tr>
<td><small><font face="Arial"><input type="radio" name="DupAction" value="BATCH_COMMIT"  >Add New Batch To Registered Compound</td></tr>
           <%'SYAN modified on 11/29/2006 to fix CSBR-73397
           if CBool(Session("MANAGE_SYSTEM_DUPLICATES" & dbkey)) = true then%>
           <tr>
<td><small><font face="Arial"><input type="radio" name="DupAction" value="NEW_COMPOUND">Add New Compound</td></tr>
			<%end if
			'End of SYAN modification
			%>

        <tr>
      <td><small><strong><font face="Arial" size = "2">Sort Temp Table By:</font></strong> </small></td>
</tr><tr>
        <td><script language="javascript">buildTempTableSelectBox()</script></td><td><script language="javascript">buildTempTableSortSelectBox()</script></td><tr>
  </table>
</form>


</body>
</html>&nbsp;