CREATE TABLE CHEMINV_PRIVILEGES(
	ROLE_INTERNAL_ID NUMBER(8) NOT NULL, 
	INV_BROWSE_ALL NUMBER(1), 
	INV_CHANGEQTY_CONTAINER NUMBER(1),
  "INV_CHANGE_STATUS_CONTAINER" NUMBER(1),
	INV_CHECKOUT_CONTAINER NUMBER(1), 
	INV_CHECKIN_CONTAINER NUMBER(1), 
	INV_RESERVE_CONTAINER NUMBER(1), 
	INV_RETIRE_CONTAINER NUMBER(1), 
	INV_PRINT_LABEL_CONTAINER NUMBER(1), 
	INV_PRINT_REPORT NUMBER(1), 
	INV_CREATE_LOCATION NUMBER(1), 
	INV_EDIT_LOCATION NUMBER(1), 
	INV_MOVE_LOCATION NUMBER(1), 
	INV_DELETE_LOCATION NUMBER(1), 
	INV_CREATE_CONTAINER NUMBER(1), 
	INV_EDIT_CONTAINER NUMBER(1), 
	INV_MOVE_CONTAINER NUMBER(1), 
	INV_DELETE_CONTAINER NUMBER(1), 
	INV_MANAGE_LINKS NUMBER(1), 
	INV_MANAGE_SUBSTANCES NUMBER(1), 
	INV_VIEW_AUDIT_TRAIL NUMBER(1),
	INV_UPDATE_LOCATION_CONTENTS NUMBER(1), 
	INV_RECTIFY_LOCATION_CONTENTS NUMBER(1),
	INV_ORDER_CONTAINER NUMBER(1),
	INV_REORDER_CONTAINER NUMBER(1),
	"INV_CERTIFY_CONTAINER" NUMBER(1),
	"INV_APPROVE_CONTAINER" NUMBER(1),
	INV_EDIT_EHS_DATA NUMBER(1), 
	INV_CREATE_PLATE NUMBER(1),
	INV_MOVE_PLATE NUMBER(1),
	INV_EDIT_PLATE NUMBER(1),
	INV_RETIRE_PLATE NUMBER(1),
	INV_REQUEST_PLATE NUMBER(1),
	INV_DILUTE_PLATE NUMBER(1),
	INV_DELETE_PLATE NUMBER(1),
	INV_PRINT_LABEL_PLATE NUMBER(1),
	INV_MANAGE_PLATE_MAPS NUMBER(1),
	INV_MANAGE_CUSTOM_FIELDS NUMBER(1),
	CONSTRAINT CHEMINV_PRIVILEGES_PK 
		PRIMARY KEY(ROLE_INTERNAL_ID)
	) TABLESPACE &&securityTableSpaceName
;

--#########################################################
--CREATE PUBLIC SYNONYM
--#########################################################

Connect &&InstallUser/&&sysPass@&&serverName

DECLARE
	PROCEDURE createSynonym(synName IN varchar2) IS
			n NUMBER;
		BEGIN
			select count(*) into n from dba_synonyms where Upper(synonym_name) = synName;
			if n = 0 then
				execute immediate 'CREATE PUBLIC SYNONYM ' || synName || ' FOR &&SecurityschemaName..' || synName;
				-- Create synonym in cs_security for backwards compatibility
				execute immediate 'CREATE SYNONYM CS_SECURITY.' || synName || ' FOR &&SecurityschemaName..' || synName;
			end if;
		END createSynonym;
BEGIN
	createSynonym('&&privTableName');
END;
/

connect &&securitySchemaName/&&securitySchemaPass@&&serverName;