--' Create Default Roles
--INV_BROWSER
	CREATE ROLE INV_BROWSER NOT IDENTIFIED;
	REVOKE "INV_BROWSER" FROM "SYSTEM";
	GRANT "CONNECT" TO "INV_BROWSER";
	GRANT CSS_USER TO "INV_BROWSER";
	
--INV_CHEMIST
	CREATE ROLE INV_CHEMIST NOT IDENTIFIED;
	REVOKE "INV_CHEMIST" FROM "SYSTEM";
	GRANT CSS_USER TO "INV_CHEMIST";
--INV_FINANCE
	CREATE ROLE INV_FINANCE NOT IDENTIFIED;
	REVOKE "INV_FINANCE" FROM "SYSTEM";
	GRANT CSS_USER TO "INV_FINANCE";
--INV_RECEIVING
	CREATE ROLE INV_RECEIVING NOT IDENTIFIED;
	REVOKE "INV_RECEIVING" FROM "SYSTEM";
	GRANT CSS_USER TO "INV_RECEIVING";
--INV_REGISTRAR
	CREATE ROLE INV_REGISTRAR NOT IDENTIFIED;
	REVOKE "INV_REGISTRAR" FROM "SYSTEM";
	GRANT CSS_USER TO "INV_REGISTRAR";
--INV_ADMIN
	CREATE ROLE INV_ADMIN NOT IDENTIFIED;
	REVOKE "INV_ADMIN" FROM "SYSTEM";
	GRANT CSS_USER TO "INV_ADMIN";


-- Grant browser role to all roles
	GRANT "INV_BROWSER" TO "INV_CHEMIST";
	GRANT "INV_BROWSER" TO "INV_FINANCE";
	GRANT "INV_BROWSER" TO "INV_RECEIVING";
	GRANT "INV_BROWSER" TO "INV_REGISTRAR";
	GRANT "INV_BROWSER" TO "INV_ADMIN";

	
connect &&securitySchemaName/&&securitySchemaPass@&&serverName;
-- inv_browser needs to see the reg and batch number
-- ' removed this code for 10

--' Insert the data for the default roles
--INV_BROWSER
INSERT INTO SECURITY_ROLES (PRIVILEGE_TABLE_INT_ID,ROLE_NAME, COEIDENTIFIER) SELECT privilege_table_id, 'INV_BROWSER', 'Inventory' FROM privilege_tables WHERE privilege_table_name = '&&privTableName';
INSERT INTO CHEMINV_PRIVILEGES(ROLE_INTERNAL_ID				,INV_BROWSE_ALL		,INV_CHANGEQTY_CONTAINER	,INV_CHECKOUT_CONTAINER	,INV_CHECKIN_CONTAINER	,INV_RESERVE_CONTAINER	,INV_RETIRE_CONTAINER	,INV_PRINT_LABEL_CONTAINER	,INV_PRINT_REPORT	,INV_CREATE_LOCATION	,INV_EDIT_LOCATION	,INV_MOVE_LOCATION	,INV_DELETE_LOCATION	,INV_CREATE_CONTAINER	,INV_EDIT_CONTAINER	,INV_MOVE_CONTAINER	,INV_DELETE_CONTAINER	,INV_MANAGE_LINKS	,INV_MANAGE_SUBSTANCES	,INV_VIEW_AUDIT_TRAIL	,INV_UPDATE_LOCATION_CONTENTS	,INV_RECTIFY_LOCATION_CONTENTS	,INV_ORDER_CONTAINER	,INV_REORDER_CONTAINER	,INV_EDIT_EHS_DATA	,INV_CREATE_PLATE	,INV_MOVE_PLATE		,INV_EDIT_PLATE		,INV_RETIRE_PLATE	,INV_REQUEST_PLATE	,INV_DILUTE_PLATE	,INV_DELETE_PLATE	,INV_PRINT_LABEL_PLATE	,INV_MANAGE_PLATE_MAPS, INV_CERTIFY_CONTAINER, INV_APPROVE_CONTAINER, INV_CHANGE_STATUS_CONTAINER, INV_MANAGE_CUSTOM_FIELDS)
			VALUES(SECURITY_ROLES_SEQ.CURRVAL		,1			,0				,0			,0			,0			,0			,0				,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0				,0				,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0		,0,		0);

--INV_CHEMIST
--Create/Edit/Move CONtainers
INSERT INTO SECURITY_ROLES (PRIVILEGE_TABLE_INT_ID,ROLE_NAME, COEIDENTIFIER) SELECT privilege_table_id, 'INV_CHEMIST', 'Inventory' FROM privilege_tables WHERE privilege_table_name = '&&privTableName';
INSERT INTO CHEMINV_PRIVILEGES(ROLE_INTERNAL_ID				,INV_BROWSE_ALL		,INV_CHANGEQTY_CONTAINER	,INV_CHECKOUT_CONTAINER	,INV_CHECKIN_CONTAINER	,INV_RESERVE_CONTAINER	,INV_RETIRE_CONTAINER	,INV_PRINT_LABEL_CONTAINER	,INV_PRINT_REPORT	,INV_CREATE_LOCATION	,INV_EDIT_LOCATION	,INV_MOVE_LOCATION	,INV_DELETE_LOCATION	,INV_CREATE_CONTAINER	,INV_EDIT_CONTAINER	,INV_MOVE_CONTAINER	,INV_DELETE_CONTAINER	,INV_MANAGE_LINKS	,INV_MANAGE_SUBSTANCES	,INV_VIEW_AUDIT_TRAIL	,INV_UPDATE_LOCATION_CONTENTS	,INV_RECTIFY_LOCATION_CONTENTS	,INV_ORDER_CONTAINER	,INV_REORDER_CONTAINER	,INV_EDIT_EHS_DATA	,INV_CREATE_PLATE	,INV_MOVE_PLATE		,INV_EDIT_PLATE		,INV_RETIRE_PLATE	,INV_REQUEST_PLATE	,INV_DILUTE_PLATE	,INV_DELETE_PLATE	,INV_PRINT_LABEL_PLATE	,INV_MANAGE_PLATE_MAPS, INV_CERTIFY_CONTAINER, INV_APPROVE_CONTAINER, INV_CHANGE_STATUS_CONTAINER, INV_MANAGE_CUSTOM_FIELDS)
			VALUES(SECURITY_ROLES_SEQ.CURRVAL		,1			,1				,1			,1			,1			,1			,1				,1			,0			,0			,0			,0			,1			,1			,1			,0			,0			,0			,0			,0				,0				,0			,0			,0 			,1			,1			,1			,1			,1			,1			,1			,1			,0			,0			,0		,1,		0);

--INV_RECEIVING
-- Create/Edit/Move CONtainers
INSERT INTO SECURITY_ROLES (PRIVILEGE_TABLE_INT_ID,ROLE_NAME, COEIDENTIFIER) SELECT privilege_table_id, 'INV_RECEIVING', 'Inventory' FROM privilege_tables WHERE privilege_table_name = '&&privTableName';
INSERT INTO CHEMINV_PRIVILEGES(ROLE_INTERNAL_ID				,INV_BROWSE_ALL		,INV_CHANGEQTY_CONTAINER	,INV_CHECKOUT_CONTAINER	,INV_CHECKIN_CONTAINER	,INV_RESERVE_CONTAINER	,INV_RETIRE_CONTAINER	,INV_PRINT_LABEL_CONTAINER	,INV_PRINT_REPORT	,INV_CREATE_LOCATION	,INV_EDIT_LOCATION	,INV_MOVE_LOCATION	,INV_DELETE_LOCATION	,INV_CREATE_CONTAINER	,INV_EDIT_CONTAINER	,INV_MOVE_CONTAINER	,INV_DELETE_CONTAINER	,INV_MANAGE_LINKS	,INV_MANAGE_SUBSTANCES	,INV_VIEW_AUDIT_TRAIL	,INV_UPDATE_LOCATION_CONTENTS	,INV_RECTIFY_LOCATION_CONTENTS	,INV_ORDER_CONTAINER	,INV_REORDER_CONTAINER	,INV_EDIT_EHS_DATA	,INV_CREATE_PLATE	,INV_MOVE_PLATE		,INV_EDIT_PLATE		,INV_RETIRE_PLATE	,INV_REQUEST_PLATE	,INV_DILUTE_PLATE	,INV_DELETE_PLATE	,INV_PRINT_LABEL_PLATE	,INV_MANAGE_PLATE_MAPS, INV_CERTIFY_CONTAINER, INV_APPROVE_CONTAINER, INV_CHANGE_STATUS_CONTAINER, INV_MANAGE_CUSTOM_FIELDS)
			VALUES(SECURITY_ROLES_SEQ.CURRVAL		,1			,0				,0			,0			,0			,0			,1				,1			,0			,0			,0			,0			,1			,1			,1			,1			,0			,0			,0			,0				,0				,0			,0			,0			,1			,1			,1			,0			,0			,0			,1			,1			,0			,0			,0		,1,		0);

--INV_FINANCE
-- Create/Edit/Move CONtainers
-- Create/Move/Delete LocatiONs
INSERT INTO SECURITY_ROLES (PRIVILEGE_TABLE_INT_ID,ROLE_NAME, COEIDENTIFIER) SELECT privilege_table_id, 'INV_FINANCE', 'Inventory' FROM privilege_tables WHERE privilege_table_name = '&&privTableName';
INSERT INTO CHEMINV_PRIVILEGES(ROLE_INTERNAL_ID				,INV_BROWSE_ALL		,INV_CHANGEQTY_CONTAINER	,INV_CHECKOUT_CONTAINER	,INV_CHECKIN_CONTAINER	,INV_RESERVE_CONTAINER	,INV_RETIRE_CONTAINER	,INV_PRINT_LABEL_CONTAINER	,INV_PRINT_REPORT	,INV_CREATE_LOCATION	,INV_EDIT_LOCATION	,INV_MOVE_LOCATION	,INV_DELETE_LOCATION	,INV_CREATE_CONTAINER	,INV_EDIT_CONTAINER	,INV_MOVE_CONTAINER	,INV_DELETE_CONTAINER	,INV_MANAGE_LINKS	,INV_MANAGE_SUBSTANCES	,INV_VIEW_AUDIT_TRAIL	,INV_UPDATE_LOCATION_CONTENTS	,INV_RECTIFY_LOCATION_CONTENTS	,INV_ORDER_CONTAINER	,INV_REORDER_CONTAINER	,INV_EDIT_EHS_DATA	,INV_CREATE_PLATE	,INV_MOVE_PLATE		,INV_EDIT_PLATE		,INV_RETIRE_PLATE	,INV_REQUEST_PLATE	,INV_DILUTE_PLATE	,INV_DELETE_PLATE	,INV_PRINT_LABEL_PLATE	,INV_MANAGE_PLATE_MAPS, INV_CERTIFY_CONTAINER, INV_APPROVE_CONTAINER, INV_CHANGE_STATUS_CONTAINER, INV_MANAGE_CUSTOM_FIELDS)
			VALUES(SECURITY_ROLES_SEQ.CURRVAL		,1			,1				,0			,0			,0			,1			,1				,1			,1			,1			,1			,1			,1			,1			,1			,1			,0			,0			,1			,0				,0				,0			,0			,0			,1			,1			,1			,0			,0			,0			,1			,1			,0			,0			,0		,0,		0);

--INV_REGISTRAR
-- Create/Edit/Delete inventory substances
INSERT INTO SECURITY_ROLES (PRIVILEGE_TABLE_INT_ID,ROLE_NAME, COEIDENTIFIER) SELECT privilege_table_id, 'INV_REGISTRAR', 'Inventory' FROM privilege_tables WHERE privilege_table_name = '&&privTableName';
INSERT INTO CHEMINV_PRIVILEGES(ROLE_INTERNAL_ID				,INV_BROWSE_ALL		,INV_CHANGEQTY_CONTAINER	,INV_CHECKOUT_CONTAINER	,INV_CHECKIN_CONTAINER	,INV_RESERVE_CONTAINER	,INV_RETIRE_CONTAINER	,INV_PRINT_LABEL_CONTAINER	,INV_PRINT_REPORT	,INV_CREATE_LOCATION	,INV_EDIT_LOCATION	,INV_MOVE_LOCATION	,INV_DELETE_LOCATION	,INV_CREATE_CONTAINER	,INV_EDIT_CONTAINER	,INV_MOVE_CONTAINER	,INV_DELETE_CONTAINER	,INV_MANAGE_LINKS	,INV_MANAGE_SUBSTANCES	,INV_VIEW_AUDIT_TRAIL	,INV_UPDATE_LOCATION_CONTENTS	,INV_RECTIFY_LOCATION_CONTENTS	,INV_ORDER_CONTAINER	,INV_REORDER_CONTAINER	,INV_EDIT_EHS_DATA	,INV_CREATE_PLATE	,INV_MOVE_PLATE		,INV_EDIT_PLATE		,INV_RETIRE_PLATE	,INV_REQUEST_PLATE	,INV_DILUTE_PLATE	,INV_DELETE_PLATE	,INV_PRINT_LABEL_PLATE	,INV_MANAGE_PLATE_MAPS, INV_CERTIFY_CONTAINER, INV_APPROVE_CONTAINER, INV_CHANGE_STATUS_CONTAINER, INV_MANAGE_CUSTOM_FIELDS)
			VALUES(SECURITY_ROLES_SEQ.CURRVAL		,1			,0				,0			,0			,0			,0			,1				,1			,0			,0			,0			,0			,0			,0			,0			,0			,1			,1			,1			,0				,0				,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0			,0		,0,		0);

--INV_ADMIN
-- Full Access
INSERT INTO SECURITY_ROLES (PRIVILEGE_TABLE_INT_ID,ROLE_NAME, COEIDENTIFIER) SELECT privilege_table_id, 'INV_ADMIN', 'Inventory' FROM privilege_tables WHERE privilege_table_name = '&&privTableName';
INSERT INTO CHEMINV_PRIVILEGES(ROLE_INTERNAL_ID				,INV_BROWSE_ALL		,INV_CHANGEQTY_CONTAINER	,INV_CHECKOUT_CONTAINER	,INV_CHECKIN_CONTAINER	,INV_RESERVE_CONTAINER	,INV_RETIRE_CONTAINER	,INV_PRINT_LABEL_CONTAINER	,INV_PRINT_REPORT	,INV_CREATE_LOCATION	,INV_EDIT_LOCATION	,INV_MOVE_LOCATION	,INV_DELETE_LOCATION	,INV_CREATE_CONTAINER	,INV_EDIT_CONTAINER	,INV_MOVE_CONTAINER	,INV_DELETE_CONTAINER	,INV_MANAGE_LINKS	,INV_MANAGE_SUBSTANCES	,INV_VIEW_AUDIT_TRAIL	,INV_UPDATE_LOCATION_CONTENTS	,INV_RECTIFY_LOCATION_CONTENTS	,INV_ORDER_CONTAINER	,INV_REORDER_CONTAINER	,INV_EDIT_EHS_DATA	,INV_CREATE_PLATE	,INV_MOVE_PLATE		,INV_EDIT_PLATE		,INV_RETIRE_PLATE	,INV_REQUEST_PLATE	,INV_DILUTE_PLATE	,INV_DELETE_PLATE	,INV_PRINT_LABEL_PLATE	,INV_MANAGE_PLATE_MAPS, INV_CERTIFY_CONTAINER, INV_APPROVE_CONTAINER, INV_CHANGE_STATUS_CONTAINER, INV_MANAGE_CUSTOM_FIELDS)
			VALUES(SECURITY_ROLES_SEQ.CURRVAL		,1			,1				,1			,1			,1			,1			,1				,1			,1			,1			,1			,1			,1			,1			,1			,1			,1			,1			,1			,0				,1				,0			,0			,0			,1			,1			,1			,1			,1			,1			,1			,1			,1			,0			,0		,1,		1);
commit;

--' grant roles based on privs
begin
	FOR role_rec IN (SELECT role_name FROM security_roles WHERE privilege_table_int_id = (SELECT privilege_table_id FROM privilege_tables WHERE privilege_table_name = '&&privTableName'))
	LOOP
		GrantPrivsToRole(role_rec.role_name);
	END LOOP;
end;
/

