--Copyright 1999-2003 CambridgeSoft Corporation. All rights reserved

PROMPT Starting users.sql

DECLARE
   n   NUMBER;
BEGIN
   SELECT COUNT (*) INTO n
     FROM dba_users
    WHERE username = UPPER ('&&schemaName');

   IF n > 0 THEN
      EXECUTE IMMEDIATE 'DROP USER &&schemaName CASCADE';
   END IF;
END;
/

CREATE USER &&schemaName
   IDENTIFIED BY &&schemaPass
   DEFAULT TABLESPACE &&tableSpaceName
   TEMPORARY TABLESPACE &&temptableSpaceName;

GRANT CONNECT TO &&schemaName WITH ADMIN OPTION;
GRANT RESOURCE TO &&schemaName;
GRANT CREATE VIEW TO &&schemaName;

--This is necesary because oracle have a bug using EXECUTE IMMEDIATE with SPLIT PARTITION  A
GRANT CREATE TABLE TO &&schemaName;
GRANT CREATE SEQUENCE TO &&schemaName;

GRANT CREATE ANY TABLE TO &&schemaName;
GRANT CREATE ANY SEQUENCE TO &&schemaName;
GRANT ALL PRIVILEGES TO &&schemaName;

GRANT SELECT ANY DICTIONARY TO &&schemaName;

GRANT ALTER USER TO &&schemaName;
GRANT CREATE USER TO &&schemaName;
GRANT DROP USER TO &&schemaName;
GRANT ALTER ANY ROLE TO &&schemaName;
GRANT CREATE ROLE TO &&schemaName;
GRANT DROP ANY ROLE TO &&schemaName;
GRANT GRANT ANY ROLE TO &&schemaName;
GRANT GRANT ANY PRIVILEGE TO &&schemaName;
GRANT SELECT ANY TABLE TO &&schemaName;


-- Define the CS User Profile 
CREATE PROFILE csuserprofile LIMIT
       FAILED_LOGIN_ATTEMPTS UNLIMITED
       PASSWORD_LIFE_TIME UNLIMITED
       PASSWORD_REUSE_TIME UNLIMITED
       PASSWORD_REUSE_MAX UNLIMITED
       PASSWORD_LOCK_TIME 1/96                            --- means 15 minutes
       PASSWORD_GRACE_TIME UNLIMITED
       PASSWORD_VERIFY_FUNCTION NULL;

ALTER USER &&schemaName TEMPORARY TABLESPACE &&tempTableSpaceName;

/*
BEGIN
   IF '&&UpgradeCsSecurity'='N' THEN
	EXECUTE IMMEDIATE 'CREATE  ROLE css_user NOT IDENTIFIED';
	EXECUTE IMMEDIATE 'GRANT  "CONNECT" TO "CSS_USER"';
 	EXECUTE IMMEDIATE 'CREATE USER cssuser IDENTIFIED BY cssuser DEFAULT TABLESPACE &&tableSpaceName TEMPORARY TABLESPACE &&temptableSpaceName PROFILE DEFAULT ACCOUNT UNLOCK';
	EXECUTE IMMEDIATE '	GRANT css_user TO cssuser';
	EXECUTE IMMEDIATE 'ALTER USER cssuser DEFAULT ROLE ALL';
	
	EXECUTE IMMEDIATE 'CREATE  ROLE css_admin NOT IDENTIFIED';
	EXECUTE IMMEDIATE 'GRANT  "CONNECT" TO "CSS_ADMIN"';
	EXECUTE IMMEDIATE 'CREATE USER cssadmin IDENTIFIED BY cssadmin DEFAULT TABLESPACE &&tableSpaceName TEMPORARY TABLESPACE &&temptableSpaceName PROFILE DEFAULT ACCOUNT UNLOCK';
	EXECUTE IMMEDIATE 'GRANT css_admin TO cssadmin';
	EXECUTE IMMEDIATE 'ALTER USER cssadmin DEFAULT ROLE ALL';
	

 END IF;
END;
/
*/