prompt 
prompt Starting "pkg_Gui_Util_def.sql"...
prompt 

CREATE OR REPLACE PACKAGE "GUI_UTIL"
AS 
TYPE  CURSOR_TYPE IS REF CURSOR;

PROCEDURE GETPROJECTNAMEVALUELIST(
O_RS OUT CURSOR_TYPE);

PROCEDURE GETPREFIXNAMEVALUELIST (
O_RS OUT CURSOR_TYPE);

PROCEDURE GETACTIVECHEMISTNAMEVALUELIST (
O_RS OUT CURSOR_TYPE);

PROCEDURE GETCHEMISTNAMEVALUELIST (
O_RS OUT CURSOR_TYPE);

PROCEDURE GETFRAGMENTTYPESVALUELIST (
O_RS OUT CURSOR_TYPE);

PROCEDURE GETFRAGMENTSLIST (
O_RS OUT CURSOR_TYPE);     

PROCEDURE GETMATCHEDFRAGMENTSLIST (
AStructure IN CLOB, O_RS OUT CURSOR_TYPE);

PROCEDURE GETPROJECTLIST (
O_RS OUT CURSOR_TYPE); 

PROCEDURE GETACTIVEPROJECTLISTBYPERSONID (
O_RS OUT CURSOR_TYPE, APersonID in Number);

PROCEDURE GETIDENTIFIERLIST (
O_RS OUT CURSOR_TYPE);

PROCEDURE GETSEQUENCELIST (
O_RS OUT CURSOR_TYPE, ASeqTypeID in Number);

PROCEDURE GETSEQUENCELISTBYPERSONID (
O_RS OUT CURSOR_TYPE,  ASeqTypeID in Number, APersonID in Number);

PROCEDURE GETTEMPREGISTRIESCOUNT (
ACount OUT NUMBER);

PROCEDURE GETPERMREGISTRIESCOUNT (
ACount OUT NUMBER);

PROCEDURE GETAPPROVEDREGISTRIESCOUNT (
ACount OUT NUMBER);

END "GUI_UTIL";
/
