


--#########################################################
--this add biosar_browser_privileges table to the cs_security schemas and creates 
--standard roles used by biosar browser.
--#########################################################

Connect &&securitySchemaName/&&securitySchemaPass@&&serverName

DECLARE
	n NUMBER;
BEGIN
	select count(*) into n from user_tables where table_name = Upper('&&privTableName');
	if n = 1 then
		execute immediate '
		DROP TABLE &&privTableName CASCADE CONSTRAINTS';
	end if;
END;
/

CREATE TABLE  &&privTableName (
	ROLE_INTERNAL_ID NUMBER(8,0) not null,
	CAMSOFT_LOG_ON NUMBER(1,0) null,
	ADD_USER_FORMGROUP NUMBER(1,0) null,
	EDIT_USER_FORMGROUP NUMBER(1,0) null,
	DELETE_USER_FORMGROUP NUMBER(1,0) null,
	SET_FORMGROUP_PUBLIC NUMBER(1,0) null,
	SEARCH_USING_FORMGROUP NUMBER(1,0) null,
	DUPLICATE_GRANTED_FORMGROUP NUMBER(1,0) null,
	EDIT_GRANTED_FORMGROUP NUMBER(1,0) null,
	EDIT_ANY_FORMGROUP NUMBER(1,0) null,
	ADD_ADMIN_SCHEMA NUMBER(1,0) null, 
	EDIT_ADMIN_SCHEMA NUMBER(1,0) null,
	DELETE_ADMIN_SCHEMA NUMBER(1,0) null, 
	EDIT_USERS_TABLE NUMBER(1,0) null,
	ADD_USERS_TABLE NUMBER(1,0) null,
	DELETE_USERS_TABLE NUMBER(1,0) null,
	EDIT_ROLES_TABLE NUMBER(1,0) null,
	ADD_ROLES_TABLE NUMBER(1,0) null,
	DELETE_ROLES_TABLE NUMBER(1,0) null,
	EDIT_PEOPLE_TABLE NUMBER(1,0) null,
	ADD_PEOPLE_TABLE NUMBER(1,0) null,
	DELETE_PEOPLE_TABLE NUMBER(1,0) null,
	IS_FORMGROUP_ROLE NUMBER(1,0) null, 
	constraint BIOSAR_BROWSER_PRIV 
	  primary key (ROLE_INTERNAL_ID) 
	  using index pctfree 0
	  tablespace &&securityTableSpaceName
) 
TABLESPACE &&securityTableSpaceName
storage (pctincrease 0);

--#########################################################
--CREATE PUBLIC SYNONYM
--#########################################################

Connect &&InstallUser/&&sysPass@&&serverName

DECLARE
	PROCEDURE createSynonym(synName IN varchar2) IS
			n NUMBER;
		BEGIN
			select count(*) into n from dba_synonyms where Upper(synonym_name) = synName;
			if n = 0 then
				execute immediate 'CREATE PUBLIC SYNONYM ' || synName || ' FOR &&SecurityschemaName..' || synName;
				-- Create synonym in cs_security for backwards compatibility
				execute immediate 'CREATE SYNONYM CS_SECURITY.' || synName || ' FOR &&SecurityschemaName..' || synName;
			end if;
		END createSynonym;
BEGIN
	createSynonym('&&privTableName');
END;
/
--#########################################################
--CREATE ROLES
--#########################################################

prompt 'dropping test roles...'

DECLARE
	PROCEDURE dropRole(roleName IN varchar2) IS
			n NUMBER;
		BEGIN
			select count(*) into n from dba_roles where Upper(role) = roleName;
			if n > 0 then
				execute immediate 'DROP ROLE ' || roleName;
			end if;
		END dropRole;
BEGIN
	dropRole('BIOSAR_BROWSER_ADMIN');
	dropRole('BIOSAR_BROWSER_USER_ADMIN');
	dropRole('BIOSAR_BROWSER_USER');
	dropRole('BIOSAR_BROWSER_USER_BROWSER');
END;
/



--CREATE_MASTER_ROLES
--BIOSAR_BROWSER_ADMIN
	CREATE ROLE BIOSAR_BROWSER_ADMIN NOT IDENTIFIED;
	REVOKE "BIOSAR_BROWSER_ADMIN" FROM "SYSTEM";
--BIOSAR_BROWSER_USER_ADMIN
	CREATE ROLE BIOSAR_BROWSER_USER_ADMIN NOT IDENTIFIED;
	REVOKE "BIOSAR_BROWSER_USER_ADMIN" FROM "SYSTEM";
--BIOSAR_BROWSER_USER
	CREATE ROLE BIOSAR_BROWSER_USER NOT IDENTIFIED;
	REVOKE "BIOSAR_BROWSER_USER" FROM "SYSTEM";
--BIOSAR_BROWSER_USER_BROWSER
	CREATE ROLE BIOSAR_BROWSER_USER_BROWSER NOT IDENTIFIED;
	REVOKE "BIOSAR_BROWSER_USER_BROWSER" FROM "SYSTEM";

--#########################################################
--ADD GRANTS TO ROLES
--#########################################################




--CAN EDIT SCHEMA AVAILABILITY USING ADMIN TOOL 

	GRANT "CONNECT" TO "BIOSAR_BROWSER_ADMIN";
	GRANT "CONNECT" TO "BIOSAR_BROWSER_USER_ADMIN";
	GRANT "CONNECT" TO "BIOSAR_BROWSER_USER";
	GRANT "CONNECT" TO "BIOSAR_BROWSER_USER_BROWSER";
	Grant CSS_ADMIN to BIOSAR_BROWSER_ADMIN;
	Grant CSS_USER to BIOSAR_BROWSER_USER_ADMIN;
	Grant CSS_USER to BIOSAR_BROWSER_USER;
	Grant CSS_USER to BIOSAR_BROWSER_USER_BROWSER;
		
	
Connect &&securitySchemaName/&&securitySchemaPass@&&serverName


			--MANAGE USER ADMIN TASKS
			
			GRANT SELECT, INSERT, DELETE, UPDATE ON &&securitySchemaName..BIOSAR_BROWSER_PRIVILEGES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON &&securitySchemaName..PEOPLE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON &&securitySchemaName..PRIVILEGE_TABLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON &&securitySchemaName..SECURITY_ROLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON &&securitySchemaName..SITES TO BIOSAR_BROWSER_ADMIN;

			
			--ADMIN SCHEMA MANAGEMENT TASKS
Connect &&schemaName/&&schemaPass@&&serverName
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_COLUMN TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DATATYPE_DISPLAY_TYPE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DISPLAY_OPTION TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DISPLAY_TYPE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DTYP_DOPT TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_RELATIONSHIP TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_SCHEMA TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_TABLE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_CHILD_TABLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_COLUMN_TABLE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMGROUP_TABLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMITEMS_ALL TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_PARENT_TABLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_TABLE_SCHEMA TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_HTTP_CONTENT_TYPE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_INDEX_TYPE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_XML_TEMPL_DEF TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.db_vw_formitems_compact TO BIOSAR_BROWSER_ADMIN;
			
			
			--ADMIN FORMGROUP MANAGEMENT TASKS
			
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP_TABLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE_DOPT TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM_ITEM TO BIOSAR_BROWSER_ADMIN;
		
			
			
			-- SEARCHING TASKS
			
		
			
			
--CAN MANAGE FORMGROUPS USING MANAGE_YOUR_FORMGROUPS TOOL  CAN MAKE FORMGROUP PUBLIC

Connect &&securitySchemaName/&&securitySchemaPass@&&serverName
			--MANAGE USER ADMIN TASKS
			
			GRANT SELECT,INSERT,UPDATE ON &&securitySchemaName..BIOSAR_BROWSER_PRIVILEGES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT,INSERT,UPDATE  ON &&securitySchemaName..PEOPLE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT,INSERT,UPDATE  ON &&securitySchemaName..PRIVILEGE_TABLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT,INSERT,UPDATE ON &&securitySchemaName..SECURITY_ROLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT,INSERT,UPDATE  ON &&securitySchemaName..SITES TO BIOSAR_BROWSER_USER_ADMIN;
Connect &&schemaName/&&schemaPass@&&serverName	
			--ADMIN SCHEMA MANAGEMENT TASKS
			
			GRANT SELECT ON BIOSARDB.DB_COLUMN TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_DATATYPE_DISPLAY_TYPE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_OPTION TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_TYPE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_DTYP_DOPT TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_RELATIONSHIP TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_SCHEMA TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_TABLE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_CHILD_TABLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_COLUMN_TABLE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMITEMS_ALL TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_PARENT_TABLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_TABLE_SCHEMA TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_HTTP_CONTENT_TYPE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_INDEX_TYPE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_XML_TEMPL_DEF TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.db_vw_formitems_compact TO BIOSAR_BROWSER_USER_ADMIN;

			

		
			--USER FORMGROUP MANAGEMENT TASKS
Connect &&schemaName/&&schemaPass@&&serverName

			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE_DOPT TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM_ITEM TO BIOSAR_BROWSER_USER_ADMIN;
			
			-- SEARCHING TASKS
			
			
			
--CAN MANAGE FORMGROUPS USING MANAGE_YOUR_FORMGROUPS TOOL CANNOT MAKE FORMGROUP PUBLIC
			
Connect &&securitySchemaName/&&securitySchemaPass@&&serverName
			--MANAGE USER ADMIN TASKS
			
			GRANT SELECT ON &&securitySchemaName..BIOSAR_BROWSER_PRIVILEGES TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON &&securitySchemaName..PEOPLE TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON &&securitySchemaName..PRIVILEGE_TABLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON &&securitySchemaName..SECURITY_ROLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON &&securitySchemaName..SITES TO BIOSAR_BROWSER_USER;
Connect &&schemaName/&&schemaPass@&&serverName			
			--ADMIN SCHEMA MANAGEMENT TASKS
			
			GRANT SELECT ON BIOSARDB.DB_COLUMN TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_DATATYPE_DISPLAY_TYPE TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_OPTION TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_TYPE TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_DTYP_DOPT TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_RELATIONSHIP TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_SCHEMA TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_TABLE TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_CHILD_TABLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_COLUMN_TABLE TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMITEMS_ALL TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_PARENT_TABLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_TABLE_SCHEMA TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_HTTP_CONTENT_TYPE TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_INDEX_TYPE TO BIOSAR_BROWSER_USER;

			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_XML_TEMPL_DEF TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.db_vw_formitems_compact TO BIOSAR_BROWSER_USER;

			
			--USER FORMGROUP MANAGEMENT TASKS
			
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE_DOPT TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM_ITEM TO BIOSAR_BROWSER_USER;

			
			-- SEARCHING TASKS
			
			
			


--CAN USE ALREADY CREATED FORMGROUPS FOR SEARCHING
Connect &&securitySchemaName/&&securitySchemaPass@&&serverName		
			--MANAGE USER ADMIN TASKS
			
			GRANT SELECT ON &&securitySchemaName..BIOSAR_BROWSER_PRIVILEGES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON &&securitySchemaName..PEOPLE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON &&securitySchemaName..PRIVILEGE_TABLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON &&securitySchemaName..SECURITY_ROLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON &&securitySchemaName..SITES TO BIOSAR_BROWSER_USER_BROWSER;
			
Connect &&schemaName/&&schemaPass@&&serverName
			--ADMIN SCHEMA MANAGEMENT TASKS
			
			GRANT SELECT ON BIOSARDB.DB_COLUMN TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_DATATYPE_DISPLAY_TYPE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_OPTION TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_TYPE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_DTYP_DOPT TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_RELATIONSHIP TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_SCHEMA TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_TABLE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_CHILD_TABLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_COLUMN_TABLE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMITEMS_ALL TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_PARENT_TABLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_TABLE_SCHEMA TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_HTTP_CONTENT_TYPE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_INDEX_TYPE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_XML_TEMPL_DEF TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.db_vw_formitems_compact TO BIOSAR_BROWSER_USER_BROWSER;

			
			--USER FORMGROUP MANAGEMENT TASKS
			
			GRANT SELECT ON BIOSARDB.DB_FORM TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_FORMGROUP TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_FORMTYPE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_FORMTYPE_DOPT TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_FORM_ITEM TO BIOSAR_BROWSER_USER_BROWSER;
			
			-- SEARCHING TASKS
			
			


--add starting data

--#########################################################
--STARTING DATA
--#########################################################

--PRIVELEGE_TABLES
Connect &&securitySchemaName/&&securitySchemaPass@&&serverName

delete from security_roles where PRIVILEGE_TABLE_INT_ID IN(Select Privilege_Table_ID  FROM PRIVILEGE_TABLES where PRIVILEGE_TABLE_NAME = 'BIOSAR_BROWSER_PRIVILEGES');
commit;
delete  from privilege_tables where PRIVILEGE_TABLE_NAME = 'BIOSAR_BROWSER_PRIVILEGES';
commit;

			
INSERT INTO PRIVILEGE_TABLES (PRIVILEGE_TABLE_ID,APP_NAME, APP_URL,PRIVILEGE_TABLE_NAME,TABLE_SPACE) values(PRIVILEGE_TABLES_seq.NextVal,'BioSAR Browser', '/BIOSAR_BROWSER_APP/default.asp', 'BIOSAR_BROWSER_PRIVILEGES', 'T_&&securitySchemaName');

commit;
			
INSERT INTO SECURITY_ROLES (ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME, COEIDENTIFIER)values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'BIOSAR_BROWSER_ADMIN', 'BioSARBrowser');
INSERT INTO BIOSAR_BROWSER_PRIVILEGES(ROLE_INTERNAL_ID,CAMSOFT_LOG_ON,SEARCH_USING_FORMGROUP,ADD_USER_FORMGROUP,EDIT_USER_FORMGROUP,DELETE_USER_FORMGROUP,SET_FORMGROUP_PUBLIC, ADD_ADMIN_SCHEMA,EDIT_ADMIN_SCHEMA,DELETE_ADMIN_SCHEMA,EDIT_USERS_TABLE,EDIT_PEOPLE_TABLE,ADD_PEOPLE_TABLE,DELETE_PEOPLE_TABLE,ADD_USERS_TABLE,DELETE_USERS_TABLE,ADD_ROLES_TABLE,EDIT_ROLES_TABLE,DELETE_ROLES_TABLE,IS_FORMGROUP_ROLE,EDIT_ANY_FORMGROUP,DUPLICATE_GRANTED_FORMGROUP,EDIT_GRANTED_FORMGROUP)values(SECURITY_ROLES_SEQ.CURRVAL,'1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','0','1','1','1');
Commit;

INSERT INTO SECURITY_ROLES (ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME, COEIDENTIFIER)values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'BIOSAR_BROWSER_USER_ADMIN', 'BioSARBrowser');
INSERT INTO BIOSAR_BROWSER_PRIVILEGES(ROLE_INTERNAL_ID,CAMSOFT_LOG_ON,SEARCH_USING_FORMGROUP,ADD_USER_FORMGROUP,EDIT_USER_FORMGROUP,DELETE_USER_FORMGROUP,SET_FORMGROUP_PUBLIC, ADD_ADMIN_SCHEMA,EDIT_ADMIN_SCHEMA,DELETE_ADMIN_SCHEMA,EDIT_USERS_TABLE,EDIT_PEOPLE_TABLE,ADD_PEOPLE_TABLE,DELETE_PEOPLE_TABLE,ADD_USERS_TABLE,DELETE_USERS_TABLE,ADD_ROLES_TABLE,EDIT_ROLES_TABLE,DELETE_ROLES_TABLE,IS_FORMGROUP_ROLE,EDIT_ANY_FORMGROUP,DUPLICATE_GRANTED_FORMGROUP,EDIT_GRANTED_FORMGROUP)values(SECURITY_ROLES_SEQ.CURRVAL,'1','1','1','1','1','1','0','0','0','1','0','0','0','0','0','0','0','0','0','0','1','1');
Commit;

INSERT INTO SECURITY_ROLES (ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME, COEIDENTIFIER)values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'BIOSAR_BROWSER_USER', 'BioSARBrowser');
INSERT INTO BIOSAR_BROWSER_PRIVILEGES(ROLE_INTERNAL_ID,CAMSOFT_LOG_ON,SEARCH_USING_FORMGROUP,ADD_USER_FORMGROUP,EDIT_USER_FORMGROUP,DELETE_USER_FORMGROUP,SET_FORMGROUP_PUBLIC, ADD_ADMIN_SCHEMA,EDIT_ADMIN_SCHEMA,DELETE_ADMIN_SCHEMA,EDIT_USERS_TABLE,EDIT_PEOPLE_TABLE,ADD_PEOPLE_TABLE,DELETE_PEOPLE_TABLE,ADD_USERS_TABLE,DELETE_USERS_TABLE,ADD_ROLES_TABLE,EDIT_ROLES_TABLE,DELETE_ROLES_TABLE,IS_FORMGROUP_ROLE,EDIT_ANY_FORMGROUP,DUPLICATE_GRANTED_FORMGROUP,EDIT_GRANTED_FORMGROUP)values(SECURITY_ROLES_SEQ.CURRVAL,'1','1','1','1','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0');
Commit;

INSERT INTO SECURITY_ROLES (ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME, COEIDENTIFIER)values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'BIOSAR_BROWSER_USER_BROWSER', 'BioSARBrowser');
INSERT INTO BIOSAR_BROWSER_PRIVILEGES(ROLE_INTERNAL_ID,CAMSOFT_LOG_ON,SEARCH_USING_FORMGROUP,ADD_USER_FORMGROUP,EDIT_USER_FORMGROUP,DELETE_USER_FORMGROUP,SET_FORMGROUP_PUBLIC, ADD_ADMIN_SCHEMA,EDIT_ADMIN_SCHEMA,DELETE_ADMIN_SCHEMA,EDIT_USERS_TABLE,EDIT_PEOPLE_TABLE,ADD_PEOPLE_TABLE,DELETE_PEOPLE_TABLE,ADD_USERS_TABLE,DELETE_USERS_TABLE,ADD_ROLES_TABLE,EDIT_ROLES_TABLE,DELETE_ROLES_TABLE,IS_FORMGROUP_ROLE,EDIT_ANY_FORMGROUP,DUPLICATE_GRANTED_FORMGROUP,EDIT_GRANTED_FORMGROUP)values(SECURITY_ROLES_SEQ.CURRVAL,'1','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0');
Commit;

delete from security_roles where PRIVILEGE_TABLE_INT_ID IN(Select Privilege_Table_ID  FROM PRIVILEGE_TABLES where PRIVILEGE_TABLE_NAME = 'OTHER_PRIVILEGES');


commit;
delete  from privilege_tables where PRIVILEGE_TABLE_NAME = 'OTHER_PRIVILEGES';
commit;

INSERT INTO PRIVILEGE_TABLES (PRIVILEGE_TABLE_ID,APP_NAME, APP_URL,PRIVILEGE_TABLE_NAME,TABLE_SPACE) values(PRIVILEGE_TABLES_seq.NextVal,'BIOSAR_BROWSER_EXCLUDE', '', 'OTHER_PRIVILEGES', 'T_&&securitySchemaName');
commit;

--#########################################################

--If they are not installed you will see errors in the script indicating roles do not exist. This is OKAY.
--Do not be concerned about these script erros.


 
Connect &&securitySchemaName/&&securitySchemaPass@&&serverName

delete from object_privileges where schema='BIOSARDB';
commit;


--- CAMSOFT_LOG_ON PRIVS

--- SEARCH_USING_FORMGROUP PRIVS

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_COMPACT');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'EXCEPTIONS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');


INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');



--- ADD_USER_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'EXCEPTIONS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_COMPACT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
--- EDIT_USER_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'EXCEPTIONS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');

--- DELETE_USER_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'EXCEPTIONS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');

--- SET_FORMGROUP_PUBLIC PRIVS

--- SEARCH_USING_FORMGROUP PRIVS

--- ADD_ADMIN_SCHEMA PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_INDEX_TYPE');

--- EDIT_ADMIN_SCHEMA PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_INDEX_TYPE');

--- DELETE_ADMIN_SCHEMA PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_INDEX_TYPE');

--- EDIT_USERS_TABLE PRIVS

--- ADD_USERS_TABLE PRIVS

--- DELETE_USERS_TABLE PRIVS

--- EDIT_ROLES_TABLE PRIVS

--- ADD_ROLES_TABLE PRIVS

--- DELETE_ROLES_TABLE PRIVS

--- EDIT_PEOPLE_TABLE PRIVS

--- ADD_PEOPLE_TABLE PRIVS


--- DELETE_PEOPLE_TABLE PRIVS


--- IS_FORMGROUP_ROLE PRIVS



--- EDIT_ANY_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'EXCEPTIONS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');

--- DUPLICATE_GRANTED_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'EXCEPTIONS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');

 --- EDIT_GRANTED_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'EXCEPTIONS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');

commit;

-- &&securitySchemaName object privileges
-- This procedure inserts into objects privilege table w/o complaining about duplicate constraint violations
DECLARE
	PROCEDURE addObjectPriv(appPriv in varchar2, priv in varchar2, schemaName in varchar2, objectName in varchar2) IS
	BEGIN
		execute immediate 'INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('''||appPriv||''','''||priv||''','''||schemaName||''','''||objectName||''')';
	EXCEPTION
  		when DUP_VAL_ON_INDEX then
      		rollback;
 	END addObjectPriv;
BEGIN
	-- SEARCH_USING_FORMGROUP
	addObjectPriv('SEARCH_USING_FORMGROUP', 'SELECT', '&&securitySchemaName', 'BIOSAR_BROWSER_PRIVILEGES');
	addObjectPriv('SEARCH_USING_FORMGROUP', 'SELECT', '&&securitySchemaName', 'CS_SECURITY_PRIVILEGES');
	addObjectPriv('SEARCH_USING_FORMGROUP', 'SELECT', '&&securitySchemaName', 'PRIVILEGE_TABLES');
	addObjectPriv('SEARCH_USING_FORMGROUP', 'SELECT', '&&securitySchemaName', 'SECURITY_ROLES');
	--- EDIT_USERS_TABLE PRIVS
	addObjectPriv('EDIT_USERS_TABLE', 'DELETE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_USERS_TABLE', 'INSERT', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_USERS_TABLE', 'UPDATE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_USERS_TABLE', 'DELETE', '&&securitySchemaName', 'CHEM_REG_PRIVILEGES');
	addObjectPriv('EDIT_USERS_TABLE', 'INSERT', '&&securitySchemaName', 'CHEM_REG_PRIVILEGES');
	addObjectPriv('EDIT_USERS_TABLE', 'UPDATE', '&&securitySchemaName', 'CS_SECURITY_PRIVILEGES');
	--- EDIT_ROLES_TABLE PRIVS
	addObjectPriv('EDIT_ROLES_TABLE', 'DELETE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_ROLES_TABLE', 'INSERT', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_ROLES_TABLE', 'DELETE', '&&securitySchemaName', 'CHEM_REG_PRIVILEGES');
	addObjectPriv('EDIT_ROLES_TABLE', 'INSERT', '&&securitySchemaName', 'CHEM_REG_PRIVILEGES');
	addObjectPriv('EDIT_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'CS_SECURITY_PRIVILEGES');

	--- ADD_ROLES_TABLE PRIVS
	addObjectPriv('ADD_ROLES_TABLE', 'DELETE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('ADD_ROLES_TABLE', 'INSERT', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('ADD_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('ADD_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'CS_SECURITY_PRIVILEGES');

	--- DELETE_ROLES_TABLE PRIVS
	addObjectPriv('DELETE_ROLES_TABLE', 'DELETE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('DELETE_ROLES_TABLE', 'INSERT', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('DELETE_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('DELETE_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'CS_SECURITY_PRIVILEGES');
END;
/