Connect &&securitySchemaName/&&securitySchemaPass@&&serverName




ALTER TABLE DB_RELATIONSHIP DROP CONSTRAINT FK_REL_CHILD_COLUMN;
ALTER TABLE DB_COLUMN DROP CONSTRAINT FK_COLUMN_TABLE;
ALTER TABLE DB_DTYP_DOPT DROP CONSTRAINT FK_DT_DO_DOPT;
ALTER TABLE DB_DTYP_DOPT DROP CONSTRAINT FK_DT_DO_DTYP;
ALTER TABLE DB_FORM_ITEM DROP CONSTRAINT FK_FORM_ITEM_FORM;
ALTER TABLE DB_FORM_ITEM DROP CONSTRAINT FK_FORM_ITEM_TABLE;
ALTER TABLE DB_FORM_ITEM DROP CONSTRAINT FK_FORM_ITEM_DISP;
ALTER TABLE DB_FORMGROUP DROP CONSTRAINT FK_FORMGROUP_COLUMN;
ALTER TABLE DB_FORMGROUP_TABLES DROP CONSTRAINT FK_FRMGRP_TABLES_FRMGRP;
ALTER TABLE DB_FORMGROUP_TABLES DROP CONSTRAINT FK_FRM_FRMGRP_TABLES_TABLE;
ALTER TABLE DB_FORMTYPE_DOPT DROP CONSTRAINT FK_FT_DO;
ALTER TABLE DB_FORMTYPE_DOPT DROP CONSTRAINT FK_FT_FT;
ALTER TABLE DB_FORM DROP CONSTRAINT FK_FORM_FORMGROUP;


DROP TABLE DB_RELATIONSHIP;
DROP TABLE DB_COLUMN;
DROP TABLE DB_DATATYPE_DISPLAY_TYPE;
DROP TABLE DB_DTYP_DOPT;
DROP TABLE DB_DISPLAY_OPTION;
DROP TABLE DB_DISPLAY_TYPE;
DROP TABLE DB_TABLE;
DROP TABLE DB_FORM_ITEM;
DROP TABLE DB_FORMGROUP;
DROP TABLE DB_FORMGROUP_TABLES;
DROP TABLE DB_FORMTYPE_DOPT;
DROP TABLE DB_FORM;
DROP TABLE DB_FORMTYPE;
DROP TABLE DB_QUERY_ITEM;
DROP TABLE DB_QUERY;
DROP TABLE DB_SCHEMA;
DROP TABLE DB_STRUCTURES;
DROP TABLE USER_SETTINGS;
DROP TABLE CSDOHITLISTID;
DROP TABLE CSDOHITLIST;

DROP VIEW DB_VW_COL_CONSTRAINTS;
DROP VIEW DB_VW_TABLE_SCHEMA;
DROP VIEW DB_VW_PARENT_TABLES;
DROP VIEW DB_VW_FORMITEMS_ALL;
DROP VIEW DB_VW_COLUMN_TABLE;
DROP VIEW DB_VW_FORMGROUP_TABLES;
DROP VIEW DB_VW_CHILD_TABLES;

DROP SEQUENCE CSDOHITLISTID_SEQ;
DROP SEQUENCE DB_FORM_ITEM_SEQ;
DROP SEQUENCE DB_TABLE_SEQ;
DROP SEQUENCE DB_FORM_SEQ;
DROP SEQUENCE DB_COLUMN_SEQ;
DROP SEQUENCE DB_QUERY_SEQ;
DROP SEQUENCE DB_FORMGROUP_SEQ;

commit;