


--#########################################################
--this add biosar_browser_privileges table to the cs_security schemas and creates 
--standard roles used by biosar browser.
--#########################################################

Connect &&securitySchemaName/&&securitySchemaPass@&&serverName

GRANT EXECUTE ON GrantOnCoreTableToAllRoles to &&schemaName;


		
Connect &&schemaName/&&schemaPass@&&serverName


Grant execute on ValidateAndRepairSchema to biosar_browser_admin;
Grant execute on ValidateAndRepairSchema to biosar_browser_admin;
--#########################################################

--If they are not installed you will see errors in the script indicating roles do not exist. This is OKAY.
--Do not be concerned about these script erros.


 
Connect &&securitySchemaName/&&securitySchemaPass@&&serverName

		
alter table BIOSAR_BROWSER_PRIVILEGES 
	add (EDIT_ANY_FORMGROUP NUMBER(1,0) null,
		 DUPLICATE_GRANTED_FORMGROUP NUMBER(1,0) null,
		EDIT_GRANTED_FORMGROUP NUMBER(1,0) null);
		
prompt 'On a new Oracle instance you may see Column Already Exists error above'


delete from &&securitySchemaName..OBJECT_PRIVILEGES where Upper(schema)='BIOSARDB';
commit;



Connect &&securitySchemaName/&&securitySchemaPass@&&serverName


			--MANAGE USER ADMIN TASKS
			
			GRANT SELECT, INSERT, DELETE, UPDATE ON &&securitySchemaName..BIOSAR_BROWSER_PRIVILEGES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON &&securitySchemaName..PEOPLE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON &&securitySchemaName..PRIVILEGE_TABLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON &&securitySchemaName..SECURITY_ROLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON &&securitySchemaName..SITES TO BIOSAR_BROWSER_ADMIN;


			--Grant to &&securitySchemaName with grant option
Connect &&schemaName/&&schemaPass@&&serverName
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_COLUMN TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP_TABLES TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE_DOPT TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM_ITEM TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DATATYPE_DISPLAY_TYPE TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DISPLAY_OPTION TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DISPLAY_TYPE TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DTYP_DOPT TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_RELATIONSHIP TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_SCHEMA TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_TABLE TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_CHILD_TABLES TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_COLUMN_TABLE TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMGROUP_TABLES TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMITEMS_ALL TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_PARENT_TABLES TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_TABLE_SCHEMA TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_HTTP_CONTENT_TYPE TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_INDEX_TYPE TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_XML_TEMPL_DEF TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.db_vw_formitems_compact TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.GLOBALS TO &&securitySchemaName with grant option;
			--GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_COL_CONSTRAINTS TO &&securitySchemaName with grant option;

			
			--ADMIN FORMGROUP MANAGEMENT TASKS
			
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP_TABLES TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE_DOPT TO &&securitySchemaName with grant option;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM_ITEM TO &&securitySchemaName with grant option;
		
			
			
			-- SEARCHING TASKS
		
			
			
			--ADMIN SCHEMA MANAGEMENT TASKS
Connect &&schemaName/&&schemaPass@&&serverName
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_COLUMN TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DATATYPE_DISPLAY_TYPE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DISPLAY_OPTION TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DISPLAY_TYPE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_DTYP_DOPT TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_RELATIONSHIP TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_SCHEMA TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_TABLE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_CHILD_TABLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_COLUMN_TABLE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMGROUP_TABLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMITEMS_ALL TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_PARENT_TABLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_TABLE_SCHEMA TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_HTTP_CONTENT_TYPE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_INDEX_TYPE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_XML_TEMPL_DEF TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.db_vw_formitems_compact TO BIOSAR_BROWSER_ADMIN;
			
			
			--ADMIN FORMGROUP MANAGEMENT TASKS
			
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP_TABLES TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE_DOPT TO BIOSAR_BROWSER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM_ITEM TO BIOSAR_BROWSER_ADMIN;
		
			
			
			-- SEARCHING TASKS
			
		
			
			
--CAN MANAGE FORMGROUPS USING MANAGE_YOUR_FORMGROUPS TOOL  CAN MAKE FORMGROUP PUBLIC

Connect &&securitySchemaName/&&securitySchemaPass@&&serverName
			--MANAGE USER ADMIN TASKS
			
			GRANT SELECT,INSERT,UPDATE ON &&securitySchemaName..BIOSAR_BROWSER_PRIVILEGES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT,INSERT,UPDATE  ON &&securitySchemaName..PEOPLE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT,INSERT,UPDATE  ON &&securitySchemaName..PRIVILEGE_TABLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT,INSERT,UPDATE ON &&securitySchemaName..SECURITY_ROLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT,INSERT,UPDATE  ON &&securitySchemaName..SITES TO BIOSAR_BROWSER_USER_ADMIN;
Connect &&schemaName/&&schemaPass@&&serverName	
			--ADMIN SCHEMA MANAGEMENT TASKS
			
			GRANT SELECT ON BIOSARDB.DB_COLUMN TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_DATATYPE_DISPLAY_TYPE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_OPTION TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_TYPE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_DTYP_DOPT TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_RELATIONSHIP TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_SCHEMA TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT ON BIOSARDB.DB_TABLE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_CHILD_TABLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_COLUMN_TABLE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMITEMS_ALL TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_PARENT_TABLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_TABLE_SCHEMA TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_HTTP_CONTENT_TYPE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_INDEX_TYPE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_XML_TEMPL_DEF TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.db_vw_formitems_compact TO BIOSAR_BROWSER_USER_ADMIN;

			

			
		
			--USER FORMGROUP MANAGEMENT TASKS
Connect &&schemaName/&&schemaPass@&&serverName

			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE_DOPT TO BIOSAR_BROWSER_USER_ADMIN;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM_ITEM TO BIOSAR_BROWSER_USER_ADMIN;
			
			-- SEARCHING TASKS
			
			
			
--CAN MANAGE FORMGROUPS USING MANAGE_YOUR_FORMGROUPS TOOL CANNOT MAKE FORMGROUP PUBLIC
			
Connect &&securitySchemaName/&&securitySchemaPass@&&serverName
			--MANAGE USER ADMIN TASKS
			
			GRANT SELECT ON &&securitySchemaName..BIOSAR_BROWSER_PRIVILEGES TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON &&securitySchemaName..PEOPLE TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON &&securitySchemaName..PRIVILEGE_TABLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON &&securitySchemaName..SECURITY_ROLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON &&securitySchemaName..SITES TO BIOSAR_BROWSER_USER;
Connect &&schemaName/&&schemaPass@&&serverName			
			--ADMIN SCHEMA MANAGEMENT TASKS
			
			GRANT SELECT ON BIOSARDB.DB_COLUMN TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_DATATYPE_DISPLAY_TYPE TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_OPTION TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_TYPE TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_DTYP_DOPT TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_RELATIONSHIP TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_SCHEMA TO BIOSAR_BROWSER_USER;
			GRANT SELECT ON BIOSARDB.DB_TABLE TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_CHILD_TABLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_COLUMN_TABLE TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMITEMS_ALL TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_PARENT_TABLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_TABLE_SCHEMA TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_HTTP_CONTENT_TYPE TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_INDEX_TYPE TO BIOSAR_BROWSER_USER;

			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_XML_TEMPL_DEF TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.db_vw_formitems_compact TO BIOSAR_BROWSER_USER;

			
			--USER FORMGROUP MANAGEMENT TASKS
			
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORMTYPE_DOPT TO BIOSAR_BROWSER_USER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_FORM_ITEM TO BIOSAR_BROWSER_USER;

			
			-- SEARCHING TASKS
			
			
			


--CAN USE ALREADY CREATED FORMGROUPS FOR SEARCHING
Connect &&securitySchemaName/&&securitySchemaPass@&&serverName		
			--MANAGE USER ADMIN TASKS
			
			GRANT SELECT ON &&securitySchemaName..BIOSAR_BROWSER_PRIVILEGES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON &&securitySchemaName..PEOPLE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON &&securitySchemaName..PRIVILEGE_TABLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON &&securitySchemaName..SECURITY_ROLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON &&securitySchemaName..SITES TO BIOSAR_BROWSER_USER_BROWSER;
			
Connect &&schemaName/&&schemaPass@&&serverName
			--ADMIN SCHEMA MANAGEMENT TASKS
			
			GRANT SELECT ON BIOSARDB.DB_COLUMN TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_DATATYPE_DISPLAY_TYPE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_OPTION TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_DISPLAY_TYPE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_DTYP_DOPT TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_RELATIONSHIP TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_SCHEMA TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_TABLE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_CHILD_TABLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_COLUMN_TABLE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_FORMITEMS_ALL TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_PARENT_TABLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_VW_TABLE_SCHEMA TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_HTTP_CONTENT_TYPE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_INDEX_TYPE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.DB_XML_TEMPL_DEF TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT, INSERT, DELETE, UPDATE ON BIOSARDB.db_vw_formitems_compact TO BIOSAR_BROWSER_USER_BROWSER;

			
			--USER FORMGROUP MANAGEMENT TASKS
			
			GRANT SELECT ON BIOSARDB.DB_FORM TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_FORMGROUP TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_FORMGROUP_TABLES TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_FORMTYPE TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_FORMTYPE_DOPT TO BIOSAR_BROWSER_USER_BROWSER;
			GRANT SELECT ON BIOSARDB.DB_FORM_ITEM TO BIOSAR_BROWSER_USER_BROWSER;
			
			-- SEARCHING TASKS
			
			

--#########################################################

--If they are not installed you will see errors in the script indicating roles do not exist. This is OKAY.
--Do not be concerned about these script erros.


 
Connect &&securitySchemaName/&&securitySchemaPass@&&serverName

delete from object_privileges where schema='BIOSARDB';
commit;


--- CAMSOFT_LOG_ON PRIVS

--- SEARCH_USING_FORMGROUP PRIVS

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_COMPACT');


INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');


INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('SEARCH_USING_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');



--- ADD_USER_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_COMPACT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
--- EDIT_USER_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');

--- DELETE_USER_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_USER_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');

--- SET_FORMGROUP_PUBLIC PRIVS

--- SEARCH_USING_FORMGROUP PRIVS

--- ADD_ADMIN_SCHEMA PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('ADD_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_INDEX_TYPE');

--- EDIT_ADMIN_SCHEMA PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_INDEX_TYPE');

--- DELETE_ADMIN_SCHEMA PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'UPDATE', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'INSERT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DELETE_ADMIN_SCHEMA', 'DELETE', 'BIOSARDB', 'DB_INDEX_TYPE');

--- EDIT_USERS_TABLE PRIVS

--- ADD_USERS_TABLE PRIVS

--- DELETE_USERS_TABLE PRIVS

--- EDIT_ROLES_TABLE PRIVS

--- ADD_ROLES_TABLE PRIVS

--- DELETE_ROLES_TABLE PRIVS

--- EDIT_PEOPLE_TABLE PRIVS

--- ADD_PEOPLE_TABLE PRIVS


--- DELETE_PEOPLE_TABLE PRIVS


--- IS_FORMGROUP_ROLE PRIVS



--- EDIT_ANY_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_ANY_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');

--- DUPLICATE_GRANTED_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DUPLICATE_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');

 --- EDIT_GRANTED_FORMGROUP PRIVS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_COLUMN');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DATATYPE_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_OPTION');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DISPLAY_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_DTYP_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_RELATIONSHIP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_CHILD_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_COLUMN_TABLE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_FORMITEMS_ALL');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_PARENT_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_VW_TABLE_SCHEMA');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_FORM_ITEM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMGROUP_TABLES');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE ');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORMTYPE_DOPT');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_FORM_ITEM');

INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_HTTP_CONTENT_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_INDEX_TYPE');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'SELECT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'UPDATE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'DELETE', 'BIOSARDB', 'DB_XML_TEMPL_DEF');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('EDIT_GRANTED_FORMGROUP', 'INSERT', 'BIOSARDB', 'DB_XML_TEMPL_DEF');

commit;


-- &&securitySchemaName object privileges
-- This procedure inserts into objects privilege table w/o complaining about duplicate constraint violations
DECLARE
	PROCEDURE addObjectPriv(appPriv in varchar2, priv in varchar2, schemaName in varchar2, objectName in varchar2) IS
	BEGIN
		execute immediate 'INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('''||appPriv||''','''||priv||''','''||schemaName||''','''||objectName||''')';
		commit;
	EXCEPTION
  		when DUP_VAL_ON_INDEX then
      		rollback;
 	END addObjectPriv;
BEGIN
	-- SEARCH_USING_FORMGROUP
	addObjectPriv('SEARCH_USING_FORMGROUP', 'SELECT', '&&securitySchemaName', 'BIOSAR_BROWSER_PRIVILEGES');
	addObjectPriv('SEARCH_USING_FORMGROUP', 'SELECT', '&&securitySchemaName', 'CS_SECURITY_PRIVILEGES');
	addObjectPriv('SEARCH_USING_FORMGROUP', 'SELECT', '&&securitySchemaName', 'PRIVILEGE_TABLES');
	addObjectPriv('SEARCH_USING_FORMGROUP', 'SELECT', '&&securitySchemaName', 'SECURITY_ROLES');
	--- EDIT_USERS_TABLE PRIVS
	addObjectPriv('EDIT_USERS_TABLE', 'DELETE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_USERS_TABLE', 'INSERT', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_USERS_TABLE', 'UPDATE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_USERS_TABLE', 'DELETE', '&&securitySchemaName', 'CHEM_REG_PRIVILEGES');
	addObjectPriv('EDIT_USERS_TABLE', 'INSERT', '&&securitySchemaName', 'CHEM_REG_PRIVILEGES');
	addObjectPriv('EDIT_USERS_TABLE', 'UPDATE', '&&securitySchemaName', 'CS_SECURITY_PRIVILEGES');
	--- EDIT_ROLES_TABLE PRIVS
	addObjectPriv('EDIT_ROLES_TABLE', 'DELETE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_ROLES_TABLE', 'INSERT', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('EDIT_ROLES_TABLE', 'DELETE', '&&securitySchemaName', 'CHEM_REG_PRIVILEGES');
	addObjectPriv('EDIT_ROLES_TABLE', 'INSERT', '&&securitySchemaName', 'CHEM_REG_PRIVILEGES');
	addObjectPriv('EDIT_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'CS_SECURITY_PRIVILEGES');

	--- ADD_ROLES_TABLE PRIVS
	addObjectPriv('ADD_ROLES_TABLE', 'DELETE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('ADD_ROLES_TABLE', 'INSERT', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('ADD_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('ADD_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'CS_SECURITY_PRIVILEGES');

	--- DELETE_ROLES_TABLE PRIVS
	addObjectPriv('DELETE_ROLES_TABLE', 'DELETE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('DELETE_ROLES_TABLE', 'INSERT', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('DELETE_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'SECURITY_ROLES');
	addObjectPriv('DELETE_ROLES_TABLE', 'UPDATE', '&&securitySchemaName', 'CS_SECURITY_PRIVILEGES');
END;
/
