--#########################################################
-- People
--######################################################### 
--' Inventory needs this user to exist
INSERT INTO people(person_id, user_id, user_code, supervisor_internal_id, last_name, site_id, active) VALUES (PEOPLE_SEQ.NEXTVAL,'UNKNOWN','UNKNOWN','1','UNKNOWN','1','0');

--#########################################################
-- Privilege_Tables
--######################################################### 
--' insert inventory entry
INSERT INTO PRIVILEGE_TABLES (PRIVILEGE_TABLE_NAME,APP_NAME,TABLE_SPACE) values('CHEMINV_PRIVILEGES','Inventory Enterprise','T_CHEMINV2');

--#########################################################
-- Object_Privileges
--######################################################### 
--' insert inventory entries
--' INV_BROWSE_ALL PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_COMPOUNDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CONTAINERS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CONTAINER_STATUS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CONTAINER_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_EXCLUDE_CONTAINER_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_LOCATIONS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_LOCATION_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_OWNERS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PICKLISTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PHYSICAL_STATE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PROJECT_JOB_INFO');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_REPORTFORMATS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_REPORTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_REPORTTYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_REQUESTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_RESERVATION_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_SOLVENTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_SUPPLIERS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_SYNONYMS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_UNITS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_UNIT_CONVERSION');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_UNIT_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_URL');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_USER_PROPERTIES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'UPDATE', '&&SchemaName', 'INV_USER_PROPERTIES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'INSERT', '&&SchemaName', 'INV_USER_PROPERTIES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_XMLDOCS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_XMLDOC_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_XSLTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_WELL_PARENT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PLATE_PARENT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_REPORTPARAMS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CONTAINER_CHECKIN_DETAILS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_WELL_COMPOUNDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_DATA_MAPS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_DATA_MAPPINGS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_MAP_FIELDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CONTAINER_BATCHES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_BATCH_STATUS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_UNIT_CONVERSION_FORMULA');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_GRAPHICS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_GRAPHIC_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_DOCS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_DOC_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ORG_UNIT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ORG_ROLES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ORG_USERS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'RACKS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'DOCS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'ORGANIZATION');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'BATCH');

INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'CHECKOUTCONTAINER');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'EXCLUDE_CONTAINERTYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'GUIUTILS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'RESERVATIONS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'REQUESTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'SELECTHAZMATDATA');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'SELECTSUBSTANCEHAZMATDATA');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'UPDATECONTAINERSTATUS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'GETLOCATIONPATH');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'XMLUtils');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'ISTRASHLOCATION');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'LOOKUPVALUE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'CHEMCALCS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'PLATECHEM');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'INSERTCHECKINDETAILS');

INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'GETNUMBEROFCOMPOUNDWELLS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'ISGRIDLOCATION');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'ISFROZENLOCATION');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'ISPLATETYPEALLOWED');

INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ALLOWED_CTYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ALLOWED_LTYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ALLOWED_PTYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_BARCODE_DESC');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ENUMERATION');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ENUMERATION_SET');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ENUM_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ESET_TYPE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_GRID_ELEMENT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_GRID_FILL_TEMPLATE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_GRID_FORMAT'); 
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_GRID_POSITION');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_GRID_STORAGE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PHYSICAL_PLATE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PLATES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PLATE_ACTIONS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PLATE_FORMAT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PLATE_HISTORY');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PLATE_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_WELLS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_ENUMERATED_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_GRID_LOCATION');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_GRID_LOCATION_LITE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_GRID_LOCATION_PARENT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_NONGRID_LOCATIONS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_PHYSICAL_PLATE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_PLATE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_PLATE_FORMAT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_PLATE_GRID_LOCATIONS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_PLATE_HISTORY');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_PLATE_LOCATIONS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_PLATE_LOCATIONS_ALL');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_WELL');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_WELL_FORMAT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_WELL_FLAT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_REG_BATCHES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_REG_STRUCTURES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_VW_REG_ALTIDS');

INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_COUNTRY');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_STATES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ADDRESS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_REQUEST_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_REQUEST_STATUS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_REQUEST_SAMPLES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ORDER_STATUS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ORDERS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_ORDER_CONTAINERS');

INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PICKLIST_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CUSTOM_FIELD_GROUPS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CUSTOM_FIELDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CONTAINER_BATCH_FIELDS');

INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'GETPRIMARYKEYIDS');

-- INV_CHANGEQTY_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CHANGEQTY_CONTAINER', 'EXECUTE', '&&SchemaName', 'UPDATECONTAINERQTYREMAINING');

-- INV_CHANGE_STATUS_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CHANGE_STATUS_CONTAINER', 'EXECUTE', '&&SchemaName', 'UPDATECONTAINER');

-- INV_CHECKOUT_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CHECKOUT_CONTAINER', 'EXECUTE', '&&SchemaName', 'CHECKOUTCONTAINER');

-- INV_CHECKIN_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CHECKIN_CONTAINER', 'EXECUTE', '&&SchemaName', 'CHECKOUTCONTAINER');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CHECKIN_CONTAINER', 'EXECUTE', '&&SchemaName', 'INSERTCHECKINDETAILS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CHECKIN_CONTAINER', 'EXECUTE', '&&SchemaName', 'CHECKINDEFAULTLOCATION');

-- INV_RESERVE_CONTAINER PRIVS

-- INV_RETIRE_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_RETIRE_CONTAINER', 'EXECUTE', '&&SchemaName', 'RETIRECONTAINER');

-- INV_PRINT_LABEL_CONTAINER
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_PRINT_LABEL_CONTAINER', 'EXECUTE', '&&SchemaName', 'REPORTPARAMS');

-- INV_PRINT_REPORT
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_PRINT_REPORT', 'EXECUTE', '&&SchemaName', 'REPORTPARAMS');

-- INV_CREATE_LOCATION PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_LOCATION', 'EXECUTE', '&&SchemaName', 'CREATELOCATION');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_LOCATION', 'EXECUTE', '&&SchemaName', 'EXCLUDE_CONTAINERTYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_LOCATION', 'EXECUTE', '&&SchemaName', 'PLATESETTINGS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_LOCATION', 'EXECUTE', '&&SchemaName', 'UPDATEADDRESS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_LOCATION', 'EXECUTE', '&&SchemaName', 'GETPKCOLUMN');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_LOCATION', 'EXECUTE', '&&SchemaName', 'UPDATETABLE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_LOCATION', 'EXECUTE', '&&SchemaName', 'CREATETABLEROW');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_LOCATION', 'EXECUTE', '&&SchemaName', 'DELETETABLEROW');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_LOCATION', 'EXECUTE', '&&SchemaName', 'REPORTS');

-- INV_EDIT_LOCATION PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_EDIT_LOCATION', 'EXECUTE', '&&SchemaName', 'UPDATELOCATION');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_EDIT_LOCATION', 'EXECUTE', '&&SchemaName', 'EXCLUDE_CONTAINERTYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_EDIT_LOCATION', 'EXECUTE', '&&SchemaName', 'UPDATEADDRESS');

-- INV_MOVE_LOCATION PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MOVE_LOCATION', 'EXECUTE', '&&SchemaName', 'MOVELOCATION');

-- INV_DELETE_LOCATION PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_DELETE_LOCATION', 'EXECUTE', '&&SchemaName', 'DELETELOCATION');

-- INV_CREATE_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_CONTAINER', 'EXECUTE', '&&SchemaName', 'CREATECONTAINER');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_CONTAINER', 'EXECUTE', '&&SchemaName', 'COPYCONTAINER');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_CONTAINER', 'EXECUTE', '&&SchemaName', 'UPDATECONTAINER');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_CONTAINER', 'EXECUTE', '&&SchemaName', 'UPDATEADDRESS');

-- INV_EDIT_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_EDIT_CONTAINER', 'EXECUTE', '&&SchemaName', 'UPDATEALLCONTAINERFIELDS');

-- INV_MOVE_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MOVE_CONTAINER', 'EXECUTE', '&&SchemaName', 'MOVECONTAINER');

-- INV_DELETE_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_DELETE_CONTAINER', 'EXECUTE', '&&SchemaName', 'DELETECONTAINER'); 
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_DELETE_CONTAINER', 'EXECUTE', '&&SchemaName', 'EMPTYTRASH'); 

-- INV_MANAGE_LINKS PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_LINKS', 'EXECUTE', '&&SchemaName', 'LINKS');

-- INV_MANAGE_SUBSTANCES PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'EXECUTE', '&&SchemaName', 'GETCOMPOUNDIDFROMNAME');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'EXECUTE', '&&SchemaName', 'COMPOUNDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'EXECUTE', '&&SchemaName', 'GETCOMPOUNDID');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'EXECUTE', '&&SchemaName', 'ISDUPLICATECOMPOUND');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'EXECUTE', '&&SchemaName', 'SUBSTANCENAMEEXISTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'INSERT', '&&SchemaName', 'INV_COMPOUNDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'UPDATE', '&&SchemaName', 'INV_COMPOUNDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'DELETE', '&&SchemaName', 'INV_COMPOUNDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'INSERT', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'UPDATE', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'DELETE', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');

-- INV_VIEW_AUDIT_TRAIL PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_VIEW_AUDIT_TRAIL', 'SELECT', '&&SchemaName', 'AUDIT_COLUMN');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_VIEW_AUDIT_TRAIL', 'SELECT', '&&SchemaName', 'AUDIT_COMPOUND');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_VIEW_AUDIT_TRAIL', 'SELECT', '&&SchemaName', 'AUDIT_DELETE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_VIEW_AUDIT_TRAIL', 'SELECT', '&&SchemaName', 'AUDIT_ROW'); 
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_VIEW_AUDIT_TRAIL', 'SELECT', '&&SchemaName', 'INV_VW_AUDIT_AGGREGATE');

-- INV_UPDATE_LOCATION_CONTENTS

-- INV_RECTIFY_LOCATION_CONTENTS

-- INV_ORDER_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_ORDER_CONTAINER', 'EXECUTE', '&&SchemaName', 'ORDERCONTAINER');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_ORDER_CONTAINER', 'SELECT', '&&SchemaName', 'INV_CONTAINER_ORDER_REASON');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_ORDER_CONTAINER', 'SELECT', '&&SchemaName', 'INV_CONTAINER_ORDER');

-- INV_REORDER_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_REORDER_CONTAINER', 'EXECUTE', '&&SchemaName', 'REORDERCONTAINER');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_REORDER_CONTAINER', 'SELECT', '&&SchemaName', 'INV_CONTAINER_ORDER');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_REORDER_CONTAINER', 'SELECT', '&&SchemaName', 'INV_CONTAINER_ORDER_REASON');

-- INV_CERTIFY_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CERTIFY_CONTAINER', 'EXECUTE', '&&SchemaName', 'CERTIFYCONTAINER');

-- INV_APPROVE_CONTAINER PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_APPROVE_CONTAINER', 'EXECUTE', '&&SchemaName', 'APPROVALS');

-- INV_EDIT_EHS_DATA
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_EDIT_EHS_DATA', 'EXECUTE', '&&SchemaName', 'INSERTHAZMATDATA');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_EDIT_EHS_DATA', 'EXECUTE', '&&SchemaName', 'UPDATEHAZMATDATA');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_EDIT_EHS_DATA', 'EXECUTE', '&&SchemaName', 'INSERTSUBSTANCEHAZMATDATA');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_EDIT_EHS_DATA', 'EXECUTE', '&&SchemaName', 'UPDATESUBSTANCEHAZMATDATA');

-- INV_CREATE_PLATE
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_PLATE', 'EXECUTE', '&&SchemaName', 'COPYPLATE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_PLATE', 'EXECUTE', '&&SchemaName', 'CREATEPLATEXML');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_PLATE', 'EXECUTE', '&&SchemaName', 'DATAMAPS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_PLATE', 'EXECUTE', '&&SchemaName', 'REFORMAT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_PLATE', 'EXECUTE', '&&SchemaName', 'UPDATEWELL');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_PLATE', 'EXECUTE', '&&SchemaName', 'CREATEPLATEFORMAT');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_PLATE', 'EXECUTE', '&&SchemaName', 'UpdatePlateFormat');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_PLATE', 'EXECUTE', '&&SchemaName', 'DeletePlateFormat');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_PLATE', 'EXECUTE', '&&SchemaName', 'UpdateWellFormat');

-- INV_MOVE_PLATE
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MOVE_PLATE', 'EXECUTE', '&&SchemaName', 'MOVEPLATE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MOVE_PLATE', 'EXECUTE', '&&SchemaName', 'MOVEPLATES');

-- INV_EDIT_PLATE
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_CREATE_PLATE', 'EXECUTE', '&&SchemaName', 'UPDATEPLATEATTRIBUTES');

-- INV_RETIRE_PLATE
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_RETIRE_PLATE', 'EXECUTE', '&&SchemaName', 'RETIREPLATE');

-- INV_REQUEST_PLATE

-- INV_DILUTE_PLATE
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_DILUTE_PLATE', 'EXECUTE', '&&SchemaName', 'SOLVATEPLATES');

-- INV_DELETE_PLATE
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_DELETE_PLATE', 'EXECUTE', '&&SchemaName', 'DELETEPLATE');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_DELETE_PLATE', 'EXECUTE', '&&SchemaName', 'DELETEPLATES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_DELETE_PLATE', 'EXECUTE', '&&SchemaName', 'EMPTYTRASH');

-- INV_PRINT_LABEL_PLATE
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_PRINT_LABEL_PLATE', 'EXECUTE', '&&SchemaName', 'REPORTPARAMS');

-- INV_MANAGE_PLATE_MAPS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_PLATE_MAPS', 'EXECUTE', '&&SchemaName', 'CREATEPLATEMAP');

-- INV_MANAGE_CUSTOM_FIELDS PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'INSERT', '&&SchemaName', 'INV_PICKLIST_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'UPDATE', '&&SchemaName', 'INV_PICKLIST_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'DELETE', '&&SchemaName', 'INV_PICKLIST_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'INSERT', '&&SchemaName', 'INV_PICKLISTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'UPDATE', '&&SchemaName', 'INV_PICKLISTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'DELETE', '&&SchemaName', 'INV_PICKLISTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'INSERT', '&&SchemaName', 'INV_CUSTOM_FIELD_GROUPS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'UPDATE', '&&SchemaName', 'INV_CUSTOM_FIELD_GROUPS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'DELETE', '&&SchemaName', 'INV_CUSTOM_FIELD_GROUPS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'INSERT', '&&SchemaName', 'INV_CUSTOM_FIELDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'UPDATE', '&&SchemaName', 'INV_CUSTOM_FIELDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'DELETE', '&&SchemaName', 'INV_CUSTOM_FIELDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'INSERT', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'UPDATE', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'DELETE', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');

Commit;
