--Copyright 1999-2003 CambridgeSoft Corporation. All rights reserved

--table creation script for CHEM_REG CS_SECURITY/Oracle version Copyright Cambridgesoft corp 1999-2001 all rights reserved
-- assumes that CS_SECURITY and REGDB tablespaces exist

--#########################################################
--CREATE TABLES
--#########################################################

Connect &&securitySchemaName/&&securitySchemaPass@&&serverName



DECLARE
	n NUMBER;
BEGIN
	SELECT count(*) INTO n 
		FROM DBA_Tab_Columns 
		WHERE Owner='CS_SECURITY' AND Table_Name='SECURITY_ROLES' AND Column_Name='COEIDENTIFIER';

	if n = 0 then
		execute immediate 'ALTER TABLE CS_SECURITY.SECURITY_ROLES ADD (COEIDENTIFIER VARCHAR2(100))';
	end if;
END;
/

--update our standard roles with the coeidentifier


UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='BIOASSAY'  WHERE ROLE_NAME='HTS_BROWSER';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='BIOASSAY'  WHERE ROLE_NAME='HTS_DATA_USER';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='BIOASSAY'  WHERE ROLE_NAME='HTS_ADMIN';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='BIOASSAY'  WHERE ROLE_NAME='HTS_SUPERVISING_ADMIN';

UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='INVENTORY'  WHERE ROLE_NAME='INV_BROWSER';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='INVENTORY'  WHERE ROLE_NAME='INV_CHEMIST';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='INVENTORY'  WHERE ROLE_NAME='INV_RECEIVING';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='INVENTORY'  WHERE ROLE_NAME='INV_FINANCE';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='INVENTORY'  WHERE ROLE_NAME='INV_REGISTRAR';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='INVENTORY'  WHERE ROLE_NAME='INV_ADMIN';

UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='CHEMACX'  WHERE ROLE_NAME='ACX_BROWSER';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='CHEMACX'  WHERE ROLE_NAME='ACX_BUYER';

UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='REGISTRATION'  WHERE ROLE_NAME='BROWSER';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='REGISTRATION'  WHERE ROLE_NAME='SUBMITTER';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='REGISTRATION'  WHERE ROLE_NAME='SUPERVISING_SCIENTIST';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='REGISTRATION'  WHERE ROLE_NAME='CHEMICAL_ADMINISTRATOR';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='REGISTRATION'  WHERE ROLE_NAME='SUPERVISING_CHEMICAL_ADMIN';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='REGISTRATION'  WHERE ROLE_NAME='PERFUME_CHEMIST';

UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='COE'  WHERE ROLE_NAME='CSS_ADMIN';
UPDATE CS_SECURITY.SECURITY_ROLES SET COEIDENTIFIER='COE'  WHERE ROLE_NAME='CSS_USER';
Commit;


--create generic schema privileges table

CREATE TABLE  COE_PRIVILEGES (
	ROLE_INTERNAL_ID NUMBER(8,0) not null,
	CAN_BROWSE NUMBER(1,0) null,
	CAN_INSERT NUMBER(1,0) null,
	CAN_UPDATE NUMBER(1,0) null,
	CAN_DELETE NUMBER(1,0) null,
	constraint PK_COE_PRIVS 
		primary key (ROLE_INTERNAL_ID) USING INDEX TABLESPACE &&indexTableSpaceName
	) 
;

INSERT INTO PRIVILEGE_TABLES (PRIVILEGE_TABLE_ID,APP_NAME, APP_URL,PRIVILEGE_TABLE_NAME,TABLE_SPACE) values(PRIVILEGE_TABLES_seq.NextVal,'COE', '', 'COE_PRIVILEGES', 'T_COE');