insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1482, 1004, null, 1, 1, '01', '01', 1, '01');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1483, 1004, null, 1, 2, '01', '02', 2, '02');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1484, 1004, null, 1, 3, '01', '03', 3, '03');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1485, 1004, null, 1, 4, '01', '04', 4, '04');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1486, 1004, null, 1, 5, '01', '05', 5, '05');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1487, 1005, null, 1, 1, '01', '01', 1, '01');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1488, 1005, null, 1, 2, '01', '02', 2, '02');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1489, 1005, null, 1, 3, '01', '03', 3, '03');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1490, 1005, null, 1, 4, '01', '04', 4, '04');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1491, 1005, null, 1, 5, '01', '05', 5, '05');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1492, 1005, null, 2, 1, '02', '01', 6, '06');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1493, 1005, null, 2, 2, '02', '02', 7, '07');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1494, 1005, null, 2, 3, '02', '03', 8, '08');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1495, 1005, null, 2, 4, '02', '04', 9, '09');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1496, 1005, null, 2, 5, '02', '05', 10, '10');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1497, 1006, null, 1, 1, '01', '01', 1, '01');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1498, 1006, null, 1, 2, '01', '02', 2, '02');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1499, 1006, null, 1, 3, '01', '03', 3, '03');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1500, 1006, null, 1, 4, '01', '04', 4, '04');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1501, 1006, null, 1, 5, '01', '05', 5, '05');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1502, 1006, null, 1, 6, '01', '06', 6, '06');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1503, 1006, null, 1, 7, '01', '07', 7, '07');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1504, 1006, null, 1, 8, '01', '08', 8, '08');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1505, 1006, null, 1, 9, '01', '09', 9, '09');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1506, 1006, null, 1, 10, '01', '10', 10, '10');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1507, 1006, null, 2, 1, '02', '01', 11, '11');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1508, 1006, null, 2, 2, '02', '02', 12, '12');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1509, 1006, null, 2, 3, '02', '03', 13, '13');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1510, 1006, null, 2, 4, '02', '04', 14, '14');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1511, 1006, null, 2, 5, '02', '05', 15, '15');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1512, 1006, null, 2, 6, '02', '06', 16, '16');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1513, 1006, null, 2, 7, '02', '07', 17, '17');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1514, 1006, null, 2, 8, '02', '08', 18, '18');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1515, 1006, null, 2, 9, '02', '09', 19, '19');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1516, 1006, null, 2, 10, '02', '10', 20, '20');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1517, 1006, null, 3, 1, '03', '01', 21, '21');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1518, 1006, null, 3, 2, '03', '02', 22, '22');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1519, 1006, null, 3, 3, '03', '03', 23, '23');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1520, 1006, null, 3, 4, '03', '04', 24, '24');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1521, 1006, null, 3, 5, '03', '05', 25, '25');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1522, 1006, null, 3, 6, '03', '06', 26, '26');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1523, 1006, null, 3, 7, '03', '07', 27, '27');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1524, 1006, null, 3, 8, '03', '08', 28, '28');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1525, 1006, null, 3, 9, '03', '09', 29, '29');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1526, 1006, null, 3, 10, '03', '10', 30, '30');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1527, 1006, null, 4, 1, '04', '01', 31, '31');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1528, 1006, null, 4, 2, '04', '02', 32, '32');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1529, 1006, null, 4, 3, '04', '03', 33, '33');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1530, 1006, null, 4, 4, '04', '04', 34, '34');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1531, 1006, null, 4, 5, '04', '05', 35, '35');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1532, 1006, null, 4, 6, '04', '06', 36, '36');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1533, 1006, null, 4, 7, '04', '07', 37, '37');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1534, 1006, null, 4, 8, '04', '08', 38, '38');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1535, 1006, null, 4, 9, '04', '09', 39, '39');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1536, 1006, null, 4, 10, '04', '10', 40, '40');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1537, 1006, null, 5, 1, '05', '01', 41, '41');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1538, 1006, null, 5, 2, '05', '02', 42, '42');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1539, 1006, null, 5, 3, '05', '03', 43, '43');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1540, 1006, null, 5, 4, '05', '04', 44, '44');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1541, 1006, null, 5, 5, '05', '05', 45, '45');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1542, 1006, null, 5, 6, '05', '06', 46, '46');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1543, 1006, null, 5, 7, '05', '07', 47, '47');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1544, 1006, null, 5, 8, '05', '08', 48, '48');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1545, 1006, null, 5, 9, '05', '09', 49, '49');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1546, 1006, null, 5, 10, '05', '10', 50, '50');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1547, 1006, null, 6, 1, '06', '01', 51, '51');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1548, 1006, null, 6, 2, '06', '02', 52, '52');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1549, 1006, null, 6, 3, '06', '03', 53, '53');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1550, 1006, null, 6, 4, '06', '04', 54, '54');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1551, 1006, null, 6, 5, '06', '05', 55, '55');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1552, 1006, null, 6, 6, '06', '06', 56, '56');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1553, 1006, null, 6, 7, '06', '07', 57, '57');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1554, 1006, null, 6, 8, '06', '08', 58, '58');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1555, 1006, null, 6, 9, '06', '09', 59, '59');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1556, 1006, null, 6, 10, '06', '10', 60, '60');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1557, 1006, null, 7, 1, '07', '01', 61, '61');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1558, 1006, null, 7, 2, '07', '02', 62, '62');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1559, 1006, null, 7, 3, '07', '03', 63, '63');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1560, 1006, null, 7, 4, '07', '04', 64, '64');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1561, 1006, null, 7, 5, '07', '05', 65, '65');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1562, 1006, null, 7, 6, '07', '06', 66, '66');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1563, 1006, null, 7, 7, '07', '07', 67, '67');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1564, 1006, null, 7, 8, '07', '08', 68, '68');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1565, 1006, null, 7, 9, '07', '09', 69, '69');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1566, 1006, null, 7, 10, '07', '10', 70, '70');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1567, 1006, null, 8, 1, '08', '01', 71, '71');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1568, 1006, null, 8, 2, '08', '02', 72, '72');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1569, 1006, null, 8, 3, '08', '03', 73, '73');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1570, 1006, null, 8, 4, '08', '04', 74, '74');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1571, 1006, null, 8, 5, '08', '05', 75, '75');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1572, 1006, null, 8, 6, '08', '06', 76, '76');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1573, 1006, null, 8, 7, '08', '07', 77, '77');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1574, 1006, null, 8, 8, '08', '08', 78, '78');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1575, 1006, null, 8, 9, '08', '09', 79, '79');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1576, 1006, null, 8, 10, '08', '10', 80, '80');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1577, 1006, null, 9, 1, '09', '01', 81, '81');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1578, 1006, null, 9, 2, '09', '02', 82, '82');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1579, 1006, null, 9, 3, '09', '03', 83, '83');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1580, 1006, null, 9, 4, '09', '04', 84, '84');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1581, 1006, null, 9, 5, '09', '05', 85, '85');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1582, 1006, null, 9, 6, '09', '06', 86, '86');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1583, 1006, null, 9, 7, '09', '07', 87, '87');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1584, 1006, null, 9, 8, '09', '08', 88, '88');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1585, 1006, null, 9, 9, '09', '09', 89, '89');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1586, 1006, null, 9, 10, '09', '10', 90, '90');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1587, 1006, null, 10, 1, '10', '01', 91, '91');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1588, 1006, null, 10, 2, '10', '02', 92, '92');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1589, 1006, null, 10, 3, '10', '03', 93, '93');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1590, 1006, null, 10, 4, '10', '04', 94, '94');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1591, 1006, null, 10, 5, '10', '05', 95, '95');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1592, 1006, null, 10, 6, '10', '06', 96, '96');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1593, 1006, null, 10, 7, '10', '07', 97, '97');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1594, 1006, null, 10, 8, '10', '08', 98, '98');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1595, 1006, null, 10, 9, '10', '09', 99, '99');
insert into INV_GRID_POSITION (GRID_POSITION_ID, GRID_FORMAT_ID_FK, GRID_FILL_TEMPLATE_ID_FK, ROW_INDEX, COL_INDEX, ROW_NAME, COL_NAME, SORT_ORDER, NAME)
values (1596, 1006, null, 10, 10, '10', '10', 100, '100');
commit;