INSERT INTO INV_RESERVATIONS (RESERVATION_ID, CONTAINER_ID_FK, USER_ID_FK, QTY_RESERVED, DATE_RESERVED, RESERVATION_TYPE_ID_FK, IS_ACTIVE, CANCELLED_BY_ID_FK)
	VALUES (1, 50, 'INVADMIN', 100, to_date('21-02-2002 17:02:35', 'dd-mm-yyyy hh24:mi:ss'), 2, 1, null);
INSERT INTO INV_RESERVATIONS (RESERVATION_ID, CONTAINER_ID_FK, USER_ID_FK, QTY_RESERVED, DATE_RESERVED, RESERVATION_TYPE_ID_FK, IS_ACTIVE, CANCELLED_BY_ID_FK)
	VALUES (2, 94, 'INVADMIN', 30, to_date('22-02-2002 16:25:38', 'dd-mm-yyyy hh24:mi:ss'), 2, 1, null);
INSERT INTO INV_RESERVATIONS (RESERVATION_ID, CONTAINER_ID_FK, USER_ID_FK, QTY_RESERVED, DATE_RESERVED, RESERVATION_TYPE_ID_FK, IS_ACTIVE, CANCELLED_BY_ID_FK)
	VALUES (21, 379, 'INVADMIN', 1, to_date('27-03-2002 20:35:23', 'dd-mm-yyyy hh24:mi:ss'), 3, 1, null);
INSERT INTO INV_RESERVATIONS (RESERVATION_ID, CONTAINER_ID_FK, USER_ID_FK, QTY_RESERVED, DATE_RESERVED, RESERVATION_TYPE_ID_FK, IS_ACTIVE, CANCELLED_BY_ID_FK)
	VALUES (22, 613, 'INVCHEMIST', 1, to_date('27-03-2002 20:41:31', 'dd-mm-yyyy hh24:mi:ss'), 3, 1, null);
commit;