insert into INV_GRID_FORMAT (GRID_FORMAT_ID, GRID_FORMAT_TYPE_FK, NAME, DESCRIPTION, ROW_COUNT, COL_COUNT, ROW_PREFIX, COL_PREFIX, ROW_USE_LETTERS, COL_USE_LETTERS, CELL_NAMING, NAME_DELIMETER, NAME_SEPARATOR, NUMBER_START_CORNER, NUMBER_DIRECTION, ZERO_PADDING_COUNT)
values (1004, 10, '1x5', null, 1, 5, null, null, 0, 0, 1, '/', null, 13, 17, 2);
insert into INV_GRID_FORMAT (GRID_FORMAT_ID, GRID_FORMAT_TYPE_FK, NAME, DESCRIPTION, ROW_COUNT, COL_COUNT, ROW_PREFIX, COL_PREFIX, ROW_USE_LETTERS, COL_USE_LETTERS, CELL_NAMING, NAME_DELIMETER, NAME_SEPARATOR, NUMBER_START_CORNER, NUMBER_DIRECTION, ZERO_PADDING_COUNT)
values (1005, 10, '2x5', null, 2, 5, null, null, 0, 0, 1, '/', null, 13, 17, 2);
insert into INV_GRID_FORMAT (GRID_FORMAT_ID, GRID_FORMAT_TYPE_FK, NAME, DESCRIPTION, ROW_COUNT, COL_COUNT, ROW_PREFIX, COL_PREFIX, ROW_USE_LETTERS, COL_USE_LETTERS, CELL_NAMING, NAME_DELIMETER, NAME_SEPARATOR, NUMBER_START_CORNER, NUMBER_DIRECTION, ZERO_PADDING_COUNT)
values (1006, 10, '10x10', null, 10, 10, null, null, 0, 0, 1, '/', null, 13, 17, 2);
commit;