INSERT INTO INV_ALLOWED_PTYPES (PLATE_TYPE_ID_FK,LOCATION_ID_FK) 
VALUES (1,1002);
INSERT INTO INV_ALLOWED_PTYPES (PLATE_TYPE_ID_FK,LOCATION_ID_FK) 
VALUES (2,1002);
INSERT INTO INV_ALLOWED_PTYPES (PLATE_TYPE_ID_FK,LOCATION_ID_FK) 
VALUES (3,1002);
INSERT INTO INV_ALLOWED_PTYPES (PLATE_TYPE_ID_FK,LOCATION_ID_FK) 
VALUES (4,1002);
INSERT INTO INV_ALLOWED_PTYPES (PLATE_TYPE_ID_FK,LOCATION_ID_FK) 
VALUES (5,1002);
Commit;