insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1010, 1006, 1248, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1011, 1006, 1349, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1012, 1006, 1450, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1013, 1006, 1551, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1014, 1006, 1652, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1015, 1006, 1753, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1016, 1006, 1854, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1017, 1006, 1955, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1018, 1006, 2056, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1019, 1006, 2157, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1005, 1005, 1193, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1006, 1005, 1204, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1007, 1005, 1215, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1008, 1005, 1226, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1009, 1005, 1237, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1000, 1004, 1163, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1001, 1004, 1169, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1002, 1004, 1175, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1003, 1004, 1181, null, null);
insert into INV_GRID_STORAGE (GRID_STORAGE_ID, GRID_FORMAT_ID_FK, LOCATION_ID_FK, CONTAINER_ID_FK, PLATE_ID_FK)
values (1004, 1004, 1187, null, null);
commit;