Alter table INV_REQUESTS
add(
"PROOF_APPROVAL" BLOB, 
"PROOF_APPROVAL_FILENAME" VARCHAR2(100 BYTE),
"PROOF_APPROVAL_FILETYPE" VARCHAR2(10 BYTE), 
"PROOF_APPROVAL_FILESIZE" NUMBER(10,0),
"SPECIAL_INSTRUCTIONS" VARCHAR2(1000 BYTE),
"BATCH_TYPE_ID_FK" Number,
CONSTRAINT "INV_REQUEST_BATCH_TYPE_ID_FK" FOREIGN KEY ("BATCH_TYPE_ID_FK") REFERENCES "INV_BATCH_TYPE" ("ID") ENABLE 
);

ALTER TABLE INV_REQUESTS 
MODIFY (DELIVERED_BY_ID_FK VARCHAR2(30));

ALTER TABLE INV_REQUESTS
MODIFY BATCH_ID_FK number;

