prompt 
prompt Starting "pkg_Gui_Util_body.sql"...
prompt 

CREATE OR REPLACE PACKAGE BODY "GUI_UTIL"
AS

 PROCEDURE GETPROJECTNAMEVALUELIST(
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   Select PROJECTID, NAME from VW_PROJECT;
 END GETPROJECTNAMEVALUELIST;


 PROCEDURE GETPREFIXNAMEVALUELIST(
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   Select SEQUENCEID, PREFIX from VW_SEQUENCE;
 END GETPREFIXNAMEVALUELIST;


 PROCEDURE GETACTIVECHEMISTNAMEVALUELIST(
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   Select PERSON_ID, USER_ID from CS_SECURITY.PEOPLE where ACTIVE=1 order by USER_ID;
 END GETACTIVECHEMISTNAMEVALUELIST;


 PROCEDURE GETCHEMISTNAMEVALUELIST(
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   Select PERSON_ID, USER_ID from CS_SECURITY.PEOPLE order by USER_ID;
 END GETCHEMISTNAMEVALUELIST;

   PROCEDURE GETFRAGMENTTYPESVALUELIST(
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   SELECT ID,DESCRIPTION from REGDB.VW_FRAGMENTTYPE;
 END GETFRAGMENTTYPESVALUELIST;

 PROCEDURE GETPROJECTLIST (
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   SELECT PROJECTID, NAME, ACTIVE, DESCRIPTION FROM REGDB.VW_PROJECT;
 END GETPROJECTLIST ;
 
 PROCEDURE GETACTIVEPROJECTLISTBYPERSONID (
  O_RS OUT CURSOR_TYPE, APersonID in Number) AS

 BEGIN
  OPEN O_RS FOR
   SELECT PRO.PROJECTID, PRO.NAME, PRO.ACTIVE, PRO.DESCRIPTION, PEO.PERSONID FROM VW_PROJECT PRO INNER JOIN
	VW_PEOPLEPROJECT PEO ON  PEO.PROJECTID = PRO.PROJECTID WHERE PRO.ACTIVE = 'T' AND PEO.PERSONID = APersonID;
 END GETACTIVEPROJECTLISTBYPERSONID ;

 PROCEDURE GETIDENTIFIERLIST (
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   SELECT ID, NAME, DESCRIPTION, ACTIVE FROM VW_IDENTIFIERTYPE WHERE ACTIVE = 'T';
 END GETIDENTIFIERLIST ;

 PROCEDURE GETFRAGMENTSLIST (
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   	    SELECT F.FRAGMENTID, F.CODE, F.DESCRIPTION, F.FRAGMENTTYPEID,F.STRUCTURE, F.MOLWEIGHT, F.FORMULA FROM REGDB.VW_FRAGMENT F
            ORDER BY F.FRAGMENTID;
 END GETFRAGMENTSLIST;  
 
 PROCEDURE GETSEQUENCELIST (
  O_RS OUT CURSOR_TYPE,  ASeqTypeID in Number) AS

 BEGIN
  OPEN O_RS FOR
   	    --Commented until changes in the DB a new couple of columns)
   	    --SELECT SEQUENCEID,REGNUMBERLENGTH, PREFIX, DISPLAY FROM VW_SEQUENCE WHERE TYPEID = ASeqTypeID; 
   	    SELECT SEQUENCEID,REGNUMBERLENGTH, PREFIX FROM VW_SEQUENCE ORDER BY PREFIX ASC;
 END GETSEQUENCELIST;
 
  --Gets the number of perm registries to be shown in the Reg home dashboard
  --Ulises - 02/26/2009
  PROCEDURE GETTEMPREGISTRIESCOUNT (
  ACount OUT NOCOPY Number) AS
 BEGIN
   	    SELECT count(*) INTO ACount FROM VW_TEMPORARYBATCH;     	   
 END GETTEMPREGISTRIESCOUNT;  
   
 --Gets the number of perm registries to be shown in the Reg home dashboard  
 --Ulises - 02/26/2009
 PROCEDURE GETPERMREGISTRIESCOUNT (
  ACount out Number) AS
 BEGIN
   	    SELECT count(*) INTO ACount FROM VW_MIXTURE;
 END GETPERMREGISTRIESCOUNT;

END "GUI_UTIL";
/