--Copyright 1999-2010 CambridgeSoft Corporation. All rights reserved

PROMPT Starting users.sql

DECLARE
   n   NUMBER;
BEGIN
   SELECT COUNT (*) INTO n
     FROM dba_users
    WHERE username = UPPER ('&&schemaName');

   IF n > 0 THEN
      EXECUTE IMMEDIATE 'DROP USER &&schemaName CASCADE';
   END IF;
END;
/

CREATE USER &&schemaName
   IDENTIFIED BY &&schemaPass
   DEFAULT TABLESPACE &&tableSpaceName
   TEMPORARY TABLESPACE &&temptableSpaceName;

GRANT CONNECT TO &&schemaName WITH ADMIN OPTION;
GRANT RESOURCE TO &&schemaName;
GRANT CREATE VIEW TO &&schemaName;

--This is necesary because oracle have a bug using EXECUTE IMMEDIATE with SPLIT PARTITION  A
GRANT CREATE TABLE TO &&schemaName;
GRANT CREATE SEQUENCE TO &&schemaName;

GRANT CREATE ANY TABLE TO &&schemaName;
GRANT CREATE ANY SEQUENCE TO &&schemaName;
GRANT ALL PRIVILEGES TO &&schemaName;

GRANT SELECT ANY DICTIONARY TO &&schemaName;

GRANT ALTER USER TO &&schemaName;
GRANT CREATE USER TO &&schemaName;
GRANT DROP USER TO &&schemaName;
GRANT ALTER ANY ROLE TO &&schemaName;
GRANT CREATE ROLE TO &&schemaName;
GRANT DROP ANY ROLE TO &&schemaName;
GRANT GRANT ANY ROLE TO &&schemaName;
GRANT GRANT ANY PRIVILEGE TO &&schemaName;
GRANT SELECT ANY TABLE TO &&schemaName;


-- Define the CS User Profile 
CREATE PROFILE csuserprofile LIMIT
       FAILED_LOGIN_ATTEMPTS UNLIMITED
       PASSWORD_LIFE_TIME UNLIMITED
       PASSWORD_REUSE_TIME UNLIMITED
       PASSWORD_REUSE_MAX UNLIMITED
       PASSWORD_LOCK_TIME 1/96                            --- means 15 minutes
       PASSWORD_GRACE_TIME UNLIMITED
       PASSWORD_VERIFY_FUNCTION NULL;

ALTER USER &&schemaName TEMPORARY TABLESPACE &&tempTableSpaceName;

DECLARE
   LExist NUMBER;
BEGIN
  SELECT COUNT (*) 
    INTO LExist   
    FROM DBA_ROLES
    WHERE UPPER(Role) = 'CSS_USER';
  
  IF LExist=0 THEN
    EXECUTE IMMEDIATE 'CREATE  ROLE CSS_USER NOT IDENTIFIED';
    EXECUTE IMMEDIATE 'GRANT  "CONNECT" TO "CSS_USER"';  
  END IF;

  SELECT COUNT (*) 
    INTO LExist   
    FROM DBA_USERS
    WHERE UPPER(UserName) = 'CSSUSER';
  
  IF LExist=0 THEN
    EXECUTE IMMEDIATE 'CREATE USER CSSUSER IDENTIFIED BY cssuser DEFAULT TABLESPACE &&tableSpaceName TEMPORARY TABLESPACE &&temptableSpaceName PROFILE DEFAULT ACCOUNT UNLOCK';
    EXECUTE IMMEDIATE '    GRANT CSS_USER TO CSSUSER';
    EXECUTE IMMEDIATE 'ALTER USER cssuser DEFAULT ROLE ALL';
  END IF;

  SELECT COUNT (*) 
    INTO LExist   
    FROM DBA_ROLES
    WHERE UPPER(Role) = 'CSS_ADMIN';
  
  IF LExist=0 THEN
    EXECUTE IMMEDIATE 'CREATE  ROLE CSS_ADMIN NOT IDENTIFIED';
    EXECUTE IMMEDIATE 'GRANT  "CONNECT" TO "CSS_ADMIN"';
  END IF;

  SELECT COUNT (*) 
    INTO LExist   
    FROM DBA_USERS
    WHERE UPPER(UserName) = 'CSSADMIN';
  
  IF LExist=0 THEN
    EXECUTE IMMEDIATE 'CREATE USER CSSADMIN IDENTIFIED BY CSSADMIN DEFAULT TABLESPACE &&tableSpaceName TEMPORARY TABLESPACE &&temptableSpaceName PROFILE DEFAULT ACCOUNT UNLOCK';
    EXECUTE IMMEDIATE 'GRANT CSS_ADMIN TO CSSADMIN';
    EXECUTE IMMEDIATE 'ALTER USER CSSADMIN DEFAULT ROLE ALL';
  END IF;
END;
/
