--Copyright Cambridgesoft Corp 2001-2003 all rights reserved
-- NOTE THIS SCRIPT MUST BE RUN FROM THE COMMAND LINE VERSION OF SQLPLUS
-- This script will not run from SQLPlus Worksheet!

-- Creates and grants to default DrugDeg Roles and populates CS_SECURITY tables
-- Assumes that CS_SECURITY schemas exist.
-- Assumes drops.sql was run to delete roles

Connect &&securitySchemaName/&&securitySchemaPass@&&serverName


GRANT EXECUTE ON GrantOnCoreTableToAllRoles to &&schemaName;

DROP TABLE D3_PRIVILEGES CASCADE CONSTRAINTS;

CREATE TABLE  D3_PRIVILEGES( 
	ROLE_INTERNAL_ID NUMBER(8,0) not null,
	D3_SEARCH NUMBER(1,0) null,
	constraint D3_PRIVILEGES_PK primary key(ROLE_INTERNAL_ID))
	TABLESPACE T_&&securitySchemaName;


--#########################################################
--CREATE ROLES
--#########################################################

-- ROLE creation script for DRUGDEG/Oracle version
-- Copyright Cambridgesoft corp 1999-2003 all rights reserved
CONNECT &&InstallUser/&&sysPass@&&serverName


-- CREATE_MASTER_ROLES

-- D3_BROWSER 
CREATE ROLE D3_BROWSER NOT IDENTIFIED;
REVOKE D3_BROWSER FROM SYSTEM;

GRANT CSS_USER TO D3_BROWSER;
--GRANT DOCMGR_BROWSER TO D3_BROWSER;



connect &&schemaName/&&schemaPass@&&serverName

-- D3_BROWSER
GRANT SELECT ON D3DATA.DRUGDEG_PARENTS 	TO D3_BROWSER;
GRANT SELECT ON D3DATA.DRUGDEG_DEGS    	TO D3_BROWSER;
GRANT SELECT ON D3DATA.DRUGDEG_EXPTS   	TO D3_BROWSER;
GRANT SELECT ON D3DATA.DRUGDEG_MECHS   	TO D3_BROWSER;
GRANT SELECT ON D3DATA.DRUGDEG_BASE64  	TO D3_BROWSER;
GRANT SELECT ON D3DATA.DRUGDEG_SALTS   	TO D3_BROWSER;
GRANT SELECT ON D3DATA.DRUGDEG_CONDS    	TO D3_BROWSER;
GRANT SELECT ON D3DATA.DRUGDEG_FGROUPS    	TO D3_BROWSER;
GRANT SELECT ON D3DATA.DRUGDEG_DEGSFGROUP 	TO D3_BROWSER;
GRANT SELECT ON D3DATA.DRUGDEG_STATUSES   	TO D3_BROWSER;
	

commit;


Connect &&securitySchemaName/&&securitySchemaPass@&&serverName

-- SECURITY_ROLES
delete from SECURITY_ROLES where (PRIVILEGE_TABLE_INT_ID) IN (SELECT PRIVILEGE_TABLE_ID FROM PRIVILEGE_TABLES WHERE PRIVILEGE_TABLE_NAME = 'D3_PRIVILEGES');
commit;

--PRIVELEGE_TABLES
delete from PRIVILEGE_TABLES where TABLE_SPACE = 'T_D3DATA';
commit;

INSERT INTO PRIVILEGE_TABLES (PRIVILEGE_TABLE_NAME,APP_NAME,TABLE_SPACE) values('D3_PRIVILEGES','D3','T_D3DATA');

INSERT INTO SECURITY_ROLES( ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME,COEIDENTIFIER)
	values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'D3_BROWSER','D3' );

INSERT INTO D3_PRIVILEGES	(ROLE_INTERNAL_ID,			D3_SEARCH)
	values			(SECURITY_ROLES_seq.CURRVAL,		'1');



Commit;


DELETE FROM &&securitySchemaName..OBJECT_PRIVILEGES WHERE Schema = '&&SchemaName';

--SEARCH
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('D3_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_PARENTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('D3_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_DEGS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('D3_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_EXPTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('D3_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_MECHS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('D3_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_BASE64');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('D3_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_SALTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('D3_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_CONDS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('D3_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_FGROUPS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('D3_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_DEGSFGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('D3_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_STATUSES');


Commit;

-- MRE changed 11/04/04
-- password now in the parameters.sql file
--Connect &&SchemaName/oracle@&&ServerName;
connect &&schemaName/&&schemaPass@&&serverName;


--- Grant all object permissions to CS_SECURITY
GRANT SELECT ON D3DATA.DRUGDEG_PARENTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON D3DATA.DRUGDEG_DEGS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON D3DATA.DRUGDEG_EXPTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON D3DATA.DRUGDEG_MECHS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON D3DATA.DRUGDEG_BASE64 TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON D3DATA.DRUGDEG_SALTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON D3DATA.DRUGDEG_CONDS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON D3DATA.DRUGDEG_FGROUPS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON D3DATA.DRUGDEG_DEGSFGROUP TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON D3DATA.DRUGDEG_STATUSES TO &&securitySchemaName WITH GRANT OPTION;

commit;
