CREATE TABLE "INV_CUSTOM_FIELD_GROUP_TYPES"(
   	"CUSTOM_FIELD_GROUP_TYPE_ID" NUMBER(4) NOT NULL, 
	"CUSTOM_FIELD_GROUP_TYPE_NAME" VARCHAR2(100), 
	CONSTRAINT "INV_CSTM_FLD_GRP_TYP_ID_PK" 
		PRIMARY KEY("CUSTOM_FIELD_GROUP_TYPE_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	);
	
CREATE SEQUENCE SEQ_CUSTOM_FIELD_GROUP_TYPE_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER "TRG_INV_CSTM_FLD_GRP_TYP_ID"
    BEFORE INSERT
    ON "INV_CUSTOM_FIELD_GROUP_TYPES"
    FOR EACH ROW
BEGIN
	if :new.custom_field_group_type_id is null then
		select SEQ_CUSTOM_FIELD_GROUP_TYPE_ID.nextval into :new.custom_field_group_type_id from dual;
	end if;
END;
/
