//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ToolBar {
    
    /// <summary>
    /// DivForMasterDV control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivForMasterDV;
    
    /// <summary>
    /// CurrentSchemaHidden control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField CurrentSchemaHidden;
    
    /// <summary>
    /// AddSchemaImageButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_ImageButton AddSchemaImageButton;
    
    /// <summary>
    /// RemoveSchemaImageButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_ImageButton RemoveSchemaImageButton;
    
    /// <summary>
    /// RefreshSchemaImageButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_ImageButton RefreshSchemaImageButton;
    
    /// <summary>
    /// DivForRegularDV control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl DivForRegularDV;
    
    /// <summary>
    /// NameAndDescImageButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_ImageButton NameAndDescImageButton;
    
    /// <summary>
    /// SecurityImageButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_ImageButton SecurityImageButton;
    
    /// <summary>
    /// BaseTableImageButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_ImageButton BaseTableImageButton;
    
    /// <summary>
    /// CancelImageButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_ImageButton CancelImageButton;
    
    /// <summary>
    /// DoneImageButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_ImageButton DoneImageButton;
}
