CREATE OR REPLACE VIEW INV_VW_AUDIT_COLUMN_DISP ( RAID,
	CAID,
	COLUMN_NAME,
	OLDVALUE,
	NEWVALUE
) AS SELECT
  raid,
  caid,
  column_name,
  DECODE(column_name,
    'LOCATION_ID_FK', (select LOCATION_NAME from INV_LOCATIONS where LOCATION_ID = old_value),
    'DEF_LOCATION_ID_FK', (select LOCATION_NAME from INV_LOCATIONS where LOCATION_ID = old_value),
    'CONTAINER_TYPE_ID_FK', (select CONTAINER_TYPE_NAME from INV_CONTAINER_TYPES where CONTAINER_TYPE_ID = old_value),
    'CONTAINER_STATUS_ID_FK', (select CONTAINER_STATUS_NAME from INV_CONTAINER_STATUS where CONTAINER_STATUS_ID = old_value),
    'UNIT_OF_MEAS_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = old_value),
    'UNIT_OF_WGHT_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = old_value),
    'UNIT_OF_CONC_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = old_value),
    'UNIT_OF_PURITY_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = old_value),
    'UNIT_OF_DENSITY_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = old_value),
    'SUPPLIER_ID_FK',(select SUPPLIER_NAME from INV_SUPPLIERS where SUPPLIER_ID = old_value),
    'UNIT_OF_COST_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = old_value),
    old_value) AS oldvalue,
  DECODE(column_name,
    'LOCATION_ID_FK', (select LOCATION_NAME from INV_LOCATIONS where LOCATION_ID = new_value),
    'CONTAINER_TYPE_ID_FK', (select CONTAINER_TYPE_NAME from INV_CONTAINER_TYPES where CONTAINER_TYPE_ID = new_value),
    'CONTAINER_STATUS_ID_FK', (select CONTAINER_STATUS_NAME from INV_CONTAINER_STATUS where CONTAINER_STATUS_ID = new_value),
    'UNIT_OF_MEAS_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = new_value),
    'UNIT_OF_WGHT_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = new_value),
    'UNIT_OF_CONC_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = new_value),
    'UNIT_OF_PURITY_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = new_value),
    'UNIT_OF_DENSITY_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = new_value),
    'SUPPLIER_ID_FK',(select SUPPLIER_NAME from INV_SUPPLIERS where SUPPLIER_ID = new_value),
    'UNIT_OF_COST_ID_FK',(select UNIT_NAME from INV_UNITS where UNIT_ID = new_value),
    new_value) AS newvalue
FROM audit_column;
   
