CREATE OR REPLACE VIEW INV_VW_PHYSICAL_PLATE (
   PHYS_PLATE_ID,
   PHYS_PLATE_NAME,
   ROW_COUNT,
   COL_COUNT,
   ROW_PREFIX,
   COL_PREFIX,
   ROW_USE_LETTERS,
   COL_USE_LETTERS,
   NAME_SEPARATOR,
   NUMBER_START_CORNER,
   NUMBER_DIRECTION,
   SUPPLIER_ID_FK,
   GRID_FORMAT_ID_FK,
   IS_PRE_BARCODED,
   WELL_CAPACITY,
   CAPACITY_UNIT_ID_FK
)
AS
   SELECT PHYS_PLATE_ID,
	  PHYS_PLATE_NAME,
	  ROW_COUNT,
	   COL_COUNT,
	   ROW_PREFIX,
	   COL_PREFIX,
	   ROW_USE_LETTERS,
	   COL_USE_LETTERS,
	   NAME_SEPARATOR,
	   NUMBER_START_CORNER,
	   NUMBER_DIRECTION,
	   SUPPLIER_ID_FK,
	   GRID_FORMAT_ID_FK,
	   IS_PRE_BARCODED,
	   WELL_CAPACITY,
	   CAPACITY_UNIT_ID_FK
     FROM INV_PHYSICAL_PLATE, INV_GRID_FORMAT
    WHERE GRID_FORMAT_ID_FK = GRID_FORMAT_ID;