CREATE TABLE "INV_CUSTOM_FIELDS"(
    "CUSTOM_FIELD_ID" NUMBER(4) NOT NULL,
    "PICKLIST_TYPE_ID_FK" NUMBER(4) NOT NULL,
    "CUSTOM_FIELD_GROUP_ID_FK" NUMBER(4),
    "CUSTOM_FIELD_NAME" VARCHAR2(50) NOT NULL,
    "READONLY" CHAR(1),
    "NULL_PICKLIST_ID_FK" NUMBER(8) NOT NULL,
    CONSTRAINT "INV_CUSTOM_FIELDS_PK"
        PRIMARY KEY("CUSTOM_FIELD_ID") USING INDEX TABLESPACE &&indexTableSpaceName
)
;

ALTER TABLE INV_CUSTOM_FIELDS ADD CONSTRAINT CustomFields_U UNIQUE (CUSTOM_FIELD_NAME);

CREATE SEQUENCE SEQ_INV_CUSTOM_FIELDS INCREMENT BY 1 START WITH 1000 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE;

ALTER TABLE "INV_CUSTOM_FIELDS" ADD CONSTRAINT INV_CUSTOM_FIELDS_FK1 FOREIGN KEY(CUSTOM_FIELD_GROUP_ID_FK) REFERENCES &&schemaName..INV_CUSTOM_FIELD_GROUPS(CUSTOM_FIELD_GROUP_ID);
ALTER TABLE "INV_CUSTOM_FIELDS" ADD CONSTRAINT INV_CUSTOM_FIELDS_FK2 FOREIGN KEY(PICKLIST_TYPE_ID_FK) REFERENCES &&schemaName..INV_PICKLIST_TYPES(PICKLIST_TYPE_ID);
ALTER TABLE "INV_CUSTOM_FIELDS" ADD CONSTRAINT INV_CUSTOM_FIELDS_FK3 FOREIGN KEY(NULL_PICKLIST_ID_FK) REFERENCES &&schemaName..INV_PICKLISTS(PICKLIST_ID);

CREATE OR REPLACE TRIGGER "TRG_INV_CUSTOM_FIELDS"
    BEFORE INSERT
    ON "INV_CUSTOM_FIELDS"
    FOR EACH ROW
    begin
        if :new.Custom_Field_ID is null then
            select seq_Inv_Custom_Fields.nextval into :new.Custom_Field_ID from dual;
        end if;
    end;
/
