--Copyright 1999-2003 CambridgeSoft Corporation. All rights reserved

prompt 
prompt Starting "Alter_CoeDB_for_ChemReg_ora.sql"...
prompt 


--#########################################################
--CREATE OBJECTS
--#########################################################

ALTER TABLE CHEM_REG_PRIVILEGES ADD (LOAD_SAVE_RECORD NUMBER(1), ADD_BATCH_PERM NUMBER(1));

update CHEM_REG_PRIVILEGES set ADD_BATCH_PERM=1
where ROLE_INTERNAL_ID IN (SELECT ROLE_ID FROM SECURITY_ROLES where ROLE_NAME IN ('SUPERVISING_CHEMICAL_ADMIN','SUPERVISING_SCIENTIST','CHEMICAL_ADMINISTRATOR'));

update CHEM_REG_PRIVILEGES set LOAD_SAVE_RECORD = 1;
commit;

prompt Removing object privileges for obsolete tables...
delete from object_privileges where object_name = 'STRUCTURE_MIXTURE';
delete from object_privileges where object_name = 'TEST_SAMPLES';
commit;


--#########################################################
-- COEFORM,COEDATAVIEW  
--#########################################################

DELETE COEFORM WHERE ID IN (4002,4003,4005,4006,4007,4010,4011,4012,4013,4014);	
DELETE COEDATAVIEW WHERE ID IN (4002,4003,4004,4005,4006,4007,4008,8001);
COMMIT;	

--#########################################################
--GRANTS
--#########################################################
 
GRANT SELECT ON People TO &&schemaName;
GRANT SELECT ON Chem_reg_privileges TO &&schemaName;
GRANT SELECT ON Privilege_tables TO &&schemaName;
GRANT SELECT ON Security_roles TO &&schemaName;

--#########################################################
--CREATE_MASTER_ROLES
--#########################################################
--BROWSER
	GRANT "CONNECT" TO "BROWSER";
--SUBMITTER
	GRANT CONNECT TO SUBMITTER;
--SUPERVISING_SCIENTIST
	GRANT CONNECT TO SUPERVISING_SCIENTIST;
--CHEMICAL_ADMINISTRATOR
	GRANT CONNECT TO CHEMICAL_ADMINISTRATOR;
--SUPERVISING_CHEMICAL_ADMIN
	GRANT CONNECT TO SUPERVISING_CHEMICAL_ADMIN;
--PERFUME_CHEMIST
	GRANT CONNECT TO PERFUME_CHEMIST;


-- System Privileges

GRANT CSS_USER TO CHEMICAL_ADMINISTRATOR;
GRANT CSS_USER TO SUPERVISING_SCIENTIST;
GRANT CSS_USER TO SUBMITTER;
GRANT CSS_USER TO BROWSER;
Grant CSS_USER to PERFUME_CHEMIST;

GRANT EXECUTE ON GrantOnCoreTableToAllRoles to &&schemaName;

-- BROWSER 
	GRANT SELECT ON SECURITY_ROLES TO BROWSER;
	GRANT SELECT ON PRIVILEGE_TABLES TO BROWSER;
	GRANT SELECT ON CHEM_REG_PRIVILEGES TO BROWSER;
-- SUBMITTER
	GRANT SELECT ON SECURITY_ROLES TO SUBMITTER;
	GRANT SELECT ON PRIVILEGE_TABLES TO SUBMITTER;
	GRANT SELECT ON CHEM_REG_PRIVILEGES TO SUBMITTER;
-- SUPERVISING_SCIENTIST
	GRANT UPDATE ON PEOPLE TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON SECURITY_ROLES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON PRIVILEGE_TABLES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON CHEM_REG_PRIVILEGES TO SUPERVISING_SCIENTIST;
-- CHEMICAL_ADMINISTRATOR
	GRANT SELECT ON SECURITY_ROLES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT ON PRIVILEGE_TABLES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT ON CHEM_REG_PRIVILEGES TO CHEMICAL_ADMINISTRATOR;
	GRANT INSERT,UPDATE  ON PEOPLE TO CHEMICAL_ADMINISTRATOR;
	GRANT INSERT, UPDATE ON SITES TO CHEMICAL_ADMINISTRATOR;
-- SUPERVISING_CHEMICAL_ADMIN
	GRANT INSERT,UPDATE,DELETE ON SITES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT INSERT,UPDATE,DELETE ON PEOPLE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON SECURITY_ROLES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON CHEM_REG_PRIVILEGES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT ON PRIVILEGE_TABLES TO SUPERVISING_CHEMICAL_ADMIN;
-- PERFUME_CHEMIST
	GRANT SELECT ON SECURITY_ROLES TO PERFUME_CHEMIST;
	GRANT SELECT ON PRIVILEGE_TABLES TO PERFUME_CHEMIST;
	GRANT SELECT ON CHEM_REG_PRIVILEGES TO PERFUME_CHEMIST;

prompt grant on coedblibrary...
grant execute on coedb.coedblibrary to &&schemaName;


--#########################################################
--DUMPs
--#########################################################

host imp &&securitySchemaName/&&securitySchemaPass@&&serverName FILE="sql\Patches\Patch 11.0.0\Dump\CoeForm.dmp" LOG="sql\Patches\Patch 11.0.0\log_ImpCoeForm.txt" IGNORE=YES
host imp &&securitySchemaName/&&securitySchemaPass@&&serverName FILE="sql\Patches\Patch 11.0.0\Dump\CoeDataView.dmp" LOG="sql\Patches\Patch 11.0.0\log_ImpCoeDataView.txt" IGNORE=YES


