//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerkinElmer.COE.Inventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_COMPOUNDS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_COMPOUNDS()
        {
            this.INV_CONTAINERS = new HashSet<INV_CONTAINERS>();
        }
    
        public int COMPOUND_ID { get; set; }
        public Nullable<int> MOL_ID { get; set; }
        public string CAS { get; set; }
        public string ACX_ID { get; set; }
        public string SUBSTANCE_NAME { get; set; }
        public string BASE64_CDX { get; set; }
        public Nullable<decimal> MOLECULAR_WEIGHT { get; set; }
        public decimal DENSITY { get; set; }
        public Nullable<decimal> CLOGP { get; set; }
        public Nullable<int> ROTATABLE_BONDS { get; set; }
        public Nullable<decimal> TOT_POL_SURF_AREA { get; set; }
        public Nullable<int> HBOND_ACCEPTORS { get; set; }
        public Nullable<int> HBOND_DONORS { get; set; }
        public string ALT_ID_1 { get; set; }
        public string ALT_ID_2 { get; set; }
        public string ALT_ID_3 { get; set; }
        public string ALT_ID_4 { get; set; }
        public string ALT_ID_5 { get; set; }
        public string CONFLICTING_FIELDS { get; set; }
        public long RID { get; set; }
        public string CREATOR { get; set; }
        public System.DateTime TIMESTAMP { get; set; }
        public Nullable<int> REG_ID_FK { get; set; }
        public Nullable<int> BATCH_NUMBER_FK { get; set; }
        public Nullable<int> CPD_INTERNAL_ID_FK { get; set; }
        public Nullable<short> LOCATION_TYPE_ID_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_CONTAINERS> INV_CONTAINERS { get; set; }
    }
}
