//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerkinElmer.COE.Inventory.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_LOCATION_TYPES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_LOCATION_TYPES()
        {
            this.INV_COMPOUNDS = new HashSet<INV_COMPOUNDS>();
            this.INV_CONTAINERS = new HashSet<INV_CONTAINERS>();
            this.INV_LOCATIONS = new HashSet<INV_LOCATIONS>();
        }
    
        public int LOCATION_TYPE_ID { get; set; }
        public string LOCATION_TYPE_NAME { get; set; }
        public Nullable<short> GRAPHIC_ID_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_COMPOUNDS> INV_COMPOUNDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_CONTAINERS> INV_CONTAINERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_LOCATIONS> INV_LOCATIONS { get; set; }
    }
}
