CREATE OR REPLACE PACKAGE ORGANIZATION
    IS

	FUNCTION CREATEORGANIZATION
		(
        p_OrgName in INV_ORG_UNIT.ORG_NAME%TYPE ,
        P_OrgType in INV_ORG_UNIT.ORG_TYPE_ID_FK%TYPE,
        P_Users in VARCHAR2,
        P_Roles in VARCHAR2
        ) RETURN INV_ORG_UNIT.ORG_UNIT_ID%TYPE;

	FUNCTION DELETEORGANIZATION
		(p_OrgUnitID in INV_ORG_UNIT.ORG_UNIT_ID%TYPE) RETURN INTEGER;

	FUNCTION UPDATEORGANIZATION
		(
        p_OrgUnitID IN INV_ORG_UNIT.ORG_UNIT_ID%TYPE, 
        p_OrgName IN INV_ORG_UNIT.ORG_NAME%TYPE,
        p_OrgType IN INV_ORG_UNIT.ORG_TYPE_ID_FK%TYPE,
        P_Users in VARCHAR2,
        P_Roles in VARCHAR2
        ) RETURN INV_ORG_UNIT.ORG_UNIT_ID%TYPE;

END ORGANIZATION;



/

show errors;