//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datalytix.browseDataview.
        /// </summary>
        internal static string AdavncedDataviewSearchHelp {
            get {
                return ResourceManager.GetString("AdavncedDataviewSearchHelp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string AVERAGE_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("AVERAGE_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG.
        /// </summary>
        internal static string AVERAGE_FUNCTION {
            get {
                return ResourceManager.GetString("AVERAGE_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between.
        /// </summary>
        internal static string BETWEEN_OPERATOR {
            get {
                return ResourceManager.GetString("BETWEEN_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear form.
        /// </summary>
        internal static string ClearFormLinkLabelText {
            get {
                return ResourceManager.GetString("ClearFormLinkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear the Query?.
        /// </summary>
        internal static string ClearQueryMsg {
            get {
                return ResourceManager.GetString("ClearQueryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clear the Result definition?.
        /// </summary>
        internal static string ClearResultDefinitionMsg {
            get {
                return ResourceManager.GetString("ClearResultDefinitionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string CONTAINS_OPERATOR {
            get {
                return ResourceManager.GetString("CONTAINS_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string COUNT_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("COUNT_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNT.
        /// </summary>
        internal static string COUNT_FUNCTION {
            get {
                return ResourceManager.GetString("COUNT_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative sample standard deviation.
        /// </summary>
        internal static string CUM_SAMP_STDDEV_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("CUM_SAMP_STDDEV_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDDEV_SAMP.
        /// </summary>
        internal static string CUM_SAMP_STDDEV_FUNCTION {
            get {
                return ResourceManager.GetString("CUM_SAMP_STDDEV_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative sample variance.
        /// </summary>
        internal static string CUM_SAMP_VARIANCE_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("CUM_SAMP_VARIANCE_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAR_SAMP.
        /// </summary>
        internal static string CUM_SAMP_VARIANCE_FUNCTION {
            get {
                return ResourceManager.GetString("CUM_SAMP_VARIANCE_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected dataview has been modified. Are you sure want to reload?.
        /// </summary>
        internal static string DataView_Modification_Alert {
            get {
                return ResourceManager.GetString("DataView_Modification_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataview not available or doesn&apos;t have permissions..
        /// </summary>
        internal static string Dataview_NotFound {
            get {
                return ResourceManager.GetString("Dataview_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected dataview has been modified. Please refresh dataviews and try again..
        /// </summary>
        internal static string Daview_Modification_Error {
            get {
                return ResourceManager.GetString("Daview_Modification_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equal.
        /// </summary>
        internal static string EQUAL_OPERAOTR {
            get {
                return ResourceManager.GetString("EQUAL_OPERAOTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load the picklist values for the field.
        /// </summary>
        internal static string Field_LargeData_Message {
            get {
                return ResourceManager.GetString("Field_LargeData_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Dataview.
        /// </summary>
        internal static string Form_Browse_DataView_Title {
            get {
                return ResourceManager.GetString("Form_Browse_DataView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datalytix for TIBCO Spotfire®.
        /// </summary>
        internal static string FORM_TITLE {
            get {
                return ResourceManager.GetString("FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} [{2}].
        /// </summary>
        internal static string Form_Title_Format {
            get {
                return ResourceManager.GetString("Form_Title_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater than.
        /// </summary>
        internal static string GREATERTHAN_OPERATOR {
            get {
                return ResourceManager.GetString("GREATERTHAN_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to greater than or equal.
        /// </summary>
        internal static string GREATERTHANEQUAL_OPERATOR {
            get {
                return ResourceManager.GetString("GREATERTHANEQUAL_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string HelpDefaultTopicId {
            get {
                return ResourceManager.GetString("HelpDefaultTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datalytix.help.
        /// </summary>
        internal static string HelpResourceName {
            get {
                return ResourceManager.GetString("HelpResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string HelpSelectDataviewTopicId {
            get {
                return ResourceManager.GetString("HelpSelectDataviewTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Searching over {0} hits from ChemBioViz form {1}.
        /// </summary>
        internal static string HITLIST_INFO {
            get {
                return ResourceManager.GetString("HITLIST_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to proceed due to one of the following reasons
        ///    1) Field may be removed from DataView.
        ///    2) Table may be removed from DataView.
        ///    3) Table may be deleted from Database.
        ///    4) DataView may be deleted from Database..
        /// </summary>
        internal static string Invalid_Daview {
            get {
                return ResourceManager.GetString("Invalid_Daview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid query structure.
        /// </summary>
        internal static string INVALID_QUERY_STRUCTURE {
            get {
                return ResourceManager.GetString("INVALID_QUERY_STRUCTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching by structure requires Lead Discovery to be installed.
        /// </summary>
        internal static string LD_NOT_INSTALLED {
            get {
                return ResourceManager.GetString("LD_NOT_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than.
        /// </summary>
        internal static string LESSTHAN_OPERATOR {
            get {
                return ResourceManager.GetString("LESSTHAN_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than or equal.
        /// </summary>
        internal static string LESSTHANEQUAL_OPERATOR {
            get {
                return ResourceManager.GetString("LESSTHANEQUAL_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field not added, because invalid lookup has been setup.
        /// </summary>
        internal static string LookupField_Validation {
            get {
                return ResourceManager.GetString("LookupField_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string MAX_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("MAX_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        internal static string MAX_FUNCTION {
            get {
                return ResourceManager.GetString("MAX_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to load {0} rows into table {1} which are more than Max Rows limit {2}. Rows exceeding the configured limit. Filter your query or adjust the Max Rows limit in Datalytix Preferences..
        /// </summary>
        internal static string Max_Row_Limit_Message {
            get {
                return ResourceManager.GetString("Max_Row_Limit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        internal static string MEDIAN_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("MEDIAN_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDIAN.
        /// </summary>
        internal static string MEDIAN_FUNCTION {
            get {
                return ResourceManager.GetString("MEDIAN_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string MIN_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("MIN_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN.
        /// </summary>
        internal static string MIN_FUNCTION {
            get {
                return ResourceManager.GetString("MIN_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Formula.
        /// </summary>
        internal static string Molecular_Formula_Validation {
            get {
                return ResourceManager.GetString("Molecular_Formula_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no dataviews available..
        /// </summary>
        internal static string No_Dataviews {
            get {
                return ResourceManager.GetString("No_Dataviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Hits for selected Query Criteria.
        /// </summary>
        internal static string No_Hit_Message {
            get {
                return ResourceManager.GetString("No_Hit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        internal static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not equal.
        /// </summary>
        internal static string NOTEQUAL_OPERATOR {
            get {
                return ResourceManager.GetString("NOTEQUAL_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population standard deviation.
        /// </summary>
        internal static string POP_STDDEV_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("POP_STDDEV_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDDEV_POP.
        /// </summary>
        internal static string POP_STDDEV_FUNCTION {
            get {
                return ResourceManager.GetString("POP_STDDEV_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population variance.
        /// </summary>
        internal static string POP_VARIANCE_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("POP_VARIANCE_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAR_POP.
        /// </summary>
        internal static string POP_VARIANCE_FUNCTION {
            get {
                return ResourceManager.GetString("POP_VARIANCE_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Please Wait....
        /// </summary>
        internal static string Process_Wait {
            get {
                return ResourceManager.GetString("Process_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string QUERY_CRITERIA_TAB_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("QUERY_CRITERIA_TAB_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} is already part of the form..
        /// </summary>
        internal static string QueryCriteria_Field_Validation {
            get {
                return ResourceManager.GetString("QueryCriteria_Field_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh dataviews successful..
        /// </summary>
        internal static string Refresh_Dataviews {
            get {
                return ResourceManager.GetString("Refresh_Dataviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh action cancelled..
        /// </summary>
        internal static string Refresh_Dataviews_Cancel {
            get {
                return ResourceManager.GetString("Refresh_Dataviews_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renderers are not installed or licensed.
        /// </summary>
        internal static string Renderer_Not_Licensed {
            get {
                return ResourceManager.GetString("Renderer_Not_Licensed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Resources_10_ItemStepEnabled {
            get {
                object obj = ResourceManager.GetObject("Resources_10_ItemStepEnabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Resources_12_LowThumb {
            get {
                object obj = ResourceManager.GetObject("Resources_12_LowThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Resources_16_RefreshDataTable {
            get {
                object obj = ResourceManager.GetObject("Resources_16_RefreshDataTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Resources_16_Search {
            get {
                object obj = ResourceManager.GetObject("Resources_16_Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Definition.
        /// </summary>
        internal static string RESULT_CRITERIA_TAB_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("RESULT_CRITERIA_TAB_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure fields are not allowed for aggregation.
        /// </summary>
        internal static string ResultCriteria_Structure_Validation {
            get {
                return ResourceManager.GetString("ResultCriteria_Structure_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result criteria must contain at least one field.
        /// </summary>
        internal static string ResultCriteria_Validation {
            get {
                return ResourceManager.GetString("ResultCriteria_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base table contains a field named {0}
        ///and there is also a child table named {0}.
        ///Please rename the field.
        /// </summary>
        internal static string SearchCriteria_Field_Validation {
            get {
                return ResourceManager.GetString("SearchCriteria_Field_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To assign the search criteria for structure field use the Structure Criteria panel.
        /// </summary>
        internal static string SearchCriteria_Structure_validation {
            get {
                return ResourceManager.GetString("SearchCriteria_Structure_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation.
        /// </summary>
        internal static string STDDEV_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("STDDEV_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STDDEV.
        /// </summary>
        internal static string STDDEV_FUNCTION {
            get {
                return ResourceManager.GetString("STDDEV_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string Structure_Field_Display_Format {
            get {
                return ResourceManager.GetString("Structure_Field_Display_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Search:
        ///Search does not supports both Mol Weight and Formula of 
        ///structure lookup at the same time.
        /// </summary>
        internal static string StructureLookupField_SearchError {
            get {
                return ResourceManager.GetString("StructureLookupField_SearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string SUM_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("SUM_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        internal static string SUM_FUNCTION {
            get {
                return ResourceManager.GetString("SUM_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has timed out.
        /// </summary>
        internal static string TimeOut_Exception_Message {
            get {
                return ResourceManager.GetString("TimeOut_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance.
        /// </summary>
        internal static string VARIANCE_DISPLAY_NAME {
            get {
                return ResourceManager.GetString("VARIANCE_DISPLAY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VARIANCE.
        /// </summary>
        internal static string VARIANCE_FUNCTION {
            get {
                return ResourceManager.GetString("VARIANCE_FUNCTION", resourceCulture);
            }
        }
    }
}
