//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_DataViewManager_ContentArea_EditDataViewXml class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_DataViewManager_ContentArea_EditDataViewXml {
    
    /// <summary>
    /// ScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    
    /// <summary>
    /// ConfirmationAreaUserControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_ConfirmationArea ConfirmationAreaUserControl;
    
    /// <summary>
    /// ErrorAreaUserControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_ErrorArea ErrorAreaUserControl;
    
    /// <summary>
    /// SummaryTitleLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label SummaryTitleLabel;
    
    /// <summary>
    /// tblTreeview control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable tblTreeview;
    
    /// <summary>
    /// SortByWebMenu control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Infragistics.WebUI.UltraWebNavigator.UltraWebMenu SortByWebMenu;
    
    /// <summary>
    /// SelectedSortLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label SelectedSortLabel;
    
    /// <summary>
    /// ExistingDataViewsUltraWebTree control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Infragistics.WebUI.UltraWebNavigator.UltraWebTree ExistingDataViewsUltraWebTree;
    
    /// <summary>
    /// DvDetails control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl DvDetails;
    
    /// <summary>
    /// DataViewTableDetails control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable DataViewTableDetails;
    
    /// <summary>
    /// DataViewNameLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label DataViewNameLabel;
    
    /// <summary>
    /// DisplayNameTextBoxWithPopUp control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label DisplayNameTextBoxWithPopUp;
    
    /// <summary>
    /// DescriptionLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label DescriptionLabel;
    
    /// <summary>
    /// DescriptionTextBoxWithPopUp control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_TextBoxWithPopUp DescriptionTextBoxWithPopUp;
    
    /// <summary>
    /// UserLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label UserLabel;
    
    /// <summary>
    /// UserTextBoxWithPopUp control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_TextBoxWithPopUp UserTextBoxWithPopUp;
    
    /// <summary>
    /// FormGroupLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label FormGroupLabel;
    
    /// <summary>
    /// FormGroupTextBoxWithPopUp control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_TextBoxWithPopUp FormGroupTextBoxWithPopUp;
    
    /// <summary>
    /// DateCreatedLabel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label DateCreatedLabel;
    
    /// <summary>
    /// DateCreatedTextBoxWithPopUp control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_Public_UserControls_TextBoxWithPopUp DateCreatedTextBoxWithPopUp;
    
    /// <summary>
    /// DataViewXmlDetails control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable DataViewXmlDetails;
    
    /// <summary>
    /// DataViewXmlText control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox DataViewXmlText;
    
    /// <summary>
    /// EditXmlButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button EditXmlButton;
    
    /// <summary>
    /// BackButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button BackButton;
    
    /// <summary>
    /// SaveXmlButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button SaveXmlButton;
    
    /// <summary>
    /// CancelButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button CancelButton;
    
    /// <summary>
    /// CopyToClipBoardButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button CopyToClipBoardButton;
    
    /// <summary>
    /// PasteFromClipBoardButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button PasteFromClipBoardButton;
    
    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new Manager.Forms.Master.DataViewManager Master {
        get {
            return ((Manager.Forms.Master.DataViewManager)(base.Master));
        }
    }
}
