--Copyright 1999-2010 CambridgeSoft Corporation. All rights reserved

--#####################################
-- Updating Registration Configuration
--#####################################
DECLARE
	v_found number(1) := 0;
BEGIN
	SELECT COUNT(1) INTO v_found FROM &&securitySchemaName..coeconfiguration WHERE LOWER(DESCRIPTION)='registration';
	IF v_found > 0 THEN
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','REGADMIN','ActiveRLS',NULL ,'This setting enables Row Level Security which is an additional layer of security utilizing Oracle''s fine grain access control functionality.', 'PICKLIST','Off|Registry Level Projects|Batch Level Projects', 'False','CambridgeSoft.COE.RegistrationAdmin.Services.RLSConfigurationProcessor','True');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','Registry_Identifiers','True' ,'Enables/Disables Identifiers grid at Registry level','PICKLIST','True|False','False','');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','Component_Identifiers','True' ,'Enables/Disables Identifiers grid at Component level','PICKLIST','True|False','False','');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','Batch_Identifiers','False' ,'Enables/Disables Identifiers grid at Batch level','PICKLIST','True|False','False','');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','CBV','SearchDuplicatesComponentsFormGroupId','4019' ,'Search Duplicates Components COEFormGroupId','TEXT','','True','');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Manager','DVManager','UnpublishableSchemas',NULL ,'A comma separated lists for those schemas that will not be allowed to be published through DV Manager', NULL,NULL, NULL); 
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Manager','MISC','PageControlsManager',NULL ,'Enable/Disable access to Page Controls Manager', NULL,NULL, NULL); 
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Manager','MISC','HomeLinkURL',NULL ,'URL for the Manager Application home page', NULL,NULL, NULL);
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Manager','MISC','AppPageTitle',NULL ,'Title to be shown on the application', NULL,NULL, NULL);
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','CustomPropertyStyles','Std20x40|Std50x40|Std50x80|Std75x40|Std100x40|Std100x80' ,NULL,NULL,NULL,NULL,NULL);
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','REGADMIN','ApprovalsEnabled',NULL ,NULL, NULL, NULL, 'True');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','REGADMIN','CustomRegFormGroupsIds',NULL ,NULL, NULL, NULL, 'True');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','REGADMIN','DataLoaderFormGroupId',NULL ,NULL, NULL, NULL, 'True');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','CustomPropertyStyles',NULL ,NULL, NULL, NULL, 'False');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','MWROUNDDIGIT',NULL ,NULL, NULL, NULL, 'False');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','AllowHitlistManagement',NULL ,NULL, NULL, NULL, 'False');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','AllowQueryManagement',NULL ,NULL, NULL, NULL, 'False');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','BatchNumberLength',NULL ,NULL, NULL, NULL, 'False');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','BatchesToTemp',NULL ,NULL, NULL, NULL, 'False');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','MISC','MaxRegisterMarked',NULL ,NULL, NULL, NULL, 'False');
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','DOCMGR','DocMgrSearchCriteriaField','DOCUMENTS.LINKID' ,NULL, NULL,NULL, NULL);
		&&securitySchemaName..ConfigurationManager.CreateOrUpdateParameter('Registration','DOCMGR','DocMgrDataViewID','8002' ,NULL, NULL,NULL, NULL);
		
		

		UPDATE &&securitySchemaName..coeconfiguration c
			SET c.configurationxml = (
				SELECT  XmlType(replace( cr.configurationxml.GetClobVal(), '11.0.2', '11.0.3' ))
			FROM &&securitySchemaName..coeconfiguration cr
				WHERE cr.Description = c.Description )
			WHERE c.Description = 'Registration';

		COMMIT;
	END IF;
END;
/


--####################################
-- Page Control Settings required XMLs
--####################################

DELETE FROM &&securitySchemaName..COEPAGECONTROL WHERE APPLICATION IN ('REGISTRATION') AND TYPE IN ('CUSTOM');
DELETE FROM &&securitySchemaName..COEPAGECONTROL WHERE APPLICATION IN ('CHEMBIOVIZ') AND TYPE IN ('CUSTOM');

DECLARE
 L_CustomXml_1 CLOB:= '<?xml version="1.0" encoding="utf-8"?>
<COEPageControlSettings>
	<Type>Custom</Type>
	<Application>REGISTRATION</Application>
	<Pages>
		<Page>
			<ID>ASP.FORMS_SUBMITRECORD_CONTENTAREA_SUBMITMIXTURE_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>Manage Components</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID/>
						<Privilege>
							<ID>ADD_COMPONENT</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>DefineMixtureImageMenuButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableMixtures</ID>
							<Key>Registration/REGADMIN/EnableMixtures</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
				<ID>Projects Enabled Registry Level</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Mix_ProjectsUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>0</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>ProjectsUsed</ID>
							<Key>Registration/MISC/ProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Projects Enabled Batch Level</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Batch_ProjectsUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>4</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>BatchProjectsUsed</ID>
							<Key>Registration/MISC/BatchProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Registry Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Mix_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>0</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>Registry_Identifiers</ID>
							<Key>Registration/MISC/Registry_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Component Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Compound_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>1</COEFormID>
						</Control>
						<Control>
							<ID>Compound_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>2</COEFormID>
						</Control>							
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>Component_Identifiers</ID>
							<Key>Registration/MISC/Component_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Batch Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Batch_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>4</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>Batch_Identifiers</ID>
							<Key>Registration/MISC/Batch_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Submission Templates</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID/>
						<Privilege>
							<ID>LOAD_SAVE_RECORD</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>SubmissionTemplateImageMenuButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableSubmissionTemplates</ID>
							<Key>
              Registration/REGADMIN/EnableSubmissionTemplates</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>SUBMITRECORD</ID>
					<Privileges>
						<Operator>OR</Operator>
						<Privilege>
							<ID>ADD_COMPOUND_TEMP</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_SUBMITRECORD_CONTENTAREA_SUBMITMIXTURE_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID>
					</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>REGISTERRECORD</ID>
					<Privileges>
						<Operator>OR</Operator>
						<Privilege>
							<ID>REGISTER_DIRECT</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>RegisterButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID>
					</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>ComponentsFragmentsGrid</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>5</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableFragments</ID>
							<Key>Registration/REGADMIN/EnableFragments</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
                    <ID>Batch Form Enabled</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>4</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>BatchProjectsUsed</ID>
							<Key>Registration/MISC/BatchProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
                        <AppSetting>
							<ID>Batch_Identifiers</ID>
							<Key>Registration/MISC/Batch_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
                </ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REVIEWREGISTER_CONTENTAREA_REVIEWREGISTERMIXTURE_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>Manage Components</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID/>
						<Privilege>
							<ID>ADD_COMPONENT</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>DefineMixtureImageMenuButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableMixtures</ID>
							<Key>Registration/REGADMIN/EnableMixtures</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>EditCompoundTemp</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>EditCompoundTemp</ID>
						<Privilege>
							<ID>EDIT_COMPOUND_TEMP</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>EditButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>RegisterFromTemp</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegisterFromTemp</ID>
						<Privilege>
							<ID>REGISTER_TEMP</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>RegisterButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>ComponentsFragmentsGrid</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>5</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableFragments</ID>
							<Key>Registration/REGADMIN/EnableFragments</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>BatchComponentsFragmentsGrid</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>6</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableFragments</ID>
							<Key>Registration/REGADMIN/EnableFragments</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Projects Enabled Registry Level</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Mix_ProjectsUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>0</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>ProjectsUsed</ID>
							<Key>Registration/MISC/ProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>RLS Enabled Batch Level</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Batch_ProjectsUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>4</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>ProjectsUsed</ID>
							<Key>Registration/MISC/BatchProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Registry Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Mix_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>0</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>Registry_Identifiers</ID>
							<Key>Registration/MISC/Registry_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Component Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Compound_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>Component_Identifiers</ID>
							<Key>Registration/MISC/Component_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Batch Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Batch_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>4</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>Component_Identifiers</ID>
							<Key>Registration/MISC/Batch_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Delete Temp Record</ID>
					<Privileges>
						<Operator>OR</Operator>
						<Privilege>
							<ID>DELETE_TEMP</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>DeleteRecordImageMenuButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_BULKREGISTERMARKED_CONTENTAREA_REGISTERMARKED_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegisterMarkedPageAccess</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegisterMarkedPageAccess</ID>
						<Privilege>
							<ID>REGISTER_TEMP</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_BULKREGISTERMARKED_CONTENTAREA_REGISTERMARKED_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_COMPONENTDUPLICATES_CONTENTAREA_COMPONENTDUPLICATES_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RLS Enabled Registry Level</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Mix_ProjectsUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
							<COEFormID>9</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>Registry_Identifiers</ID>
							<Key>Registration/MISC/ProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>RLS Enabled Batch Level</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Batch_ProjectsUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
							<COEFormID>2</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>Registry_Identifiers</ID>
							<Key>Registration/MISC/BatchProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Registry Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Mix_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
							<COEFormID>9</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>ProjectsUsed</ID>
							<Key>Registration/MISC/Registry_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Component Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>ACompoundIdentifiersUltraGrid</ID>
							<TypeOfControl>CompositeControl</TypeOfControl>
							<ParentControlID>ComponentRepeater</ParentControlID>
							<PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
							<COEFormID>9</COEFormID>
						</Control>
						<Control>
							<ID>ACompoundIdentifiersUltraGrid</ID>
							<TypeOfControl>CompositeControl</TypeOfControl>
							<ParentControlID>ComponentRepeater</ParentControlID>
							<PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
							<COEFormID>0</COEFormID>
						</Control>
						<Control>
							<ID>ACompoundIdentifiersUltraGrid</ID>
							<TypeOfControl>CompositeControl</TypeOfControl>
							<PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
							<COEFormID>0</COEFormID>
						</Control>
						<Control>
							<ID>ACompoundIdentifiersUltraGrid0OF1</ID>
							<TypeOfControl>COEWebGridColumn</TypeOfControl>
							<PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
							<COEFormID>0</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>ComponentIdentifiers</ID>
							<Key>Registration/MISC/Component_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Batch Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Batch_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
							<COEFormID>2</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>BatchIdentifiers</ID>
							<Key>Registration/MISC/Batch_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>ComponentsFragmentsGrid</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>1</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableFragments</ID>
							<Key>Registration/REGADMIN/EnableFragments</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>AddBatchButton</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>AddBatchButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableAddBatchButton</ID>
							<Key>Registration/REGADMIN/EnableAddBatchButton</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>DuplicateRegistryButton</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>DuplicateRegistryButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableDuplicateButton</ID>
							<Key>Registration/REGADMIN/EnableDuplicateButton</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>CreateCompoundFormButton</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>CreateCompoundFormButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableUseComponentButton</ID>
							<Key>Registration/REGADMIN/EnableUseComponentButton</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>UseStructureButton</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>UseStructureButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableUseStructureButton</ID>
							<Key>Registration/REGADMIN/EnableUseStructureButton</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
				  <ID>BatchComponentCustomProperties</ID>
				  <Privileges>
					<Operator>AND</Operator>
					<ID></ID>
				  </Privileges>
				  <Controls>
					<Control>
					  <ID>1003</ID>
					  <TypeOfControl>COEForm</TypeOfControl>
					  <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
					  <COEFormID>-1</COEFormID>
					  <Action>Hide</Action>
					</Control>
				  </Controls>
				  <AppSettings>
					<Operator>OR</Operator>
					<ID></ID>
					<AppSetting>
					  <ID>EnableMixtures</ID>
					  <Key>Registration/REGADMIN/EnableMixtures</Key>
					  <Value>True</Value>
					  <Type>COEConfiguration</Type>
					</AppSetting>
				  </AppSettings>
				</ControlSetting>
			</ControlSettings>
		</Page>';	

 L_CustomXml_2 CLOB:= '<Page>
			<ID>ASP.FORMS_VIEWMIXTURE_CONTENTAREA_VIEWMIXTURE_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RLS Enabled Registry Level</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Mix_ProjectsUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>0</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>ProjectsUsed</ID>
							<Key>Registration/MISC/ProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Manage Components</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID/>
						<Privilege>
							<ID>ADD_COMPONENT</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>DefineMixtureImageMenuButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableMixtures</ID>
							<Key>Registration/REGADMIN/EnableMixtures</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>EditRegisteredRecord</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>EditRegisteredRecord</ID>
						<Privilege>
							<ID>EDIT_COMPOUND_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>EditButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>DeleteRegisteredRecord</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>DeleteRegisteredRecord</ID>
						<Privilege>
							<ID>DELETE_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>DeleteRecordImageMenuButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>DeleteMoveBatchFromPerm</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>DeleteMoveBatchFromPerm</ID>
						<Privilege>
							<ID>DELETE_BATCH_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>DeleteBatchButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
						<Control>
							<ID>MoveBatchButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>MoveBatchInPerm</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID>MoveBatchInPerm</ID>
					</Privileges>
					<Controls>
						<Control>
							<ID>MoveBatchButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableMoveBatch</ID>
							<Key>Registration/REGADMIN/EnableMoveBatch</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>AddComponentPerm</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>AddComponentPerm</ID>
						<Privilege>
							<ID>ADD_COMPONENT</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>AddComponentButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>AddBatchPerm</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>AddBatchPerm</ID>
						<Privilege>
							<ID>ADD_BATCH_PERM</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>AddBatchButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>SendToInventory</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>SendToInventory</ID>
						<Privilege>
							<ID>INV_CREATE_CONTAINER</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>SendToInventoryImageMenuButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>EditApprovedRecord</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID/>
						<Privilege>
							<ID>TOGGLE_APPROVED_FLAG</ID>
						</Privilege>
						<Privilege>
							<ID>EDIT_COMPOUND_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>EditButton</ID>
							<TypeOfControl>Control</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
						<Control>
							<ID>0</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
							<Action>Disable</Action>
						</Control>
						<Control>
							<ID>1000</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
							<Action>Disable</Action>
						</Control>
						<Control>
							<ID>1</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
							<Action>Disable</Action>
						</Control>
						<Control>
							<ID>1001</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
							<Action>Disable</Action>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>ApprovalsEnabled</ID>
							<Key>Registration/REGADMIN/ApprovalsEnabled</Key>
							<Value>False</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
						<AppSetting>
							<ID>IsRegistryApproved</ID>
							<Key>IsRegistryApproved</Key>
							<Value>False</Value>
							<Type>Session</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>ApprovedEnabled</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID/>
						<Privilege>
							<ID>SET_APPROVED_FLAG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>APPROVEDProperty</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>0</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>AND</Operator>
						<ID/>
						<AppSetting>
							<ID>ApprovalsEnabled</ID>
							<Key>Registration/REGADMIN/ApprovalsEnabled</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>ComponentsFragmentsGrid</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>5</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableFragments</ID>
							<Key>Registration/REGADMIN/EnableFragments</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Registry Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Mix_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>0</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>Registry_Identifiers</ID>
							<Key>Registration/MISC/Registry_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>ComponentsFragmentsGridEdit</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>6</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>EnableFragments</ID>
							<Key>Registration/REGADMIN/EnableFragments</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
					<ID>Batch Identifiers</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Batch_IdentifiersUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>4</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>Batch_Identifiers</ID>
							<Key>Registration/MISC/Batch_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
				<ControlSetting>
                    <ID>Batch Projects</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Batch_ProjectsUltraGrid</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>4</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>BatchProjectsUsed</ID>
							<Key>Registration/MISC/BatchProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
                </ControlSetting> 
                <ControlSetting>
                    <ID>Batch Form Enabled</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>4</ID>
							<TypeOfControl>COEForm</TypeOfControl>
							<PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>BatchProjectsUsed</ID>
							<Key>Registration/MISC/BatchProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
                        <AppSetting>
							<ID>Batch_Identifiers</ID>
							<Key>Registration/MISC/Batch_Identifiers</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
                </ControlSetting> 
			</ControlSettings>
		</Page>';
		
L_CustomXml_3 CLOB:= '<Page>
			<ID>ASP.FORMS_VIEWMIXTURE_CONTENTAREA_MOVEDELETE_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>MoveDeletePageAccess</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>MoveDeletePageAccess</ID>
						<Privilege>
							<ID>DELETE_BATCH_REG</ID>
						</Privilege>
						<Privilege>
							<ID>DELETE_TEMP</ID>
						</Privilege>
						<Privilege>
							<ID>DELETE_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_VIEWMIXTURE_CONTENTAREA_MOVEDELETE_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_VIEWMIXTURE_CONTENTAREA_VIEWMIXTURESEARCH_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>SearchRegistry</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>SearchRegistry</ID>
						<Privilege>
							<ID>SEARCH_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_VIEWMIXTURE_CONTENTAREA_VIEWMIXTURESEARCH_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REVIEWREGISTER_CONTENTAREA_REVIEWREGISTERSEARCH_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>SearchTempRegistry</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>SearchTempRegistry</ID>
						<Privilege>
							<ID>SEARCH_TEMP</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REVIEWREGISTER_CONTENTAREA_REVIEWREGISTERSEARCH_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_DEFAULT_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegAdmin_Default</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegAdmin_Default</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_DEFAULT_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_TABLEEDITOR_CONTENTAREA_TABLEEDITOR_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>TableEditorPage</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>TableEditorPage</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_TABLEEDITOR_CONTENTAREA_TABLEEDITOR_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
				<ControlSetting>
					<ID>VW_PROJECT_ChildTable</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID/>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>VW_PROJECT_ChildTable</ID>
							<TypeOfControl>
              COETableManagerChildTable</TypeOfControl>
							<PlaceHolderID>COETableManager1</PlaceHolderID>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>ApprovalsEnabled</ID>
							<Key>Registration/REGADMIN/ActiveRLS</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ROOTPROPERTYLIST_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegAdmin_RootPropertyList</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegAdmin_RootPropertyList</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ROOTPROPERTYLIST_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_COMPOUND_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegAdmin_Compound</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegAdmin_Compound</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_COMPOUND_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_BATCH_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegAdmin_BatchPage</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegAdmin_BatchPage</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_BATCH_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_PARAMEDIT_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegAdmin_ParamEdit</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegAdmin_ParamEdit</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_PARAMEDIT_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_VALIDATIONRULES_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegAdmin_ValRules</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegAdmin_ValRules</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_VALIDATIONRULES_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ADDINS_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegAdmin_AddInsPage</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegAdmin_AddInsPage</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ADDINS_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ADDINSEDIT_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegAdmin_AddInsEditPage</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegAdmin_AddInsEditPage</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ADDINSEDIT_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_IMPORTEXPORTCUSTOM_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegAdmin_ImpExp</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegAdmin_ImpExp</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_IMPORTEXPORTCUSTOM_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
			<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_CONFIGSETTINGS_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>RegAdmin_ConfigSet</ID>
					<Privileges>
						<Operator>OR</Operator>
						<ID>RegAdmin_ConfigSet</ID>
						<Privilege>
							<ID>CONFIG_REG</ID>
						</Privilege>
					</Privileges>
					<Controls>
						<Control>
							<ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_CONFIGSETTINGS_ASPX</ID>
							<TypeOfControl>Page</TypeOfControl>
							<PlaceHolderID/>
							<COEFormID>-1</COEFormID>
						</Control>
					</Controls>
					<AppSettings/>
				</ControlSetting>
			</ControlSettings>
		</Page>
		<Page>
            <ID>ASP.FORMS_PUBLIC_CONTENTAREA_HOME_ASPX</ID>
            <ControlSettings>
                <ControlSetting>
                    <ID>Test</ID>
                    <Privileges>
                        <Operator>AND</Operator>
                    </Privileges>
                    <Controls>
                        <Control>
                            <ID>ApprovedPermRegistries</ID>
                            <Description>Control description goes here!</Description>
                            <FriendlyName>Control friendly name</FriendlyName>
                            <PlaceHolderID/>
                            <TypeOfControl>Control</TypeOfControl>
                            <COEFormID>-1</COEFormID>
                        </Control>
                    </Controls>
                    <AppSettings>
                        <AppSetting>
                            <ID>ApprovalsEnabled</ID>
                            <Key>Registration/REGADMIN/ApprovalsEnabled</Key>
                            <Value>True</Value>
                            <Type>COEConfiguration</Type>
                        </AppSetting>
                    </AppSettings>
                </ControlSetting>
            </ControlSettings>
        </Page>
		<Page>
			<ID>ASP.FORMS_REGISTRYDUPLICATES_CONTENTAREA_REGISTRYDUPLICATES_ASPX</ID>
			<ControlSettings>
				<ControlSetting>
					<ID>Projects Enabled Batch Level</ID>
					<Privileges>
						<Operator>AND</Operator>
						<ID/>
					</Privileges>
					<Controls>
						<Control>
							<ID>Batch_ProjectsUltraGrid0OF1</ID>
							<TypeOfControl>COEGenerableControl</TypeOfControl>
							<PlaceHolderID>duplicateFormHolder</PlaceHolderID>
							<COEFormID>2</COEFormID>
						</Control>
					</Controls>
					<AppSettings>
						<Operator>OR</Operator>
						<ID/>
						<AppSetting>
							<ID>BatchProjectsUsed</ID>
							<Key>Registration/MISC/BatchProjectsUsed</Key>
							<Value>True</Value>
							<Type>COEConfiguration</Type>
						</AppSetting>
					</AppSettings>
				</ControlSetting>
			</ControlSettings>
		</Page>
	</Pages>
</COEPageControlSettings>';

 L_CustomXml_ChemBioviz_1 CLOB:= '<?xml version="1.0" encoding="utf-8"?>
<COEPageControlSettings>
    <Type>Custom</Type>
    <Application>Chembioviz</Application>
    <Pages>
        <Page>
            <ID>ASP.forms_search_contentarea_chembiovizsearch_aspx</ID>
            <ControlSettings>
                <ControlSetting>
                    <ID>Projects Enabled Registry Level Perm</ID>
                    <Privileges>
                        <Operator>AND</Operator>
                        <ID/>
                    </Privileges>
                    <Controls>
                        <Control>
                            <ID>REGISTRY_PROJECTDropDownListPerm</ID>
                            <TypeOfControl>COEGenerableControl</TypeOfControl>
                            <PlaceHolderID>FormGeneratorHolder</PlaceHolderID>
                            <COEFormID>0</COEFormID>
                        </Control>
                    </Controls>
                    <AppSettings>
                        <Operator>OR</Operator>
                        <ID/>
                        <AppSetting>
                            <ID>ProjectsUsed</ID>
                            <Key>Registration/MISC/ProjectsUsed</Key>
                            <Value>True</Value>
                            <Type>COEConfiguration</Type>
                        </AppSetting>
                    </AppSettings>
                </ControlSetting>
                <ControlSetting>
                    <ID>Projects Enabled Batch Level Perm</ID>
                    <Privileges>
                        <Operator>AND</Operator>
                        <ID/>
                    </Privileges>
                    <Controls>
                        <Control>
                            <ID>BATCH_PROJECTDropDownListPerm</ID>
                            <TypeOfControl>COEGenerableControl</TypeOfControl>
                            <PlaceHolderID>FormGeneratorHolder</PlaceHolderID>
                            <COEFormID>2</COEFormID>
                        </Control>
                    </Controls>
                    <AppSettings>
                        <Operator>OR</Operator>
                        <ID/>
                        <AppSetting>
                            <ID>ProjectsUsed</ID>
                            <Key>Registration/MISC/BatchProjectsUsed</Key>
                            <Value>True</Value>
                            <Type>COEConfiguration</Type>
                        </AppSetting>
                    </AppSettings>
                </ControlSetting>
                <ControlSetting>
                    <ID>Projects Enabled Registry Level Temp</ID>
                    <Privileges>
                        <Operator>AND</Operator>
                        <ID/>
                    </Privileges>
                    <Controls>
                        <Control>
                            <ID>REGISTRY_PROJECTDropDownListTemp</ID>
                            <TypeOfControl>COEGenerableControl</TypeOfControl>
                            <PlaceHolderID>FormGeneratorHolder</PlaceHolderID>
                            <COEFormID>0</COEFormID>
                        </Control>
                    </Controls>
                    <AppSettings>
                        <Operator>OR</Operator>
                        <ID/>
                        <AppSetting>
                            <ID>ProjectsUsed</ID>
                            <Key>Registration/MISC/ProjectsUsed</Key>
                            <Value>True</Value>
                            <Type>COEConfiguration</Type>
                        </AppSetting>
                    </AppSettings>
                </ControlSetting>
                <ControlSetting>
                    <ID>Projects Enabled Batch Level Temp</ID>
                    <Privileges>
                        <Operator>AND</Operator>
                        <ID/>
                    </Privileges>
                    <Controls>
                        <Control>
                            <ID>BATCH_PROJECTDropDownListTemp</ID>
                            <TypeOfControl>COEGenerableControl</TypeOfControl>
                            <PlaceHolderID>FormGeneratorHolder</PlaceHolderID>
                            <COEFormID>0</COEFormID>
                        </Control>
                    </Controls>
                    <AppSettings>
                        <Operator>OR</Operator>
                        <ID/>
                        <AppSetting>
                            <ID>ProjectsUsed</ID>
                            <Key>Registration/MISC/BatchProjectsUsed</Key>
                            <Value>True</Value>
                            <Type>COEConfiguration</Type>
                        </AppSetting>
                    </AppSettings>
                </ControlSetting>';
 L_CustomXml_ChemBioviz_2 CLOB:= '                <ControlSetting>
                    <ID>ApprovalsEnabled</ID>
                    <Privileges>
                        <Operator>AND</Operator>
                        <ID/>
                        <Privilege>
                            <ID>SET_APPROVED_FLAG</ID>
                        </Privilege>
                    </Privileges>
                    <Controls>
                        <Control>
                            <ID>ApprovedStateControl</ID>
                            <PlaceHolderID>FormGeneratorHolder</PlaceHolderID>
                            <TypeOfControl>COEGenerableControl</TypeOfControl>
                            <COEFormID>0</COEFormID>
                        </Control>
                        <Control>
                            <ID>APPROVEDCOLUMN</ID>
                            <Description>Approved or not flag</Description>
                            <FriendlyName>Approved or not flag</FriendlyName>
                            <PlaceHolderID>FormGeneratorHolder</PlaceHolderID>
                            <TypeOfControl>Control</TypeOfControl>
                            <ParentControlID>ListView</ParentControlID>
                            <COEFormID>0</COEFormID>
                        </Control>
                        <Control>
                            <ID>ApproveMarkedLink</ID>
                            <Description>Approve Marked linkButton</Description>
                            <FriendlyName>Approve Marked linkButton</FriendlyName>
                            <PlaceHolderID/>
                            <TypeOfControl/>
                            <COEFormID/>
                        </Control>
                    </Controls>
                    <AppSettings>
                        <Operator>AND</Operator>
                        <AppSetting>
                            <Key>Registration/REGADMIN/ApprovalsEnabled</Key>
                            <Value>True</Value>
                            <Type>COEConfiguration</Type>
                        </AppSetting>
                    </AppSettings>
                </ControlSetting>
            </ControlSettings>
        </Page>
    </Pages>
</COEPageControlSettings>';
 

 L_COEPageControl_Seq NUmber(8);

BEGIN
	INSERT INTO &&securitySchemaName..COEPAGECONTROL (APPLICATION, TYPE, CONFIGURATIONXML) VALUES ('REGISTRATION','CUSTOM', L_CustomXml_1);	
	SELECT &&securitySchemaName..COEPageControl_seq.CURRVAL INTO L_COEPageControl_Seq FROM DUAL;
	UPDATE &&securitySchemaName..COEPAGECONTROL SET CONFIGURATIONXML=CONFIGURATIONXML||L_CustomXml_2||L_CustomXml_3 WHERE ID=L_COEPageControl_Seq;

	INSERT INTO &&securitySchemaName..COEPAGECONTROL (APPLICATION, TYPE, CONFIGURATIONXML) VALUES ('CHEMBIOVIZ','CUSTOM',  L_CustomXml_ChemBioviz_1);	
	SELECT &&securitySchemaName..COEPageControl_seq.CURRVAL INTO L_COEPageControl_Seq FROM DUAL;
	UPDATE &&securitySchemaName..COEPAGECONTROL SET CONFIGURATIONXML=CONFIGURATIONXML|| L_CustomXml_ChemBioviz_2 WHERE ID=L_COEPageControl_Seq;	
	COMMIT;    
END;
/


--#####################################
-- Updating Registration Object Config.
--#####################################

-- Recapture PropertyList/Property 'type' and 'precision' attributes
--   Required by consumer code for validation and formatting
DECLARE
  config_clob CLOB;
  config_xml XMLTYPE;
  targetconfig_xml XMLTYPE;
  v_found number(1):=0;
  results XMLTYPE;
  myclob CLOB;

BEGIN
  SELECT COUNT(1) INTO v_found FROM &&schemaName..COEOBJECTCONFIG WHERE ID=2;
  IF v_found > 0 THEN
	  &&schemaName..configurationcompoundregistry.GetCoeObjectConfig(config_clob);
	  config_xml := XMLTYPE(config_clob);

	  SELECT xmltype(c.xml) INTO targetconfig_xml
	  FROM &&schemaName..coeobjectconfig c
	  WHERE c.id = 2;

	  SELECT UPDATEXML(targetconfig_xml,
		'/MultiCompoundRegistryRecord/PropertyList',
			extract(config_xml, '/ConfigurationRegistryRecord/PropertyList'),
		'/MultiCompoundRegistryRecord/ComponentList/Component/Compound/PropertyList',
			extract(config_xml, '/ConfigurationRegistryRecord/Compound/PropertyList'),
		'/MultiCompoundRegistryRecord/BatchList/Batch/PropertyList',
			extract(config_xml, '/ConfigurationRegistryRecord/Batch/PropertyList'),
		'/MultiCompoundRegistryRecord/BatchList/Batch/BatchComponentList/BatchComponent/PropertyList',
			extract(config_xml, '/ConfigurationRegistryRecord/BatchComponent/PropertyList')
	  ) INTO results FROM dual;

	  --try to pretty-print the xml when it gets written back to the CLOB field
	  BEGIN
		$IF dbms_db_version.ver_le_10_1 $THEN
		  raise_application_error(-31061, 'Unsupported Oracle version');
		$ELSIF dbms_db_version.ver_le_10_2 $THEN
		  UPDATE &&schemaName..coeobjectconfig w
		  SET w.xml = results.getClobVal()
		  WHERE w.id = 2;
		$ELSE
		  UPDATE &&schemaName..coeobjectconfig w
		  SET w.xml = xmlserialize(document results AS CLOB indent SIZE = 2)
		  WHERE w.id = 2;
		$END
		
	  EXCEPTION WHEN OTHERS THEN
		BEGIN
		  --if the version-checks cause an error, be sure to update the CLOB anyway
		  UPDATE &&schemaName..coeobjectconfig w
		  SET w.xml = results.getClobVal()
		  WHERE w.id = 2;
		END;
	  END;

	  COMMIT;
  END IF;
END;
/
