--######################
-- Page Control Settings required XMLs
--######################


prompt 
prompt Starting "LoadCoepagecontrols_reg_custom.sql"...
prompt Starting "Updating the coepagercontrol table(Registration Custom)"...
prompt 

DECLARE


L_CustomXml_1 CLOB:='<?xml version="1.0" encoding="WINDOWS-1252"?>
<COEPageControlSettings>
  <Type>Custom</Type>
  <Application>REGISTRATION</Application>
  <Pages>
    <Page>
      <ID>ASP.FORMS_SUBMITRECORD_CONTENTAREA_SUBMITMIXTURE_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>Manage Components</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID/>
            <Privilege>
              <ID>ADD_COMPONENT</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>DefineMixtureImageMenuButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableMixtures</ID>
              <Key>Registration/REGADMIN/EnableMixtures</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Projects Enabled Registry Level</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Mix_ProjectsUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>ProjectsUsed</ID>
              <Key>Registration/MISC/ProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Projects Enabled Batch Level</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Batch_ProjectsUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>4</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>BatchProjectsUsed</ID>
              <Key>Registration/MISC/BatchProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Registry Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Mix_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Registry_Identifiers</ID>
              <Key>Registration/MISC/Registry_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Component Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Compound_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1001</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Component_Identifiers</ID>
              <Key>Registration/MISC/Component_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Batch Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Batch_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>4</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Batch_Identifiers</ID>
              <Key>Registration/MISC/Batch_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Submission Templates</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID/>
            <Privilege>
              <ID>LOAD_SAVE_RECORD</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>SubmissionTemplateImageMenuButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableSubmissionTemplates</ID>
              <Key>Registration/REGADMIN/EnableSubmissionTemplates</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>SUBMITRECORD</ID>
          <Privileges>
            <Operator>OR</Operator>
            <Privilege>
              <ID>ADD_COMPOUND_TEMP</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_SUBMITRECORD_CONTENTAREA_SUBMITMIXTURE_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID>
              </PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>REGISTERRECORD</ID>
          <Privileges>
            <Operator>OR</Operator>
            <Privilege>
              <ID>REGISTER_DIRECT</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>RegisterButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID>
              </PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>ComponentsFragmentsGrid</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>5</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableFragments</ID>
              <Key>Registration/REGADMIN/EnableFragments</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Batch Form Enabled</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>4</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>BatchProjectsUsed</ID>
              <Key>Registration/MISC/BatchProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
            <AppSetting>
              <ID>Batch_Identifiers</ID>
              <Key>Registration/MISC/Batch_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Structure Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Structure_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>'; 

L_CustomXml_2 CLOB:='<Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Structure_Identifiers</ID>
              <Key>Registration/MISC/Structure_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>EnableUseBatchPrefixes</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>BATCH_PREFIXProperty</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1002</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableUseBatchPrefixes</ID>
              <Key>Registration/REGADMIN/EnableUseBatchPrefixes</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>EnableUseBatchPrefixes</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>SequenceDropDownList</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableUseBatchPrefixes</ID>
              <Key>Registration/REGADMIN/EnableUseBatchPrefixes</Key>
              <Value>False</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>EnableUseBatchPrefixes</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>SALTANDBATCHSUFFIXProperty</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1002</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableUseBatchPrefixes</ID>
              <Key>Registration/REGADMIN/EnableUseBatchPrefixes</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REVIEWREGISTER_CONTENTAREA_REVIEWREGISTERMIXTURE_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>Manage Components</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID/>
            <Privilege>
              <ID>ADD_COMPONENT</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>DefineMixtureImageMenuButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableMixtures</ID>
              <Key>Registration/REGADMIN/EnableMixtures</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>EditCompoundTemp</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>EditCompoundTemp</ID>
            <Privilege>
              <ID>EDIT_COMPOUND_TEMP</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>EditButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>RegisterFromTemp</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegisterFromTemp</ID>
            <Privilege>
              <ID>REGISTER_TEMP</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>RegisterButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>ComponentsFragmentsGrid</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>5</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableFragments</ID>
              <Key>Registration/REGADMIN/EnableFragments</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>BatchComponentsFragmentsGrid</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>6</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableFragments</ID>
              <Key>Registration/REGADMIN/EnableFragments</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Projects Enabled Registry Level</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Mix_ProjectsUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>ProjectsUsed</ID>
              <Key>Registration/MISC/ProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>RLS Enabled Batch Level</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Batch_ProjectsUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>4</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>ProjectsUsed</ID>
              <Key>Registration/MISC/BatchProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Registry Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Mix_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Registry_Identifiers</ID>
              <Key>Registration/MISC/Registry_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Component Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Compound_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1001</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Component_Identifiers</ID>
              <Key>Registration/MISC/Component_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>'; 

L_CustomXml_3 CLOB:='<ControlSetting>
          <ID>Batch Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Batch_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>4</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Component_Identifiers</ID>
              <Key>Registration/MISC/Batch_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Delete Temp Record</ID>
          <Privileges>
            <Operator>OR</Operator>
            <Privilege>
              <ID>DELETE_TEMP</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>DeleteRecordImageMenuButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>Structure Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Structure_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1</COEFormID>
            </Control>
            <Control>
              <ID>Structure_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>2</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Structure_Identifiers</ID>
              <Key>Registration/MISC/Structure_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>StatusControlSettingForApprovals</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>StatusProperty</ID>
              <Description>This control allows the modification of the status from Submitted to Approved and the other way around</Description>
              <FriendlyName>Approved Control</FriendlyName>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <AppSetting>
              <ID>ApprovalsEnabled</ID>
              <Key>Registration/REGADMIN/ApprovalsEnabled</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>EnableUseBatchPrefixes</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>BATCH_PREFIXProperty</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1002</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableUseBatchPrefixes</ID>
              <Key>Registration/REGADMIN/EnableUseBatchPrefixes</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>EnableUseBatchPrefixes</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>SALTANDBATCHSUFFIXProperty</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1002</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableUseBatchPrefixes</ID>
              <Key>Registration/REGADMIN/EnableUseBatchPrefixes</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>EnableUseBatchPrefixes</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>SequenceDropDownList</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableUseBatchPrefixes</ID>
              <Key>Registration/REGADMIN/EnableUseBatchPrefixes</Key>
              <Value>False</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>SubmissionCommentsIDSettingForTempDups</ID>
          <Privileges>
            <Operator>OR</Operator>
            <Privilege>
              <ID>REGISTER_TEMP</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>SubmissionCommentsID</ID>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <AppSetting>
              <ID>ApprovalsEnabled</ID>
              <Key>Registration/REGADMIN/EnableSubmissionDuplicateChecking</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_BULKREGISTERMARKED_CONTENTAREA_REGISTERMARKED_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegisterMarkedPageAccess</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegisterMarkedPageAccess</ID>
            <Privilege>
              <ID>REGISTER_TEMP</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_BULKREGISTERMARKED_CONTENTAREA_REGISTERMARKED_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_COMPONENTDUPLICATES_CONTENTAREA_COMPONENTDUPLICATES_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RLS Enabled Registry Level</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Mix_ProjectsUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
              <COEFormID>9</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Registry_Identifiers</ID>
              <Key>Registration/MISC/ProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>RLS Enabled Batch Level</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Batch_ProjectsUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
              <COEFormID>2</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Registry_Identifiers</ID>
              <Key>Registration/MISC/BatchProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Registry Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Mix_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
              <COEFormID>9</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>ProjectsUsed</ID>
              <Key>Registration/MISC/Registry_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Component Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>'; 


L_CustomXml_4 CLOB:='            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>ACompoundIdentifiersUltraGrid</ID>
              <TypeOfControl>CompositeControl</TypeOfControl>
              <ParentControlID>ComponentRepeater</ParentControlID>
              <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
              <COEFormID>9</COEFormID>
            </Control>
            <Control>
              <ID>ACompoundIdentifiersUltraGrid</ID>
              <TypeOfControl>CompositeControl</TypeOfControl>
              <ParentControlID>ComponentRepeater</ParentControlID>
              <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
            <Control>
              <ID>ACompoundIdentifiersUltraGrid</ID>
              <TypeOfControl>CompositeControl</TypeOfControl>
              <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
            <Control>
              <ID>ACompoundIdentifiersUltraGrid0OF1</ID>
              <TypeOfControl>COEWebGridColumn</TypeOfControl>
              <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>ComponentIdentifiers</ID>
              <Key>Registration/MISC/Component_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Batch Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Batch_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
              <COEFormID>2</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>BatchIdentifiers</ID>
              <Key>Registration/MISC/Batch_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>AddBatchButton</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>AddBatchButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableAddBatchButton</ID>
              <Key>Registration/REGADMIN/EnableAddBatchButton</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>DuplicateRegistryButton</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>DuplicateRegistryButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableDuplicateButton</ID>
              <Key>Registration/REGADMIN/EnableDuplicateButton</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>CreateCompoundFormButton</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>CreateCompoundFormButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableUseComponentButton</ID>
              <Key>Registration/REGADMIN/EnableUseComponentButton</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>UseStructureButton</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>UseStructureButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableUseStructureButton</ID>
              <Key>Registration/REGADMIN/EnableUseStructureButton</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>BatchComponentCustomProperties</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>1003</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
              <Action>Hide</Action>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableMixtures</ID>
              <Key>Registration/REGADMIN/EnableMixtures</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Structure Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Structure_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Structure_Identifiers</ID>
              <Key>Registration/MISC/Structure_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>ComponentsFragmentsGrid</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>3</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>duplicateRepeaterFormHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableFragments</ID>
              <Key>Registration/REGADMIN/EnableFragments</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_VIEWMIXTURE_CONTENTAREA_VIEWMIXTURE_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RLS Enabled Registry Level</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Mix_ProjectsUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>ProjectsUsed</ID>
              <Key>Registration/MISC/ProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Manage Components</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID/>
            <Privilege>
              <ID>ADD_COMPONENT</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>DefineMixtureImageMenuButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableMixtures</ID>
              <Key>Registration/REGADMIN/EnableMixtures</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>'; 

L_CustomXml_5 CLOB:='        <ControlSetting>
          <ID>EditRegisteredRecord</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>EditRegisteredRecord</ID>
            <Privilege>
              <ID>EDIT_COMPOUND_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>EditButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>DeleteRegisteredRecord</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>DeleteRegisteredRecord</ID>
            <Privilege>
              <ID>DELETE_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>DeleteRecordImageMenuButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>DeleteMoveBatchFromPerm</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>DeleteMoveBatchFromPerm</ID>
            <Privilege>
              <ID>DELETE_BATCH_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>DeleteBatchButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
            <Control>
              <ID>MoveBatchButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>MoveBatchInPerm</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID>MoveBatchInPerm</ID>
          </Privileges>
          <Controls>
            <Control>
              <ID>MoveBatchButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableMoveBatch</ID>
              <Key>Registration/REGADMIN/EnableMoveBatch</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>AddComponentPerm</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>AddComponentPerm</ID>
            <Privilege>
              <ID>ADD_COMPONENT</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>AddComponentButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>AddBatchPerm</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>AddBatchPerm</ID>
            <Privilege>
              <ID>ADD_BATCH_PERM</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>AddBatchButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>SendToInventory</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>SendToInventory</ID>
            <Privilege>
              <ID>INV_CREATE_CONTAINER</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>SendToInventoryImageMenuButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <ID>InventoryIntegration</ID>
            <Operator>AND</Operator>
            <AppSetting>
              <ID>InventoryIntegration</ID>
              <Key>Registration/INVENTORY/InventoryIntegration</Key>
              <Value>Enabled</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>EditApprovedRecord</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID/>
            <Privilege>
              <ID>TOGGLE_APPROVED_FLAG</ID>
            </Privilege>
            <Privilege>
              <ID>EDIT_COMPOUND_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>EditButton</ID>
              <TypeOfControl>Control</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
            <Control>
              <ID>0</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
              <Action>Disable</Action>
            </Control>
            <Control>
              <ID>1000</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
              <Action>Disable</Action>
            </Control>
            <Control>
              <ID>1</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
              <Action>Disable</Action>
            </Control>
            <Control>
              <ID>1001</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
              <Action>Disable</Action>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>AND</Operator>
            <ID>LockingEnabled</ID>
            <AppSetting>
              <ID>ApprovalsEnabled</ID>
              <Key>Registration/REGADMIN/LockingEnabled</Key>
              <Value>False</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
            <AppSetting>
              <ID>IsRegistryLocked</ID>
              <Key>IsRegistryLocked</Key>
              <Value>True</Value>
              <Type>Session</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>ApprovedEnabled</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID/>
            <Privilege>
              <ID>SET_APPROVED_FLAG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>APPROVEDProperty</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>AND</Operator>
            <ID/>
            <AppSetting>
              <ID>ApprovalsEnabled</ID>
              <Key>Registration/REGADMIN/ApprovalsEnabled</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>ComponentsFragmentsGrid</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>5</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableFragments</ID>
              <Key>Registration/REGADMIN/EnableFragments</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Registry Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Mix_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Registry_Identifiers</ID>
              <Key>Registration/MISC/Registry_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>ComponentsFragmentsGridEdit</ID>
          <Privileges>'; 

L_CustomXml_6 CLOB:='            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>6</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableFragments</ID>
              <Key>Registration/REGADMIN/EnableFragments</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Batch Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Batch_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>4</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Batch_Identifiers</ID>
              <Key>Registration/MISC/Batch_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Batch Projects</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Batch_ProjectsUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>4</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>BatchProjectsUsed</ID>
              <Key>Registration/MISC/BatchProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Batch Form Enabled</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>4</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>BatchProjectsUsed</ID>
              <Key>Registration/MISC/BatchProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
            <AppSetting>
              <ID>Batch_Identifiers</ID>
              <Key>Registration/MISC/Batch_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Structure Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Structure_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Structure_Identifiers</ID>
              <Key>Registration/MISC/Structure_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>Component Identifiers</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Compound_IdentifiersUltraGrid</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1001</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>Component_Identifiers</ID>
              <Key>Registration/MISC/Component_Identifiers</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>ShowContainers</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>ShowContainers</ID>
            <Privilege>
              <ID>INV_BROWSE_ALL</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>9</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
              <Action>Hide</Action>
            </Control>
          </Controls>
          <AppSettings>
            <ID>InventoryIntegration</ID>
            <Operator>AND</Operator>
            <AppSetting>
              <ID>InventoryIntegration</ID>
              <Key>Registration/INVENTORY/InventoryIntegration</Key>
              <Value>Enabled</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>RequestMaterial</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RequestMaterial</ID>
            <Privilege>
              <ID>INV_SAMPLE_REQUEST</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ReqMaterial</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>9</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>AND</Operator>
            <ID/>
            <AppSetting>
              <ID>ShowRequestMaterial</ID>
              <Key>Registration/INVENTORY/ShowRequestMaterial</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
            <AppSetting>
              <ID>InvHasRegIdInGroupingField</ID>
              <Key>InvHasRegIdInGroupingField</Key>
              <Value>True</Value>
              <Type>Application</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>RequestMaterialFromBatch</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RequestMaterialFromBatch</ID>
            <Privilege>
              <ID>INV_SAMPLE_REQUEST</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>RequestFromBatchURL</ID>
              <TypeOfControl>Control</TypeOfControl>
              <ParentControlID>VContainersUltraGrid0OF1</ParentControlID>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>9</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>AND</Operator>
            <ID/>
            <AppSetting>
              <ID>ShowRequestFromBatch</ID>
              <Key>Registration/INVENTORY/ShowRequestFromBatch</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
            <AppSetting>
              <ID>InvHasRegBatchIdInGroupingField</ID>
              <Key>InvHasRegBatchIdInGroupingField</Key>
              <Value>True</Value>
              <Type>Application</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>RequestMaterialFromContainer</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RequestMaterialFromContainer</ID>
            <Privilege>
              <ID>INV_SAMPLE_REQUEST</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>RequestFromContainerURL</ID>
              <TypeOfControl>Control</TypeOfControl>
              <ParentControlID>VContainersUltraGrid0OF1</ParentControlID>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>9</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>ShowRequestFromContainer</ID>
              <Key>Registration/INVENTORY/ShowRequestFromContainer</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>StatusControlSettingForLocking</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>LockedStatusProperty</ID>
              <Description>This control allows the modification of the status from Registered to Locked and the other way around</Description>
              <FriendlyName>Lock Control</FriendlyName>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <COEFormID>0</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <AppSetting>
              <ID>LockingEnabled</ID>
              <Key>Registration/REGADMIN/LockingEnabled</Key>
              <Value>True</Value>'; 

L_CustomXml_7 CLOB:='              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>EnableUseBatchPrefixes</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>BATCH_PREFIXProperty</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1002</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableUseBatchPrefixes</ID>
              <Key>Registration/REGADMIN/EnableUseBatchPrefixes</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>EnableUseBatchPrefixes</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>SALTANDBATCHSUFFIXProperty</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>1002</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>EnableUseBatchPrefixes</ID>
              <Key>Registration/REGADMIN/EnableUseBatchPrefixes</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>DocMgrEnabled</ID>
          <Privileges>
             <Operator>AND</Operator> 
          </Privileges>
          <Controls>
            <Control>
              <ID>8</ID>
              <TypeOfControl>COEForm</TypeOfControl>
              <PlaceHolderID>mixtureInformationHolder</PlaceHolderID>
              <COEFormID>-1</COEFormID>
              <Action>Hide</Action>
            </Control>
          </Controls>
          <AppSettings>
            <ID>DocMgrEnabled</ID>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>DocMgrEnabled</ID>
              <Key>REGISTRATION/DOCMGR/DocMgrEnabled</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_VIEWMIXTURE_CONTENTAREA_MOVEDELETE_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>MoveDeletePageAccess</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>MoveDeletePageAccess</ID>
            <Privilege>
              <ID>DELETE_BATCH_REG</ID>
            </Privilege>
            <Privilege>
              <ID>DELETE_TEMP</ID>
            </Privilege>
            <Privilege>
              <ID>DELETE_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_VIEWMIXTURE_CONTENTAREA_MOVEDELETE_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_VIEWMIXTURE_CONTENTAREA_VIEWMIXTURESEARCH_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>SearchRegistry</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>SearchRegistry</ID>
            <Privilege>
              <ID>SEARCH_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_VIEWMIXTURE_CONTENTAREA_VIEWMIXTURESEARCH_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REVIEWREGISTER_CONTENTAREA_REVIEWREGISTERSEARCH_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>SearchTempRegistry</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>SearchTempRegistry</ID>
            <Privilege>
              <ID>SEARCH_TEMP</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REVIEWREGISTER_CONTENTAREA_REVIEWREGISTERSEARCH_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_DEFAULT_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegAdmin_Default</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegAdmin_Default</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_DEFAULT_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_TABLEEDITOR_CONTENTAREA_TABLEEDITOR_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>TableEditorPage</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>TableEditorPage</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_TABLEEDITOR_CONTENTAREA_TABLEEDITOR_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
        <ControlSetting>
          <ID>VW_PROJECT_ChildTable</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID/>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>VW_PROJECT_ChildTable</ID>
              <TypeOfControl>
                COETableManagerChildTable
              </TypeOfControl>
              <PlaceHolderID>COETableManager1</PlaceHolderID>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>ApprovalsEnabled</ID>
              <Key>Registration/REGADMIN/ActiveRLS</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ROOTPROPERTYLIST_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegAdmin_RootPropertyList</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegAdmin_RootPropertyList</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ROOTPROPERTYLIST_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_COMPOUND_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegAdmin_Compound</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegAdmin_Compound</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_COMPOUND_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_BATCH_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegAdmin_BatchPage</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegAdmin_BatchPage</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_BATCH_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>'; 

L_CustomXml_8 CLOB:='            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_PARAMEDIT_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegAdmin_ParamEdit</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegAdmin_ParamEdit</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_PARAMEDIT_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_VALIDATIONRULES_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegAdmin_ValRules</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegAdmin_ValRules</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_VALIDATIONRULES_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ADDINS_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegAdmin_AddInsPage</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegAdmin_AddInsPage</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ADDINS_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ADDINSEDIT_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegAdmin_AddInsEditPage</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegAdmin_AddInsEditPage</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_ADDINSEDIT_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_IMPORTEXPORTCUSTOM_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegAdmin_ImpExp</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegAdmin_ImpExp</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_IMPORTEXPORTCUSTOM_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_CONFIGSETTINGS_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>RegAdmin_ConfigSet</ID>
          <Privileges>
            <Operator>OR</Operator>
            <ID>RegAdmin_ConfigSet</ID>
            <Privilege>
              <ID>CONFIG_REG</ID>
            </Privilege>
          </Privileges>
          <Controls>
            <Control>
              <ID>ASP.FORMS_REGISTRATIONADMIN_CONTENTAREA_CONFIGSETTINGS_ASPX</ID>
              <TypeOfControl>Page</TypeOfControl>
              <PlaceHolderID/>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings/>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_PUBLIC_CONTENTAREA_HOME_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>ApprovedTempRegistries</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>ApprovedTempRegistries</ID>
              <PlaceHolderID/>
              <TypeOfControl>Control</TypeOfControl>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <AppSetting>
              <ID>ApprovalsEnabled</ID>
              <Key>Registration/REGADMIN/ApprovalsEnabled</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>SubmittedTempRegistries</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>SubmittedTempRegistries</ID>
              <PlaceHolderID/>
              <TypeOfControl>Control</TypeOfControl>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <AppSetting>
              <ID>ApprovalsEnabled</ID>
              <Key>Registration/REGADMIN/ApprovalsEnabled</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
        <ControlSetting>
          <ID>TempRegistries</ID>
          <Privileges>
            <Operator>AND</Operator>
          </Privileges>
          <Controls>
            <Control>
              <ID>TempRegistries</ID>
              <PlaceHolderID/>
              <TypeOfControl>Control</TypeOfControl>
              <COEFormID>-1</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <AppSetting>
              <ID>ApprovalsEnabled</ID>
              <Key>Registration/REGADMIN/ApprovalsEnabled</Key>
              <Value>False</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
      </ControlSettings>
    </Page>
    <Page>
      <ID>ASP.FORMS_REGISTRYDUPLICATES_CONTENTAREA_REGISTRYDUPLICATES_ASPX</ID>
      <ControlSettings>
        <ControlSetting>
          <ID>Projects Enabled Batch Level</ID>
          <Privileges>
            <Operator>AND</Operator>
            <ID/>
          </Privileges>
          <Controls>
            <Control>
              <ID>Batch_ProjectsUltraGrid0OF1</ID>
              <TypeOfControl>COEGenerableControl</TypeOfControl>
              <PlaceHolderID>duplicateFormHolder</PlaceHolderID>
              <COEFormID>2</COEFormID>
            </Control>
          </Controls>
          <AppSettings>
            <Operator>OR</Operator>
            <ID/>
            <AppSetting>
              <ID>BatchProjectsUsed</ID>
              <Key>Registration/MISC/BatchProjectsUsed</Key>
              <Value>True</Value>
              <Type>COEConfiguration</Type>
            </AppSetting>
          </AppSettings>
        </ControlSetting>
      </ControlSettings>
    </Page>
  </Pages>
</COEPageControlSettings>'; 


BEGIN
    
    UPDATE COEDB.COEPAGECONTROL SET CONFIGURATIONXML=L_CustomXml_1 ||L_CustomXml_2 ||L_CustomXml_3||L_CustomXml_4||L_CustomXml_5||L_CustomXml_6||L_CustomXml_7||L_CustomXml_8   WHERE APPLICATION IN ('REGISTRATION') AND TYPE='CUSTOM';

   
END;
/