using System;
using System.Collections.Generic;
using System.Text;
using NUnit.Framework;
using CambridgeSoft.COE.Registration.Services.Types;

namespace CambridgeSoft.COE.Registration.UnitTests.BLL
{
    [TestFixture]
    public class ComponentListTests
    {
        #region XML

        private const string updatedComponentXml_PropertyChanged = @"<MultiCompoundRegistryRecord SameBatchesIdentity=""True"" ActiveRLS=""Off"" IsEditable=""True"">
   <ComponentList>
    <Component>
      <ID/>
      <ComponentIndex>-2</ComponentIndex>
      <Compound>
        <CompoundID>2</CompoundID>
        <DateCreated>2011-07-22 02:00:02</DateCreated>
        <PersonCreated>15</PersonCreated>
        <PersonRegistered>15</PersonRegistered>
        <DateLastModified>2011-08-05 03:11:22</DateLastModified>
        <Tag/>
        <PropertyList>
          <Property name=""CMP_COMMENTS"">changed commnents</Property>
          <Property name=""STRUCTURE_COMMENTS_TXT"">ecc</Property>
        </PropertyList>
        <RegNumber>
          <RegID>4</RegID>
          <SequenceNumber>2</SequenceNumber>
          <RegNumber>C000002</RegNumber>
          <SequenceID>2</SequenceID>
        </RegNumber>
        <BaseFragment>
          <Structure>
            <StructureID>6</StructureID>
            <StructureFormat/>
            <Structure molWeight=""194.35624"" formula=""C14H26"">VmpDRDAxMDAEAwIBAAAAAAAAAAAAAACAAAAAAAMAFQAAAENoZW1EcmF3IDEyLjAu
Mi45MTgIABMAAABVbnRpdGxlZCBEb2N1bWVudAQCEABriT0AawlUAJT2hgC94+UA
AQkIAADAEgAAQP//AgkIAAAAAAAAAAAADQgBAAEIBwEAAToEAQABOwQBAABFBAEA
ATwEAQAADAYBAAEPBgEAAQ0GAQAAQgQBAABDBAEAAEQEAQAACggIAAMAYADIAAMA
CwgIAAQAAADwAAMACQgEADOzAgAICAQAAAACAAcIBAAAAAEABggEAAAABAAFCAQA
AAAeAAQIAgB4AAMIBAAAAHgAIwgBAAUMCAEAACgIAQABKQgBAAEqCAEAAQIIEAAA
ACQAAAAkAAAAJAAAACQAAQMCAAAAAgMCAAEAAAMyAAgA////////AAAAAAAA//8A
AAAA/////wAAAAD//wAAAAD/////AAAAAP////8AAP//AAEkAAAAAgADAOQEBQBB
cmlhbAQA5AQPAFRpbWVzIE5ldyBSb21hbgGALgAAAAQCEAAAAAAAAAAAAJR2+AKU
dmgCFggEAAAAJAAYCAQAAAAkABkIAAAQCAIAAQAPCAIAAQADgAUAAAAEAhAAa4k9
AGsJVACU9oYAvePlAASAAgAAAAACCAAAQFMAa4lUAAoAAgABADcEAQABAAAEgAQA
AAAAAggAAEBxAGuJVAAKAAIAAwA3BAEAAQAABIAGAAAAAAIIAJR2hgAAwGkACgAC
AAUANwQBAAEAAASACAAAAAACCACUdoYAAMCHAAoAAgAHADcEAQABAAAEgAoAAAAA
AggAAEBxAJT2nAAKAAIACQAAAASADAAAAAACCAAAQFMAlPacAAoAAgALAAAABIAO
AAAAAAIIAGsJPgAAwIcACgACAA0ANwQBAAEAAASAEAAAAAACCABrCT4AAMBpAAoA
AgAPADcEAQABAAAEgBoAAAAAAggAlHaGACktsgAKAAIAGQA3BAEAAQAABIAcAAAA
AAIIAJR2hgApLdAACgACABsANwQBAAEAAASAHgAAAAACCAAAQHEAvWPlAAoAAgAd
ADcEAQABAAAEgCAAAAAAAggAAEBTAL1j5QAKAAIAHwA3BAEAAQAABIAiAAAAAAII
AGsJPgApLdAACgACACEANwQBAAEAAASAJAAAAAACCABrCT4AKS2yAAoAAgAjADcE
AQABAAAFgBIAAAAKAAIAEQAEBgQAAgAAAAUGBAAEAAAACgYBAAEAAAWAEwAAAAoA
AgASAAQGBAAEAAAABQYEAAYAAAAKBgEAAQAABYAUAAAACgACABMABAYEAAYAAAAF
BgQACAAAAAoGAQABAAAFgBUAAAAKAAIAFAAEBgQACAAAAAUGBAAKAAAACgYBAAEA
AAWAFgAAAAoAAgAVAAQGBAAKAAAABQYEAAwAAAAKBgEAAQAABYAXAAAACgACABYA
BAYEAAwAAAAFBgQADgAAAAoGAQABAAAFgBgAAAAKAAIAFwAEBgQADgAAAAUGBAAQ
AAAACgYBAAEAAAWAGQAAAAoAAgAYAAQGBAAQAAAABQYEAAIAAAAKBgEAAQAABYAm
AAAACgACACUABAYEAAoAAAAFBgQAGgAAAAoGAQABAAAFgCcAAAAKAAIAJgAEBgQA
GgAAAAUGBAAcAAAACgYBAAEAAAWAKAAAAAoAAgAnAAQGBAAcAAAABQYEAB4AAAAK
BgEAAQAABYApAAAACgACACgABAYEAB4AAAAFBgQAIAAAAAoGAQABAAAFgCoAAAAK
AAIAKQAEBgQAIAAAAAUGBAAiAAAACgYBAAEAAAWAKwAAAAoAAgAqAAQGBAAiAAAA
BQYEACQAAAAKBgEAAQAABYAsAAAACgACACsABAYEACQAAAAFBgQADAAAAAoGAQAB
AAAAAAAAAAAAAA==
</Structure>
            <NormalizedStructure>VmpDRDAxMDAEAwIBAAAAAAAAAAAAAACAAAAAAAMAFQAAAENoZW1EcmF3IDEyLjAu
Mi45MTgIABMAAABVbnRpdGxlZCBEb2N1bWVudAQCEABriT0AawlUAJT2hgC94+UA
AQkIAADAEgAAQP//AgkIAAAAAAAAAAAADQgBAAEIBwEAAToEAQABOwQBAABFBAEA
ATwEAQAADAYBAAEPBgEAAQ0GAQAAQgQBAABDBAEAAEQEAQAACggIAAMAYADIAAMA
CwgIAAQAAADwAAMACQgEADOzAgAICAQAAAACAAcIBAAAAAEABggEAAAABAAFCAQA
AAAeAAQIAgB4AAMIBAAAAHgAIwgBAAUMCAEAACgIAQABKQgBAAEqCAEAAQIIEAAA
ACQAAAAkAAAAJAAAACQAAQMCAAAAAgMCAAEAAAMyAAgA////////AAAAAAAA//8A
AAAA/////wAAAAD//wAAAAD/////AAAAAP////8AAP//AAEkAAAAAgADAOQEBQBB
cmlhbAQA5AQPAFRpbWVzIE5ldyBSb21hbgGALgAAAAQCEAAAAAAAAAAAAJR2+AKU
dmgCFggEAAAAJAAYCAQAAAAkABkIAAAQCAIAAQAPCAIAAQADgAUAAAAEAhAAa4k9
AGsJVACU9oYAvePlAASAAgAAAAACCAAAQFMAa4lUAAoAAgABADcEAQABAAAEgAQA
AAAAAggAAEBxAGuJVAAKAAIAAwA3BAEAAQAABIAGAAAAAAIIAJR2hgAAwGkACgAC
AAUANwQBAAEAAASACAAAAAACCACUdoYAAMCHAAoAAgAHADcEAQABAAAEgAoAAAAA
AggAAEBxAJT2nAAKAAIACQAAAASADAAAAAACCAAAQFMAlPacAAoAAgALAAAABIAO
AAAAAAIIAGsJPgAAwIcACgACAA0ANwQBAAEAAASAEAAAAAACCABrCT4AAMBpAAoA
AgAPADcEAQABAAAEgBoAAAAAAggAlHaGACktsgAKAAIAGQA3BAEAAQAABIAcAAAA
AAIIAJR2hgApLdAACgACABsANwQBAAEAAASAHgAAAAACCAAAQHEAvWPlAAoAAgAd
ADcEAQABAAAEgCAAAAAAAggAAEBTAL1j5QAKAAIAHwA3BAEAAQAABIAiAAAAAAII
AGsJPgApLdAACgACACEANwQBAAEAAASAJAAAAAACCABrCT4AKS2yAAoAAgAjADcE
AQABAAAFgBIAAAAKAAIAEQAEBgQAAgAAAAUGBAAEAAAACgYBAAEAAAWAEwAAAAoA
AgASAAQGBAAEAAAABQYEAAYAAAAKBgEAAQAABYAUAAAACgACABMABAYEAAYAAAAF
BgQACAAAAAoGAQABAAAFgBUAAAAKAAIAFAAEBgQACAAAAAUGBAAKAAAACgYBAAEA
AAWAFgAAAAoAAgAVAAQGBAAKAAAABQYEAAwAAAAKBgEAAQAABYAXAAAACgACABYA
BAYEAAwAAAAFBgQADgAAAAoGAQABAAAFgBgAAAAKAAIAFwAEBgQADgAAAAUGBAAQ
AAAACgYBAAEAAAWAGQAAAAoAAgAYAAQGBAAQAAAABQYEAAIAAAAKBgEAAQAABYAm
AAAACgACACUABAYEAAoAAAAFBgQAGgAAAAoGAQABAAAFgCcAAAAKAAIAJgAEBgQA
GgAAAAUGBAAcAAAACgYBAAEAAAWAKAAAAAoAAgAnAAQGBAAcAAAABQYEAB4AAAAK
BgEAAQAABYApAAAACgACACgABAYEAB4AAAAFBgQAIAAAAAoGAQABAAAFgCoAAAAK
AAIAKQAEBgQAIAAAAAUGBAAiAAAACgYBAAEAAAWAKwAAAAoAAgAqAAQGBAAiAAAA
BQYEACQAAAAKBgEAAQAABYAsAAAACgACACsABAYEACQAAAAFBgQADAAAAAoGAQAB
AAAAAAAAAAAAAA==
</NormalizedStructure>
            <UseNormalization>T</UseNormalization>
            <DrawingType>0</DrawingType>
            <PropertyList>
              <Property name=""STRUCT_COMMENTS"">sccc</Property>
              <Property name=""STRUCT_NAME"">tetradecahydrooctalene</Property>
            </PropertyList>
            <IdentifierList/>
          </Structure>
        </BaseFragment>
        <FragmentList>
          <Fragment>
            <CompoundFragmentID>3</CompoundFragmentID>
            <FragmentID>343</FragmentID>
            <Code>343</Code>
            <Name>1-Propanol</Name>
            <FragmentTypeID lookupTable=""FragmentType"" lookupField=""ID"" displayField=""Description"" displayValue=""Solvate"">2</FragmentTypeID>
            <DateCreated>2009-06-30 02:02:33</DateCreated>
            <DateLastModified>2009-06-30 02:02:33</DateLastModified>
            <Equivalents/>
            <Structure>
              <StructureFormat/>
              <Structure molWeight=""60.09502"" formula=""C3H8O"">
        VmpDRDAxMDAEAwIBAAAAAAAAAAAAAACAAAAAAAMAGAAAAENzQ2FydHJpZGdlIDEx
        LjAuMC4xNjUAAw4AAgD///////8AAAAAAAABgAAAAAADgAoAAAAEgAEAAAAAAASA
        AgAAAAAABIADAAAAAAAEgAQAAAACBAIACAAAAAWABgAAAAQGBAABAAAABQYEAAIA
        AAAAAAWABwAAAAQGBAACAAAABQYEAAMAAAAAAAWACAAAAAQGBAADAAAABQYEAAQA
        AAAAAAAAAAAAAAAA
      </Structure>
            </Structure>
          </Fragment>
        </FragmentList>
        <IdentifierList/>
      </Compound>
    </Component>
  </ComponentList>
</MultiCompoundRegistryRecord>";

        private const string updatedComponentXml_StructurePropertyChanged = @"<MultiCompoundRegistryRecord SameBatchesIdentity=""True"" ActiveRLS=""Off"" IsEditable=""True"">
   <ComponentList>
    <Component>
      <ID/>
      <ComponentIndex>-2</ComponentIndex>
      <Compound>
        <CompoundID>2</CompoundID>
        <DateCreated>2011-07-22 02:00:02</DateCreated>
        <PersonCreated>15</PersonCreated>
        <PersonRegistered>15</PersonRegistered>
        <DateLastModified>2011-08-05 03:11:22</DateLastModified>
        <Tag/>
        <PropertyList>
          <Property name=""CMP_COMMENTS"">ccc</Property>
          <Property name=""STRUCTURE_COMMENTS_TXT"">ecc</Property>
        </PropertyList>
        <RegNumber>
          <RegID>4</RegID>
          <SequenceNumber>2</SequenceNumber>
          <RegNumber>C000002</RegNumber>
          <SequenceID>2</SequenceID>
        </RegNumber>
        <BaseFragment>
          <Structure>
            <StructureID>6</StructureID>
            <StructureFormat/>
            <Structure molWeight=""194.35624"" formula=""C14H26"">VmpDRDAxMDAEAwIBAAAAAAAAAAAAAACAAAAAAAMAFQAAAENoZW1EcmF3IDEyLjAu
Mi45MTgIABMAAABVbnRpdGxlZCBEb2N1bWVudAQCEABriT0AawlUAJT2hgC94+UA
AQkIAADAEgAAQP//AgkIAAAAAAAAAAAADQgBAAEIBwEAAToEAQABOwQBAABFBAEA
ATwEAQAADAYBAAEPBgEAAQ0GAQAAQgQBAABDBAEAAEQEAQAACggIAAMAYADIAAMA
CwgIAAQAAADwAAMACQgEADOzAgAICAQAAAACAAcIBAAAAAEABggEAAAABAAFCAQA
AAAeAAQIAgB4AAMIBAAAAHgAIwgBAAUMCAEAACgIAQABKQgBAAEqCAEAAQIIEAAA
ACQAAAAkAAAAJAAAACQAAQMCAAAAAgMCAAEAAAMyAAgA////////AAAAAAAA//8A
AAAA/////wAAAAD//wAAAAD/////AAAAAP////8AAP//AAEkAAAAAgADAOQEBQBB
cmlhbAQA5AQPAFRpbWVzIE5ldyBSb21hbgGALgAAAAQCEAAAAAAAAAAAAJR2+AKU
dmgCFggEAAAAJAAYCAQAAAAkABkIAAAQCAIAAQAPCAIAAQADgAUAAAAEAhAAa4k9
AGsJVACU9oYAvePlAASAAgAAAAACCAAAQFMAa4lUAAoAAgABADcEAQABAAAEgAQA
AAAAAggAAEBxAGuJVAAKAAIAAwA3BAEAAQAABIAGAAAAAAIIAJR2hgAAwGkACgAC
AAUANwQBAAEAAASACAAAAAACCACUdoYAAMCHAAoAAgAHADcEAQABAAAEgAoAAAAA
AggAAEBxAJT2nAAKAAIACQAAAASADAAAAAACCAAAQFMAlPacAAoAAgALAAAABIAO
AAAAAAIIAGsJPgAAwIcACgACAA0ANwQBAAEAAASAEAAAAAACCABrCT4AAMBpAAoA
AgAPADcEAQABAAAEgBoAAAAAAggAlHaGACktsgAKAAIAGQA3BAEAAQAABIAcAAAA
AAIIAJR2hgApLdAACgACABsANwQBAAEAAASAHgAAAAACCAAAQHEAvWPlAAoAAgAd
ADcEAQABAAAEgCAAAAAAAggAAEBTAL1j5QAKAAIAHwA3BAEAAQAABIAiAAAAAAII
AGsJPgApLdAACgACACEANwQBAAEAAASAJAAAAAACCABrCT4AKS2yAAoAAgAjADcE
AQABAAAFgBIAAAAKAAIAEQAEBgQAAgAAAAUGBAAEAAAACgYBAAEAAAWAEwAAAAoA
AgASAAQGBAAEAAAABQYEAAYAAAAKBgEAAQAABYAUAAAACgACABMABAYEAAYAAAAF
BgQACAAAAAoGAQABAAAFgBUAAAAKAAIAFAAEBgQACAAAAAUGBAAKAAAACgYBAAEA
AAWAFgAAAAoAAgAVAAQGBAAKAAAABQYEAAwAAAAKBgEAAQAABYAXAAAACgACABYA
BAYEAAwAAAAFBgQADgAAAAoGAQABAAAFgBgAAAAKAAIAFwAEBgQADgAAAAUGBAAQ
AAAACgYBAAEAAAWAGQAAAAoAAgAYAAQGBAAQAAAABQYEAAIAAAAKBgEAAQAABYAm
AAAACgACACUABAYEAAoAAAAFBgQAGgAAAAoGAQABAAAFgCcAAAAKAAIAJgAEBgQA
GgAAAAUGBAAcAAAACgYBAAEAAAWAKAAAAAoAAgAnAAQGBAAcAAAABQYEAB4AAAAK
BgEAAQAABYApAAAACgACACgABAYEAB4AAAAFBgQAIAAAAAoGAQABAAAFgCoAAAAK
AAIAKQAEBgQAIAAAAAUGBAAiAAAACgYBAAEAAAWAKwAAAAoAAgAqAAQGBAAiAAAA
BQYEACQAAAAKBgEAAQAABYAsAAAACgACACsABAYEACQAAAAFBgQADAAAAAoGAQAB
AAAAAAAAAAAAAA==
</Structure>
            <NormalizedStructure>VmpDRDAxMDAEAwIBAAAAAAAAAAAAAACAAAAAAAMAFQAAAENoZW1EcmF3IDEyLjAu
Mi45MTgIABMAAABVbnRpdGxlZCBEb2N1bWVudAQCEABriT0AawlUAJT2hgC94+UA
AQkIAADAEgAAQP//AgkIAAAAAAAAAAAADQgBAAEIBwEAAToEAQABOwQBAABFBAEA
ATwEAQAADAYBAAEPBgEAAQ0GAQAAQgQBAABDBAEAAEQEAQAACggIAAMAYADIAAMA
CwgIAAQAAADwAAMACQgEADOzAgAICAQAAAACAAcIBAAAAAEABggEAAAABAAFCAQA
AAAeAAQIAgB4AAMIBAAAAHgAIwgBAAUMCAEAACgIAQABKQgBAAEqCAEAAQIIEAAA
ACQAAAAkAAAAJAAAACQAAQMCAAAAAgMCAAEAAAMyAAgA////////AAAAAAAA//8A
AAAA/////wAAAAD//wAAAAD/////AAAAAP////8AAP//AAEkAAAAAgADAOQEBQBB
cmlhbAQA5AQPAFRpbWVzIE5ldyBSb21hbgGALgAAAAQCEAAAAAAAAAAAAJR2+AKU
dmgCFggEAAAAJAAYCAQAAAAkABkIAAAQCAIAAQAPCAIAAQADgAUAAAAEAhAAa4k9
AGsJVACU9oYAvePlAASAAgAAAAACCAAAQFMAa4lUAAoAAgABADcEAQABAAAEgAQA
AAAAAggAAEBxAGuJVAAKAAIAAwA3BAEAAQAABIAGAAAAAAIIAJR2hgAAwGkACgAC
AAUANwQBAAEAAASACAAAAAACCACUdoYAAMCHAAoAAgAHADcEAQABAAAEgAoAAAAA
AggAAEBxAJT2nAAKAAIACQAAAASADAAAAAACCAAAQFMAlPacAAoAAgALAAAABIAO
AAAAAAIIAGsJPgAAwIcACgACAA0ANwQBAAEAAASAEAAAAAACCABrCT4AAMBpAAoA
AgAPADcEAQABAAAEgBoAAAAAAggAlHaGACktsgAKAAIAGQA3BAEAAQAABIAcAAAA
AAIIAJR2hgApLdAACgACABsANwQBAAEAAASAHgAAAAACCAAAQHEAvWPlAAoAAgAd
ADcEAQABAAAEgCAAAAAAAggAAEBTAL1j5QAKAAIAHwA3BAEAAQAABIAiAAAAAAII
AGsJPgApLdAACgACACEANwQBAAEAAASAJAAAAAACCABrCT4AKS2yAAoAAgAjADcE
AQABAAAFgBIAAAAKAAIAEQAEBgQAAgAAAAUGBAAEAAAACgYBAAEAAAWAEwAAAAoA
AgASAAQGBAAEAAAABQYEAAYAAAAKBgEAAQAABYAUAAAACgACABMABAYEAAYAAAAF
BgQACAAAAAoGAQABAAAFgBUAAAAKAAIAFAAEBgQACAAAAAUGBAAKAAAACgYBAAEA
AAWAFgAAAAoAAgAVAAQGBAAKAAAABQYEAAwAAAAKBgEAAQAABYAXAAAACgACABYA
BAYEAAwAAAAFBgQADgAAAAoGAQABAAAFgBgAAAAKAAIAFwAEBgQADgAAAAUGBAAQ
AAAACgYBAAEAAAWAGQAAAAoAAgAYAAQGBAAQAAAABQYEAAIAAAAKBgEAAQAABYAm
AAAACgACACUABAYEAAoAAAAFBgQAGgAAAAoGAQABAAAFgCcAAAAKAAIAJgAEBgQA
GgAAAAUGBAAcAAAACgYBAAEAAAWAKAAAAAoAAgAnAAQGBAAcAAAABQYEAB4AAAAK
BgEAAQAABYApAAAACgACACgABAYEAB4AAAAFBgQAIAAAAAoGAQABAAAFgCoAAAAK
AAIAKQAEBgQAIAAAAAUGBAAiAAAACgYBAAEAAAWAKwAAAAoAAgAqAAQGBAAiAAAA
BQYEACQAAAAKBgEAAQAABYAsAAAACgACACsABAYEACQAAAAFBgQADAAAAAoGAQAB
AAAAAAAAAAAAAA==
</NormalizedStructure>
            <UseNormalization>T</UseNormalization>
            <DrawingType>0</DrawingType>
            <PropertyList>
              <Property name=""STRUCT_COMMENTS"">changed structure comments</Property>
              <Property name=""STRUCT_NAME"">tetradecahydrooctalene</Property>
            </PropertyList>
            <IdentifierList/>
          </Structure>
        </BaseFragment>
        <FragmentList>
          <Fragment>
            <CompoundFragmentID>3</CompoundFragmentID>
            <FragmentID>343</FragmentID>
            <Code>343</Code>
            <Name>1-Propanol</Name>
            <FragmentTypeID lookupTable=""FragmentType"" lookupField=""ID"" displayField=""Description"" displayValue=""Solvate"">2</FragmentTypeID>
            <DateCreated>2009-06-30 02:02:33</DateCreated>
            <DateLastModified>2009-06-30 02:02:33</DateLastModified>
            <Equivalents/>
            <Structure>
              <StructureFormat/>
              <Structure molWeight=""60.09502"" formula=""C3H8O"">
        VmpDRDAxMDAEAwIBAAAAAAAAAAAAAACAAAAAAAMAGAAAAENzQ2FydHJpZGdlIDEx
        LjAuMC4xNjUAAw4AAgD///////8AAAAAAAABgAAAAAADgAoAAAAEgAEAAAAAAASA
        AgAAAAAABIADAAAAAAAEgAQAAAACBAIACAAAAAWABgAAAAQGBAABAAAABQYEAAIA
        AAAAAAWABwAAAAQGBAACAAAABQYEAAMAAAAAAAWACAAAAAQGBAADAAAABQYEAAQA
        AAAAAAAAAAAAAAAA
      </Structure>
            </Structure>
          </Fragment>
        </FragmentList>
        <IdentifierList/>
      </Compound>
    </Component>
  </ComponentList>
</MultiCompoundRegistryRecord>";

        #endregion

        private string originalXml = string.Empty;

        [SetUp]
        public void SetUp()
        {
            Helpers.Authentication.Logon("T5_85", "T5_85");
        }

        [Test]
        public void UpdateFromXml_Should_Update_ComponentListLevel_PropertyChanged()
        {
            RegistryRecord record = RegistryRecord.GetRegistryRecord("AB-000002");

            Assert.IsNotNull(record);

            if (string.IsNullOrEmpty(originalXml))
                originalXml = record.Xml;

            record.UpdateFromXml(updatedComponentXml_PropertyChanged);

            record.Save();

            RegistryRecord updatedRecord = RegistryRecord.GetRegistryRecord("AB-000002");

            string expectedCommnents = "changed commnents";

            Assert.AreEqual(expectedCommnents,updatedRecord.ComponentList[0].Compound.PropertyList["CMP_COMMENTS"].Value);

            if (!string.IsNullOrEmpty(originalXml))
            {
                updatedRecord.Xml = originalXml;
                updatedRecord.Save();
            }
        }

        [Test]
        public void UpdateFromXml_Should_Update_ComponentListLevel_StructurePropertyChanged()
        {
            RegistryRecord record = RegistryRecord.GetRegistryRecord("AB-000002");

            Assert.IsNotNull(record);

            if (string.IsNullOrEmpty(originalXml))
                originalXml = record.Xml;

            record.UpdateFromXml(updatedComponentXml_StructurePropertyChanged);

            record.Save();

            RegistryRecord updatedRecord = RegistryRecord.GetRegistryRecord("AB-000002");

            string expectedCommnents = "changed structure comments";

            Assert.AreEqual(expectedCommnents, updatedRecord.ComponentList[0].Compound.BaseFragment.Structure.PropertyList["STRUCT_COMMENTS"].Value);

            if (!string.IsNullOrEmpty(originalXml))
            {
                updatedRecord.Xml = originalXml;
                updatedRecord.Save();
            }
        }

        [TearDown]
        public void TearDown()
        {
            

            Helpers.Authentication.Logoff();
        }
    }
}
