prompt 
prompt Starting "pkg_Gui_Util_body.sql"...
prompt 

CREATE OR REPLACE PACKAGE BODY REGDB."GUI_UTIL"
AS

 PROCEDURE GETPROJECTNAMEVALUELIST(
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   Select PROJECTID, NAME from VW_PROJECT;
 END GETPROJECTNAMEVALUELIST;


 PROCEDURE GETPREFIXNAMEVALUELIST(
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   Select SEQUENCEID, PREFIX from VW_SEQUENCE;
 END GETPREFIXNAMEVALUELIST;


 PROCEDURE GETACTIVECHEMISTNAMEVALUELIST(
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   Select PERSON_ID, USER_ID from CS_SECURITY.PEOPLE where ACTIVE=1 order by USER_ID;
 END GETACTIVECHEMISTNAMEVALUELIST;


 PROCEDURE GETCHEMISTNAMEVALUELIST(
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   Select PERSON_ID, USER_ID from CS_SECURITY.PEOPLE order by USER_ID;
 END GETCHEMISTNAMEVALUELIST;

   PROCEDURE GETFRAGMENTTYPESVALUELIST(
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   SELECT ID,DESCRIPTION from REGDB.VW_FRAGMENTTYPE;
 END GETFRAGMENTTYPESVALUELIST;

 PROCEDURE GETPROJECTLIST (
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   SELECT PROJECTID, NAME, ACTIVE, DESCRIPTION, TYPE FROM VW_PROJECT ORDER BY NAME;
 END GETPROJECTLIST ;

 PROCEDURE GETACTIVEPROJECTLISTBYPERSONID (
  O_RS OUT CURSOR_TYPE, APersonID in Number,AType IN Char:='A') AS

 BEGIN
  OPEN O_RS FOR
    SELECT DISTINCT PRO.PROJECTID, PRO.NAME, PRO.ACTIVE, PRO.DESCRIPTION, PRO.TYPE
      FROM REGDB.VW_PROJECT PRO
	LEFT JOIN VW_PEOPLEPROJECT PEO ON  PEO.PROJECTID = PRO.PROJECTID AND PEO.PERSONID = APersonID
      WHERE PRO.ACTIVE = 'T' AND (PRO.TYPE=AType OR AType='A'OR PRO.TYPE='A')
      ORDER BY 2;
 END GETACTIVEPROJECTLISTBYPERSONID ;

 PROCEDURE GETIDENTIFIERLIST (
  O_RS OUT CURSOR_TYPE,AType IN Char:='A') AS

 BEGIN
  OPEN O_RS FOR
   SELECT ID, NAME, DESCRIPTION, ACTIVE FROM VW_IDENTIFIERTYPE WHERE ACTIVE = 'T' AND (TYPE=AType OR AType='A' OR TYPE='A');
 END GETIDENTIFIERLIST ;

 PROCEDURE GETFRAGMENTSLIST (
  O_RS OUT CURSOR_TYPE) AS

 BEGIN
  OPEN O_RS FOR
   	    SELECT F.FRAGMENTID, F.CODE, F.DESCRIPTION, F.FRAGMENTTYPEID,F.STRUCTURE, F.MOLWEIGHT, F.FORMULA FROM REGDB.VW_FRAGMENT F
            ORDER BY F.DESCRIPTION;
 END GETFRAGMENTSLIST;

 PROCEDURE GETMATCHEDFRAGMENTSLIST (
   AStructure IN CLOB, O_RS OUT CURSOR_TYPE
 ) AS

 BEGIN
  OPEN O_RS FOR
   	    SELECT F.FRAGMENTID, F.CODE, F.DESCRIPTION, F.FRAGMENTTYPEID,F.STRUCTURE, F.MOLWEIGHT, F.FORMULA FROM REGDB.VW_FRAGMENT F
        WHERE CsCARTRIDGE.MoleculeContains(
            F.STRUCTURE, dbms_lob.substr(AStructure, 32767, 1), NULL, 'IDENTITY=YES,TAUTOMER=YES'
        ) = 1
        ORDER BY F.DESCRIPTION;
 END GETMATCHEDFRAGMENTSLIST;

 PROCEDURE GETSEQUENCELIST (
  O_RS OUT CURSOR_TYPE,  ASeqTypeID in Number) AS

 BEGIN
  OPEN O_RS FOR
   	   SELECT S.SEQUENCEID, S.REGNUMBERLENGTH, S.PREFIX FROM VW_SEQUENCE S ORDER BY S.PREFIX ASC;
 END GETSEQUENCELIST;

   --Gets the list of sequences given a personID - Ulises 08/14/09
  PROCEDURE GETSEQUENCELISTBYPERSONID (
  O_RS OUT CURSOR_TYPE,  ASeqTypeID in Number, APersonID in Number) AS
 BEGIN
  OPEN O_RS FOR
   	    SELECT S.SEQUENCEID, S.REGNUMBERLENGTH, S.PREFIX FROM VW_SEQUENCE S INNER JOIN PREFIX_USER PF ON S.SEQUENCEID = PF.SEQUENCE_ID WHERE PF.PERSON_ID = APersonID ORDER BY S.PREFIX ASC;
 END GETSEQUENCELISTBYPERSONID;

  --Gets the number of perm registries to be shown in the Reg home dashboard
  --Ulises - 02/26/2009
  PROCEDURE GETTEMPREGISTRIESCOUNT (
  ACount OUT NOCOPY Number) AS
 BEGIN
   	    SELECT count(*) INTO ACount FROM VW_TEMPORARYBATCH;
 END GETTEMPREGISTRIESCOUNT;

 --Gets the number of perm registries to be shown in the Reg home dashboard
 --Ulises - 02/26/2009
 PROCEDURE GETPERMREGISTRIESCOUNT (
  ACount out Number) AS
 BEGIN
   	    SELECT count(*) INTO ACount FROM VW_MIXTURE;
 END GETPERMREGISTRIESCOUNT;

 PROCEDURE GETAPPROVEDREGISTRIESCOUNT (
  ACount out Number) AS
 BEGIN
   	    SELECT count(*) INTO ACount FROM VW_MIXTURE WHERE APPROVED='Approved';
 END GETAPPROVEDREGISTRIESCOUNT;

 --Get the number of compound duplicated
 --Fari - 10/09/2010
 PROCEDURE GETDUPLICATEDCOMPOUNDCOUNT (
  ACount out Number) AS
 BEGIN
    SELECT count(1) INTO ACount FROM
        (
         SELECT RegNumber FROM VW_Duplicates
           UNION
         SELECT RegNumberDuplicated FROM VW_Duplicates
        );
 END GETDUPLICATEDCOMPOUNDCOUNT;

END "GUI_UTIL";
/