Alter table CHEMINV_PRIVILEGES
add(
INV_SUBSTANCE_SAFETY_DATA NUMBER(1));

update CHEMINV_PRIVILEGES
set INV_SUBSTANCE_SAFETY_DATA =0;
commit;

update CHEMINV_PRIVILEGES
set INV_SUBSTANCE_SAFETY_DATA =1
where INV_MANAGE_SUBSTANCES = 1;
commit;

