CREATE TABLE DB_FORMGROUP (
	FORMGROUP_ID NUMBER(8,0) not null,
	FORMGROUP_NAME VARCHAR2(50) not null,
	USER_ID VARCHAR2(100), 
	IS_PUBLIC VARCHAR2(1) not null,
	DESCRIPTION VARCHAR2(254),
	BASE_TABLE_ID NUMBER(8,0),
	CREATED_DATE DATE not null, 
	constraint PK_FORMGROUP 
		primary key (FORMGROUP_ID) 
	);