CREATE TABLE "INV_DATA_MAPPINGS" (
  "DATA_MAP_ID_FK" NUMBER(16),
  "MAP_FIELD_ID_FK" NUMBER(16),
  "COLUMN_NUMBER" NUMBER(4),
	PRIMARY KEY("DATA_MAP_ID_FK", "MAP_FIELD_ID_FK"),
	CONSTRAINT "INV_DATA_MAPPINGS_DATAMAPID_FK"
		FOREIGN KEY("DATA_MAP_ID_FK")
	    REFERENCES "INV_DATA_MAPS"("DATA_MAP_ID")
    	ON DELETE CASCADE,
	CONSTRAINT "INV_DATA_MAPPINGS_MFIELDID_FK"
		FOREIGN KEY("MAP_FIELD_ID_FK")
	    REFERENCES "INV_MAP_FIELDS"("MAP_FIELD_ID")
    	ON DELETE CASCADE
 	) ORGANIZATION INDEX;
