CREATE TABLE INV_ORDERS (
	"ORDER_ID" NUMBER(9) NOT NULL,
	"DELIVERY_LOCATION_ID_FK" NUMBER(9) NOT NULL,
	"SHIP_TO_NAME" VARCHAR2(255) NOT NULL,
	"ORDER_STATUS_ID_FK" NUMBER(4) NOT NULL,
  "SHIPPING_CONDITIONS" VARCHAR2(255),
	"DATE_CREATED" DATE,
	"DATE_SHIPPED" DATE,
	"DATE_RECEIVED" DATE,  
	"CANCEL_REASON" VARCHAR2(1000),
  "RID" NUMBER(10) NOT NULL, 
	"CREATOR" VARCHAR2(30) DEFAULT RTRIM(user) NOT NULL, 
	"TIMESTAMP" DATE DEFAULT sysdate NOT NULL,   
  CONSTRAINT "INV_ORDERS_ORDERSTATUS_FK"
		FOREIGN KEY("ORDER_STATUS_ID_FK")
		REFERENCES "INV_ORDER_STATUS"("ORDER_STATUS_ID") ON DELETE CASCADE,  
  CONSTRAINT "INV_ORDERS_LOCATIONID_FK"
		FOREIGN KEY("DELIVERY_LOCATION_ID_FK")
		REFERENCES "INV_LOCATIONS"("LOCATION_ID") ON DELETE CASCADE,
  CONSTRAINT "INV_ORDERS_PK"
		PRIMARY KEY("ORDER_ID") USING INDEX TABLESPACE &&indexTableSpaceName);

CREATE SEQUENCE SEQ_INV_ORDERS INCREMENT BY 1 START WITH 1000;

CREATE OR REPLACE TRIGGER "TRG_INV_ORDERS_ORDER_ID"
    BEFORE INSERT
    ON "INV_ORDERS"
    FOR EACH ROW
    begin
		if :new.ORDER_ID is null then
			select seq_INV_ORDERS.nextval into :new.ORDER_ID from dual;
		end if;
end;
/

CREATE INDEX IORDERS_DELIVERY_LOC_ID_FK_IDX ON INV_ORDERS(DELIVERY_LOCATION_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX ORDER_STATUS_ID_FK_IDX ON INV_ORDERS(ORDER_STATUS_ID_FK) TABLESPACE &&indexTableSpaceName;
