CREATE TABLE "INV_PLATE_ACTIONS"(
	"PLATE_ACTION_ID" NUMBER(9) NOT NULL, 
    "PLATE_ACTION_NAME" VARCHAR2(50) NOT NULL,  
    CONSTRAINT "INV_PLATE_ACTIONS_PK" 
		PRIMARY KEY("PLATE_ACTION_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

create sequence SEQ_INV_PLATE_ACTIONS INCREMENT BY 1 START WITH 1000;

create or replace trigger TRG_PLATE_ACTION_ID BEFORE INSERT ON INV_PLATE_ACTIONS FOR EACH ROW 
begin
if :new.PLATE_ACTION_ID is null then
  select SEQ_INV_PLATE_ACTIONS.nextval into :new.PLATE_ACTION_ID from dual;
end if;
end;
/
