CREATE TABLE "INV_REQUEST_TYPES"(
	"REQUEST_TYPE_ID" NUMBER(4) NOT NULL,
	"REQUEST_TYPE_NAME" VARCHAR2(50) NOT NULL,
    CONSTRAINT "INV_REQUEST_TYPES_PK"
		PRIMARY KEY("REQUEST_TYPE_ID") USING INDEX TABLESPACE &&indexTableSpaceName);

CREATE SEQUENCE SEQ_INV_REQUEST_TYPES INCREMENT BY 1 START WITH 1000 MAXVALUE 99999 MINVALUE 1 NOCYCLE NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "TRG_INV_REQUEST_TYPE_ID"
    BEFORE INSERT
    ON "INV_REQUEST_TYPES"
    FOR EACH ROW
    begin
		if :new.REQUEST_TYPE_ID is null then
			select seq_INV_REQUEST_TYPES.nextval into :new.REQUEST_TYPE_ID from dual;
		end if;
end;
/
