CREATE TABLE "INV_RESERVATION_TYPES"(
    "RESERVATION_TYPE_ID" NUMBER(4) NOT NULL, 
    "RESERVATION_TYPE_NAME" VARCHAR2(50), 
    CONSTRAINT "INV_RESERVATION_TYPES_PK" 
		PRIMARY KEY("RESERVATION_TYPE_ID") USING INDEX TABLESPACE &&indexTableSpaceName  
	)
; 

CREATE SEQUENCE SEQ_INV_RESERVATION_TYPES INCREMENT BY 1 START WITH 10 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;

CREATE OR REPLACE TRIGGER TRG_RESERVATION_TYPES 
    BEFORE INSERT 
    ON INV_RESERVATION_TYPES 
    FOR EACH ROW 
begin
  if :new.RESERVATION_TYPE_ID is null then
    select SEQ_INV_RESERVATION_TYPES.nextval into :new.RESERVATION_TYPE_ID from dual;
  end if;
end;  
/

