CREATE TABLE "INV_MAP_FIELDS" (
		"MAP_FIELD_ID" NUMBER(16),
    "DISPLAY_NAME" VARCHAR2(50) NOT NULL,
    "TABLE_NAME" VARCHAR2(30),
    "COLUMN_NAME" VARCHAR2(30),
    PRIMARY KEY("MAP_FIELD_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	);

CREATE SEQUENCE SEQ_INV_MAP_FIELDS INCREMENT BY 1 START WITH 1000 MAXVALUE 999999 MINVALUE 1 NOCYCLE NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "TRG_INV_MAP_FIELDS" 
    BEFORE INSERT 
    ON "INV_MAP_FIELDS" 
    FOR EACH ROW 
    begin
		if :new.MAP_FIELD_ID is null then
			select SEQ_INV_MAP_FIELDS.nextval INTO :new.MAP_FIELD_ID from dual;
		end if;
end;
/

