CREATE TABLE INV_REPORTFORMATS (
	ID NUMBER(6,0) NOT NULL,
	FORMATDISPLAYNAME VARCHAR2(255) NULL,
	REPORTFORMAT VARCHAR2(5) NULL,
	AVAILABLE CHAR(1) NULL, 
	CONSTRAINT "INV_REPORTFORMATS_PK" 
		PRIMARY KEY ("ID") USING INDEX TABLESPACE &&indexTableSpaceName
	); 


CREATE SEQUENCE SEQ_INV_REPORTFORMATS INCREMENT BY 1 START WITH 1000;

CREATE OR REPLACE TRIGGER "TRG_INV_REPORTFORMATS" 
    BEFORE INSERT 
    ON "INV_REPORTFORMATS" 
    FOR EACH ROW WHEN (new.id is null or new.id = 0) begin
			select SEQ_INV_REPORTFORMATS .nextval into :new.ID from dual;
end;
/


