CREATE TABLE "INV_CONTAINER_CHECKIN_DETAILS"(
	"CHECKIN_DETAILS_ID" NUMBER(16) NOT NULL,
  "CONTAINER_ID_FK" NUMBER(9) NOT NULL,
	"USER_ID_FK" VARCHAR2(50), 
  "FIELD_1" VARCHAR2(2000),
  "FIELD_2" VARCHAR2(2000),
  "FIELD_3" VARCHAR2(2000),
  "FIELD_4" VARCHAR2(2000),
  "FIELD_5" VARCHAR2(2000),
  "FIELD_6" VARCHAR2(2000),
  "FIELD_7" VARCHAR2(2000),
  "FIELD_8" VARCHAR2(2000),
  "FIELD_9" VARCHAR2(2000),
  "FIELD_10" VARCHAR2(2000),
  "DATE_1" DATE,
  "DATE_2" DATE,
  "DATE_3" DATE,
  "RID" NUMBER(10) NOT NULL, 
	"CREATOR" VARCHAR2(30) DEFAULT RTRIM(user) NOT NULL, 
	"TIMESTAMP" DATE DEFAULT sysdate NOT NULL,   
  CONSTRAINT "INV_CON_CHECKIN_CONTAINERID_FK" 
		FOREIGN KEY("CONTAINER_ID_FK") 
		REFERENCES "INV_CONTAINERS"("CONTAINER_ID") 
		ON DELETE CASCADE, 
	CONSTRAINT "INV_CON_CHECKIN_USERID_FK"
  	FOREIGN KEY("USER_ID_FK")
    REFERENCES "PEOPLE"("USER_ID"),
  CONSTRAINT "INV_CON_CHECKIN_DETAILS_PK" 
		PRIMARY KEY("CHECKIN_DETAILS_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;
CREATE SEQUENCE SEQ_INV_CON_CHECKIN_DETAILS INCREMENT BY 1 START WITH 1000;
CREATE INDEX INV_CONCCHKIN_CONTAINERID_IDX ON INV_CONTAINER_CHECKIN_DETAILS(CONTAINER_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX INV_CONCCHKIN_USERID_IDX ON INV_CONTAINER_CHECKIN_DETAILS(USER_ID_FK) TABLESPACE &&indexTableSpaceName;

CREATE OR REPLACE TRIGGER "TRG_INV_CON_CHECKIN_DET_CDID"
    BEFORE INSERT
    ON "INV_CONTAINER_CHECKIN_DETAILS"
    FOR EACH ROW
    begin
		if :new.CHECKIN_DETAILS_ID is null then
			select seq_INV_CON_CHECKIN_DETAILS.nextval into :new.CHECKIN_DETAILS_ID from dual;
		end if;
end;
/
