CREATE TABLE "INV_SUPPLIERS"(
	"SUPPLIER_ID" NUMBER(4) NOT NULL,
	"SUPPLIER_NAME" VARCHAR2(255),
	"SUPPLIER_SHORT_NAME" VARCHAR2(50),
	"SUPPLIER_CODE" VARCHAR2(50), 
	"SUPPLIER_FACILITY_NAME" VARCHAR2(255),
	"SUPPLIER_ADDRESS_ID_FK" NUMBER(4),
  "IS_OFFICIAL_SUPPLIER" NUMBER(1) DEFAULT 0,
  "RID" NUMBER(10) NOT NULL, 
	"CREATOR" VARCHAR2(30) DEFAULT RTRIM(user) NOT NULL, 
	"TIMESTAMP" DATE DEFAULT sysdate NOT NULL,   
  CONSTRAINT "INV_SUPPLIERS_PK" 
		PRIMARY KEY("SUPPLIER_ID") USING INDEX TABLESPACE &&indexTableSpaceName,  
  CONSTRAINT "INV_SUPPLIERS_ISOFFICIAL_CHK"
	  CHECK (IS_OFFICIAL_SUPPLIER IN (0,1)),
  CONSTRAINT "INV_SUPPLIERS_ADDRESSID_FK" 
		FOREIGN KEY("SUPPLIER_ADDRESS_ID_FK") 
		REFERENCES "INV_ADDRESS"("ADDRESS_ID")
    ON DELETE SET NULL
	)
; 

CREATE INDEX INV_SUPPLIERS_ADDRESS_IDX ON INV_SUPPLIERS(SUPPLIER_ADDRESS_ID_FK) TABLESPACE &&indexTableSpaceName;

create sequence SEQ_INV_SUPPLIERS INCREMENT BY 1 START WITH 1000;

CREATE OR REPLACE TRIGGER "TRG_INV_SUPPLIERS" BEFORE 
    INSERT 
    ON "INV_SUPPLIERS" 
    FOR EACH ROW 
    begin
		if :new.Supplier_ID is null then
			select seq_Inv_Suppliers.nextval into :new.Supplier_id from dual;
		end if;
end;
/

