CREATE TABLE "INV_ORG_ROLES"(
	"ORG_ROLE_ID" NUMBER NOT NULL,
	"ROLE_ID_FK" NUMBER(4) not null,
	"ORG_UNIT_ID_FK" NUMBER(4) not null,
    CONSTRAINT "INV_ORG_ROLE_ID_PK"
		PRIMARY KEY("ORG_ROLE_ID") USING INDEX TABLESPACE &&indexTableSpaceName,
	CONSTRAINT "INV_ROLES_ORG_UNIT_ID_FK" 
		FOREIGN KEY ("ORG_UNIT_ID_FK")
		REFERENCES "INV_ORG_UNIT" ("ORG_UNIT_ID"),
	CONSTRAINT "INV_ORG_ROLE_ID_FK" 
		FOREIGN KEY ("ROLE_ID_FK")
		REFERENCES &&securitySchemaName..SECURITY_ROLES ("ROLE_ID")
	);

CREATE SEQUENCE SEQ_INV_ORG_ROLE_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER "TRG_INV_ORG_ROLE_ID"
    BEFORE INSERT
    ON "INV_ORG_ROLES"
    FOR EACH ROW
BEGIN
	if :new.org_role_id is null then
		select SEQ_INV_ORG_ROLE_ID.nextval into :new.org_role_id from dual;
	end if;
END;
/
	