CREATE TABLE INV_PLATE_PARENT (
	PARENT_PLATE_ID_FK NUMBER(16),
	CHILD_PLATE_ID_FK NUMBER(16),
	PRIMARY KEY(PARENT_PLATE_ID_FK, CHILD_PLATE_ID_FK),
	CONSTRAINT "INV_PLATE_PARENT_PARENTIDFK_FK"
		FOREIGN KEY("PARENT_PLATE_ID_FK")
	    REFERENCES "INV_PLATES"("PLATE_ID")
    	ON DELETE CASCADE,
	CONSTRAINT "INV_PLATE_PARENT_CHILDIDFK_FK"
		FOREIGN KEY("CHILD_PLATE_ID_FK")
	    REFERENCES "INV_PLATES"("PLATE_ID")
    	ON DELETE CASCADE)
  	ORGANIZATION INDEX;

CREATE INDEX INV_PLATE_PARENT_CHILDID_IDX ON INV_PLATE_PARENT(CHILD_PLATE_ID_FK) TABLESPACE &&indexTableSpaceName;    
