CREATE TABLE "INV_GRID_FORMAT"(
	"GRID_FORMAT_ID" NUMBER(9) NOT NULL, 
	"GRID_FORMAT_TYPE_FK" NUMBER(9), 
	"NAME" VARCHAR2(50), 
	"DESCRIPTION" VARCHAR2(255), 
	"ROW_COUNT" NUMBER(6) NOT NULL, 
	"COL_COUNT" NUMBER(6) NOT NULL, 
	"ROW_PREFIX" VARCHAR2(50), 
	"COL_PREFIX" VARCHAR2(50), 
	"ROW_USE_LETTERS" NUMBER(1), 
  "COL_USE_LETTERS" NUMBER(1), 
  "CELL_NAMING" NUMBER(1),  
  "NAME_DELIMETER" VARCHAR2(50),  
  "NAME_SEPARATOR" VARCHAR2(1), 
  "NUMBER_START_CORNER" NUMBER(9), 
  "NUMBER_DIRECTION" NUMBER(9), 
	"ZERO_PADDING_COUNT" NUMBER(4),
  CONSTRAINT "INV_GRID_FORMAT_PK" 
		PRIMARY KEY("GRID_FORMAT_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

create sequence SEQ_INV_GRID_FORMAT INCREMENT BY 1 START WITH 1000;

create or replace trigger TRG_GRID_FORMAT_ID BEFORE INSERT ON INV_GRID_FORMAT FOR EACH ROW 
begin
if :new.GRID_FORMAT_ID is null then
  select SEQ_INV_GRID_FORMAT.nextval into :new.GRID_FORMAT_ID from dual;
end if;
end;
/

