CREATE TABLE INV_REPORTS (
	ID NUMBER(6,0) NOT NULL,
	REPORTDISPLAYNAME VARCHAR2(255) NULL,
	REPORTNAME VARCHAR2(255) NULL,
	REPORTTYPE_ID NUMBER(6,0) NULL, 
	REPORTSQL CLOB,
	REPORT_DESC VARCHAR2(2000),
	QUERYNAME VARCHAR2(255),
	CONSTRAINT "INV_REPORTS_PK" 
		PRIMARY KEY ("ID") USING INDEX TABLESPACE &&indexTableSpaceName
	); 

CREATE SEQUENCE SEQ_INV_REPORTS INCREMENT BY 1 START WITH 1000;

-- Before insert on inv_reports 
CREATE OR REPLACE TRIGGER "TRG_INV_REPORTS" 
    BEFORE INSERT 
    ON "INV_REPORTS" 
    FOR EACH ROW WHEN (new.id is null or new.id = 0) begin
  select trunc(seq_rid.nextval)
  into :new.id
  from dual;
end;
/


