CREATE TABLE "INV_XSLTS" (
	XSLT_ID NUMBER(4) PRIMARY KEY USING INDEX  TABLESPACE &&indexTableSpaceName,
	XSLT CLOB,
	XSLT_NAME VARCHAR2(200)
	)
	LOB (XSLT) STORE AS(
	DISABLE STORAGE IN ROW
	TABLESPACE &&lobsTableSpaceName
	NOCACHE
	CHUNK 2K
	PCTVERSION 10
	STORAGE(INITIAL &&lobXML NEXT &&lobXML));

CREATE SEQUENCE SEQ_INV_XSLTS INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;

CREATE OR REPLACE TRIGGER TRG_XSLT BEFORE INSERT
    ON INV_XSLTS
    FOR EACH ROW 
begin
  if :new.XSLT_ID is null then
    select SEQ_INV_XSLTS.nextval into :new.XSLT_ID from dual;
  end if;
end;
/
