CREATE TABLE "INV_PLATE_FORMAT"(
	"PLATE_FORMAT_ID" NUMBER(9) NOT NULL, 
	"PHYS_PLATE_ID_FK" NUMBER(9) NOT NULL, 
    "PLATE_FORMAT_NAME" VARCHAR2(50), "IS_ACTIVE" VARCHAR2(1), 
    CONSTRAINT "INV_PFORMAT_PHYSPLATE_FK" 
		FOREIGN KEY("PHYS_PLATE_ID_FK") 
		REFERENCES "INV_PHYSICAL_PLATE"("PHYS_PLATE_ID"), 
    CONSTRAINT "INV_PLATE_FORMAT_PK" 
		PRIMARY KEY("PLATE_FORMAT_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;



CREATE INDEX PHYS_PLATE_ID_FK_IDX ON INV_PLATE_FORMAT(PHYS_PLATE_ID_FK) TABLESPACE &&indexTableSpaceName;

create sequence SEQ_INV_PLATE_FORMAT INCREMENT BY 1 START WITH 1000;

create or replace trigger TRG_PLATE_FORMAT_ID BEFORE INSERT ON INV_PLATE_FORMAT FOR EACH ROW 
begin
if :new.PLATE_FORMAT_ID is null then
  select SEQ_INV_PLATE_FORMAT.nextval into :new.PLATE_FORMAT_ID from dual;
end if;
end;
/

