CREATE TABLE "INV_ENUMERATION_SET"(
	"ESET_ID" NUMBER(9) NOT NULL, 
	"ESET_NAME" VARCHAR2(255) NOT NULL, 
    "ESET_TYPE_ID_FK" NUMBER(9) NOT NULL,
    CONSTRAINT ESET_ESET_TYPE_FK
		FOREIGN KEY (ESET_TYPE_ID_FK)
		REFERENCES INV_ESET_TYPE (ESET_TYPE_ID)
		ON DELETE CASCADE, 
    CONSTRAINT "INV_ENUMERATION_SET_PK" 
		PRIMARY KEY("ESET_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

create sequence SEQ_INV_ENUMERATION_SET INCREMENT BY 1 START WITH 1000;

create or replace trigger TRG_ESET_ID BEFORE INSERT ON INV_ENUMERATION_SET FOR EACH ROW 
begin
if :new.ESET_ID is null then
  select SEQ_INV_ENUMERATION_SET.nextval into :new.ESET_ID from dual;
end if;
end;
/

