CREATE TABLE "INV_UNIT_TYPES"(
	"UNIT_TYPE_ID" NUMBER(4) NOT NULL,
	"UNIT_TYPE_NAME" VARCHAR2(50) NOT NULL, 
    CONSTRAINT "INV_UNIT_TYPES_PK" 
		PRIMARY KEY("UNIT_TYPE_ID") USING INDEX TABLESPACE &&indexTableSpaceName  
	)
;     

Create sequence SEQ_INV_UNIT_TYPES INCREMENT BY 1 START WITH 1000;

CREATE OR REPLACE TRIGGER TRG_INV_UNIT_TYPES
    BEFORE INSERT 
    ON INV_UNIT_TYPES
    FOR EACH ROW 
begin
  if :new.UNIT_TYPE_ID is null then
    select SEQ_INV_UNIT_TYPES.nextval into :new.UNIT_TYPE_ID from dual;
  end if;
end;  
/

show errors;
