CREATE TABLE "INV_LOCATION_TYPES"(
	"LOCATION_TYPE_ID" NUMBER(4) NOT NULL, 
	"LOCATION_TYPE_NAME" VARCHAR2(50) NOT NULL, 
	"GRAPHIC_ID_FK" NUMBER(4),
  CONSTRAINT "INV_LOCATION_TYPES_PK" 
		PRIMARY KEY("LOCATION_TYPE_ID") USING INDEX TABLESPACE &&indexTableSpaceName,  
	CONSTRAINT "LOCATION_TYPES_GRAPHIC_ID_FK"
		FOREIGN KEY ("GRAPHIC_ID_FK")
		REFERENCES "INV_GRAPHICS" ("GRAPHIC_ID")	
	)
; 

create sequence SEQ_INV_LOCATION_TYPES INCREMENT BY 1 START WITH 1000;

CREATE OR REPLACE TRIGGER "TRG_INV_LOCATION_TYPES" 
    BEFORE INSERT 
    ON "INV_LOCATION_TYPES" 
    FOR EACH ROW 
    begin
		if :new.Location_type_ID is null then
			select seq_inv_location_types.nextval into :new.location_type_id from dual;
		end if;
end;
/