CREATE TABLE INV_WELL_PARENT (
	PARENT_WELL_ID_FK NUMBER(16),
	CHILD_WELL_ID_FK NUMBER(16),
	PRIMARY KEY(PARENT_WELL_ID_FK, CHILD_WELL_ID_FK),
	CONSTRAINT "INV_WELL_PARENT_PARENTIDFK_FK"
		FOREIGN KEY("PARENT_WELL_ID_FK")
	    REFERENCES "INV_WELLS"("WELL_ID")
    	ON DELETE CASCADE,
	CONSTRAINT "INV_WELL_PARENT_CHILDIDFK_FK"
		FOREIGN KEY("CHILD_WELL_ID_FK")
	    REFERENCES "INV_WELLS"("WELL_ID")
    	ON DELETE CASCADE)
	ORGANIZATION INDEX;   

CREATE INDEX INV_WELL_PARENT_CHILDID_IDX ON INV_WELL_PARENT(CHILD_WELL_ID_FK) TABLESPACE &&indexTableSpaceName;       
