CREATE TABLE "INV_LABEL_PRINTERS"(
	"LABEL_PRINTER_ID" NUMBER(9) NOT NULL,
	"SERVER_NAME" VARCHAR2(100) NOT NULL,
	"QUEUE_NAME" VARCHAR2(100) NOT NULL,
	"LPR_DEFINITION_ID_FK" NUMBER(9) NOT NULL,
	"REPORTTYPE_ID_FK" NUMBER(9) NOT NULL,
	"DISPLAY_NAME" VARCHAR2(200) NOT NULL,
	"IS_AVAILABLE" NUMBER(1,0) NOT NULL,
	CONSTRAINT "INV_LABEL_PRINTERS_PK"
		PRIMARY KEY("LABEL_PRINTER_ID") USING INDEX TABLESPACE &&indexTableSpaceName,
	CONSTRAINT "INV_LABEL_PRINTERS_U" 
		UNIQUE ("DISPLAY_NAME") USING INDEX TABLESPACE &&indexTableSpaceName,
	CONSTRAINT "INV_LBLPRNT_LPRDEFN_FK" 
		FOREIGN KEY ("LPR_DEFINITION_ID_FK") REFERENCES &&schemaName..INV_LPR_DEFINITION(LPR_DEFINITION_ID),
	CONSTRAINT "INV_LBLPRNT_REPORTTYPE_FK" 
		FOREIGN KEY ("REPORTTYPE_ID_FK") REFERENCES &&schemaName..INV_REPORTTYPES(REPORTTYPE_ID)
);

CREATE SEQUENCE SEQ_INV_LABEL_PRINTERS_VALUES INCREMENT BY 1 START WITH 1000 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE;

CREATE OR REPLACE TRIGGER "TRG_INV_LABEL_PRINTERS_VALUES"
    BEFORE INSERT
    ON "INV_LABEL_PRINTERS"
    FOR EACH ROW
    begin
        if :new.LABEL_PRINTER_ID is null then
            select SEQ_INV_LABEL_PRINTERS_VALUES.nextval into :new.LABEL_PRINTER_ID from dual;
        end if;
    end;
/
