CREATE TABLE "INV_PHYSICAL_PLATE"(
	"PHYS_PLATE_ID" NUMBER(9) NOT NULL, 
	"PHYS_PLATE_NAME" VARCHAR2(50), 
    "SUPPLIER_ID_FK" NUMBER(4) NOT NULL, 
    "GRID_FORMAT_ID_FK" NUMBER(9) NOT NULL, 
    "IS_PRE_BARCODED" VARCHAR2(1) NOT NULL, 
    "WELL_CAPACITY" NUMBER, "CAPACITY_UNIT_ID_FK" NUMBER(9), 
    "IS_ACTIVE" VARCHAR2(1), 
    CONSTRAINT "INV_PHSYPLATE_SUPPID_FK" 
		FOREIGN KEY("SUPPLIER_ID_FK") 
		REFERENCES "INV_SUPPLIERS"("SUPPLIER_ID"), 
    CONSTRAINT "INV_PHYSPLATE_GRIDF_FK" 
		FOREIGN KEY("GRID_FORMAT_ID_FK") 
		REFERENCES "INV_GRID_FORMAT"("GRID_FORMAT_ID")
		ON DELETE CASCADE, 
    CONSTRAINT "INV_PHYSPLATE_UNITID_FK" 
		FOREIGN KEY("CAPACITY_UNIT_ID_FK") 
		REFERENCES "INV_UNITS"("UNIT_ID"), 
    CONSTRAINT "INV_PHYSICAL_PLATE_PK" 
		PRIMARY KEY("PHYS_PLATE_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;



CREATE INDEX SUPPLIER_ID_FK_IDX ON INV_PHYSICAL_PLATE(SUPPLIER_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX GRID_FORMAT_ID_FK_IDX ON INV_PHYSICAL_PLATE(GRID_FORMAT_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX CAPACITY_UNIT_ID_FK_IDX ON INV_PHYSICAL_PLATE(CAPACITY_UNIT_ID_FK) TABLESPACE &&indexTableSpaceName;  


create sequence SEQ_INV_PHYSICAL_PLATE INCREMENT BY 1 START WITH 1000;


create or replace trigger TRG_PHYS_PLATE_ID BEFORE INSERT ON INV_PHYSICAL_PLATE FOR EACH ROW 
begin
if :new.PHYS_PLATE_ID is null then
  select SEQ_INV_PHYSICAL_PLATE.nextval into :new.PHYS_PLATE_ID from dual;
end if;
end;
/
