CREATE TABLE "INV_DATA_MAPS" (
	"DATA_MAP_ID" NUMBER(16),
  "DATA_MAP_NAME" VARCHAR2(50) NOT NULL,
  "DATA_MAP_TYPE_ID_FK" NUMBER(16) NOT NULL,
  "DATA_MAP_COMMENTS" VARCHAR2(2000) NOT NULL,
  "NUM_HEADER_ROWS" NUMBER(4),
  "NUM_COLUMNS" NUMBER(4) NOT NULL,
  "COLUMN_DELIMITER" VARCHAR2(3) NOT NULL,
	"USE_WELL_COORDINATES" NUMBER(1) DEFAULT 0 NOT NULL,  
  CONSTRAINT "INV_DATA_MAPS_TYPEID_FK" 
		FOREIGN KEY("DATA_MAP_TYPE_ID_FK") 
		REFERENCES "INV_ENUMERATION"("ENUM_ID"),
  CONSTRAINT INV_DATA_MAPS_UQ UNIQUE (DATA_MAP_NAME),
	PRIMARY KEY("DATA_MAP_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

CREATE SEQUENCE SEQ_INV_DATA_MAPS INCREMENT BY 1 START WITH 1000 MAXVALUE 999999 MINVALUE 1 NOCYCLE NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "TRG_INV_DATA_MAPS" 
    BEFORE INSERT 
    ON "INV_DATA_MAPS" 
    FOR EACH ROW 
    begin
		if :new.DATA_MAP_ID is null then
			select SEQ_INV_DATA_MAPS.nextval INTO :new.DATA_MAP_ID from dual;
		end if;
end;
/

CREATE INDEX INV_DATA_MAPS_TYPEIDFK_IDX ON INV_DATA_MAPS(DATA_MAP_TYPE_ID_FK) TABLESPACE &&indexTableSpaceName;
