CREATE TABLE "INV_UNIT_CONVERSION"(
    "FROM_UNIT_ID_FK" NUMBER(4) NOT NULL, 
    "TO_UNIT_ID_FK" NUMBER(4) NOT NULL, 
    "CONVERSION_FACTOR" NUMBER(25, 15) NOT NULL,    
    CONSTRAINT "INV_UNIT_CONV_UNIT_ID_FK1" 
		FOREIGN KEY("FROM_UNIT_ID_FK") 
		REFERENCES "INV_UNITS"("UNIT_ID") 
		ON DELETE CASCADE,
    CONSTRAINT "INV_UNIT_CONV_UNIT_ID_FK2" 
		FOREIGN KEY("TO_UNIT_ID_FK") 
		REFERENCES "INV_UNITS"("UNIT_ID") 
		ON DELETE CASCADE,
    CONSTRAINT "UNIT_CONVERSION_PK" 
		PRIMARY KEY("FROM_UNIT_ID_FK", "TO_UNIT_ID_FK") USING INDEX TABLESPACE &&indexTableSpaceName
); 

CREATE INDEX Unit_Conversion_from_idx ON inv_Unit_Conversion (from_unit_id_fk ASC) TABLESPACE &&indexTableSpaceName;
CREATE INDEX Unit_Conversion_to_idx ON inv_Unit_Conversion(to_unit_id_fk ASC) TABLESPACE &&indexTableSpaceName;
