CREATE TABLE INV_OWNERS (
  "OWNER_ID"	VARCHAR2(50) NOT NULL,
  "DESCRIPTION" VARCHAR2(255) NOT NULL,
  PRIMARY KEY (owner_id) USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

CREATE SEQUENCE SEQ_INV_OWNERS INCREMENT BY 1 START WITH 1000 MAXVALUE 999999 MINVALUE 1 NOCYCLE NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "TRG_INV_OWNERS" 
    BEFORE INSERT 
    ON "INV_OWNERS" 
    FOR EACH ROW 
    begin
		if :new.OWNER_ID is null then
			select seq_inv_owners.nextval into :new.owner_id from dual;
		end if;
end;
/