CREATE TABLE "INV_CONTAINER_ORDER"(
	"CONTAINER_ID" NUMBER(9) NOT NULL, 
	"DUE_DATE" DATE NOT NULL, 
	"PROJECT_NO" VARCHAR2(8) NOT NULL, 
	"JOB_NO" VARCHAR2(4) NOT NULL, 
    "ISRUSHORDER" NUMBER(1) NOT NULL, 
    "DELIVERY_LOCATION_ID_FK" NUMBER(9) NOT NULL, 
    "NEW_SUPPLIER_NAME" VARCHAR2(50), 
    "NEW_SUPPLIER_CONTACT" VARCHAR2(30), 
    "NEW_SUPPLIER_PHONE" VARCHAR2(30), 
    "NEW_SUPPLIER_FAX" VARCHAR2(30), 
    "ORDER_SOURCE" NUMBER, 
    "CONTAINER_ORDER_REASON_ID_FK" NUMBER(1), 
    "REASON_IF_OTHER" VARCHAR2(255), 
    "OWNER_ID_FK" NUMBER(4), 
    CONSTRAINT "CONTAINER_ORDERS_PK" 
		PRIMARY KEY("CONTAINER_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	); 

CREATE INDEX Order_Delivery_FK_IDX ON inv_Container_Order (delivery_location_id_fk ASC) TABLESPACE &&indexTableSpaceName;
CREATE INDEX Order_reason_FK_IDX ON inv_Container_Order (container_order_reason_id_fk ASC) TABLESPACE &&indexTableSpaceName;
CREATE INDEX Order_ownwer_FK_IDX ON inv_Container_Order (owner_id_fk ASC) TABLESPACE &&indexTableSpaceName;
