CREATE TABLE "INV_PLATES"(
	"PLATE_ID" NUMBER(9) NOT NULL, 
	"LOCATION_ID_FK" NUMBER(16), 
	"CONTAINER_ID_FK" NUMBER(16), 
 	"PLATE_TYPE_ID_FK" NUMBER(9) NOT NULL, 
 	"PLATE_FORMAT_ID_FK" NUMBER(9) NOT NULL, 
	"PLATE_BARCODE" varchar2(32) NOT NULL,  
	"PLATE_NAME" VARCHAR2(50),
 	"STATUS_ID_FK" NUMBER(9) NOT NULL, 
 	"GROUP_NAME" VARCHAR2(50), 
 	"LIBRARY_ID_FK" NUMBER(9),
 	"FT_CYCLES" NUMBER(4,0), 
 	"WEIGHT" NUMBER, 
 	"WEIGHT_UNIT_FK" NUMBER(9), 
 	"QTY_INITIAL" NUMBER, 
 	"QTY_REMAINING" NUMBER, 
 	"QTY_UNIT_FK" NUMBER(9), 
 	"SOLVENT" VARCHAR2(255), 
 	"CONCENTRATION" NUMBER, 
 	"CONC_UNIT_FK" NUMBER(9), 
 	"DATE_CREATED" DATE,
	"SUPPLIER_BARCODE" VARCHAR2(50),  
  "SUPPLIER_SHIPMENT_CODE" VARCHAR2(50), 
  "SUPPLIER_SHIPMENT_NUMBER" NUMBER(9,0),
  "SUPPLIER_SHIPMENT_DATE" DATE,
	"SOLVENT_ID_FK" NUMBER(9),
	"SOLVENT_VOLUME" NUMBER, 
	"SOLVENT_VOLUME_INITIAL" NUMBER,
  "SOLVENT_VOLUME_UNIT_ID_FK" NUMBER(9), 
  "SOLUTION_VOLUME" NUMBER,
  "MOLAR_AMOUNT" NUMBER,
  "MOLAR_UNIT_FK" NUMBER(9,0),
  "MOLAR_CONC" NUMBER, 
	"WELL_CAPACITY" NUMBER,
	"WELL_CAPACITY_UNIT_ID_FK" NUMBER(9),
  "AMOUNTS_DIFFER" NUMBER(1,0),
  "SUPPLIER" VARCHAR2(50),
  "PLATE_EXISTS" NUMBER(1,0),
	"IS_PLATE_MAP" NUMBER(1,0),
	"PLATE_MAP_ID_FK" NUMBER(9,0),
	"PURITY" NUMBER,
	"PURITY_UNIT_FK" NUMBER(9,0),
	"FIELD_1" VARCHAR2(2000), 
	"FIELD_2" VARCHAR2(2000),
	"FIELD_3" VARCHAR2(2000), 
	"FIELD_4" VARCHAR2(2000), 
	"FIELD_5" VARCHAR2(2000), 
	"DATE_1" DATE, 
	"DATE_2" DATE,
	"RID" NUMBER(10) NOT NULL, 
	"CREATOR" VARCHAR2(30) DEFAULT RTRIM(user) NOT NULL, 
 	"TIMESTAMP" DATE DEFAULT sysdate NOT NULL,  
  CONSTRAINT "INV_PLATES_CUID_FK" 
		FOREIGN KEY("CONC_UNIT_FK") 
		REFERENCES "INV_UNITS"("UNIT_ID"), 
  CONSTRAINT "INV_PLATES_PFORMAT_FK" 
		FOREIGN KEY("PLATE_FORMAT_ID_FK") 
		REFERENCES "INV_PLATE_FORMAT"("PLATE_FORMAT_ID"), 
  CONSTRAINT "INV_PLATES_PTYPE_FK" 
		FOREIGN KEY("PLATE_TYPE_ID_FK") 
		REFERENCES "INV_PLATE_TYPES"("PLATE_TYPE_ID"), 
  CONSTRAINT "INV_PLATES_WUID_FK" 
		FOREIGN KEY("WEIGHT_UNIT_FK") 
		REFERENCES "INV_UNITS"("UNIT_ID"),
  CONSTRAINT PLATE_LOCATION_FK
		FOREIGN KEY (LOCATION_ID_FK)
		REFERENCES "INV_LOCATIONS" (LOCATION_ID)
		ON DELETE CASCADE,
  CONSTRAINT PLATE_QTY_UNIT_FK
		FOREIGN KEY (QTY_UNIT_FK)
		REFERENCES "INV_UNITS" (UNIT_ID),
  CONSTRAINT PLATE_MOLAR_UNIT_FK
		FOREIGN KEY (MOLAR_UNIT_FK)
		REFERENCES "INV_UNITS" (UNIT_ID),	
  CONSTRAINT "PLATE_SOLVENT_UNIT_FK" 
		FOREIGN KEY("SOLVENT_VOLUME_UNIT_ID_FK")
	 	REFERENCES "INV_UNITS"("UNIT_ID"),
	CONSTRAINT "INV_PLATES_SOLVENTID_FK"
  	FOREIGN KEY("SOLVENT_ID_FK")
    REFERENCES "INV_SOLVENTS"("SOLVENT_ID"),    
  CONSTRAINT "PLATE_WELL_CAPACITY_UNIT_FK" 
		FOREIGN KEY("WELL_CAPACITY_UNIT_ID_FK")
	 	REFERENCES "INV_UNITS"("UNIT_ID"),
  CONSTRAINT "INV_PLATES_BARCODE_U" 
		UNIQUE("PLATE_BARCODE") USING INDEX TABLESPACE &&indexTableSpaceName,
  CONSTRAINT "INV_PLATES_PK" 
		PRIMARY KEY("PLATE_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

create sequence SEQ_INV_PLATES INCREMENT BY 1 START WITH 1000;

CREATE OR REPLACE
TRIGGER TRG_PLATE_ID BEFORE INSERT ON INV_PLATES FOR EACH ROW
begin
if :new.PLATE_ID is null then
  select SEQ_INV_PLATES.nextval into :new.PLATE_ID from dual;
end if;
if :new.Plate_Barcode is null then
   :new.Plate_Barcode := :new.PLATE_ID;
end if;
end;
/

CREATE INDEX CONC_UNIT_FK_IDX ON INV_PLATES(CONC_UNIT_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX PLATE_FORMAT_ID_FK_IDX ON INV_PLATES(PLATE_FORMAT_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX PLATE_TYPE_ID_FK_IDX ON INV_PLATES(PLATE_TYPE_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX PLATE_WEIGHT_UNIT_FK_IDX ON INV_PLATES(WEIGHT_UNIT_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX PLATE_LOCATION_ID_FK_IDX ON INV_PLATES(LOCATION_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX PLATE_QTY_UNIT_FK_IDX ON INV_PLATES(QTY_UNIT_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX PLATE_MOLAR_UNIT_FKIDX ON INV_PLATES(MOLAR_UNIT_FK) TABLESPACE &&indexTableSpaceName;   
CREATE INDEX PLATE_LIBRARY_ID_FK_IDX ON INV_PLATES(LIBRARY_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX PLATEWELLCAPACITY_UNIT_FK_IDX ON INV_PLATES(WELL_CAPACITY_UNIT_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX PLATE_SOLVENT_ID_FK_IDX ON INV_PLATES(SOLVENT_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX PLATE_STATUS_ID_FK_IDX ON INV_PLATES(STATUS_ID_FK) TABLESPACE &&indexTableSpaceName;