CREATE TABLE "INV_WELL_COMPOUNDS"(
	WELL_COMPOUND_ID NUMBER(9) NOT NULL,
  WELL_ID_FK NUMBER(9) NOT NULL,
	COMPOUND_ID_FK NUMBER(9),
  REG_ID_FK NUMBER(9),
  BATCH_NUMBER_FK NUMBER(9),
  CONSTRAINT "INV_WELL_COMPOUNDS_PK" 
		PRIMARY KEY("WELL_COMPOUND_ID") USING INDEX TABLESPACE &&indexTableSpaceName, 
  CONSTRAINT "INV_WELLCMPD_COMPOUNDID_FK" 
		FOREIGN KEY("COMPOUND_ID_FK") 
		REFERENCES "INV_COMPOUNDS"("COMPOUND_ID"),
  CONSTRAINT "INV_WELLCMPD_WELLID_FK" 
		FOREIGN KEY("WELL_ID_FK") 
		REFERENCES "INV_WELLS"("WELL_ID")
    ON DELETE CASCADE
  );

CREATE SEQUENCE SEQ_INV_WELL_COMPOUNDS INCREMENT BY 1 START WITH 1000;

-- Create table level triggers for table INV_WELL_COMPOUNDS.
CREATE OR REPLACE TRIGGER "TRG_INV_WELL_COMPOUNDS" 
    BEFORE INSERT 
    ON "INV_WELL_COMPOUNDS" 
    FOR EACH ROW 
    begin
		if :new.WELL_COMPOUND_ID is null then
			select seq_inv_well_compounds.nextval into :new.well_compound_id from dual;
		end if;
end;
/

CREATE INDEX IWC_COMPOUND_ID_FK_IDX ON INV_WELL_COMPOUNDS(COMPOUND_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX IWC_WELL_ID_FK_IDX ON INV_WELL_COMPOUNDS(WELL_ID_FK) TABLESPACE &&indexTableSpaceName;

