CREATE TABLE "INV_RESERVATIONS"(
	"RESERVATION_ID" NUMBER(9) NOT NULL, 
	"CONTAINER_ID_FK" NUMBER(9), 
	"USER_ID_FK" VARCHAR2(50), 
	"QTY_RESERVED" NUMBER, 
	"DATE_RESERVED" DATE, 
	"RESERVATION_TYPE_ID_FK" NUMBER(4), 
	"IS_ACTIVE" NUMBER(1), 
	"CANCELLED_BY_ID_FK" VARCHAR2(50), 
	CONSTRAINT "INV_RESERVATIONS_PK" 
		PRIMARY KEY("RESERVATION_ID") USING INDEX TABLESPACE &&indexTableSpaceName, 
	CONSTRAINT "INV_RESV_USERID_FK"
  	FOREIGN KEY("USER_ID_FK")
	REFERENCES "PEOPLE"("USER_ID"),
	CONSTRAINT "INV_RESV_CONTAINERS_FK" 
		FOREIGN KEY("CONTAINER_ID_FK") 
		REFERENCES "INV_CONTAINERS"("CONTAINER_ID") 
		ON DELETE CASCADE, 
	CONSTRAINT "INV_RESV_RESV_TYPES_FK" 
		FOREIGN KEY("RESERVATION_TYPE_ID_FK") 
		REFERENCES "INV_RESERVATION_TYPES"("RESERVATION_TYPE_ID")
	)
; 

CREATE INDEX INV_RESERVATIONS_USERID_IDX ON INV_RESERVATIONS(USER_ID_FK) TABLESPACE &&indexTableSpaceName;

CREATE INDEX CONTAINER_ID_FK_IDX ON INV_RESERVATIONS(CONTAINER_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX RESERVATION_TYPE_ID_FK_IDX ON INV_RESERVATIONS(RESERVATION_TYPE_ID_FK) TABLESPACE &&indexTableSpaceName;


create sequence SEQ_INV_RESERVATIONS INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER "TRG_INV_RESERVATIONS" 
    BEFORE INSERT 
    ON "INV_RESERVATIONS" 
    FOR EACH ROW 
    begin
		if :new.Reservation_ID is null then
			select SEQ_INV_RESERVATIONS.nextval into :new.Reservation_ID from dual;
		end if;
end;
/