--Copyright 1999-2010 CambridgeSoft Corporation. All rights reserved
prompt 
prompt Starting "Migrate_10_to_11.0.1.sql"...
prompt

spool log_Migrate_10_to_11.0.1.txt

SET ECHO OFF
SET VERIFY OFF

--#########################################################
-- PROMPT THE USER FOR SCRIPT SUBSTITUTION VARIABLES
--######################################################### 

ACCEPT serverName CHAR PROMPT 'Enter the target Oracle service name:'
ACCEPT InstallUser CHAR DEFAULT 'regdb' PROMPT 'Enter the name of an Oracle account with system privileges (regdb):'
ACCEPT sysPass CHAR DEFAULT 'oracle' PROMPT 'Enter the above oracle account password (oracle):' hide

WHENEVER SQLERROR EXIT

Connect &&InstallUser/&&sysPass@&&serverName
PROMPT Working...

INSERT INTO TEMPORARY_BATCH(
  TEMPBATCHID,AMOUNT,AMOUNT_UNITS,APPEARANCE,BATCH_COMMENTS,BATCH_FORMULA,BATCH_PROJECT_ID,BP,C13NMR,CHN_COMBUSTION,COLOR,CPD_INTERNAL_ID,CREATION_DATE,DATE_BATCH_FIELD_1,DATE_BATCH_FIELD_2 ,DATE_BATCH_FIELD_3 ,DATE_BATCH_FIELD_4 ,DATE_BATCH_FIELD_5 ,DATE_BATCH_FIELD_6,FIELD_1,FIELD_10,FIELD_2,FIELD_3,FIELD_4,FIELD_5,FIELD_6,FIELD_7,FIELD_8,FIELD_9,FLASHPOINT,FORMULA_WEIGHT,GC,H1NMR,HPLC,INT_BATCH_FIELD_1,INT_BATCH_FIELD_2,INT_BATCH_FIELD_3,INT_BATCH_FIELD_4,INT_BATCH_FIELD_5,INT_BATCH_FIELD_6,IR,LAST_MOD_PERSON_ID,LC_UV_MS,LIT_REF,LOAD_ID,LOGD,MOL_ID,MP,MS,NOTEBOOK_INTERNAL_ID,NOTEBOOK_PAGE,NOTEBOOK_TEXT,OPTICAL_ROTATION,PERCENT_ACTIVE,PHYSICAL_FORM,PREPARATION,PRODUCER,PURITY,REAL_BATCH_FIELD_1,REAL_BATCH_FIELD_2,REAL_BATCH_FIELD_3,REAL_BATCH_FIELD_4,REAL_BATCH_FIELD_5,REAL_BATCH_FIELD_6, REFRACTIVE_INDEX,SALT_EQUIVALENTS,SALT_MW,SALT_NAME,SALT_INTERNAL_ID,SCIENTIST_ID,SOLUBILITY,SOLVATE_EQUIVALENTS,SOLVATE_ID,SOLVATE_MW,SOLVATE_NAME,SOURCE,STORAGE_REQ_AND_WARNINGS,UV_SPECTRUM,VENDOR_ID,VENDOR_NAME,DATECREATED,DATELASTMODIFIED,STRUCTUREAGGREGATION)
SELECT TEMP_COMPOUND_ID,AMOUNT,AMOUNT_UNITS,APPEARANCE,BATCH_COMMENT,BATCH_FORMULA,BATCH_PROJECT_ID,BP,C13NMR,CHN_COMBUSTION,COLOR,CPD_INTERNAL_ID,CREATION_DATE,DATE_BATCH_FIELD_1,DATE_BATCH_FIELD_2 ,DATE_BATCH_FIELD_3 ,DATE_BATCH_FIELD_4 ,DATE_BATCH_FIELD_5 ,DATE_BATCH_FIELD_6,FIELD_1,FIELD_10,FIELD_2,FIELD_3,FIELD_4,FIELD_5,FIELD_6,FIELD_7,FIELD_8,FIELD_9,FLASHPOINT,FORMULA_WEIGHT,GC,H1NMR,HPLC,INT_BATCH_FIELD_1,INT_BATCH_FIELD_2,INT_BATCH_FIELD_3,INT_BATCH_FIELD_4,INT_BATCH_FIELD_5,INT_BATCH_FIELD_6,IR,LAST_MOD_PERSON_ID,LC_UV_MS,LIT_REF,LOAD_ID,LOGD,MOL_ID,MP,MS,NOTEBOOK_NUMBER,NOTEBOOK_PAGE,NOTEBOOK_TEXT,OPTICAL_ROTATION ,PERCENT_ACTIVE,PHYSICAL_FORM,PREPARATION,PRODUCER,PURITY,REAL_BATCH_FIELD_1,REAL_BATCH_FIELD_2,REAL_BATCH_FIELD_3,REAL_BATCH_FIELD_4,REAL_BATCH_FIELD_5,REAL_BATCH_FIELD_6,REFRACTIVE_INDEX,SALT_EQUIVALENTS,SALT_MW,SALT_NAME,SALT_CODE,SCIENTIST_ID,SOLUBILITY,SOLVATE_EQUIVALENTS,SOLVATE_ID,SOLVATE_MW,SOLVATE_NAME,SOURCE ,STORAGE_REQ_AND_WARNINGS,UV_SPECTRUM,VENDOR_ID,VENDOR_NAME,TO_DATE(DATETIME_STAMP,'HH:MI:SS AM:MM/DD/YYYY'),TO_DATE(DATETIME_STAMP,'HH:MI:SS AM:MM/DD/YYYY'),BASE64_CDX  
  FROM TEMPORARY_STRUCTURES;  

INSERT INTO PICKLIST(ID,PICKLISTDOMAINID,PICKLISTVALUE) 
(SELECT (SELECT NVL(MAX(ID),0) FROM PICKLIST)+ROWNUM,2,AMOUNT_UNITS 
    FROM (SELECT DISTINCT AMOUNT_UNITS FROM TEMPORARY_STRUCTURES MINUS SELECT PICKLISTVALUE FROM PICKLIST));
    
INSERT INTO PICKLIST(ID,PICKLISTDOMAINID,PICKLISTVALUE) 
(SELECT (SELECT NVL(MAX(ID),0) FROM PICKLIST)+ROWNUM,2,AMOUNT_UNITS 
    FROM (SELECT DISTINCT AMOUNT_UNITS FROM BATCHES MINUS SELECT PICKLISTVALUE FROM PICKLIST));
    
UPDATE TEMPORARY_BATCH
    SET AMOUNT_UNITS=(SELECT ID FROM PICKLIST WHERE PICKLISTVALUE=AMOUNT_UNITS)
    WHERE AMOUNT_UNITS IS NOT NULL;

UPDATE BATCHES
    SET AMOUNT_UNITS=(SELECT ID FROM PICKLIST WHERE PICKLISTVALUE=AMOUNT_UNITS)
    WHERE AMOUNT_UNITS IS NOT NULL;

DECLARE
  LNextID NUMBER(8);
BEGIN
    SELECT NVL(MAX(TEMPBATCHID),0)+1 INTO LNextID FROM TEMPORARY_BATCH;
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TEMPORARY_BATCH';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TEMPORARY_BATCH START WITH '||LNextID||' CACHE 2';
END;
/

INSERT INTO TEMPORARY_COMPOUND(
  TEMPCOMPOUNDID,TEMPBATCHID,USENORMALIZATION,BASE64_CDX,CHIRAL,CLOGP,COMPOUND_TYPE,DATE_CMPD_FIELD_1,DATE_CMPD_FIELD_2,DATE_CMPD_FIELD_3,DATE_CMPD_FIELD_4,FORMULA2,FRAGMENTXML,H_BOND_ACCEPTORS,H_BOND_DONORS,INT_CMPD_FIELD_1,INT_CMPD_FIELD_2 ,INT_CMPD_FIELD_3,INT_CMPD_FIELD_4, LOAD_ID,MF_TEXT,MW,MW_TEXT,MW2,PRODUCT_TYPE,REAL_CMPD_FIELD_1,REAL_CMPD_FIELD_2,REAL_CMPD_FIELD_3,REAL_CMPD_FIELD_4,REGID,SEQUENCE_INTERNAL_ID,STRUCTURE_COMMENTS_TXT,TXT_CMPD_FIELD_1,TXT_CMPD_FIELD_2,TXT_CMPD_FIELD_3,TXT_CMPD_FIELD_4,DATELASTMODIFIED,DATECREATED,NORMALIZEDSTRUCTURE)
SELECT TEMP_COMPOUND_ID,TEMP_COMPOUND_ID,'F',BASE64_CDX,CHIRAL,CLOGP,COMPOUND_TYPE,DATE_CMPD_FIELD_1,DATE_CMPD_FIELD_2,DATE_CMPD_FIELD_3,DATE_CMPD_FIELD_4,FORMULA2,FRAGMENTS,H_BOND_ACCEPTORS,H_BOND_DONORS,INT_CMPD_FIELD_1,INT_CMPD_FIELD_2 ,INT_CMPD_FIELD_3,INT_CMPD_FIELD_4,LOAD_ID,MF_TEXT,MW,MW_TEXT,MW2,PRODUCT_TYPE,REAL_CMPD_FIELD_1,REAL_CMPD_FIELD_2,REAL_CMPD_FIELD_3,REAL_CMPD_FIELD_4,REG_INTERNAL_ID,SEQUENCE_ID,STRUCTURE_COMMENTS_TXT,TXT_CMPD_FIELD_1,TXT_CMPD_FIELD_2,TXT_CMPD_FIELD_3,TXT_CMPD_FIELD_4,TO_DATE(DATETIME_STAMP,'HH:MI:SS AM:MM/DD/YYYY'),TO_DATE(DATETIME_STAMP,'HH:MI:SS AM:MM/DD/YYYY'),BASE64_CDX
  FROM TEMPORARY_STRUCTURES;


DECLARE
  LNextID NUMBER(8);
BEGIN
    SELECT NVL(MAX(TEMPCOMPOUNDID),0)+1 INTO LNextID FROM TEMPORARY_COMPOUND;
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TEMPORARY_COMPOUND';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TEMPORARY_COMPOUND START WITH '||LNextID||' CACHE 2';
END;
/

UPDATE BATCHES SET DATECREATED=CREATION_DATE;
UPDATE BATCHES SET DATECREATED=BATCH_REG_DATE  WHERE DATECREATED IS NULL;
UPDATE BATCHES SET LAST_MOD_DATE=DATECREATED WHERE LAST_MOD_DATE IS NULL;
UPDATE BATCHES B SET FULLREGNUMBER=(SELECT SUBSTR(RN.Reg_Number||'-'||LPad(B.Batch_Number,2,'0'),1,50) FROM REG_NUMBERS RN WHERE RN.Reg_ID=B.REG_INTERNAL_ID);
UPDATE BATCHES SET CHEMIST=BATCH_REG_PERSON_ID;

UPDATE COMPOUND_MOLECULE SET DATECREATED=ROOT_REG_DATE,USENORMALIZATION='F';
UPDATE COMPOUND_MOLECULE CM SET PERSONCREATED=(SELECT REGISTRAR_PERSON_ID FROM REG_NUMBERS RN WHERE RN.REG_ID=CM.CPD_DATABASE_COUNTER);
UPDATE COMPOUND_MOLECULE CM SET PERSONREGISTERED=(SELECT REGISTRAR_PERSON_ID FROM REG_NUMBERS RN WHERE RN.REG_ID=CM.CPD_DATABASE_COUNTER);
UPDATE COMPOUND_MOLECULE SET REGID=SEQ_REG_NUMBERS.NextVal;
UPDATE COMPOUND_MOLECULE SET StructureID= CPD_DATABASE_COUNTER WHERE CPD_DATABASE_COUNTER IN (SELECT CPD_INTERNAL_ID from STRUCTURES);
UPDATE COMPOUND_MOLECULE SET NORMALIZEDSTRUCTURE=(SELECT BASE64_CDX FROM STRUCTURES WHERE CPD_INTERNAL_ID=STRUCTUREID) WHERE CPD_DATABASE_COUNTER IN (SELECT CPD_INTERNAL_ID from STRUCTURES);

INSERT INTO MIXTURES(MIX_INTERNAL_ID,CREATED,MODIFIED,REGID,STRUCTUREAGGREGATION,APPROVED)
  SELECT CM.CPD_DATABASE_COUNTER,CM.ROOT_REG_DATE,CM.LAST_MOD_DATE,CM.CPD_DATABASE_COUNTER,S.BASE64_CDX,'Approved' FROM COMPOUND_MOLECULE CM,STRUCTURES S WHERE CM.CPD_DATABASE_COUNTER=S.CPD_INTERNAL_ID;

INSERT INTO REG_NUMBERS(REG_ID,SEQUENCE_INTERNAL_ID,SEQUENCE_NUMBER,REG_NUMBER,REGISTRAR_PERSON_ID)
  SELECT CM.REGID,RN.SEQUENCE_INTERNAL_ID,CM.REGID,S.Prefix||S.Prefix_Delimiter||lpad(NVL(CM.REGID,1),S.RegNumber_Length,'0'),RN.REGISTRAR_PERSON_ID    
  FROM COMPOUND_MOLECULE CM,REG_NUMBERS RN,SEQUENCE S WHERE CM.CPD_DATABASE_COUNTER=RN.Reg_ID AND S.SEQUENCE_ID=RN.SEQUENCE_INTERNAL_ID;

DECLARE
  LNextID NUMBER(8);
BEGIN
    SELECT NVL(MAX(MIX_INTERNAL_ID),0)+1 INTO LNextID FROM MIXTURES;
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MIXTURE';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_MIXTURE START WITH '||LNextID||' CACHE 2';
END;
/

INSERT INTO MIXTURE_COMPONENT (ID,MIXTRUREID,COMPOUNDID)
  SELECT CPD_DATABASE_COUNTER,CPD_DATABASE_COUNTER,CPD_DATABASE_COUNTER FROM COMPOUND_MOLECULE
    WHERE CPD_DATABASE_COUNTER IN (SELECT MIX_INTERNAL_ID from MIXTURES);

DECLARE
  LNextID NUMBER(8);
BEGIN
    SELECT NVL(MAX(ID),0)+1 INTO LNextID FROM MIXTURE_COMPONENT;
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MIXTURE_COMPONENT';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_MIXTURE_COMPONENT START WITH '||LNextID||' CACHE 2';
END;
/

INSERT INTO BATCHCOMPONENT(
 ID,BATCHID,MIXTURECOMPONENTID)
(SELECT BATCH_INTERNAL_ID,BATCH_INTERNAL_ID,REG_INTERNAL_ID FROM Batches);	

DECLARE
  LNextID NUMBER(8);
BEGIN
    SELECT NVL(MAX(ID),0)+1 INTO LNextID FROM BATCHCOMPONENT;
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BATCHCOMPONENT';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BATCHCOMPONENT START WITH '||LNextID||' CACHE 2';
END;
/

INSERT INTO FRAGMENTS (FRAGMENT_ID,CODE,DESCRIPTION,FRAGMENTTYPEID,MOLWEIGHT,FORMULA,CREATED,MODIFIED,BASE64_CDX,STRUCTUREFORMAT)
  SELECT SALT_CODE,SALT_CODE,SALT_NAME,1,SALT_MW,SALT_MF,SYSDATE,SYSDATE,BASE64_CDX,NULL FROM SALTS;

INSERT INTO FRAGMENTS (FRAGMENT_ID,CODE,DESCRIPTION,FRAGMENTTYPEID,MOLWEIGHT,FORMULA,CREATED,MODIFIED,BASE64_CDX,STRUCTUREFORMAT)
  SELECT SOLVATE_ID,SOLVATE_ID,SOLVATE_NAME,2,SOLVATE_MW,SOLVATE_MF,SYSDATE,SYSDATE,BASE64_CDX,NULL FROM SOLVATES;

UPDATE FRAGMENTS SET CODE=FRAGMENT_ID;

COMMIT;

prompt logged session to: log_Migrate_10_to_11.0.1.txt
spool off

exit
