CREATE TABLE "INV_BATCH_STATUS"(
	"BATCH_STATUS_ID" NUMBER(4) NOT NULL,
	"BATCH_STATUS_NAME" VARCHAR2(50) NOT NULL,
    CONSTRAINT "INV_BATCH_STATUS_PK"
		PRIMARY KEY("BATCH_STATUS_ID") USING INDEX TABLESPACE &&indexTableSpaceName);

CREATE SEQUENCE SEQ_INV_BATCH_STATUS INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 100 ORDER;

CREATE OR REPLACE TRIGGER "TRG_INV_BATCH_STATUS_ID"
    BEFORE INSERT
    ON "INV_BATCH_STATUS"
    FOR EACH ROW
    begin
		if :new.BATCH_STATUS_ID is null then
			select seq_INV_BATCH_STATUS.nextval into :new.BATCH_STATUS_ID from dual;
		end if;
end;
/