CREATE TABLE "INV_ORG_UNIT"(
	"ORG_UNIT_ID" NUMBER NOT NULL,
	"ORG_NAME" VARCHAR2(100) not null,
	"ORG_TYPE_ID_FK" NUMBER(4) not null,
    CONSTRAINT "INV_ORG_UNIT_PK"
		PRIMARY KEY("ORG_UNIT_ID") USING INDEX TABLESPACE &&indexTableSpaceName,
	CONSTRAINT "INV_ORG_TYPE_ID_FK" 
		FOREIGN KEY ("ORG_TYPE_ID_FK")
		REFERENCES "INV_ENUMERATION" ("ENUM_ID")
	);

CREATE SEQUENCE SEQ_ORG_UNIT_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER "TRG_INV_ORG_UNIT_ID"
    BEFORE INSERT
    ON "INV_ORG_UNIT"
    FOR EACH ROW
BEGIN
	if :new.org_unit_id is null then
		select SEQ_ORG_UNIT_ID.nextval into :new.org_unit_id from dual;
	end if;
END;
/
