

CREATE INDEX B64_MOL_ID_INDX ON DRUGDEG_BASE64
(MOL_ID)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX COND_FK_INDX ON DRUGDEG_EXPTS
(DEG_COND_FK)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX DEGFGROUP_INDX ON DRUGDEG_DEGSFGROUP
(DEG_CMPD_ID)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX DEG_CMPD_EXPT_INDX ON DRUGDEG_DEGS
(DEG_EXPT_FK)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE UNIQUE INDEX DEG_CMPD_INDX ON DRUGDEG_DEGS
(DEG_CMPD_KEY)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;



CREATE UNIQUE INDEX EXPT_KEY_INDX ON DRUGDEG_EXPTS
(EXPT_KEY)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX IX_DEGSFGROUP ON DRUGDEG_DEGSFGROUP
(DEG_CMPD_ID, DEG_FGROUP_ID)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX IX_DEGS_MOLID ON DRUGDEG_DEGS
(MOL_ID)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX IX_DEGS_MW_CHG ON DRUGDEG_DEGS
(MW_AMT_CHG)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX IX_EXPTS_STATUS ON DRUGDEG_EXPTS
(STATUS)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX IX_PARENT_CNAME ON DRUGDEG_PARENTS
(COMMON_NAME)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX IX_PARENT_CNUMBER ON DRUGDEG_PARENTS
(COMPOUND_NUMBER)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX IX_PARENT_TNAME ON DRUGDEG_PARENTS
(TRADE_NAME)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX IX_SALT_SNAME ON DRUGDEG_SALTS
(SALT_NAME)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX MECH_DEG_CMPD_INDX ON DRUGDEG_MECHS
(DEG_CMPD_FK)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MECH_KEY_INDX ON DRUGDEG_MECHS
(MECH_KEY)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX MECH_MOL_ID_INX ON DRUGDEG_MECHS
(MOL_ID)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;




CREATE INDEX PARENT_MOL_ID_INDX ON DRUGDEG_PARENTS
(MOL_ID)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX PARENT_NAME_INDX ON DRUGDEG_PARENTS
(GENERIC_NAME)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;






CREATE INDEX PARENT_SALT_INDX ON DRUGDEG_PARENTS
(SALT)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE INDEX PAR_FK_INDX ON DRUGDEG_EXPTS
(PARENT_CMPD_FK)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PKDRUGDEG_BASE64 ON DRUGDEG_BASE64
(BASE64_ID)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


--CREATE UNIQUE INDEX PKDRUGDEG_CONDS ON DRUGDEG_CONDS
--(DEG_COND_KEY)  TABLESPACE &&indexTableSpaceName
--NOLOGGING
--NOPARALLEL;


---CREATE UNIQUE INDEX PKDRUGDEG_FGROUP ON DRUGDEG_FGROUPS
---(DEG_FGROUP_KEY)  TABLESPACE &&indexTableSpaceName
---NOLOGGING
---NOPARALLEL;


CREATE UNIQUE INDEX PKDRUGDEG_PARENTS ON DRUGDEG_PARENTS
(PARENT_CMPD_KEY)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PKDRUGDEG_SALTS ON DRUGDEG_SALTS
(SALT_KEY)  TABLESPACE &&indexTableSpaceName
NOLOGGING
NOPARALLEL;


---CREATE UNIQUE INDEX PKDRUGDEG_STATUSES ON DRUGDEG_STATUSES
---(STATUS_KEY)  TABLESPACE &&indexTableSpaceName
---NOLOGGING
---NOPARALLEL;





ALTER TABLE DRUGDEG_BASE64 ADD (
  CONSTRAINT PKDRUGDEG_BASE64
 PRIMARY KEY
 (BASE64_ID) USING INDEX TABLESPACE &&indexTableSpaceName ); 

ALTER TABLE DRUGDEG_CONDS ADD (
  CONSTRAINT PKDRUGDEG_CONDS
 PRIMARY KEY
 (DEG_COND_KEY) USING INDEX TABLESPACE &&indexTableSpaceName ); 

ALTER TABLE DRUGDEG_DEGS ADD (
  CONSTRAINT DEG_CMPD_INDX
 PRIMARY KEY
 (DEG_CMPD_KEY) USING INDEX TABLESPACE &&indexTableSpaceName ); 

ALTER TABLE DRUGDEG_EXPTS ADD (
  CONSTRAINT EXPT_KEY_INDX
 PRIMARY KEY
 (EXPT_KEY) USING INDEX TABLESPACE &&indexTableSpaceName ); 

ALTER TABLE DRUGDEG_FGROUPS ADD (
  CONSTRAINT PKDRUGDEG_FGROUP
 PRIMARY KEY
 (DEG_FGROUP_KEY) USING INDEX TABLESPACE &&indexTableSpaceName ); 

ALTER TABLE DRUGDEG_MECHS ADD (
  CONSTRAINT MECH_KEY_INDX
 PRIMARY KEY
 (MECH_KEY) USING INDEX TABLESPACE &&indexTableSpaceName ); 

ALTER TABLE DRUGDEG_PARENTS ADD (
  CONSTRAINT PKDRUGDEG_PARENTS
 PRIMARY KEY
 (PARENT_CMPD_KEY) USING INDEX TABLESPACE &&indexTableSpaceName ); 

ALTER TABLE DRUGDEG_SALTS ADD (
  CONSTRAINT PKDRUGDEG_SALTS
 PRIMARY KEY
 (SALT_KEY) USING INDEX TABLESPACE &&indexTableSpaceName ); 

ALTER TABLE DRUGDEG_STATUSES ADD (
  CONSTRAINT PKDRUGDEG_STATUSES
 PRIMARY KEY
 (STATUS_KEY) USING INDEX TABLESPACE &&indexTableSpaceName ); 

--jhs adding to match existing
ALTER TABLE DRUGDEG_EXPTS
 ADD CONSTRAINT REFDRUGDEG_CONDS1 
 FOREIGN KEY (DEG_COND_FK) 
 REFERENCES DRUGDEG_CONDS (DEG_COND_KEY);

ALTER TABLE DRUGDEG_EXPTS
 ADD CONSTRAINT REFDRUGDEG_PARENTS7 
 FOREIGN KEY (PARENT_CMPD_FK) 
 REFERENCES DRUGDEG_PARENTS (PARENT_CMPD_KEY);

ALTER TABLE DRUGDEG_DEGS
 ADD CONSTRAINT REFDRUGDEG_EXPTS2 
 FOREIGN KEY (DEG_EXPT_FK) 
 REFERENCES DRUGDEG_EXPTS (EXPT_KEY);

ALTER TABLE DRUGDEG_DEGSFGROUP
 ADD CONSTRAINT REF_DEGSFGROUP1 
 FOREIGN KEY (DEG_CMPD_ID) 
 REFERENCES DRUGDEG_DEGS (DEG_CMPD_KEY);

ALTER TABLE DRUGDEG_DEGSFGROUP
 ADD CONSTRAINT REF_DEGSFGROUP2 
 FOREIGN KEY (DEG_FGROUP_ID) 
 REFERENCES DRUGDEG_FGROUPS (DEG_FGROUP_KEY);

ALTER TABLE DRUGDEG_MECHS
 ADD CONSTRAINT REFDRUGDEG_DEGS4 
 FOREIGN KEY (DEG_CMPD_FK) 
 REFERENCES DRUGDEG_DEGS (DEG_CMPD_KEY);