--Copyright Cambridgesoft Corp 2001-2003 all rights reserved
-- NOTE THIS SCRIPT MUST BE RUN FROM THE COMMAND LINE VERSION OF SQLPLUS
-- This script will not run from SQLPlus Worksheet!

-- Creates and grants to default DrugDeg Roles and populates CS_SECURITY tables
-- Assumes that CS_SECURITY schemas exist.
-- Assumes drops.sql was run to delete roles

Connect &&securitySchemaName/&&securitySchemaPass@&&serverName


GRANT EXECUTE ON GrantOnCoreTableToAllRoles to &&schemaName;

DROP TABLE DRUGDEG_PRIVILEGES CASCADE CONSTRAINTS;

CREATE TABLE  DRUGDEG_PRIVILEGES( 
	ROLE_INTERNAL_ID NUMBER(8,0) not null,
	DD_SEARCH NUMBER(1,0) null,
	DD_ADD_RECORDS NUMBER(1,0) null,
	DD_EDIT_RECORDS NUMBER(1,0) null,
	DD_DELETE_RECORDS NUMBER(1,0) null,
	DD_LINK_DOCUMENTS NUMBER(1,0) null,
	DD_APPROVE_RECORDS NUMBER(1,0) null,
	constraint DRUGDEG_PRIVILEGES_PK primary key(ROLE_INTERNAL_ID))
	TABLESPACE T_&&securitySchemaName.;


--#########################################################
--CREATE ROLES
--#########################################################

-- ROLE creation script for DRUGDEG/Oracle version
-- Copyright Cambridgesoft corp 1999-2003 all rights reserved
CONNECT &&InstallUser/&&sysPass@&&serverName


-- CREATE_MASTER_ROLES

-- DRUGDEG_BROWSER 
CREATE ROLE DRUGDEG_BROWSER NOT IDENTIFIED;
REVOKE DRUGDEG_BROWSER FROM SYSTEM;


-- DRUGDEG_SUBMITTER;
CREATE ROLE DRUGDEG_SUBMITTER NOT IDENTIFIED;
REVOKE DRUGDEG_SUBMITTER FROM SYSTEM;

-- DRUGDEG_ADMINISTRATOR 
CREATE ROLE DRUGDEG_ADMINISTRATOR NOT IDENTIFIED;
REVOKE DRUGDEG_ADMINISTRATOR FROM SYSTEM;





-- MRE changed 11/04/04
-- password now in the parameters.sql file
--Connect &&SchemaName/oracle@&&ServerName;
connect &&schemaName/&&schemaPass@&&serverName

-- DRUGDEG_BROWSER
GRANT SELECT ON DRUGDEG_PARENTS 	TO DRUGDEG_BROWSER;
GRANT SELECT ON DRUGDEG_DEGS    	TO DRUGDEG_BROWSER;
GRANT SELECT ON DRUGDEG_EXPTS   	TO DRUGDEG_BROWSER;
GRANT SELECT ON DRUGDEG_MECHS   	TO DRUGDEG_BROWSER;
GRANT SELECT ON DRUGDEG_BASE64  	TO DRUGDEG_BROWSER;
GRANT SELECT ON DRUGDEG_SALTS   	TO DRUGDEG_BROWSER;
GRANT SELECT ON DRUGDEG_CONDS    	TO DRUGDEG_BROWSER;
GRANT SELECT ON DRUGDEG_FGROUPS    	TO DRUGDEG_BROWSER;
GRANT SELECT ON DRUGDEG_DEGSFGROUP 	TO DRUGDEG_BROWSER;
GRANT SELECT ON DRUGDEG_STATUSES   	TO DRUGDEG_BROWSER;
	
-- DRUGDEG_SUBMITTER
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_PARENTS TO DRUGDEG_SUBMITTER;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_DEGS TO DRUGDEG_SUBMITTER;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_EXPTS TO DRUGDEG_SUBMITTER;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_MECHS TO DRUGDEG_SUBMITTER;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_BASE64 TO DRUGDEG_SUBMITTER;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_SALTS TO DRUGDEG_SUBMITTER;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_CONDS TO DRUGDEG_SUBMITTER;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_FGROUPS TO DRUGDEG_SUBMITTER;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_DEGSFGROUP TO DRUGDEG_SUBMITTER;
GRANT SELECT ON DRUGDEG_STATUSES TO DRUGDEG_SUBMITTER;


-- DRUGDEG_ADMINISTRATOR
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_PARENTS TO DRUGDEG_ADMINISTRATOR;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_DEGS TO DRUGDEG_ADMINISTRATOR;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_EXPTS TO DRUGDEG_ADMINISTRATOR;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_MECHS TO DRUGDEG_ADMINISTRATOR;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_BASE64 TO DRUGDEG_ADMINISTRATOR;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_SALTS TO DRUGDEG_ADMINISTRATOR;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_CONDS TO DRUGDEG_ADMINISTRATOR;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_FGROUPS TO DRUGDEG_ADMINISTRATOR;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_DEGSFGROUP TO DRUGDEG_ADMINISTRATOR;
GRANT SELECT,INSERT,DELETE,UPDATE ON DRUGDEG_STATUSES TO DRUGDEG_ADMINISTRATOR;





commit;
--JHS added 3/27/2003
--The schemaname did not seem to have enough permissions to find the PRIVILEGE_TABLES
--connect &&securitySchemaName./oracle@&&serverName
-- MRE added 11/4/2004
-- connection values set in the parameters.sql file

Connect &&securitySchemaName/&&securitySchemaPass@&&serverName

-- SECURITY_ROLES
delete from SECURITY_ROLES where (PRIVILEGE_TABLE_INT_ID) IN (SELECT PRIVILEGE_TABLE_ID FROM PRIVILEGE_TABLES WHERE PRIVILEGE_TABLE_NAME = 'DRUGDEG_PRIVILEGES');
commit;

--PRIVELEGE_TABLES
delete from PRIVILEGE_TABLES where TABLE_SPACE = 'T_DRUGDEG';
commit;

INSERT INTO PRIVILEGE_TABLES (PRIVILEGE_TABLE_NAME,APP_NAME,TABLE_SPACE) values('DRUGDEG_PRIVILEGES','Drug Degradation','T_DRUGDEG');

INSERT INTO SECURITY_ROLES( ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME,COEIDENTIFIER )
	values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'DRUGDEG_BROWSER', 'DrugDeg' );
INSERT INTO DRUGDEG_PRIVILEGES	(ROLE_INTERNAL_ID,			DD_SEARCH,	DD_ADD_RECORDS,	DD_DELETE_RECORDS,	DD_EDIT_RECORDS, DD_LINK_DOCUMENTS, DD_APPROVE_RECORDS)
	values						(SECURITY_ROLES_seq.CURRVAL,'1',		'0',			'0',				'0',				'0',			'0');

INSERT INTO SECURITY_ROLES( ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME,COEIDENTIFIER )
	values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'DRUGDEG_SUBMITTER', 'DrugDeg' );
INSERT INTO DRUGDEG_PRIVILEGES	(ROLE_INTERNAL_ID,			DD_SEARCH,	DD_ADD_RECORDS,	DD_DELETE_RECORDS,	DD_EDIT_RECORDS, DD_LINK_DOCUMENTS, DD_APPROVE_RECORDS)
	values						(SECURITY_ROLES_seq.CURRVAL,'1',		'1',			'1',				'1',				'1',			'0');

INSERT INTO SECURITY_ROLES( ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME,COEIDENTIFIER )
	values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'DRUGDEG_ADMINISTRATOR', 'DrugDeg' );
INSERT INTO DRUGDEG_PRIVILEGES	(ROLE_INTERNAL_ID,			DD_SEARCH,	DD_ADD_RECORDS,	DD_DELETE_RECORDS,	DD_EDIT_RECORDS, DD_LINK_DOCUMENTS, DD_APPROVE_RECORDS)
	values						(SECURITY_ROLES_seq.CURRVAL,'1',		'1',			'1',				'1',				'1',			'1');


Commit;


DELETE FROM &&securitySchemaName..OBJECT_PRIVILEGES WHERE Schema = '&&SchemaName';

--SEARCH
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_PARENTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_DEGS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_EXPTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_MECHS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_BASE64');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_SALTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_CONDS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_FGROUPS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_DEGSFGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_SEARCH', 'SELECT', '&&SchemaName', 'DRUGDEG_STATUSES');


--ADD_RECORDS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_ADD_RECORDS', 'INSERT', '&&SchemaName', 'DRUGDEG_PARENTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_ADD_RECORDS', 'INSERT', '&&SchemaName', 'DRUGDEG_DEGS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_ADD_RECORDS', 'INSERT', '&&SchemaName', 'DRUGDEG_EXPTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_ADD_RECORDS', 'INSERT', '&&SchemaName', 'DRUGDEG_MECHS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_ADD_RECORDS', 'INSERT', '&&SchemaName', 'DRUGDEG_BASE64');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_ADD_RECORDS', 'INSERT', '&&SchemaName', 'DRUGDEG_SALTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_ADD_RECORDS', 'INSERT', '&&SchemaName', 'DRUGDEG_CONDS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_ADD_RECORDS', 'INSERT', '&&SchemaName', 'DRUGDEG_FGROUPS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_ADD_RECORDS', 'INSERT', '&&SchemaName', 'DRUGDEG_DEGSFGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_ADD_RECORDS', 'INSERT', '&&SchemaName', 'DRUGDEG_STATUSES');

--DELETE_RECORDS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_DELETE_RECORDS', 'DELETE', '&&SchemaName', 'DRUGDEG_PARENTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_DELETE_RECORDS', 'DELETE', '&&SchemaName', 'DRUGDEG_DEGS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_DELETE_RECORDS', 'DELETE', '&&SchemaName', 'DRUGDEG_EXPTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_DELETE_RECORDS', 'DELETE', '&&SchemaName', 'DRUGDEG_MECHS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_DELETE_RECORDS', 'DELETE', '&&SchemaName', 'DRUGDEG_BASE64');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_DELETE_RECORDS', 'DELETE', '&&SchemaName', 'DRUGDEG_SALTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_DELETE_RECORDS', 'DELETE', '&&SchemaName', 'DRUGDEG_CONDS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_DELETE_RECORDS', 'DELETE', '&&SchemaName', 'DRUGDEG_FGROUPS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_DELETE_RECORDS', 'DELETE', '&&SchemaName', 'DRUGDEG_DEGSFGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_DELETE_RECORDS', 'DELETE', '&&SchemaName', 'DRUGDEG_STATUSES');



--EDIT_RECORDS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_EDIT_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_PARENTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_EDIT_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_DEGS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_EDIT_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_EXPTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_EDIT_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_MECHS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_EDIT_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_BASE64');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_EDIT_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_SALTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_EDIT_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_CONDS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_EDIT_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_FGROUPS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_EDIT_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_DEGSFGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_EDIT_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_STATUSES');

--APPROVE_RECORDS
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_APPROVE_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_PARENTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_APPROVE_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_DEGS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_APPROVE_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_EXPTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_APPROVE_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_MECHS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_APPROVE_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_BASE64');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_APPROVE_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_SALTS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_APPROVE_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_CONDS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_APPROVE_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_FGROUPS');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_APPROVE_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_DEGSFGROUP');
INSERT INTO &&securitySchemaName..OBJECT_PRIVILEGES VALUES ('DD_APPROVE_RECORDS', 'UPDATE', '&&SchemaName', 'DRUGDEG_STATUSES');

Commit;

-- MRE changed 11/04/04
-- password now in the parameters.sql file
--Connect &&SchemaName/oracle@&&ServerName;
connect &&schemaName/&&schemaPass@&&serverName;


--- Grant all object permissions to &&securitySchemaName
GRANT SELECT ON DRUGDEG_PARENTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON DRUGDEG_DEGS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON DRUGDEG_EXPTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON DRUGDEG_MECHS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON DRUGDEG_BASE64 TO &&securitySchemaName. WITH GRANT OPTION;
GRANT SELECT ON DRUGDEG_SALTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON DRUGDEG_CONDS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON DRUGDEG_FGROUPS TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON DRUGDEG_DEGSFGROUP TO &&securitySchemaName WITH GRANT OPTION;
GRANT SELECT ON DRUGDEG_STATUSES TO &&securitySchemaName WITH GRANT OPTION;

GRANT UPDATE ON DRUGDEG_PARENTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT UPDATE ON DRUGDEG_DEGS TO &&securitySchemaName WITH GRANT OPTION;
GRANT UPDATE ON DRUGDEG_EXPTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT UPDATE ON DRUGDEG_MECHS TO &&securitySchemaName WITH GRANT OPTION;
GRANT UPDATE ON DRUGDEG_BASE64 TO &&securitySchemaName WITH GRANT OPTION;
GRANT UPDATE ON DRUGDEG_SALTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT UPDATE ON DRUGDEG_CONDS TO &&securitySchemaName WITH GRANT OPTION;
GRANT UPDATE ON DRUGDEG_FGROUPS TO &&securitySchemaName WITH GRANT OPTION;
GRANT UPDATE ON DRUGDEG_DEGSFGROUP TO &&securitySchemaName WITH GRANT OPTION;
GRANT UPDATE ON DRUGDEG_STATUSES TO &&securitySchemaName WITH GRANT OPTION;

GRANT INSERT ON DRUGDEG_PARENTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT INSERT ON DRUGDEG_DEGS TO &&securitySchemaName WITH GRANT OPTION;
GRANT INSERT ON DRUGDEG_EXPTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT INSERT ON DRUGDEG_MECHS TO &&securitySchemaName WITH GRANT OPTION;
GRANT INSERT ON DRUGDEG_BASE64 TO &&securitySchemaName WITH GRANT OPTION;
GRANT INSERT ON DRUGDEG_SALTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT INSERT ON DRUGDEG_CONDS TO &&securitySchemaName WITH GRANT OPTION;
GRANT INSERT ON DRUGDEG_FGROUPS TO &&securitySchemaName. WITH GRANT OPTION;
GRANT INSERT ON DRUGDEG_DEGSFGROUP TO &&securitySchemaName WITH GRANT OPTION;
GRANT INSERT ON DRUGDEG_STATUSES TO &&securitySchemaName WITH GRANT OPTION;

GRANT DELETE ON DRUGDEG_PARENTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT DELETE ON DRUGDEG_DEGS TO &&securitySchemaName WITH GRANT OPTION;
GRANT DELETE ON DRUGDEG_EXPTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT DELETE ON DRUGDEG_MECHS TO &&securitySchemaName WITH GRANT OPTION;
GRANT DELETE ON DRUGDEG_BASE64 TO &&securitySchemaName WITH GRANT OPTION;
GRANT DELETE ON DRUGDEG_SALTS TO &&securitySchemaName WITH GRANT OPTION;
GRANT DELETE ON DRUGDEG_CONDS TO &&securitySchemaName WITH GRANT OPTION;
GRANT DELETE ON DRUGDEG_FGROUPS TO &&securitySchemaName WITH GRANT OPTION;
GRANT DELETE ON DRUGDEG_DEGSFGROUP TO &&securitySchemaName WITH GRANT OPTION;
GRANT DELETE ON DRUGDEG_STATUSES TO &&securitySchemaName WITH GRANT OPTION;

commit;
