INSERT INTO INV_REQUEST_STATUS (REQUEST_STATUS_ID, REQUEST_STATUS_NAME) VALUES (8,'Pending');
INSERT INTO INV_REQUEST_STATUS (REQUEST_STATUS_ID, REQUEST_STATUS_NAME) VALUES (9,'Reserved');

INSERT INTO INV_GRAPHIC_TYPES (GRAPHIC_TYPE_ID,GRAPHIC_TYPE_NAME) VALUES (1,'Tree Icons');

INSERT INTO DB_FORMGROUP (FORMGROUP_ID, FORMGROUP_NAME, IS_PUBLIC, DESCRIPTION, CREATED_DATE) VALUES
						 (6, 'BATCHES_FORM_GROUP', '1', 'Batch Search', sysdate);

UPDATE DB_FORMGROUP SET FORMGROUP_NAME=UPPER(FORMGROUP_NAME);

INSERT INTO INV_GRAPHICS (GRAPHIC_ID,GRAPHIC_NAME,GRAPHIC_TYPE_ID_FK,GRAPHIC_WIDTH,GRAPHIC_HEIGHT,URL_ACTIVE,URL_INACTIVE) VALUES (1,'Freezer',1,16,16,'freezer_open.gif','freezer_close.gif');
INSERT INTO INV_GRAPHICS (GRAPHIC_ID,GRAPHIC_NAME,GRAPHIC_TYPE_ID_FK,GRAPHIC_WIDTH,GRAPHIC_HEIGHT,URL_ACTIVE,URL_INACTIVE) VALUES (2,'Rack',1,16,16,'rack_open.gif','rack_closed.gif');
INSERT INTO INV_GRAPHICS (GRAPHIC_ID,GRAPHIC_NAME,GRAPHIC_TYPE_ID_FK,GRAPHIC_WIDTH,GRAPHIC_HEIGHT,URL_ACTIVE, URL_INACTIVE) VALUES (3,'Plate',1,16,16,'icon_openfold2.gif','icon_clsdfold2.gif');
INSERT INTO INV_GRAPHICS (GRAPHIC_ID,GRAPHIC_NAME,GRAPHIC_TYPE_ID_FK,GRAPHIC_WIDTH,GRAPHIC_HEIGHT,URL_ACTIVE, URL_INACTIVE) VALUES (4,'Trash',1,16,16,'trash_open.gif','trash_closed.gif');

INSERT INTO INV_LOCATION_TYPES (LOCATION_TYPE_ID,LOCATION_TYPE_NAME,GRAPHIC_ID_FK) VALUES (27,'Rack',2);

UPDATE INV_LOCATION_TYPES SET GRAPHIC_ID_FK=1 WHERE LOCATION_TYPE_ID IN (9,10,25,509);
UPDATE INV_LOCATION_TYPES SET GRAPHIC_ID_FK=2 WHERE LOCATION_TYPE_ID IN (27);
UPDATE INV_LOCATION_TYPES SET GRAPHIC_ID_FK=3 WHERE LOCATION_TYPE_ID IN (26);
UPDATE INV_LOCATION_TYPES SET GRAPHIC_ID_FK=4 WHERE LOCATION_TYPE_ID IN (502);

INSERT INTO INV_DOC_TYPES (DOC_TYPE_ID,TYPE_NAME) VALUES (1,'Batch Sample Request Receipt');
INSERT INTO INV_DOC_TYPES (DOC_TYPE_ID,TYPE_NAME) VALUES (2,'Batch Sample Worksheet');

INSERT INTO INV_ENUMERATION_SET (ESET_ID,ESET_NAME,ESET_TYPE_ID_FK) VALUES (9,'Batch Document Types',2);
INSERT INTO INV_ENUMERATION_SET (ESET_ID,ESET_NAME,ESET_TYPE_ID_FK) VALUES (10,'Organization Types',1);
-- INSERT INTO INV_ENUMERATION (ENUM_VALUE,ESET_ID_FK) VALUES ('Certificate of Testing',9);
-- INSERT INTO INV_ENUMERATION (ENUM_VALUE,ESET_ID_FK) VALUES ('Other',9);
INSERT INTO INV_ENUMERATION (ENUM_ID,ENUM_VALUE,ESET_ID_FK) VALUES (19,'Group',10);
INSERT INTO INV_ENUMERATION (ENUM_ID,ENUM_VALUE,ESET_ID_FK) VALUES (20,'Department',10);

INSERT INTO INV_CONTAINER_STATUS (CONTAINER_STATUS_ID,CONTAINER_STATUS_NAME,CONTAINER_STATUS_DESC) VALUES (23,'Requestable','');

-- INSERT DATA FOR BATCH REPORTS
INSERT INTO INV_REPORTTYPES (REPORTTYPE_ID,REPORTTYPEDESC) VALUES (8,'Batch Report');
INSERT INTO INV_REPORTS(ID,REPORTDISPLAYNAME,REPORTNAME,REPORTTYPE_ID) VALUES (13,'Batch Search Results Report 1','rptBatchSearchResults1',8);
INSERT INTO INV_REPORTS(ID,REPORTDISPLAYNAME,REPORTNAME,REPORTTYPE_ID) VALUES (14,'Batch Search Results Report 2','rptBatchSearchResults2',8);

COMMIT;
