prompt 
prompt Starting "pkg_Gui_Util_def.sql"...
prompt 
CREATE OR REPLACE PACKAGE REGDB."GUI_UTIL"
AS
  --Types
  TYPE CURSOR_TYPE IS REF CURSOR;
  TYPE FRAGMENT_IDS IS TABLE OF vw_fragment.fragmentid%type INDEX BY BINARY_INTEGER;
  /** System settings xml doc for Registration */
  VSystemSettings XMLTYPE;
  /** System setting: Gets the column name to sort the fragments grid */
  vFragmentsSortField VARCHAR2(200);

  --Procedures
  PROCEDURE GETPROJECTNAMEVALUELIST(O_RS OUT CURSOR_TYPE);
  PROCEDURE GETPREFIXNAMEVALUELIST (O_RS OUT CURSOR_TYPE);
  PROCEDURE GETACTIVECHEMISTNAMEVALUELIST (O_RS OUT CURSOR_TYPE);
  PROCEDURE GETCHEMISTNAMEVALUELIST (O_RS OUT CURSOR_TYPE);
  PROCEDURE GETFRAGMENTTYPESVALUELIST (O_RS OUT CURSOR_TYPE);
  PROCEDURE GETFRAGMENTSLIST (O_RS OUT CURSOR_TYPE);
  PROCEDURE GETRECORDSCONTAININGCOMPOUND(pCompoundId IN VW_COMPOUND.COMPOUNDID%type, O_RS OUT CURSOR_TYPE);
  PROCEDURE GETRECORDSCONTAININGSTRUCTURE(pStructureId IN VW_COMPOUND.STRUCTUREID%type, pExcludeNonStructureValues IN NUMBER, O_RS OUT CURSOR_TYPE);
  PROCEDURE getfragmentlistbyids(
    AIdList IN FRAGMENT_IDS
    , O_RS OUT CURSOR_TYPE
  );
  PROCEDURE GETMATCHEDFRAGMENTSLIST (
    AStructure IN CLOB
    , O_RS OUT CURSOR_TYPE
  );
  PROCEDURE GETPROJECTLIST (O_RS OUT CURSOR_TYPE);
  PROCEDURE GETACTIVEPROJECTLISTBYPERSONID (
    O_RS OUT CURSOR_TYPE
    , APersonID in Number
    , AType IN Char:='A'
  );
  PROCEDURE GETIDENTIFIERLIST (
    O_RS OUT CURSOR_TYPE
    , AType IN Char:='A' 
    , AActive IN Char:='T'
  );
  PROCEDURE GETSEQUENCELIST (
    O_RS OUT CURSOR_TYPE
    , ASeqTypeID in Number
  );
  PROCEDURE GETSEQUENCELISTBYPERSONID (
    O_RS OUT CURSOR_TYPE
    , ASeqTypeID in Number
    , APersonID in Number
  );
  PROCEDURE GETTEMPREGISTRIESCOUNT (ACount OUT NUMBER);
  PROCEDURE GETTEMPSUBMREGISTRIESCOUNT (ACount OUT NUMBER);
  PROCEDURE GETTEMPAPPROVEDREGISTRIESCOUNT (ACount OUT NUMBER);
  PROCEDURE GETPERMREGISTRIESCOUNT (ACount OUT NUMBER);
  PROCEDURE GETAPPROVEDREGISTRIESCOUNT (ACount OUT NUMBER);
  PROCEDURE GETDUPLICATEDCOMPOUNDCOUNT (ACount OUT NUMBER);
  PROCEDURE CHECKFRAGMENTUSED (FieldValue varchar ,  RecordCount out Number); 
END "GUI_UTIL";
/
