<%@ LANGUAGE=VBScript%>
<%Response.expires=0
'Copyright 1998-2001 CambridgeSoft Corporation All Rights Reserved
'DO NOT EDIT THIS FILE

if not dbkey <> "" then dbkey=request("dbname")

if Not Session("UserValidated" & dbkey) = 1 then  response.redirect "/" & Application("Appkey") & "/logged_out.asp"%>
<html>
<head>
<!--#INCLUDE VIRTUAL = "/cfserverasp/source/cows_func_js.asp"-->
<!--#INCLUDE FILE = "../../source/secure_nav.asp"-->



<!--#INCLUDE VIRTUAL = "/cfserverasp/source/search_func_vbs.asp"-->
<!--#INCLUDE FILE = "../../cs_security/admin_utils_vbs.asp"-->
<!--#INCLUDE FILE = "../../cs_security/admin_utils_js.js"-->


<script language="javascript">

function goAdminTables(manage_type, table_name,sql_string){

		actiontemp = action_form_path
		MainWindow.document.cows_input_form.sql_string.value = sql_string
		MainWindow.document.cows_input_form.action= actiontemp + "?dbname=<%=dbkey%>&formgroup=" + manage_type + "_form_group&dataaction=get_sql_string&sql_source=sql_string&base_table_name=" + table_name
		MainWindow.document.cows_input_form.submit()
}

function goAdminTables2(table_name,sql_string){
		actiontemp = action_form_path
		MainWindow.document.cows_input_form.sql_string.value = sql_string
		MainWindow.document.cows_input_form.action= actiontemp + "?dbname=<%=dbkey%>&formgroup=manage_tables_form_group&dataaction=get_sql_string&sql_source=sql_string&base_table_name=" + table_name
		MainWindow.document.cows_input_form.submit()
}

</script>

<%
privTable = Application("Priv_Table_Name")
dba_users_sql_string = getUsersListSQL("", dbkey, formgroup, privTable)
'roles_sql_string ="Select role_ID from security_roles where privilege
roles_sql_string = "Select role_ID from SECURITY_ROLES, PRIVILEGE_TABLES where Upper(privilege_table_name)=" & "'" & UCase(privTable) & "'" & " AND privilege_tables.privilege_table_ID = security_roles.privilege_table_int_ID"

people_sql_string = "Select person_id from people"
sites_sql_string = "Select site_id from sites"%>



</head>
<body <%=Application("BODY_BACKGROUND")%>>



<!--#INCLUDE FILE = "../../source/app_vbs.asp"-->
<!--#INCLUDE VIRTUAL = "/cfserverasp/source/header_vbs.asp"-->

<input type="hidden" name="sql_string" value>

<table width="373">




	<%if Session("Edit_USERS_Table" & dbkey) then%>

	<tr>
    <td align="left" width="220"><a href="javascript:goAdminTables('manage_users','dba_users',&quot;<%=dba_users_sql_string%>&quot;)"><img SRC="/<%=Application("AppKey")%>/graphics/usr_mgr_btn.gif" alt="add/edit users" BORDER="0"></a></td>
  </tr>

 <%end if%>

<tr>	

    <td align="left" width="220"><a href="javascript:goAdminTables('manage_roles','security_roles',&quot;<%=roles_sql_string%>&quot;)"><img SRC="/<%=Application("AppKey")%>/graphics/manage_roles_btn.gif" BORDER="0" alt="add/edit roles"></a></td>
  </tr>
<%if CBool(Application("ShowSecTabinUsrMgr")) = True then %>
<%if (Session("Edit_People_Table" & dbkey)OR Session("ADD_People_Table" & dbkey) OR Session("DElete_People_Table" & dbkey)) then%>

  <tr>
    <td align="left" width="220"><a href="javascript:goAdminTables2('people','<%=people_sql_string%>')"><img SRC="/<%=Application("AppKey")%>/graphics/manage_people_btn.gif" BORDER="0" alt="edit/add to people table"></a></td>
  </tr>
   <%end if%>
   
   <%if Session("Edit_Sites_Table" & dbkey) = true  AND CBool(Application("Sites_Used")) = True then%>

  <tr>
    <td align="left" width="220"><a href="javascript:goAdminTables2('sites','<%=sites_sql_string%>')"><img SRC="/<%=Application("AppKey")%>/graphics/manage_sites_btn.gif" BORDER="0" alt="edit/add to sites table"></a></td>
  </tr>
   <%end if
   end if%>



   
</table>




<!--#INCLUDE VIRTUAL = "/cfserverasp/source/input_form_footer_vbs.asp"-->

</body>
</html>
