--Copyright 1999-2010 CambridgeSoft Corporation. All rights reserved

prompt 
prompt Starting "Update_10.0_to_11.0.1.sql"...
prompt 


--#########################################################
--DROP OBJECTS
--#########################################################

prompt Dropping objects...

DECLARE
    PROCEDURE DropTrigger(AObject_Name VARCHAR2) IS
        LCount NUMBER;
    BEGIN
        SELECT COUNT(1) INTO LCount  FROM USER_OBJECTS  WHERE Object_Name=AObject_Name;
        
        IF LCount > 0 THEN
            EXECUTE IMMEDIATE 'DROP TRIGGER '||AObject_Name;
        END IF;
    END;
    
BEGIN
    DropTrigger('TRG_UTILIATIONS');
    DropTrigger('TRG_TEMP_MOL_ID');
    DropTrigger('TRG_SOLVATES');
    DropTrigger('TRG_SALTS');
    DropTrigger('TRG_BATCH_PROJECTS');
    DropTrigger('"BIN$itMKpEx4TLO8IGhC/F2C1g==$0"');
END;
/

DROP TABLE STRUCTURE_MIXTURE;

DROP TABLE DUPLICATES;

ALTER TABLE PROJECTS DROP COLUMN ACTIVE;


--#########################################################
--CREATE TABLES
--######################################################### 


CREATE TABLE FRAGMENTTYPE(ID NUMBER(8,0) ,DESCRIPTION VARCHAR2(255));

CREATE TABLE  HISTORY (
	ID NUMBER(8,0) not null,
	NAME VARCHAR2(100) null, 
	DESCRIPTION VARCHAR2(500), 
	DATECREATED DATE,
	constraint PK_HISTORY_ID 
		primary key (ID) USING INDEX TABLESPACE &&indexTableSpaceName);

CREATE TABLE BATCH_PROJECT 
(
	ID         NUMBER(8,0),
	BATCHID    NUMBER(8,0),
	PROJECTID  NUMBER(8,0),
	ORDERINDEX NUMBER(8,0),  --Version 11.0.1
	CONSTRAINT BATCH_PROJECT_PK 
		PRIMARY KEY (ID) USING INDEX TABLESPACE &&indexTableSpaceName
);

CREATE TABLE MIXTURE_COMPONENT (
	ID NUMBER(8,0) ,
	MIXTRUREID NUMBER(8,0),
	COMPOUNDID NUMBER(8,0)
);

CREATE TABLE COMPOUND_FRAGMENT (
	ID NUMBER(8,0) ,
	COMPOUNDID NUMBER(8,0), 
	FRAGMENTID NUMBER(8,0),
	EQUIVALENTS NUMBER
);

CREATE TABLE BATCH_IDENTIFIER 
(
    ID           NUMBER(8,0),
    TYPE         NUMBER(8,0), 
    BATCHID      NUMBER(8,0),
    VALUE        VARCHAR2(2000 Byte),
    ORDERINDEX   NUMBER(8,0),
    CONSTRAINT BATCH_IDENTIFIER_PK 
        PRIMARY KEY (ID) USING INDEX TABLESPACE &&indexTableSpaceName
);

CREATE TABLE BATCHCOMPONENT 
(
	ID                 NUMBER(8,0), 
	BATCHID            NUMBER(8,0), 
	MIXTURECOMPONENTID NUMBER(8,0),
	ORDERINDEX         NUMBER(8,0),  
	CONSTRAINT BATCHCOMPONENT_PK PRIMARY KEY (ID) USING INDEX TABLESPACE &&indexTableSpaceName
);


CREATE TABLE COEOBJECTTYPE(
	ID NUMBER(4) NOT NULL,
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	CONSTRAINT PK_COEOBJECTTYPE PRIMARY KEY(ID) USING INDEX TABLESPACE T_REGDB_INDEX);

CREATE TABLE COEOBJECTCONFIG (
	ID NUMBER(4) NOT NULL,
	OBJECTTYPEID NUMBER(10),  
	XML CLOB ,
	CONSTRAINT PK_COEOBJECTCONFIG PRIMARY KEY(ID) USING INDEX TABLESPACE T_REGDB_INDEX);

CREATE TABLE TEMPORARY_BATCH 
(
	TEMPBATCHID               NUMBER(8),
	BATCHNUMBER               NUMBER(5),
	PROJECTXML                CLOB,
        IDENTIFIERXML             CLOB,
	DATELASTMODIFIED          DATE,
	DATECREATED               DATE,
	PERSONCREATED             NUMBER(8),
	STATUSID                  NUMBER(8),
        StructureAggregation      CLOB,
	SequenceID 	          NUMBER(8,0), --Version 11.0.1
	ProjectXMLBatch           CLOB,        --Version 11.0.1
	IdentifierXMLBatch        CLOB,        --Version 11.0.1
	CONSTRAINT PK_TEMPBATCHID
		PRIMARY KEY (TEMPBATCHID) USING INDEX TABLESPACE &&indexTableSpaceName
);

CREATE TABLE TEMPORARY_COMPOUND
(
  TEMPCOMPOUNDID            NUMBER(8) NOT NULL,
  TEMPBATCHID               NUMBER(8),
  FORMULAWEIGHT             NUMBER,
  MOLECULARFORMULA          VARCHAR2(200 BYTE),
  PERSONCREATED             NUMBER(8),
  DATELASTMODIFIED          DATE,
  DATECREATED               DATE,
  PROJECTXML                CLOB,
  BASE64_CDX                CLOB,
  FRAGMENTXML               CLOB,
  BATCHCOMPFRAGMENTXML	    CLOB,
  IDENTIFIERXML             CLOB,
  TAG		            VARCHAR2(50),
  STRUCTUREID               NUMBER(8),
  REGID                     NUMBER(8),
  NORMALIZEDSTRUCTURE       CLOB,
  USENORMALIZATION          NCHAR(1),  
  SequenceID 	            NUMBER(8,0), --Version 11.0.1
  CONSTRAINT PK_TEMPCOMPOUNDID PRIMARY KEY (TEMPCOMPOUNDID) USING INDEX TABLESPACE &&indexTableSpaceName	
); 

CREATE TABLE PICKLISTDOMAIN
(
  ID                        NUMBER(8,0),
  DESCRIPTION               VARCHAR2(255) CONSTRAINT UK_PICKLISTDOMAIN_DESCRIPTION UNIQUE,
  Ext_Table		    VARCHAR2(100)	NULL, --Version 11.0.1
  Ext_ID_Col		    VARCHAR2(30)	NULL, --Version 11.0.1
  Ext_Display_Col	    VARCHAR2(30)	NULL, --Version 11.0.1
  Ext_SQL_Filter	    VARCHAR2(2000)	NULL, --Version 11.0.1	
  CONSTRAINT PK_PICKLISTDOMAIN PRIMARY KEY (ID) USING INDEX TABLESPACE &&indexTableSpaceName
);

CREATE TABLE PICKLIST
(
  ID               NUMBER(8,0) ,
  PICKLISTDOMAINID NUMBER(8,0),
  PICKLISTVALUE    VARCHAR2(1000),
  CONSTRAINT PK_PICKLIST PRIMARY KEY (ID) USING INDEX TABLESPACE &&indexTableSpaceName
);

CREATE TABLE BATCHCOMPONENTFRAGMENT
(
  ID                 NUMBER(8,0) ,
  BATCHCOMPONENTID   NUMBER(8,0),
  COMPOUNDFRAGMENTID NUMBER(8,0), 
  EQUIVALENT         NUMBER,
  ORDERINDEX         NUMBER(8,0),
  CONSTRAINT BATCHCOMPONENTFRAGMENT_PK PRIMARY KEY (ID) USING INDEX TABLESPACE &&indexTableSpaceName
);

cREATE TABLE REG_NUMBERS_PROJECT
(
  ID         NUMBER(8,0) ,
  REGID      NUMBER(8,0),
  PROJECTID  NUMBER(8,0),
  ORDERINDEX NUMBER(8,0), --Version 11.0.1
  CONSTRAINT REG_NUMBERS_PROJECT_PK PRIMARY KEY (ID) USING INDEX TABLESPACE &&indexTableSpaceName
);

CREATE TABLE DUPLICATES
(
  ID  NUMBER(8),
  RegNumber VARCHAR2(50),
  RegNumberDuplicated VARCHAR2(50),
  PersonID NUMBER(8), 
  Created DATE
);


CREATE TABLE LOG_BULKREGISTRATION_ID
(
  LOG_ID            INTEGER,
  DUPLICATE_ACTION  VARCHAR2(20 BYTE)           NOT NULL,
  DESCRIPTION       VARCHAR2(250 BYTE),
  USER_ID           VARCHAR2(30 BYTE),
  DATETIME_STAMP    DATE,
  CONSTRAINT LOG_BULKREGISTRATION_ID_PK PRIMARY KEY (LOG_ID) USING INDEX TABLESPACE &&indexTableSpaceName
);

CREATE TABLE LOG_BULKREGISTRATION
(
  ID               INTEGER,
  LOG_ID           INTEGER,
  TEMP_ID          INTEGER,
  ACTION           VARCHAR2(1 BYTE),
  REG_NUMBER       VARCHAR2(10 BYTE),
  BATCH_NUMBER     NUMBER,
  COMMENTS         VARCHAR2(500 BYTE),
  CONSTRAINT LOG_BULKREGISTRATION_PK PRIMARY KEY (ID) USING INDEX TABLESPACE &&indexTableSpaceName
  -- Commented out as DataLoader provides no TEMP_ID.
  -- CONSTRAINT LOG_BULKREGISTRATION_PK PRIMARY KEY (LOG_ID, TEMP_ID) USING INDEX TABLESPACE &&indexTableSpaceName
);

CREATE TABLE PREFIX_USER 
(
  PERSON_ID NUMBER(8,0),
  SEQUENCE_ID NUMBER(8,0)
)
;

CREATE TABLE Log
(
  ID NUMBER(8),
  LogDate DATE DEFAULT SYSDATE, 
  LogUser VARCHAR(30) DEFAULT USER, 
  PC VARCHAR(30) DEFAULT USERENV('TERMINAL'),
  LogProcedure CLOB,
  LogComment CLOB
);


--#########################################################
--ALTER TABLES
--#########################################################


ALTER TABLE SEQUENCE ADD DUP_CHECK_LOCAL NUMBER(1) DEFAULT 0;
ALTER TABLE SEQUENCE ADD SUFFIX VARCHAR2(150);
ALTER TABLE SEQUENCE ADD SUFFIXDELIMITER VARCHAR2(1);
ALTER TABLE SEQUENCE ADD OBJECTTYPE VARCHAR2(20) NULL;
ALTER TABLE SEQUENCE ADD EXAMPLE VARCHAR2(50) NULL;
ALTER TABLE SEQUENCE ADD SALTSUFFIXTYPE VARCHAR2(30) NULL;
ALTER TABLE SEQUENCE ADD SITEID NUMBER(8);
ALTER TABLE SEQUENCE ADD TYPE NCHAR(1);
ALTER TABLE SEQUENCE ADD BATCHDELIMETER VARCHAR2(1);

ALTER TABLE SEQUENCE ADD REGNUMBER_LENGTH NUMBER(3) DEFAULT 6;

ALTER TABLE PROJECTS ADD DESCRIPTION VARCHAR2(500);
ALTER TABLE PROJECTS ADD TYPE NCHAR(1);

ALTER TABLE PROJECTS ADD ACTIVE NCHAR(1);

ALTER TABLE STRUCTURES ADD StructureFormat VARCHAR2(150);  
ALTER TABLE STRUCTURES ADD Structure CLOB;

ALTER TABLE MIXTURES ADD REGID NUMBER(8);
ALTER TABLE MIXTURES ADD CONSTRAINT MIXTURES_REG_NUMBERS  FOREIGN KEY (REGID) REFERENCES REG_NUMBERS (REG_ID);
ALTER TABLE MIXTURES ADD NAME VARCHAR2(150);
ALTER TABLE MIXTURES ADD CREATED DATE;
ALTER TABLE MIXTURES ADD MODIFIED DATE;
ALTER TABLE MIXTURES ADD PERSONCREATED NUMBER(8);
ALTER TABLE MIXTURES ADD STRUCTUREAGGREGATION CLOB;
ALTER TABLE MIXTURES ADD APPROVED VARCHAR2(10) DEFAULT 'NotSet';


ALTER TABLE FRAGMENTTYPE ADD (
	CONSTRAINT PK_FRAGMENTTYPE
	PRIMARY KEY (ID)
	USING INDEX 
	TABLESPACE T_REGDB_INDEX);

ALTER TABLE FRAGMENTS ADD STRUCTUREFORMAT VARCHAR2(150);
ALTER TABLE FRAGMENTS ADD CODE VARCHAR2(10);
ALTER TABLE FRAGMENTS ADD DESCRIPTION VARCHAR2(250);
ALTER TABLE FRAGMENTS ADD FRAGMENTTYPEID NUMBER(8,0);
ALTER TABLE FRAGMENTS ADD MOLWEIGHT NUMBER;
ALTER TABLE FRAGMENTS ADD FORMULA VARCHAR2(200);
ALTER TABLE FRAGMENTS ADD CREATED DATE;
ALTER TABLE FRAGMENTS ADD MODIFIED DATE;
ALTER TABLE FRAGMENTS ADD CONSTRAINT FRAGMENTTYPE_FRAGMENTS FOREIGN KEY(FragmentTypeID) 
REFERENCES FRAGMENTTYPE(ID);

ALTER TABLE NOTEBOOKS ADD DESCRIPTION VARCHAR2(200);

ALTER TABLE NOTEBOOKS MODIFY USER_CODE NULL;

ALTER TABLE BATCH_PROJECT ADD CONSTRAINT BATCH_PROJECT_BATCHES FOREIGN KEY(BATCHID) 
REFERENCES BATCHES (BATCH_INTERNAL_ID);

ALTER TABLE BATCH_PROJECT ADD CONSTRAINT BATCH_PROJECT_PROJECTS FOREIGN KEY(PROJECTID) 
REFERENCES PROJECTS (PROJECT_INTERNAL_ID);

ALTER TABLE MIXTURE_COMPONENT ADD (CONSTRAINT MIXTURE_COMPONENT_PK PRIMARY KEY (ID) USING INDEX TABLESPACE T_REGDB_INDEX);

ALTER TABLE MIXTURE_COMPONENT ADD (
	CONSTRAINT MIXTURE_COMPONENT_MIXTURE  FOREIGN KEY (MIXTRUREID) REFERENCES MIXTURES (MIX_INTERNAL_ID),
	CONSTRAINT MIXTURE_COMPONENT_COMPOUND FOREIGN KEY (COMPOUNDID) REFERENCES COMPOUND_MOLECULE (CPD_DATABASE_COUNTER));


ALTER TABLE COMPOUND_FRAGMENT ADD (
	CONSTRAINT COMPOUND_FRAGMENT_PK PRIMARY KEY (ID) USING INDEX TABLESPACE T_REGDB_INDEX);

ALTER TABLE COMPOUND_FRAGMENT ADD (
	CONSTRAINT COMPOUND_FRAGMENT_FRAGMENTS  FOREIGN KEY (FRAGMENTID) REFERENCES FRAGMENTS (FRAGMENT_ID),
	CONSTRAINT COMPOUND_FRAGMENT_COMP_MOL FOREIGN KEY (COMPOUNDID) REFERENCES COMPOUND_MOLECULE (CPD_DATABASE_COUNTER));

ALTER TABLE REG_NUMBERS ADD Type NCHAR(1);
--ALTER TABLE REG_NUMBERS DROP COLUMN REG_NUMBER;
ALTER TABLE REG_NUMBERS ADD SITEID NUMBER(8);

ALTER TABLE COMPOUND_MOLECULE ADD StructureID NUMBER(8,0);
ALTER TABLE COMPOUND_MOLECULE ADD CONSTRAINT COMPOUND_MOLECULE_STRUCTURES FOREIGN KEY(STRUCTUREID ) REFERENCES STRUCTURES(CPD_INTERNAL_ID);
ALTER TABLE COMPOUND_MOLECULE ADD REGID NUMBER(8,0);
ALTER TABLE COMPOUND_MOLECULE ADD FORMULAWEIGHT NUMBER;
ALTER TABLE COMPOUND_MOLECULE ADD MOLECULARFORMULA VARCHAR2(200);
ALTER TABLE COMPOUND_MOLECULE ADD DATECREATED DATE;
ALTER TABLE COMPOUND_MOLECULE ADD NORMALIZEDSTRUCTURE CLOB;
ALTER TABLE COMPOUND_MOLECULE ADD USENORMALIZATION NCHAR(1);
ALTER TABLE COMPOUND_MOLECULE ADD Tag VARCHAR2(50);
ALTER TABLE COMPOUND_MOLECULE ADD PersonCreated NUMBER(8);
ALTER TABLE COMPOUND_MOLECULE ADD PersonRegistered NUMBER(8);
 
ALTER TABLE ALT_IDS ADD ORDERINDEX NUMBER(8);
ALTER TABLE ALT_IDS MODIFY IDENTIFIER VARCHAR2 (2000);

ALTER TABLE IDENTIFIERS ADD Active NCHAR(1) NULL;    
ALTER TABLE IDENTIFIERS ADD Name VARCHAR2(200);
ALTER TABLE IDENTIFIERS ADD Type NCHAR(1);

ALTER TABLE IDENTIFIERS ADD 
CONSTRAINT UK_IDENTIFIERS_IDENTIFIER_TYPE
 UNIQUE (IDENTIFIER_TYPE);

ALTER TABLE BATCH_IDENTIFIER ADD CONSTRAINT BATCH_IDENTIFIER_BATCHES_FK foreign key (BATCHID) 
REFERENCES BATCHES (BATCH_INTERNAL_ID);

ALTER TABLE BATCH_IDENTIFIER ADD CONSTRAINT BATCH_IDENTIFIER_IDENTIFIER_FK FOREIGN KEY (TYPE) REFERENCES IDENTIFIERS (IDENTIFIER_TYPE); 

ALTER TABLE ALT_IDS ADD 
CONSTRAINT FK_ALT_IDS_IDENTIFIERS
 FOREIGN KEY (IDENTIFIER_TYPE)
 REFERENCES REGDB.IDENTIFIERS (IDENTIFIER_TYPE);Ç

ALTER TABLE BATCHES ADD TEMPBATCHID NUMBER(8);
ALTER TABLE BATCHES ADD DATECREATED DATE;
ALTER TABLE BATCHES ADD STATUS_ID NUMBER(8,0) NULL;
ALTER TABLE BATCHES ADD FULLREGNUMBER VARCHAR2(50) NULL;

ALTER TABLE COEOBJECTCONFIG ADD (
  CONSTRAINT FK_COEOBJECTCONFIG_TYPE 
 FOREIGN KEY (OBJECTTYPEID) 
 REFERENCES COEOBJECTTYPE (ID));

ALTER TABLE BATCHCOMPONENT ADD (
  CONSTRAINT BATCHCOMPONENT_BATCH  FOREIGN KEY (BATCHID) REFERENCES BATCHES (BATCH_INTERNAL_ID),
  CONSTRAINT BATCHCOMPONENT_MIX_COMP FOREIGN KEY (MIXTURECOMPONENTID) REFERENCES MIXTURE_COMPONENT (ID));

ALTER TABLE TEMPORARY_COMPOUND ADD CONSTRAINT TEMP_COMP_TEMPORARY_BATCH FOREIGN KEY (TEMPBATCHID) 
REFERENCES TEMPORARY_BATCH (TEMPBATCHID); 


ALTER TABLE PICKLIST ADD (
  CONSTRAINT PICKLIST_PICKLISTDOMAIN  FOREIGN KEY (PICKLISTDOMAINID) REFERENCES PICKLISTDOMAIN (ID));

ALTER TABLE BATCHCOMPONENTFRAGMENT  ADD (
  CONSTRAINT BATCHCOMPFRAGMENT_BATCOM FOREIGN KEY (BATCHCOMPONENTID) REFERENCES BATCHCOMPONENT(ID),
  CONSTRAINT BATCHCOMPFRAGMENT_COMFRA FOREIGN KEY (COMPOUNDFRAGMENTID) REFERENCES COMPOUND_FRAGMENT(ID));

ALTER TABLE REG_NUMBERS_PROJECT ADD CONSTRAINT REGNUMPROJ_PROJECTS FOREIGN KEY (PROJECTID) 
REFERENCES PROJECTS (PROJECT_INTERNAL_ID);

ALTER TABLE REG_NUMBERS_PROJECT ADD CONSTRAINT REGNUMPROJ_REGNUMBERS_FK  FOREIGN KEY (REGID) 
REFERENCES REG_NUMBERS (REG_ID);

ALTER TABLE DUPLICATES ADD (CONSTRAINT DUPLICATES_PK PRIMARY KEY (ID) USING INDEX TABLESPACE T_REGDB_INDEX);

ALTER TABLE LOG_BULKREGISTRATION ADD CONSTRAINT LOG_BULKREGISTRATION_R01 FOREIGN KEY (LOG_ID) 
REFERENCES LOG_BULKREGISTRATION_ID (LOG_ID);

ALTER TABLE Log ADD CONSTRAINT LogPK PRIMARY KEY (ID) USING INDEX TABLESPACE T_REGDB_INDEX;

--#########################################################
--CREATE SEQUENCES
--#########################################################  

CREATE SEQUENCE SEQ_FRAGMENTTYPE INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SEQ_HISTORY INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SEQ_MIXTURE INCREMENT By 1 START With 1;

CREATE SEQUENCE SEQ_BATCH_PROJECT INCREMENT By 1 START With 1;

CREATE SEQUENCE SEQ_MIXTURE_COMPONENT INCREMENT By 1 START With 1;

CREATE SEQUENCE SEQ_COMPOUND_FRAGMENT INCREMENT By 1 START With 1;

CREATE SEQUENCE SEQ_BATCH_IDENTIFIER INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SEQ_BATCHCOMPONENT INCREMENT By 1 START With 1;

CREATE SEQUENCE SEQ_TEMPORARY_BATCH INCREMENT By 1 START With 1;

CREATE SEQUENCE SEQ_TEMPORARY_COMPOUND INCREMENT By 1 START With 1;

CREATE SEQUENCE SEQ_BATCHCOMPONENTFRAGMENT INCREMENT By 1 START With 1;  

CREATE SEQUENCE SEQ_REG_NUMBERS_PROJECT INCREMENT By 1 START With 1; 

CREATE SEQUENCE SEQ_DUPLICATES INCREMENT By 1 START With 1;  

CREATE SEQUENCE SEQ_LOG_BULKREGISTRATION_ID INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SEQ_LOG_BULKREGISTRATION INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE LOGSEQ INCREMENT BY 1 START WITH 1;

--#########################################################
--UPDATE ROWS
--#########################################################

UPDATE SEQUENCE SET BATCHDELIMETER = PREFIX_DELIMITER;
UPDATE SEQUENCE SET SUFFIXDELIMITER = PREFIX_DELIMITER;
UPDATE SEQUENCE SET TYPE = 'R';
COMMIT;

UPDATE SEQUENCE SET ACTIVE = NULL;
ALTER TABLE SEQUENCE MODIFY ACTIVE NCHAR (1);
UPDATE SEQUENCE SET ACTIVE = 'T',EXAMPLE='AB-000001';
COMMIT;

UPDATE SEQUENCE SET  REGNUMBER_LENGTH=ROOT_NUMBER_LENGTH;
ALTER TABLE SEQUENCE DROP COLUMN ROOT_NUMBER_LENGTH;
COMMIT;

UPDATE PROJECTS SET DESCRIPTION=PROJECT_NAME,ACTIVE='T';
COMMIT;

ALTER TABLE NOTEBOOKS MODIFY ACTIVE NULL;
UPDATE NOTEBOOKS SET ACTIVE = NULL;
ALTER TABLE NOTEBOOKS MODIFY ACTIVE NCHAR (1);
UPDATE NOTEBOOKS SET ACTIVE = 'T';
ALTER TABLE NOTEBOOKS MODIFY ACTIVE NOT NULL;

UPDATE IDENTIFIERS SET Active='T',Name =IDENTIFIER_DESCRIPTOR,TYPE='R';

COMMIT;


--#########################################################
--CREATE INDEX
--#########################################################

CREATE INDEX Batch_Project_OrderIndex_IX ON BATCH_PROJECT(Orderindex ASC) TABLESPACE &&indexTableSpaceName;

CREATE INDEX INDEX_CMPDMOL_REGID ON COMPOUND_MOLECULE ( REGID ASC) TABLESPACE &&indexTableSpaceName;

CREATE INDEX ALT_IDS_OrderIndex_IX ON ALT_IDS(Orderindex ASC) TABLESPACE &&indexTableSpaceName;

CREATE INDEX Batch_Identifier_OrderIndex_IX ON BATCH_IDENTIFIER(Orderindex ASC) TABLESPACE &&indexTableSpaceName;

CREATE INDEX BatchComponent_OrderIndex_IX ON BATCHCOMPONENT(Orderindex ASC) TABLESPACE &&indexTableSpaceName;

CREATE INDEX TemporaryBatchSequenceIDx_IX ON TEMPORARY_BATCH(sequenceID ASC) TABLESPACE &&indexTableSpaceName;

CREATE INDEX INDEX_TEMP_COMP_TEMPBATCHID ON TEMPORARY_COMPOUND(TEMPBATCHID) TABLESPACE &&indexTableSpaceName;

CREATE INDEX TemporaryCompoundSequenceID_IX ON TEMPORARY_COMPOUND(sequenceID ASC) TABLESPACE &&indexTableSpaceName;

CREATE INDEX BatchCompFrag_OrderIndex_IX ON BATCHCOMPONENTFRAGMENT(Orderindex ASC) TABLESPACE &&indexTableSpaceName;

CREATE INDEX RegNumberproject_OrderIndex_IX ON REG_NUMBERS_PROJECT(Orderindex ASC) TABLESPACE &&indexTableSpaceName;

CREATE INDEX DuplicatesRegNumber_IX ON DUPLICATES (RegNumber) LOGGING NOPARALLEL;

CREATE INDEX DuplicatesRegNumberDupl_IX ON DUPLICATES (RegNumberDuplicated) LOGGING NOPARALLEL;

prompt Creating chemical structure indexes...

--The following procedure is created, used and dropped. If you use a block PL/SQL then you will not able show error messages in the file log.

CREATE OR REPLACE PROCEDURE createCartridgeIndex(iName IN varchar2, tName IN varchar2, fName IN varchar2) IS
	n NUMBER;
BEGIN
	select count(*) into n from user_indexes where Upper(index_name) = iName AND Upper(table_owner)= '&&schemaName';
	if n = 1 then
		execute immediate 'DROP INDEX '||iName||' force';
	end if;
	execute immediate 'CREATE INDEX '||iName|| ' ON ' || tName || '('||fName||')
		indexType is cscartridge.moleculeindextype
		PARAMETERS(''TABLESPACE=&&cscartTableSpaceName,FULLEXACT=INDEX'')';
END createCartridgeIndex;
/

exec createCartridgeIndex('MX', 'STRUCTURES', 'BASE64_CDX');

exec createCartridgeIndex('MX2', 'TEMPORARY_COMPOUND', 'BASE64_CDX');

exec createCartridgeIndex('MX3', 'MIXTURES', 'STRUCTUREAGGREGATION');

DROP PROCEDURE createCartridgeIndex;

--#########################################################
--TRIGGERS
--#########################################################

prompt Creating triggers...

DROP TRIGGER TRG_REG_NUMBERS;

DROP TRIGGER TRG_COMPOUND_MOLECULE;

DROP TRIGGER TRG_BATCHES;

DROP TRIGGER TRG_TEMPORARY_STRUCTURES;

CREATE OR REPLACE TRIGGER TRG_BATCH_PROJECT
BEFORE INSERT
ON BATCH_PROJECT 
FOR EACH ROW
BEGIN
 SELECT SEQ_BATCH_PROJECT.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_BATCH_IDENTIFIER
BEFORE INSERT ON BATCH_IDENTIFIER FOR EACH ROW
BEGIN
  SELECT SEQ_BATCH_IDENTIFIER.NEXTVAL INTO :NEW.ID  FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_BATCHCOMPONENTFRAGMENT 
BEFORE INSERT
ON BATCHCOMPONENTFRAGMENT  
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
 SELECT SEQ_BATCHCOMPONENTFRAGMENT .NEXTVAL INTO :NEW.ID FROM DUAL;
END TRG_BATCHCOMPONENTFRAGMENT ;
/

CREATE OR REPLACE TRIGGER TRG_REG_NUMBERS_PROJECT
BEFORE INSERT
ON  REG_NUMBERS_PROJECT 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
 SELECT SEQ_REG_NUMBERS_PROJECT.NEXTVAL INTO :NEW.ID FROM DUAL;
END TRG_REG_NUMBERS_PROJECT;
/

CREATE OR REPLACE TRIGGER TRG_DUPLICATES
BEFORE INSERT
ON  DUPLICATES
FOR EACH ROW
BEGIN
 SELECT SEQ_DUPLICATES.NEXTVAL INTO :NEW.ID FROM DUAL;
END TRG_DUPLICATES;
/

CREATE OR REPLACE TRIGGER TRG_LOG_BULKREGISTRATION_ID
BEFORE INSERT ON LOG_BULKREGISTRATION_ID
FOR EACH ROW
BEGIN
 SELECT SEQ_LOG_BULKREGISTRATION_ID.NEXTVAL INTO :NEW.LOG_ID  FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_LOG_BULKREGISTRATION
BEFORE INSERT ON LOG_BULKREGISTRATION
FOR EACH ROW
BEGIN
 SELECT SEQ_LOG_BULKREGISTRATION.NEXTVAL INTO :NEW.ID  FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_LOG_BULKREGISTRATION
BEFORE INSERT ON LOG_BULKREGISTRATION
FOR EACH ROW
BEGIN
 SELECT SEQ_LOG_BULKREGISTRATION.NEXTVAL INTO :NEW.ID  FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER LogTrg
  BEFORE INSERT ON Log
  FOR EACH ROW
BEGIN
  SELECT LogSeq.NEXTVAL INTO :NEW.ID  FROM DUAL;
END;
/

--#########################################################
--CREATE VIEWS
--#########################################################

--Version 11

CREATE OR REPLACE NOFORCE VIEW VW_Sequence
	(SequenceID,RegNumberLength, Prefix, PrefixDelimiter,Suffix,SuffixDelimiter,SaltSuffixType,BatchDelimiter,NextInSequence,Example,ACTIVE,TYPE,SITEID) AS 
	SELECT SEQUENCE_ID,REGNUMBER_LENGTH,PREFIX,PREFIX_DELIMITER,SUFFIX,SUFFIXDELIMITER,SALTSUFFIXTYPE,BATCHDELIMETER,NEXT_IN_SEQUENCE,EXAMPLE,ACTIVE,TYPE,SITEID FROM SEQUENCE;
 
CREATE OR REPLACE NOFORCE VIEW VW_Project 
	(ProjectID,Name,Active,Description, Type) AS 
	SELECT PROJECT_INTERNAL_ID,PROJECT_NAME,ACTIVE,DESCRIPTION,TYPE FROM PROJECTS;

CREATE OR REPLACE NOFORCE VIEW VW_Structure 
	(StructureID,StructureFormat,Structure) AS 
	SELECT CPD_INTERNAL_ID,StructureFormat,BASE64_CDX FROM STRUCTURES;

CREATE OR REPLACE NOFORCE VIEW VW_FragmentType 
	(ID,Description) AS 
	SELECT ID,Description FROM FragmentType;

CREATE OR REPLACE NOFORCE VIEW VW_Fragment 
        (FragmentID,Code,Description,FragmentTypeID,MolWeight,Formula,Created,Modified,Structure,StructureFormat) AS
        SELECT FRAGMENT_ID,CODE,DESCRIPTION,FRAGMENTTYPEID,MOLWEIGHT,FORMULA,CREATED,MODIFIED,BASE64_CDX,STRUCTUREFORMAT FROM FRAGMENTS;

CREATE OR REPLACE NOFORCE VIEW VW_Mixture 
	(MixtureID,RegID,Name,Created,Modified,PERSONCREATED,StructureAggregation,Approved  ) AS 
	SELECT MIX_INTERNAL_ID,REGID,NAME,CREATED,MODIFIED,PERSONCREATED,STRUCTUREAGGREGATION,APPROVED FROM MIXTURES;

CREATE OR REPLACE NOFORCE VIEW VW_Notebook 
	(NoteBookID,Name,Description,Active) AS 
	SELECT NOTEBOOK_NUMBER,NOTEBOOK_NAME,DESCRIPTION,ACTIVE FROM NOTEBOOKS;

CREATE OR REPLACE NOFORCE VIEW VW_Batch_Project 
	(ID,BatchID,ProjectID,OrderIndex) AS 
	SELECT ID,BATCHID,PROJECTID,ORDERINDEX FROM BATCH_PROJECT;

CREATE OR REPLACE NOFORCE VIEW VW_Mixture_Component 
	(MixtureComponentID,MixtureID,CompoundID) AS 
	SELECT ID,MIXTRUREID,COMPOUNDID FROM MIXTURE_COMPONENT;

CREATE OR REPLACE NOFORCE VIEW VW_Compound_Fragment 
	(ID,CompoundID,FragmentID,Equivalents) AS
	SELECT ID,COMPOUNDID,FRAGMENTID,EQUIVALENTS FROM COMPOUND_FRAGMENT;
  
CREATE OR REPLACE NOFORCE VIEW VW_RegistryNumber 
	(RegID,SequenceID,SequenceNumber,RegNumber,PersonRegistered,DateCreated) AS 
	SELECT REG_ID,SEQUENCE_INTERNAL_ID,SEQUENCE_NUMBER,REG_NUMBER,REGISTRAR_PERSON_ID,REGISTRY_DATE FROM REG_NUMBERS;

CREATE OR REPLACE NOFORCE VIEW VW_Compound_Identifier 
	(ID,Type,RegID,Value,OrderIndex) AS 
	SELECT ID,IDENTIFIER_TYPE,REG_INTERNAL_ID,IDENTIFIER,ORDERINDEX FROM ALT_IDS;
    
CREATE OR REPLACE NOFORCE VIEW VW_IdentifierType 
	(ID,Name,Description,Type,Active) AS 
	SELECT IDENTIFIER_TYPE,NAME,IDENTIFIER_DESCRIPTOR,TYPE,ACTIVE FROM IDENTIFIERS;

CREATE OR REPLACE NOFORCE VIEW VW_BatchComponent 
	(ID,BatchID,MixtureComponentID,OrderIndex) AS
	SELECT ID,BATCHID,MIXTURECOMPONENTID,ORDERINDEX FROM BATCHCOMPONENT;

CREATE OR REPLACE NOFORCE VIEW VW_PickListDomain
	(ID,Description, Ext_Table, Ext_ID_Col, Ext_Display_Col, Ext_SQL_Filter ) AS 
	SELECT ID,Description, Ext_Table, Ext_ID_Col, Ext_Display_Col, Ext_SQL_Filter FROM PickListDomain;

CREATE OR REPLACE NOFORCE VIEW VW_PickList 
	(ID,PickListDomain,PickListValue) AS 
	SELECT ID,PickListDomainId,PickListValue FROM PickList;

CREATE OR REPLACE NOFORCE VIEW VW_BatchComponentFragment 
	(ID,BatchComponentID,CompoundFragmentID,Equivalent,OrderIndex) AS 
	SELECT ID,BATCHCOMPONENTID,COMPOUNDFRAGMENTID,EQUIVALENT,ORDERINDEX  FROM BATCHCOMPONENTFRAGMENT;

CREATE OR REPLACE NOFORCE VIEW VW_PeopleProject 
	(PersonID,ProjectID) AS 
	SELECT PERSON_ID,PROJECT_ID FROM PEOPLE_PROJECT;

CREATE OR REPLACE NOFORCE VIEW VW_RegistryNumber_Project 
	(ID,RegID,ProjectID,OrderIndex) AS 
	SELECT ID,REGID,PROJECTID,ORDERINDEX FROM REG_NUMBERS_PROJECT;

CREATE OR REPLACE NOFORCE VIEW VW_Duplicates
	(ID,RegNumber,RegNumberDuplicated,PersonID,Created) AS 
	SELECT ID,REGNUMBER,REGNUMBERDUPLICATED,PERSONID,CREATED FROM DUPLICATES;

CREATE OR REPLACE NOFORCE VIEW VW_Compound 	(CompoundID,StructureID,RegID,FormulaWeight,MolecularFormula,PersonCreated,PersonRegistered,DateCreated,DateLastModified,Tag,NormalizedStructure,UseNormalization) AS 
	SELECT CPD_DATABASE_COUNTER,STRUCTUREID,RegID,FORMULAWEIGHT,MOLECULARFORMULA ,PersonCreated,PersonRegistered,DATECREATED,LAST_MOD_DATE,Tag,NORMALIZEDSTRUCTURE,USENORMALIZATION FROM COMPOUND_MOLECULE;

CREATE OR REPLACE NOFORCE VIEW VW_Batch 
	(BatchID,BatchNumber,RegID,FullRegNumber,DATECREATED,DateLastModified,PERSONCREATED,PersonRegistered,StatusID,TempBatchID) AS 
	SELECT BATCH_INTERNAL_ID,BATCH_NUMBER,REG_INTERNAL_ID,FullRegNumber,DATECREATED,LAST_MOD_DATE,ENTRY_PERSON_ID,BATCH_REG_PERSON_ID,STATUS_ID,TempBatchID FROM BATCHES;

CREATE OR REPLACE NOFORCE VIEW VW_TemporaryCompound    
	(TempCompoundID, TempBatchID, formulaWeight, MolecularFormula, PersonCreated, DateLastModified, DateCreated, SequenceID, ProjectXML, Base64_CDX, StructureID, FragmentXML, BatchCompFragmentXML, IdentifierXML, RegID, NormalizedStructure, UseNormalization, Tag) AS
	SELECT TempCompoundID, TempBatchID, FormulaWeight, MolecularFormula, PersonCreated, DateLastModified, DateCreated, SequenceID, ProjectXML, Base64_CDX, StructureID, FragmentXML, BatchCompFragmentXML, IdentifierXML, RegID, NORMALIZEDSTRUCTURE, USENORMALIZATION, Tag FROM TEMPORARY_COMPOUND;

CREATE OR REPLACE NOFORCE VIEW VW_TemporaryBatch 
	(TempBatchID, BatchNumber, SequenceID, ProjectXML, IdentifierXML, DateLastModified, DateCreated, PersonCreated, StatusID, CompoundCount, StructureAggregation,ProjectXMLBatch, IdentifierXMLBatch) AS 
	SELECT TempBatchID,BatchNumber, SequenceID, ProjectXML, IdentifierXML, DateLastModified, DateCreated, PersonCreated, StatusID, (SELECT Count(1) FROM VW_TemporaryCompound WHERE TempBatchID=TB.TempBatchID), StructureAggregation,ProjectXMLBatch, IdentifierXMLBatch FROM TEMPORARY_BATCH TB;


CREATE OR REPLACE FORCE VIEW VW_Unit AS
	SELECT L.ID, PICKLISTVALUE AS UNIT
	FROM PICKLIST L , PICKLISTDOMAIN D
	WHERE D.ID = L.PICKLISTDOMAINID AND D.DESCRIPTION = 'Units';

--Version 11.0.1

-- Remove when the search service supports grandchild tables. Used in Perm Search form.
CREATE OR REPLACE VIEW VW_COMPOUND_STRUCTURE 
	(COMPOUNDID, STRUCTURE, REG_NUMBER) AS
	SELECT C.COMPOUNDID, S.STRUCTURE, R.REGNUMBER FROM VW_COMPOUND C
        	INNER JOIN VW_STRUCTURE S ON C.STRUCTUREID = S.STRUCTUREID
	        INNER JOIN VW_REGISTRYNUMBER R ON C.REGID = R.REGID;

CREATE OR REPLACE VIEW VW_MIXTURE_STRUCTURE AS
	SELECT M.MIXTUREID, MC.MIXTURECOMPONENTID, C.*, S.STRUCTURE, R.REGNUMBER, CR.REGNUMBER as COMPONENTID
        FROM   VW_MIXTURE M, VW_MIXTURE_COMPONENT MC, VW_COMPOUND C, VW_STRUCTURE S, VW_REGISTRYNUMBER R, VW_REGISTRYNUMBER CR
        WHERE  M.MIXTUREID = MC.MIXTUREID AND MC.COMPOUNDID = C.COMPOUNDID AND C.STRUCTUREID = S.STRUCTUREID AND M.REGID = R.REGID AND
	       C.REGID = CR.REGID
        ORDER BY R.REGNUMBER;

CREATE OR REPLACE VIEW VW_MIXTURE_BATCHCOMPONENT AS 
    SELECT MC.MIXTUREID, BC.ID, BC.BATCHID, BC.MIXTURECOMPONENTID, BC.ORDERINDEX 
    FROM VW_MIXTURE_COMPONENT MC, VW_BATCHCOMPONENT BC WHERE MC.MIXTURECOMPONENTID = BC.MIXTURECOMPONENTID;

CREATE OR REPLACE VIEW VW_MIXTURE_BATCH AS 
    SELECT M.MIXTUREID, R.REGNUMBER, B.BATCHID, B.BATCHNUMBER, B.REGID, B.DATECREATED, B.DATELASTMODIFIED, B.PERSONCREATED, B.PERSONREGISTERED, B.TEMPBATCHID 
        FROM REGDB.VW_MIXTURE M, REGDB.VW_REGISTRYNUMBER R, REGDB.VW_BATCH B
        WHERE M.REGID = R.REGID AND R.REGID = B.REGID;

CREATE OR REPLACE VIEW VW_MIXTURE_REGNUMBER AS
    SELECT  M.*, R.RegNumber, R.SequenceNumber 
    FROM VW_Mixture M, VW_RegistryNumber R WHERE  M.RegID =R.RegID; 

CREATE OR REPLACE NOFORCE VIEW VW_BatchIdentifier 
	(ID,TYPE,BatchID,Value,OrderIndex) AS 
	SELECT ID,TYPE,BATCHID,VALUE,ORDERINDEX FROM BATCH_IDENTIFIER;

--BULKREGISTRATION LOG

CREATE OR REPLACE FORCE VIEW VW_Log_BulkRegistration_id 
	(Log_ID,Duplicate_Action,Description,User_ID,Datetime_Stamp) AS
	SELECT LOG_ID, DUPLICATE_ACTION, DESCRIPTION, USER_ID, DATETIME_STAMP FROM Log_BulkRegistration_ID;

CREATE OR REPLACE FORCE VIEW VW_Log_BulkRegistration 
	(Id, Log_ID, temp_id, Action, reg_number, batch_number, comments) AS
	SELECT Id, Log_ID, Temp_ID, ACTION, Reg_Number, Batch_Number, Comments FROM Log_BulkRegistration;

--#########################################################
--INSERT ROWS
--#########################################################

INSERT INTO HISTORY (ID, NAME, DESCRIPTION, DATECREATED) VALUES (1,'Upgrade RegDB schema', 'Upgrade from 10 to 11.0.1',CURRENT_DATE);

INSERT INTO COEOBJECTTYPE(ID,NAME,DESCRIPTION) VALUES(1,'','');

INSERT INTO VW_Structure (STRUCTUREID,  STRUCTURE)
   SELECT -1, cscartridge.convertcdx.cdxtob64 ('[No]1=[No]S1')
     FROM DUAL;

INSERT INTO VW_STRUCTURE (STRUCTUREID,  STRUCTURE) VALUES (-2, 'VmpDRDAxMDAEAwIBAAAAAAAAAAAAAACAAAAAAAMAEwAAAENoZW1EcmF3IDEyLjBkNjcyCAATAAAAVW50aXRsZWQgRG9jdW1lbnQEAhAAAIBsAABAYgAzc3oAM7O8AAEJCAAAAAAAAAAAAAIJCAAAAOEAAAAsAQ0IAQABCAcBAAE6BAEAATsEAQAARQQBAAE8BAEAAAwGAQABDwYBAAENBgEAAEIEAQAAQwQBAABEBAEAAAoICAADAGAAyAADAAsICAAEAAAA8AADAAkIBAAzswIACAgEAAAAAgAHCAQAAAABAAYIBAAAAAQABQgEAAAAHgAECAIAeAADCAQAAAB4ACMIAQAFDAgBAAAoCAEAASkIAQABKggBAAECCBAAAAAkAAAAJAAAACQAAAAkAAEDAgAAAAIDAgABAAADMgAIAP///////wAAAAAAAP//AAAAAP////8AAAAA//8AAAAA/////wAAAAD/////AAD//wABJAAAAAIAAwDkBAUAQXJpYWwEAOQEDwBUaW1lcyBOZXcgUm9tYW4BgBgAAAAEAhAAAAAAAAAAAAAAANACAAAcAhYIBAAAACQAGAgEAAAAJAAZCAAAEAgCAAEADwgCAAEABoAWAAAAAAIIAABAdwAAQGIABAIQAACAbAAAQGIAM3N6ADOzvAAKAAIAAQAQACYAAABDaGVtRHJhdyBjYW4ndCBpbnRlcnByZXQgdGhpcyBsYWJlbC4CBwIAAQAABxgAAQAAAAQAAADwAAMATk8gU1RSVUNUVVJFAAAAAAAAAAA=');

INSERT INTO VW_STRUCTURE (STRUCTUREID,  STRUCTURE) VALUES (-3, 'VmpDRDAxMDAEAwIBAAAAAAAAAAAAAACAAAAAAAMAEwAAAENoZW1EcmF3IDEyLjBk NjcyCAATAAAAVW50aXRsZWQgRG9jdW1lbnQEAhAAAEBbAADAYwAzM2kAzAz6AAEJ CAAAAPT/AAD0/wIJCAAAAOEAAADhAA0IAQABCAcBAAE6BAEAATsEAQAARQQBAAE8 BAEAAAwGAQABDwYBAAENBgEAAEIEAQAAQwQBAABEBAEAAAoICAADAGAAyAADAAsI CAAEAAAA8AADAAkIBAAzswIACAgEAAAAAgAHCAQAAAABAAYIBAAAAAQABQgEAAAA HgAECAIAeAADCAQAAAB4ACMIAQAFDAgBAAAoCAEAASkIAQABKggBAAECCBAAAAAk AAAAJAAAACQAAAAkAAEDAgAAAAIDAgABAAADMgAIAP///////wAAAAAAAP//AAAA AP////8AAAAA//8AAAAA/////wAAAAD/////AAD//wABJAAAAAIAAwDkBAUAQXJp YWwEAOQEDwBUaW1lcyBOZXcgUm9tYW4BgAQAAAAEAhAAAAAAAAAAAAAAANACAAAc AhYIBAAAACQAGAgEAAAAJAAZCAAAEAgCAAEADwgCAAEABoACAAAAAAIIAAAAZgAA wGMABAIQAABAWwAAwGMAMzNpAMwM+gAKAAIAAQAQACYAAABDaGVtRHJhdyBjYW4n dCBpbnRlcnByZXQgdGhpcyBsYWJlbC4CBwIAAQAAByAAAQAAAAQAAADwAAMATk9O IENIRU1JQ0FMIENPTlRFTlQAAAAAAAAAAA==');

COMMIT;

--#########################################################
--CREATE VIEW FOR BIOASSAY
--#########################################################

drop materialized view vw_reg_batches;

create materialized view vw_reg_batches
	storage (initial 1k next 100k pctincrease 0)
	pctfree 0
	pctused 99
	nologging
	tablespace &&tableSpaceName.
	build immediate
	refresh complete
	with primary key
	start with trunc(sysdate) + 23.2/24
	next trunc(sysdate) + 1 + 23.2/24
as
 SELECT
	reg_numbers.reg_id,
	reg_numbers.mol_id,
	reg_numbers.registry_date,
	reg_numbers.cpd_internal_id,
	reg_numbers.reg_number,
	reg_numbers.sequence_number,
	reg_numbers.sequence_internal_id,
	reg_numbers.last_batch_number,
	reg_numbers.registrar_person_id,
	reg_numbers.load_id,
	reg_numbers.datetime_stamp,
	batches.batch_internal_id,
	batches.batch_number,
	batches.FullRegNumber FULL_REG_NUMBER
FROM
  reg_Numbers,
  batches
WHERE
  reg_numbers.reg_id = batches.reg_internal_id;

CREATE INDEX "INDEX_VW_REGDB_BATCHES"
    ON "VW_REG_BATCHES"  ("FULL_REG_NUMBER")
    TABLESPACE "&&indexTableSpaceName";

CREATE INDEX "INDEX_BATCH_INTERNAL_ID"
    ON "VW_REG_BATCHES"  ("BATCH_INTERNAL_ID")
    TABLESPACE "&&indexTableSpaceName";

--#########################################################
--Temporary Test Data*
--#########################################################

INSERT INTO REGDB.FRAGMENTTYPE(ID,DESCRIPTION) VALUES (1,'Salt');
INSERT INTO REGDB.FRAGMENTTYPE(ID,DESCRIPTION) VALUES (2,'Solvate');
UPDATE REGDB.VW_PROJECT SET NAME='Default Proj', DESCRIPTION='Default project description',ACTIVE='T' WHERE PROJECTID=1;
INSERT INTO REGDB.VW_PROJECT(ProjectID,Name,Active,Description) VALUES(2,'PR100','T','Project 100 Name');
INSERT INTO REGDB.PICKLISTDOMAIN(ID,Description) VALUES(1,'Status');
INSERT INTO REGDB.PICKLISTDOMAIN(ID,Description) VALUES(2,'Units');
INSERT INTO REGDB.PICKLIST(ID,PICKLISTDOMAINID,PICKLISTVALUE) VALUES(1,1,'');
INSERT INTO REGDB.PICKLIST(ID,PICKLISTDOMAINID,PICKLISTVALUE) VALUES(2,1,'Rejected');
INSERT INTO REGDB.PICKLIST(ID,PICKLISTDOMAINID,PICKLISTVALUE) VALUES(3,2,'mg');
INSERT INTO REGDB.PICKLIST(ID,PICKLISTDOMAINID,PICKLISTVALUE) VALUES(4,2,'g');
INSERT INTO REGDB.PICKLIST(ID,PICKLISTDOMAINID,PICKLISTVALUE) VALUES(5,2,'ml');
INSERT INTO REGDB.PICKLIST(ID,PICKLISTDOMAINID,PICKLISTVALUE) VALUES(6,2,'l');

COMMIT;

--#########################################################
--CREATE AND COMPILE PACKAGES
--#########################################################

@"sql\Patches\Patch 11.0.1\sql\CREATE_Packages.sql"

ALTER PACKAGE CSCHEMREG COMPILE;
ALTER PROCEDURE PopulateBatchFormula COMPILE;
ALTER VIEW VW_COMPOUND_STRUCTURE COMPILE;
ALTER VIEW VW_MIXTURE_STRUCTURE COMPILE;




