-- SUBSTANCE IDXS
CREATE INDEX FIDX_SUBSTANCE_ACX_ID
    ON SUBSTANCE(LOWER(ACX_ID))
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX IDX_SUBSTANCE_ACX_ID
    ON SUBSTANCE(ACX_ID)
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX FIDX_SUBSTANCE_CAS
    ON SUBSTANCE(LOWER(CAS))
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX IDX_SUBSTANCE_CAS
    ON SUBSTANCE(CAS)
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX IDX_SUBSTANCE_MOL_ID
    ON SUBSTANCE(MOL_ID)
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX IDX_SUBSTANCE_SUPPLIER
    ON SUBSTANCE(SUPPLIERID)
    TABLESPACE &&indexTableSpaceName
    ;

-- PRODUCT IDXS
CREATE INDEX IDX_PRODUCT_CATNUM
    ON PRODUCT(CATALOGNUM)
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX FIDX_PRODUCT_CATNUM
    ON PRODUCT(LOWER(CATALOGNUM))
    TABLESPACE &&indexTableSpaceName
    ;


CREATE INDEX IDX_PRODUCT_NAME
    ON PRODUCT(PRODNAME)
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX FIDX_PRODUCT_NAME
    ON PRODUCT(LOWER(PRODNAME))
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX IDX_PRODUCT_DESCRIP
    ON PRODUCT(PRODDESCRIP)
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX IDX_PRODUCT_ACXID
    ON PRODUCT(ACX_ID)
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX IDX_PRODUCT_SUPPLIER_ID
    ON PRODUCT(SUPPLIERID)
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX IDX_PRODUCT_CSNUM
    ON PRODUCT(CSNUM)
    TABLESPACE &&indexTableSpaceName
    ;


-- PACKAGE IDXS
CREATE INDEX IDX_PACKAGE_PROD_ID
    ON PACKAGE(PRODUCTID)
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX FIDX_PACKAGE_CATNUM
    ON PACKAGE(LOWER(CATALOGNUM))
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX IDX_PACKAGE_CATNUM
    ON PACKAGE(CATALOGNUM)
    TABLESPACE &&indexTableSpaceName
    ;


CREATE INDEX IDX_PACKAGE_SUPPLIERID
    ON PACKAGE(SUPPLIERID)
    TABLESPACE &&indexTableSpaceName
    ;


-- SYNONYM IDXS
CREATE INDEX FIDX_SYNONYM_NAME
    ON ACX_SYNONYM(LOWER(NAME))
    TABLESPACE &&indexTableSpaceName
    ;

CREATE INDEX IDX_SYNONYM_NAME
    ON ACX_SYNONYM(NAME)
    TABLESPACE &&indexTableSpaceName
    ;

-- PACKAGESIZECONVERSION
CREATE INDEX PACKAGESIZECONVERSION_SIZE_FK
    ON PACKAGESIZECONVERSION(SIZE_FK)
    TABLESPACE &&indexTableSpaceName
    ;

-- PRIMARY KEYS
ALTER TABLE PACKAGE
    ADD CONSTRAINT PACKAGE_PK PRIMARY KEY(
    PACKAGEID)USING INDEX TABLESPACE &&indexTableSpaceName
    ;

ALTER TABLE PRODUCT
    ADD CONSTRAINT PRODUCT_PK PRIMARY KEY(
    PRODUCTID) USING INDEX TABLESPACE &&indexTableSpaceName
    ;

ALTER TABLE SUBSTANCE
    ADD CONSTRAINT SUBSTANCE_PK PRIMARY KEY(
    CSNUM) USING INDEX TABLESPACE &&indexTableSpaceName
    ;

ALTER TABLE ACX_SYNONYM
    ADD CONSTRAINT SYNONYM_PK PRIMARY KEY(
    SYNONYMID) USING INDEX TABLESPACE &&indexTableSpaceName
    ;

ALTER TABLE SUPPLIER
    ADD CONSTRAINT SUPPLIER_PK PRIMARY KEY(
    SUPPLIERID) USING INDEX TABLESPACE &&indexTableSpaceName
    ;

ALTER TABLE SUPPLIERADDR
    ADD CONSTRAINT SUPPLIERADDR_PK PRIMARY KEY(
    SUPPLIERADDRID) USING INDEX TABLESPACE &&indexTableSpaceName
    ;

ALTER TABLE SUPPLIERPHONEID
    ADD CONSTRAINT SUPPLIERPHONEID_PK PRIMARY KEY(
    SUPPLIERPHONEID) USING INDEX TABLESPACE &&indexTableSpaceName
    ;

ALTER TABLE SHOPPINGCART
    ADD CONSTRAINT SHOPPINGCART_PK PRIMARY KEY(
    CSUSERNAME) USING INDEX TABLESPACE &&indexTableSpaceName
    ;

ALTER TABLE MSDX
    ADD CONSTRAINT MSDX_PK PRIMARY KEY(
    IDAUTONUMBER) USING INDEX TABLESPACE &&indexTableSpaceName
    ;

ALTER TABLE PROPERTYCLASSALPHA
    ADD CONSTRAINT PROPERTYCLASSALPHA_PK PRIMARY KEY(
    PROPERTYCLASSALPHAID) USING INDEX TABLESPACE &&indexTableSpaceName
    ;


delete from PROPERTYALPHA where productid is null;
commit;    
ALTER TABLE PROPERTYALPHA
    ADD CONSTRAINT PROPERTYALPHA_PK PRIMARY KEY(
    PRODUCTID, PROPERTY) USING INDEX TABLESPACE &&indexTableSpaceName
    ;    

ALTER TABLE PACKAGESIZECONVERSION
    ADD CONSTRAINT PACKAGESIZECONVERSION_PK PRIMARY KEY(
    ID) USING INDEX TABLESPACE &&indexTableSpaceName
    ;

-- Analize
connect system/manager2@&&serverName
begin
	dbms_stats.gather_schema_stats(ownname=> 'CHEMACXDB' , cascade=> TRUE);
end;

--Create Cartridge Index
--create index mx on substance(base64_cdx) indextype is cscartridge.moleculeindextype;



