DROP INDEX INV_COMPOUNDS_SN_IDX;

ALTER TABLE "INV_COMPOUNDS" MODIFY (
	"SUBSTANCE_NAME" VARCHAR2(2000)
);

CREATE INDEX INV_COMPOUNDS_SN_IDX ON INV_COMPOUNDS(SUBSTANCE_NAME ASC) TABLESPACE &&indexTableSpaceName;

ALTER TABLE "INV_COMPOUNDS" ADD (
	REG_ID_FK number(9,0) null,
	BATCH_NUMBER_FK number(9,0) null,
  CPD_INTERNAL_ID_FK number(9,0) null
);
