-- Copyright Cambridgesoft Corp 2001-2007 all rights reserved

--#########################################################
-- Alter cs_security schema for Inventory 10
-- Creates and grants to default ChemInv Roles and populates CS_SECURITY tables
--######################################################### 

prompt '#########################################################'
prompt 'Altering the cs_security schema...'
prompt '#########################################################'

--' Grant all cheminvdb2 object permissions to CS_SECURITY   
Connect &&schemaName/&&schemaPass@&&serverName
-- new tables
GRANT SELECT,INSERT,UPDATE,DELETE ON "&&SchemaName".INV_PICKLIST_TYPES TO CS_SECURITY WITH GRANT OPTION;
GRANT SELECT,INSERT,UPDATE,DELETE ON "&&SchemaName".INV_PICKLISTS TO CS_SECURITY WITH GRANT OPTION;
GRANT SELECT,INSERT,UPDATE,DELETE ON "&&SchemaName".INV_CUSTOM_FIELD_GROUPS TO CS_SECURITY WITH GRANT OPTION;
GRANT SELECT,INSERT,UPDATE,DELETE ON "&&SchemaName".INV_CUSTOM_FIELDS TO CS_SECURITY WITH GRANT OPTION;
GRANT SELECT,INSERT,UPDATE,DELETE ON "&&SchemaName".INV_CUSTOM_CPD_FIELD_VALUES TO CS_SECURITY WITH GRANT OPTION;
GRANT SELECT ON "&&SchemaName".INV_CONTAINER_BATCH_FIELDS TO CS_SECURITY WITH GRANT OPTION;
grant SELECT on "&&SchemaName".INV_CONTAINER_BATCH_FIELDS TO Inv_Browser;
GRANT EXECUTE ON "&&SchemaName".GETPRIMARYKEYIDS to CS_SECURITY WITH GRANT OPTION;

--' Create cs_security objects and data for Inventory 
connect &&securitySchemaName/&&securitySchemaPass@&&serverName;
-- new privilege
ALTER TABLE CS_SECURITY.CHEMINV_PRIVILEGES ADD (
    "INV_MANAGE_CUSTOM_FIELDS" Number(1)
)
;
commit;

--#########################################################
-- Object_Privileges
--######################################################### 
--' insert inventory entries
--' INV_BROWSE_ALL PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_PICKLIST_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CUSTOM_FIELD_GROUPS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CUSTOM_FIELDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'SELECT', '&&SchemaName', 'INV_CONTAINER_BATCH_FIELDS');
-- INV_MANAGE_SUBSTANCES PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'INSERT', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'UPDATE', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_SUBSTANCES', 'DELETE', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
-- INV_MANAGE_CUSTOM_FIELDS PRIVS
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'INSERT', '&&SchemaName', 'INV_PICKLIST_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'UPDATE', '&&SchemaName', 'INV_PICKLIST_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'DELETE', '&&SchemaName', 'INV_PICKLIST_TYPES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'INSERT', '&&SchemaName', 'INV_PICKLISTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'UPDATE', '&&SchemaName', 'INV_PICKLISTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'DELETE', '&&SchemaName', 'INV_PICKLISTS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'INSERT', '&&SchemaName', 'INV_CUSTOM_FIELD_GROUPS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'UPDATE', '&&SchemaName', 'INV_CUSTOM_FIELD_GROUPS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'DELETE', '&&SchemaName', 'INV_CUSTOM_FIELD_GROUPS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'INSERT', '&&SchemaName', 'INV_CUSTOM_FIELDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'UPDATE', '&&SchemaName', 'INV_CUSTOM_FIELDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'DELETE', '&&SchemaName', 'INV_CUSTOM_FIELDS');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'INSERT', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'UPDATE', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');
INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_MANAGE_CUSTOM_FIELDS', 'DELETE', '&&SchemaName', 'INV_CUSTOM_CPD_FIELD_VALUES');

INSERT INTO CS_SECURITY.OBJECT_PRIVILEGES VALUES ('INV_BROWSE_ALL', 'EXECUTE', '&&SchemaName', 'GETPRIMARYKEYIDS');

commit;

--' Create default roles for Inventory 
connect &&securitySchemaName/&&securitySchemaPass@&&serverName;
UPDATE CS_SECURITY.CHEMINV_PRIVILEGES SET INV_MANAGE_CUSTOM_FIELDS=0 WHERE INV_MANAGE_CUSTOM_FIELDS IS NULL;
commit;
UPDATE CS_SECURITY.CHEMINV_PRIVILEGES SET INV_MANAGE_CUSTOM_FIELDS=1 WHERE ROLE_INTERNAL_ID = (SELECT ROLE_ID FROM CS_SECURITY.SECURITY_ROLES WHERE ROLE_NAME = 'INV_ADMIN');
commit;

@@..\..\Alter\Cs_Security\GrantPrivsToRole.sql
commit;

--' grant roles based on privs
begin
	FOR role_rec IN (SELECT role_name FROM security_roles WHERE privilege_table_int_id = (SELECT privilege_table_id FROM privilege_tables WHERE privilege_table_name = '&&privTableName'))
	LOOP
		GrantPrivsToRole(role_rec.role_name);
	END LOOP;
end;
/
