CREATE OR REPLACE PACKAGE "DOCS" IS
  TYPE  CURSOR_TYPE IS REF CURSOR ;

  FUNCTION INSERTDOC(
    p_TableName INV_DOCS.TABLE_NAME%TYPE
    , p_FieldName INV_DOCS.FIELD_NAME%TYPE
    , p_FieldValue INV_DOCS.FIELD_VALUE%TYPE
    , p_DocType INV_DOCS.DOC_TYPE_ID_FK%TYPE
    , p_Doc INV_DOCS.DOC%TYPE
  ) RETURN INV_DOCS.DOC_ID%TYPE ;
  
  PROCEDURE GETDOC(
    p_DocID INV_DOCS.DOC_ID%TYPE
    , O_RS OUT CURSOR_TYPE
    ) ;

END "DOCS" ; 


/

show errors;