CREATE or replace PROCEDURE DEL_PROCEEDED_TEMP_RECORDS AS
-- procedure which deletes registred records from temporary tables
BEGIN
    insert into TEMP_DELETE_TEMP_REC select id  FROM FOR_DELETE_TEMP_REC D;
    DELETE TEMPORARY_COMPOUND TC WHERE  EXISTS (SELECT 1 FROM TEMP_DELETE_TEMP_REC D WHERE D.ID = TC.TEMPBATCHID);
    DELETE TEMPORARY_BATCH_PROJECT TC WHERE  EXISTS (SELECT 1 FROM TEMP_DELETE_TEMP_REC D WHERE D.ID = TC.TEMPBATCHID);
    DELETE TEMPORARY_REG_NUMBERS_PROJECT TC WHERE  EXISTS (SELECT 1 FROM TEMP_DELETE_TEMP_REC D WHERE D.ID = TC.TEMPBATCHID);
    DELETE TEMPORARY_BATCH TC WHERE   EXISTS (SELECT 1 FROM TEMP_DELETE_TEMP_REC D WHERE D.ID = TC.TEMPBATCHID);
	-- remove proceeded records from our service table
    DELETE FOR_DELETE_TEMP_REC  TC WHERE   EXISTS (SELECT 1 FROM TEMP_DELETE_TEMP_REC D WHERE D.ID = TC.ID);
    commit;
END;
/