//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_ContentArea_About class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_ContentArea_About {
    
    /// <summary>
    /// ConfirmationAreaUserControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_UserControls_ConfirmationArea ConfirmationAreaUserControl;
    
    /// <summary>
    /// ErrorAreaUserControl control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Forms_UserControls_ErrorArea ErrorAreaUserControl;
    
    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new ChemBioVizMasterPage Master {
        get {
            return ((ChemBioVizMasterPage)(base.Master));
        }
    }
}
