
  CREATE TABLE INV_BATCH_TYPE
   (	"ID" NUMBER NOT NULL ENABLE, 
	"BATCH_TYPE" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"BATCH_ORDER" NUMBER(1,0), 
	 CONSTRAINT "BATCH_TYPE_PK" PRIMARY KEY ("ID"));
 
CREATE SEQUENCE SEQ_INV_BATCH_TYPE INCREMENT BY 1 START WITH 1;

  CREATE OR REPLACE TRIGGER TRG_INV_BATCH_TYPE BEFORE
    INSERT
    ON "INV_BATCH_TYPE"
    FOR EACH ROW
    BEGIN
		IF :NEW.ID IS NULL THEN
			SELECT SEQ_INV_BATCH_TYPE.NEXTVAL INTO :NEW.ID FROM DUAL;
		END IF;
END;
/

 
