CREATE TABLE SEARCHLOG (SEARCHTIMESTAMP TIMESTAMP(6),
    					IP VARCHAR2(15),
    					ASPSESSIONID VARCHAR2(50),
    					ISPLUGIN VARCHAR2(5),
    					HOST VARCHAR2(255),
    					REFERER VARCHAR2(255),
    					CSUSERID VARCHAR2(30));
