CREATE OR REPLACE VIEW INV_VW_PLATE_FORMAT (
   PLATE_FORMAT_ID,
   PLATE_FORMAT_NAME,
   PHYS_PLATE_ID,
   PHYS_PLATE_NAME,
   ROW_COUNT,
   COL_COUNT,
   SUPPLIER_ID_FK,
   GRID_FORMAT_ID_FK,
   IS_PRE_BARCODED
)
AS
   SELECT
	PLATE_FORMAT_ID,
	PLATE_FORMAT_NAME,
	   PHYS_PLATE_ID,
	  PHYS_PLATE_NAME,
	  ROW_COUNT,
	   COL_COUNT,
	   SUPPLIER_ID_FK,
	   GRID_FORMAT_ID_FK,
	   IS_PRE_BARCODED
     FROM INV_PLATE_FORMAT, INV_VW_PHYSICAL_PLATE
    WHERE PHYS_PLATE_ID_FK = PHYS_PLATE_ID;
