//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Forms_ContentArea_DVHome class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Forms_ContentArea_DVHome {
    
    /// <summary>
    /// WebPartManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.WebParts.WebPartManager WebPartManager1;
    
    /// <summary>
    /// Panel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.WebParts.WebPartZone Panel;
    
    /// <summary>
    /// PanelWebPart0_0 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart PanelWebPart0_0;
    
    /// <summary>
    /// PanelWebPart0_1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart PanelWebPart0_1;
    
    /// <summary>
    /// PanelWebPart0_2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart PanelWebPart0_2;
    
    /// <summary>
    /// PanelWebPart0_3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart PanelWebPart0_3;
    
    /// <summary>
    /// DashBoard control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.WebParts.WebPartZone DashBoard;
    
    /// <summary>
    /// DashWebPart0_1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart DashWebPart0_1;
    
    /// <summary>
    /// DashWebPart0_2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart DashWebPart0_2;
    
    /// <summary>
    /// DashWebPart0_3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart DashWebPart0_3;
    
    /// <summary>
    /// DashWebPart0_4 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart DashWebPart0_4;
    
    /// <summary>
    /// DashWebPart0_5 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart DashWebPart0_5;
    
    /// <summary>
    /// DashWebPart0_6 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart DashWebPart0_6;
    
    /// <summary>
    /// DashWebPart0_7 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart DashWebPart0_7;
    
    /// <summary>
    /// DashWebPart0_8 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart DashWebPart0_8;
    
    /// <summary>
    /// DashWebPart0_9 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart DashWebPart0_9;
    
    /// <summary>
    /// DashWebPart0_10 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CambridgeSoft.COE.Framework.Controls.WebParts.HomeWebPart DashWebPart0_10;
    
    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new Manager.Forms.Master.DataViewManager Master {
        get {
            return ((Manager.Forms.Master.DataViewManager)(base.Master));
        }
    }
}
