-- Copyright Cambridgesoft Corp 2001-2005 all rights reserved
-- NOTE THIS SCRIPT MUST BE RUN FROM THE COMMAND LINE VERSION OF SQLPLUS
-- This script will not run from SQLPlus Worksheet!

-- Grants object permissions to ChemInv Roles
-- Assumes CHEMINV objects and roles alerady exist

Connect &&schemaName/&&schemaPass@&&serverName
--INV_BROWSER
-- All roles inherit from this one
GRANT SELECT ON inv_compounds TO INV_BROWSER;
GRANT SELECT ON inv_containers TO INV_BROWSER;
GRANT SELECT ON inv_container_status TO INV_BROWSER;
GRANT SELECT ON inv_container_types TO INV_BROWSER;                 
GRANT SELECT ON inv_exclude_container_types TO inv_browser;
GRANT SELECT ON inv_locations TO INV_BROWSER;
GRANT SELECT ON inv_location_types TO INV_BROWSER;
GRANT SELECT ON inv_owners TO inv_browser;
GRANT SELECT ON inv_picklists TO INV_BROWSER;
GRANT SELECT ON inv_physical_state TO INV_BROWSER;
GRANT SELECT ON inv_project_job_info TO inv_browser;
GRANT SELECT ON inv_reportformats TO inv_browser;
GRANT SELECT ON inv_reports TO inv_browser;
GRANT SELECT ON inv_reporttypes TO inv_browser;
GRANT SELECT ON inv_requests TO INV_BROWSER;
GRANT SELECT ON inv_reservation_types TO INV_BROWSER;      
GRANT SELECT ON inv_solvents TO INV_BROWSER;
GRANT SELECT ON inv_suppliers TO INV_BROWSER;
GRANT SELECT ON inv_synonyms TO INV_BROWSER;
GRANT SELECT ON inv_units TO INV_BROWSER;      
GRANT SELECT ON inv_unit_conversion TO INV_BROWSER;
GRANT SELECT ON inv_unit_types TO INV_BROWSER;
GRANT SELECT ON inv_url TO INV_BROWSER;
GRANT SELECT, INSERT, UPDATE ON inv_user_properties TO INV_BROWSER;
GRANT SELECT ON inv_xmldocs TO INV_BROWSER;
GRANT SELECT ON inv_xmldoc_types TO INV_BROWSER;
GRANT SELECT ON inv_xslts TO INV_BROWSER;
GRANT SELECT ON inv_well_parent TO INV_BROWSER;
GRANT SELECT ON inv_plate_parent TO INV_BROWSER;
GRANT SELECT ON inv_REPORTPARAMS TO INV_BROWSER;
GRANT SELECT ON INV_CONTAINER_CHECKIN_DETAILS TO INV_BROWSER;
GRANT SELECT ON INV_WELL_COMPOUNDS TO INV_BROWSER;

GRANT EXECUTE ON checkoutcontainer TO INV_BROWSER;
GRANT EXECUTE ON Exclude_ContainerTypes TO INV_BROWSER;
GRANT EXECUTE ON guiutils TO inv_browser;
GRANT EXECUTE ON requests TO inv_browser;
GRANT EXECUTE ON reservations TO inv_browser;
GRANT EXECUTE ON SELECTHAZMATDATA TO inv_browser;
GRANT EXECUTE ON SELECTSUBSTANCEHAZMATDATA TO inv_browser;
GRANT EXECUTE ON updatecontainerstatus TO INV_BROWSER;
GRANT EXECUTE ON getlocationpath TO inv_browser;
GRANT EXECUTE ON IsTrashLocation TO inv_browser; 
GRANT EXECUTE ON XMLUtils TO INV_BROWSER;
GRANT EXECUTE ON ChemCalcs TO INV_BROWSER;
GRANT EXECUTE ON PlateChem TO INV_BROWSER;
GRANT EXECUTE ON LookUpValue TO INV_BROWSER;
GRANT EXECUTE ON InsertCheckInDetails TO INV_BROWSER;
GRANT EXECUTE ON Reservations TO INV_BROWSER;

GRANT SELECT ON inv_allowed_ctypes TO INV_BROWSER;
GRANT SELECT ON inv_allowed_ltypes TO INV_BROWSER;
GRANT SELECT ON inv_allowed_ptypes TO INV_BROWSER;
GRANT SELECT ON inv_barcode_desc TO INV_BROWSER;
GRANT SELECT ON inv_enumeration TO INV_BROWSER;
GRANT SELECT ON inv_enumeration_set TO INV_BROWSER;
GRANT SELECT ON inv_enum_values TO INV_BROWSER;
GRANT SELECT ON inv_eset_type TO INV_BROWSER;
GRANT SELECT ON inv_grid_element TO INV_BROWSER;
GRANT SELECT ON inv_grid_fill_template TO INV_BROWSER;
GRANT SELECT ON inv_grid_format TO INV_BROWSER;
GRANT SELECT ON inv_grid_position TO INV_BROWSER;
GRANT SELECT ON inv_grid_storage TO INV_BROWSER;
GRANT SELECT ON inv_physical_plate TO INV_BROWSER;
GRANT SELECT ON inv_plates TO INV_BROWSER;
GRANT SELECT ON inv_plate_actions TO INV_BROWSER;
GRANT SELECT ON inv_plate_format TO INV_BROWSER;
GRANT SELECT ON inv_plate_history TO INV_BROWSER;
GRANT SELECT ON inv_plate_types TO INV_BROWSER;
GRANT SELECT ON inv_wells TO INV_BROWSER;
GRANT SELECT ON inv_vw_enumerated_values TO INV_BROWSER;
GRANT SELECT ON inv_vw_grid_location TO INV_BROWSER;
GRANT SELECT ON inv_vw_grid_location_lite TO INV_BROWSER;
GRANT SELECT ON inv_vw_grid_location_parent TO INV_BROWSER;
GRANT SELECT ON inv_vw_nongrid_locations TO INV_BROWSER;
GRANT SELECT ON inv_vw_plate TO INV_BROWSER;
GRANT SELECT ON inv_vw_plate_format TO INV_BROWSER;
GRANT SELECT ON inv_vw_plate_grid_locations TO INV_BROWSER;
GRANT SELECT ON inv_vw_plate_history TO INV_BROWSER;
GRANT SELECT ON inv_vw_plate_locations TO INV_BROWSER;
GRANT SELECT ON inv_vw_plate_locations_all TO INV_BROWSER;
GRANT SELECT ON inv_vw_physical_plate TO INV_BROWSER;
GRANT SELECT ON inv_vw_well TO INV_BROWSER;
GRANT SELECT ON inv_vw_well_format TO INV_BROWSER;
GRANT SELECT ON INV_VW_WELL_FLAT TO INV_BROWSER;

GRANT EXECUTE ON GetNumberOfCompoundWells TO INV_BROWSER;
GRANT EXECUTE ON IsGridLocation TO INV_BROWSER;
GRANT EXECUTE ON IsFrozenLocation TO INV_BROWSER;
GRANT EXECUTE ON IsPlateTypeAllowed TO INV_BROWSER;

GRANT SELECT ON INV_COUNTRY TO INV_BROWSER;
GRANT SELECT ON INV_STATES TO INV_BROWSER;
GRANT SELECT ON INV_ADDRESS TO INV_BROWSER;
GRANT SELECT ON INV_REQUEST_TYPES TO INV_BROWSER;
GRANT SELECT ON INV_REQUEST_STATUS TO INV_BROWSER;
GRANT SELECT ON INV_REQUEST_SAMPLES TO INV_BROWSER;
GRANT SELECT ON INV_ORDER_STATUS TO INV_BROWSER;
GRANT SELECT ON INV_ORDERS TO INV_BROWSER;
GRANT SELECT ON INV_ORDER_CONTAINERS TO INV_BROWSER;

--INV_CHEMIST
-- Edit/Move/Reserve/CheckOut Containers
GRANT EXECUTE ON Reservations TO INV_CHEMIST;
GRANT EXECUTE ON UpdateAllContainerFields TO INV_CHEMIST;
GRANT EXECUTE ON UpdateContainerQtyRemaining TO INV_CHEMIST;
GRANT EXECUTE ON CreateContainer TO INV_CHEMIST;
GRANT EXECUTE ON CopyContainer TO INV_CHEMIST;
GRANT EXECUTE ON UpdateContainer TO INV_CHEMIST;
GRANT EXECUTE ON MoveContainer TO INV_CHEMIST;
GRANT EXECUTE ON RetireContainer TO INV_CHEMIST;
GRANT EXECUTE ON CheckOutContainer TO INV_CHEMIST;
--GRANT EXECUTE ON OrderContainer TO INV_CHEMIST;
--GRANT EXECUTE ON ReOrderContainer TO INV_CHEMIST;   

--Create/Edit/Move/Delete Plates
GRANT EXECUTE ON DeletePlate TO INV_CHEMIST;
GRANT EXECUTE ON MovePlate TO INV_CHEMIST;
GRANT EXECUTE ON MovePlates TO INV_CHEMIST;
GRANT EXECUTE ON CreatePlateMap TO INV_CHEMIST;
GRANT EXECUTE ON CopyPlate TO INV_CHEMIST;
GRANT EXECUTE ON DeletePlates TO INV_CHEMIST;
GRANT EXECUTE ON RetirePlate TO INV_CHEMIST;
GRANT EXECUTE ON SolvatePlates TO INV_CHEMIST;
GRANT EXECUTE ON UpdatePlateAttributes TO INV_CHEMIST;
GRANT EXECUTE ON UpdateWell TO INV_CHEMIST;
GRANT EXECUTE ON CreatePlateXML TO INV_CHEMIST;
GRANT EXECUTE ON Reformat TO INV_CHEMIST;


--INV_RECEIVING
-- Create/Edit/Move Containers
GRANT EXECUTE ON CreateContainer TO INV_RECEIVING;
GRANT EXECUTE ON CopyContainer TO INV_RECEIVING;
GRANT EXECUTE ON UpdateContainer TO INV_RECEIVING;
GRANT EXECUTE ON UpdateAllContainerFields TO INV_RECEIVING;
GRANT EXECUTE ON MoveContainer TO INV_RECEIVING;
GRANT EXECUTE ON DeleteContainer TO INV_RECEIVING;
--Create/Edit/Move Plates
GRANT EXECUTE ON MovePlate TO INV_RECEIVING;
GRANT EXECUTE ON MovePlates TO INV_RECEIVING;
GRANT EXECUTE ON CreatePlateMap TO INV_RECEIVING;
GRANT EXECUTE ON CopyPlate TO INV_RECEIVING;
GRANT EXECUTE ON RetirePlate TO INV_RECEIVING;
GRANT EXECUTE ON SolvatePlates TO INV_RECEIVING;
GRANT EXECUTE ON UpdatePlateAttributes TO INV_RECEIVING;
GRANT EXECUTE ON UpdateWell TO INV_RECEIVING;
GRANT EXECUTE ON CreatePlateXML TO INV_RECEIVING;
GRANT EXECUTE ON Reformat TO INV_RECEIVING;


--INV_FINANCE
-- Create/Edit/Move Containers
-- Create/Edit/Move/Delete Locations
GRANT SELECT ON audit_column TO INV_FINANCE;
GRANT SELECT ON audit_row TO INV_FINANCE;
GRANT SELECT ON audit_delete TO INV_FINANCE;
GRANT SELECT ON audit_compound TO INV_FINANCE;
GRANT SELECT ON INV_VW_AUDIT_AGGREGATE TO INV_FINANCE;
GRANT EXECUTE ON CreateContainer TO INV_FINANCE;
GRANT EXECUTE ON CopyContainer TO INV_FINANCE;
GRANT EXECUTE ON UpdateContainer TO INV_CHEMIST;
GRANT EXECUTE ON RetireContainer TO INV_FINANCE;
GRANT EXECUTE ON UpdateAllContainerFields TO INV_FINANCE;
GRANT EXECUTE ON UpdateContainerQtyRemaining TO INV_FINANCE;
GRANT EXECUTE ON MoveContainer TO INV_FINANCE;
GRANT EXECUTE ON CreateLocation TO INV_FINANCE;
GRANT EXECUTE ON UpdateLocation TO INV_FINANCE;
GRANT EXECUTE ON MoveLocation TO INV_FINANCE;
GRANT EXECUTE ON DeleteLocation TO INV_FINANCE;
GRANT EXECUTE ON platesettings TO INV_FINANCE;
--Create/Edit/Move Plates
GRANT EXECUTE ON MovePlate TO INV_FINANCE;
GRANT EXECUTE ON MovePlates TO INV_FINANCE;
GRANT EXECUTE ON CreatePlateMap TO INV_FINANCE;
GRANT EXECUTE ON CopyPlate TO INV_FINANCE;
GRANT EXECUTE ON RetirePlate TO INV_FINANCE;
GRANT EXECUTE ON SolvatePlates TO INV_FINANCE;
GRANT EXECUTE ON UpdatePlateAttributes TO INV_FINANCE;
GRANT EXECUTE ON UpdateWell TO INV_FINANCE;
GRANT EXECUTE ON CreatePlateXML TO INV_FINANCE;
GRANT EXECUTE ON Reformat TO INV_FINANCE;

--INV_REGISTRAR
-- Create/Edit/Delete inventory substances
GRANT INSERT, UPDATE, DELETE ON inv_compounds TO INV_REGISTRAR;
GRANT SELECT ON audit_column TO INV_REGISTRAR;
GRANT SELECT ON audit_row TO INV_REGISTRAR;
GRANT SELECT ON audit_delete TO INV_REGISTRAR;
GRANT SELECT ON audit_compound TO INV_REGISTRAR;
GRANT SELECT ON INV_VW_AUDIT_AGGREGATE TO INV_REGISTRAR;
GRANT EXECUTE ON GetCompoundIdFromName TO INV_REGISTRAR;
GRANT EXECUTE ON SubstanceNameExists TO INV_REGISTRAR;
GRANT EXECUTE ON Compounds TO INV_REGISTRAR;
GRANT EXECUTE ON links TO INV_REGISTRAR;
GRANT EXECUTE ON ISDUPLICATECOMPOUND TO INV_REGISTRAR;
GRANT EXECUTE ON GETCOMPOUNDID TO INV_REGISTRAR;


--INV_ADMIN
-- Full Access
GRANT INSERT, UPDATE, DELETE ON inv_synonyms TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_compounds TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_containers TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_locations TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_units TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_container_types TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_location_types TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_unit_types TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_container_status TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_suppliers TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_physical_state TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_exclude_container_types TO INV_ADMIN;
GRANT SELECT ON inv_container_order TO INV_ADMIN;
GRANT SELECT ON inv_container_order_reason TO INV_ADMIN;
GRANT SELECT ON audit_column TO INV_ADMIN;
GRANT SELECT ON audit_row TO INV_ADMIN;
GRANT SELECT ON audit_delete TO INV_ADMIN;
GRANT SELECT ON audit_compound TO INV_ADMIN;
GRANT SELECT ON INV_VW_AUDIT_AGGREGATE TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_REPORTPARAMS TO INV_ADMIN;
GRANT SELECT ON inv_VW_AUDIT_COLUMN_DISP TO INV_ADMIN;

GRANT EXECUTE ON CreateContainer TO INV_ADMIN;
GRANT EXECUTE ON CopyContainer TO INV_ADMIN;
GRANT EXECUTE ON UpdateContainer TO INV_ADMIN;
GRANT EXECUTE ON RetireContainer TO INV_ADMIN;
GRANT EXECUTE ON CreateLocation TO INV_ADMIN;
GRANT EXECUTE ON DeleteContainer TO INV_ADMIN;
GRANT EXECUTE ON DeleteLocation TO INV_ADMIN;
GRANT EXECUTE ON UpdateLocation TO INV_ADMIN;
GRANT EXECUTE ON GetCompoundIdFromName TO INV_ADMIN;
GRANT EXECUTE ON MoveContainer TO INV_ADMIN;
GRANT EXECUTE ON MoveLocation TO INV_ADMIN;
GRANT EXECUTE ON SubstanceNameExists TO INV_ADMIN;
GRANT EXECUTE ON UpdateAllContainerFields TO INV_ADMIN;
GRANT EXECUTE ON UpdateContainerQtyRemaining TO INV_ADMIN;
GRANT EXECUTE ON Reservations TO INV_ADMIN;
GRANT EXECUTE ON CheckOutContainer TO INV_ADMIN;
GRANT EXECUTE ON Compounds TO INV_ADMIN;
GRANT EXECUTE ON links TO INV_ADMIN;
GRANT EXECUTE ON ISDUPLICATECOMPOUND TO INV_ADMIN;
GRANT EXECUTE ON GETCOMPOUNDID TO INV_ADMIN;
GRANT EXECUTE ON reports TO inv_admin;
GRANT EXECUTE ON reportparams TO inv_admin;
--GRANT EXECUTE ON Ordercontainer TO INV_ADMIN;
--GRANT EXECUTE ON ReOrdercontainer TO INV_ADMIN;
GRANT EXECUTE ON insertHazmatData TO INV_ADMIN;
GRANT EXECUTE ON UpdateHazmatData TO INV_ADMIN;
GRANT EXECUTE ON insertSubstanceHazmatData TO INV_ADMIN;
GRANT EXECUTE ON UpdateSubstanceHazmatData TO INV_ADMIN;
GRANT EXECUTE ON platesettings TO INV_ADMIN;
GRANT EXECUTE ON GetPKColumn TO INV_ADMIN;
GRANT EXECUTE ON UpdateTable TO INV_ADMIN;
GRANT EXECUTE ON CreateTableRow TO INV_ADMIN;
GRANT EXECUTE ON EmptyTrash TO INV_ADMIN;
GRANT EXECUTE ON InsertCheckInDetails TO INV_ADMIN;
GRANT EXECUTE ON DeleteTableRow TO INV_ADMIN;

GRANT INSERT, UPDATE, DELETE ON inv_barcode_desc TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_grid_format TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_grid_fill_template TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_grid_position TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_grid_storage TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_grid_element TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_enumeration TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_enumeration_set TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_eset_type TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inV_enum_values TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_physical_plate TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_plate_format TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_plate_types TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_plates TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_plate_history TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_plate_actions TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_wells TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_allowed_ctypes TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_allowed_ltypes TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_allowed_ptypes TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_well_parent TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON inv_plate_parent TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_COUNTRY TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_STATES TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_ADDRESS TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_REQUEST_TYPES TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_REQUEST_STATUS TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_REQUEST_SAMPLES TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_ORDER_STATUS TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_ORDERS TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_ORDER_CONTAINERS TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_CONTAINER_CHECKIN_DETAILS TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_SOLVENTS TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_WELL_COMPOUNDS TO INV_ADMIN;
GRANT INSERT, UPDATE, DELETE ON INV_OWNERS TO INV_ADMIN;

-- Plate proc privs
GRANT EXECUTE ON CreatePhysPlateType TO INV_ADMIN;
GRANT EXECUTE ON DeletePhysPlateType TO INV_ADMIN;
GRANT EXECUTE ON UpdatePhysPlateType TO INV_ADMIN;
GRANT EXECUTE ON CreatePlateFormat TO INV_ADMIN;
GRANT EXECUTE ON UpdatePlateFormat TO INV_ADMIN;
GRANT EXECUTE ON DeletePlateFormat TO INV_ADMIN;
GRANT EXECUTE ON UpdateWellFormat TO INV_ADMIN;
GRANT EXECUTE ON DeletePlate TO INV_ADMIN;
GRANT EXECUTE ON EnableGridForLocation TO INV_ADMIN;
GRANT EXECUTE ON AssignLocationToGrid TO INV_ADMIN;
GRANT EXECUTE ON CreateGridFormat TO INV_ADMIN;
GRANT EXECUTE ON MovePlate TO INV_ADMIN;
GRANT EXECUTE ON MovePlates TO INV_ADMIN;
GRANT EXECUTE ON CreatePlateMap TO INV_ADMIN;
GRANT EXECUTE ON CopyPlate TO INV_ADMIN;
GRANT EXECUTE ON DeletePlates TO INV_ADMIN;
GRANT EXECUTE ON RetirePlate TO INV_ADMIN;
GRANT EXECUTE ON SolvatePlates TO INV_ADMIN;
GRANT EXECUTE ON UpdatePlateAttributes TO INV_ADMIN;
GRANT EXECUTE ON UpdateWell TO INV_ADMIN;
GRANT EXECUTE ON CreatePlateXML TO INV_ADMIN;
GRANT EXECUTE ON UpdateAddress TO INV_ADMIN;
GRANT EXECUTE ON CertifyContainer TO INV_ADMIN;
GRANT EXECUTE ON Approvals TO INV_ADMIN;

-- Plate packages
GRANT EXECUTE ON Reformat TO INV_ADMIN;

