--Copyright 1999-2003 CambridgeSoft Corporation. All rights reserved

--run this script only if your datastructure was created prior to April, 2001.


Connect &&schemaName/&&schemaPass@&&serverName



ALTER TABLE "REGDB"."REG_NUMBERS" ADD ("SEQUENCE_INTERNAL_ID" NUMBER(8,0));
ALTER TABLE "REGDB"."REG_NUMBERS" ADD ("SEQUENCE_NUMBER" NUMBER(8,0));
ALTER TABLE "REGDB"."REG_NUMBERS" ADD ("REGISTRAR_PERSON_ID" NUMBER(8,0));

ALTER TABLE "REGDB"."TEMPORARY_STRUCTURES" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."COMPOUND_MOLECULE" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."COMPOUND_PROJECT" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."REG_NUMBERS" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."REG_APPROVED" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."REG_QUALITY_CHECKED" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."MIXTURES" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."DUPLICATES" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."COMPOUND_SALT" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."BATCHES" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."ALT_IDS" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."STRUCTURES" ADD("DATETIME_STAMP" VARCHAR2(30));

ALTER TABLE "REGDB"."TEST_SAMPLES" ADD("DATETIME_STAMP" VARCHAR2(30));
ALTER TABLE "REGDB"."SPECTRA" ADD("DATETIME_STAMP" VARCHAR2(30));



commit;
