--Copyright 1999-2003 CambridgeSoft Corporation. All rights reserved

--table creation script for CHEM_REG CS_SECURITY/Oracle version Copyright Cambridgesoft corp 1999-2001 all rights reserved
-- assumes that CS_SECURITY and REGDB tablespaces exist

--#########################################################
--CREATE TABLES
--#########################################################

Connect &&securitySchemaName/&&securitySchemaPass@&&serverName

DECLARE
	n NUMBER;
BEGIN
	select count(*) into n from user_tables where table_name = Upper('&&privTableName');
	if n = 1 then
		execute immediate '
		DROP TABLE &&privTableName CASCADE CONSTRAINTS';
	end if;
END;
/

CREATE TABLE  &&privTableName (
	ROLE_INTERNAL_ID NUMBER(8,0) not null,
	CAMSOFT_LOG_ON NUMBER(1,0) null,
	SEARCH_TEMP NUMBER(1,0) null,
	SEARCH_REG NUMBER(1,0) null,
	ADD_COMPOUND_TEMP NUMBER(1,0) null,
	ADD_BATCH_TEMP NUMBER(1,0) null,
	ADD_SALT_TEMP NUMBER(1,0) null,
	ADD_IDENTIFIER_TEMP NUMBER(1,0) null,
	EDIT_COMPOUND_TEMP NUMBER(1,0) null,
	EDIT_BATCH_TEMP NUMBER(1,0) null,
	EDIT_SALT_TEMP NUMBER(1,0) null,
	EDIT_IDENTIFIERS_TEMP NUMBER(1,0) null,
	DELETE_TEMP NUMBER(1,0) null,
	REGISTER_TEMP NUMBER(1,0) null,
	EDIT_COMPOUND_REG NUMBER(1,0) null,
	EDIT_BATCH_REG NUMBER(1,0) null,
	EDIT_SALT_REG NUMBER(1,0) null,
	EDIT_IDENTIFIERS_REG NUMBER(1,0) null,
	DELETE_REG NUMBER(1,0) null,
	DELETE_BATCH_REG NUMBER(1,0) null,
	EDIT_SCOPE_SELF NUMBER(1,0) null,
	EDIT_SCOPE_SUPERVISOR NUMBER(1,0) null,
	EDIT_SCOPE_ALL NUMBER(1,0) null,
	SET_APPROVED_FLAG NUMBER(1,0) null,
	TOGGLE_APPROVED_FLAG NUMBER(1,0) null,
	SET_QUALITY_CHECK_FLAG NUMBER(1,0) null,
	TOGGLE_QUALITY_CHECK_FLAG NUMBER(1,0) null,
	EDIT_SALT_TABLE NUMBER(1,0) null,
	ADD_SALT_TABLE NUMBER(1,0) null,
	DELETE_SALT_TABLE NUMBER(1,0) null,
	EDIT_SEQUENCES_TABLE NUMBER(1,0) null,
	ADD_SEQUENCES_TABLE NUMBER(1,0) null,
	DELETE_SEQUENCES_TABLE NUMBER(1,0) null,
	EDIT_NOTEBOOKS_TABLE NUMBER(1,0) null,
	ADD_NOTEBOOKS_TABLE NUMBER(1,0) null,
	DELETE_NOTEBOOKS_TABLE NUMBER(1,0) null,
	EDIT_PROJECTS_TABLE NUMBER(1,0) null,
	ADD_PROJECTS_TABLE NUMBER(1,0) null,
	DELETE_PROJECTS_TABLE NUMBER(1,0) null,
	EDIT_SOLVATES_TABLE NUMBER(1,0) null,
	ADD_SOLVATES_TABLE NUMBER(1,0) null,
	DELETE_SOLVATES_TABLE NUMBER(1,0) null,
	EDIT_COMPOUND_TYPE_TABLE NUMBER(1,0) null,
	ADD_COMPOUND_TYPE_TABLE NUMBER(1,0) null,
	DELETE_COMPOUND_TYPE_TABLE NUMBER(1,0) null,
	EDIT_UTILIZATIONS_TABLE NUMBER(1,0) null,
	ADD_UTILIZATIONS_TABLE NUMBER(1,0) null,
	DELETE_UTILIZATIONS_TABLE NUMBER(1,0) null,
	EDIT_BATCH_PROJECTS_TABLE NUMBER(1,0) null,
	ADD_BATCH_PROJECTS_TABLE NUMBER(1,0) null,
	DELETE_BATCH_PROJECTS_TABLE NUMBER(1,0) null,
	EDIT_USERS_TABLE NUMBER(1,0) null,
	EDIT_PEOPLE_TABLE NUMBER(1,0) null,
	ADD_PEOPLE_TABLE NUMBER(1,0) null,
	DELETE_PEOPLE_TABLE NUMBER(1,0) null,
	EDIT_WORKGROUP NUMBER(1,0) null,
	ADD_WORKGROUP NUMBER(1,0) null,
	DELETE_WORKGROUP NUMBER(1,0) null,
	EDIT_EVAL_DATA NUMBER(1,0) null,
	ADD_EVAL_DATA NUMBER(1,0) null,
	SEARCH_EVAL_DATA NUMBER(1,0) null,
	EDIT_SITES_TABLE NUMBER(1,0) null, 
	ADD_ANALYTICS_TABLES NUMBER(1,0) null,
	DELETE_ANALYTICS_TABLES NUMBER(1,0) null,
	EDIT_ANALYTICS_TABLES NUMBER(1,0) null,
	DELETE_SITES_TABLE NUMBER(1,0) null,
	ADD_SITES_TABLE NUMBER(1,0) null,
	DELETE_EVAL_DATA NUMBER(1,0) null, 
	SITE_ACCESS_ALL NUMBER(1,0) null, 
	constraint PK_CHEMREG_PRIVS 
		primary key (ROLE_INTERNAL_ID)
	) TABLESPACE &&securityTableSpaceName
;

		
--#########################################################
--CREATE PUBLIC SYNONYM
--#########################################################
Connect &&InstallUser/&&sysPass@&&serverName

DECLARE
	PROCEDURE createSynonym(synName IN varchar2) IS
			n NUMBER;
		BEGIN
			select count(*) into n from dba_synonyms where Upper(synonym_name) = synName;
			if n = 0 then
				execute immediate 'CREATE PUBLIC SYNONYM ' || synName || ' FOR &&schemaName..' || synName;
			end if;
		END createSynonym;
BEGIN
	createSynonym('&&privTableName');
END;
/

--#########################################################
--CREATE ROLES
--#########################################################

prompt 'dropping test roles...'

DECLARE
	PROCEDURE dropRole(roleName IN varchar2) IS
			n NUMBER;
		BEGIN
			select count(*) into n from dba_roles where Upper(role) = roleName;
			if n > 0 then
				execute immediate 'DROP ROLE ' || roleName;
			end if;
		END dropRole;
BEGIN
	dropRole('BROWSER');
	dropRole('SUBMITTER');
	dropRole('SUPERVISING_SCIENTIST');
	dropRole('CHEMICAL_ADMINISTRATOR');
	dropRole('SUPERVISING_CHEMICAL_ADMIN');
	dropRole('PERFUME_CHEMIST');
END;
/

--CREATE_MASTER_ROLES
--BROWSER
	CREATE ROLE BROWSER NOT IDENTIFIED;
	REVOKE "BROWSER" FROM "SYSTEM";
	GRANT "CONNECT" TO "BROWSER";
--SUBMITTER
	CREATE ROLE SUBMITTER NOT IDENTIFIED;
	REVOKE "SUBMITTER" FROM "SYSTEM";
	GRANT CONNECT TO SUBMITTER;
--SUPERVISING_SCIENTIST
	CREATE ROLE SUPERVISING_SCIENTIST NOT IDENTIFIED;
	REVOKE "SUPERVISING_SCIENTIST" FROM "SYSTEM";
	GRANT CONNECT TO SUPERVISING_SCIENTIST;
--CHEMICAL_ADMINISTRATOR
	CREATE ROLE CHEMICAL_ADMINISTRATOR NOT IDENTIFIED;
	REVOKE "CHEMICAL_ADMINISTRATOR" FROM "SYSTEM";
	GRANT CONNECT TO CHEMICAL_ADMINISTRATOR;
--SUPERVISING_CHEMICAL_ADMIN
	CREATE ROLE SUPERVISING_CHEMICAL_ADMIN NOT IDENTIFIED;
	REVOKE "SUPERVISING_CHEMICAL_ADMIN" FROM "SYSTEM";
	GRANT CONNECT TO SUPERVISING_CHEMICAL_ADMIN;
--PERFUME_CHEMIST
	CREATE ROLE PERFUME_CHEMIST NOT IDENTIFIED;
	REVOKE "PERFUME_CHEMIST" FROM "SYSTEM";
	GRANT CONNECT TO PERFUME_CHEMIST;


-- System Privileges
	--these are revoked in the 172 script. They are left here to avoid the script errors
	GRANT SELECT ANY TABLE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT CREATE USER TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT DROP USER TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT ALTER USER TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT CREATE ROLE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT ALTER ANY ROLE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT DROP ANY ROLE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT GRANT ANY ROLE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT GRANT ANY PRIVILEGE TO SUPERVISING_CHEMICAL_ADMIN;

Connect &&schemaName/&&schemaPass@&&serverName

-- BROWSER
	GRANT SELECT ON NOTEBOOKS TO BROWSER;
	GRANT SELECT ON PROJECTS TO BROWSER;
	GRANT SELECT ON SALTS TO BROWSER;
	GRANT SELECT ON SOLVATES TO BROWSER;
	GRANT SELECT ON COMPOUND_TYPE TO BROWSER;
	GRANT SELECT ON NOTEBOOKS TO BROWSER;
	GRANT SELECT ON SALTS TO BROWSER;
	GRANT SELECT ON COMPOUND_TYPE TO BROWSER;
	GRANT SELECT ON ALT_IDS TO BROWSER;
	GRANT SELECT ON BATCHES TO BROWSER;
	GRANT SELECT ON COMMIT_TYPES TO BROWSER;
	GRANT SELECT ON COMPOUND_MOLECULE TO BROWSER;
	GRANT SELECT ON COMPOUND_PROJECT TO BROWSER;
	GRANT SELECT ON COMPOUND_SALT TO BROWSER;
	GRANT SELECT ON COMPOUND_TYPE TO BROWSER;
	GRANT SELECT ON DUPLICATES TO BROWSER;
	GRANT SELECT ON IDENTIFIERS TO BROWSER;
	GRANT SELECT ON MIXTURES TO BROWSER;
	GRANT SELECT ON NOTEBOOKS TO BROWSER;
	GRANT SELECT ON REG_APPROVED TO BROWSER;
	GRANT SELECT ON REG_NUMBERS TO BROWSER;
	GRANT SELECT ON REG_QUALITY_CHECKED TO BROWSER;
	GRANT SELECT ON SALTS TO BROWSER;
	GRANT SELECT ON SEQUENCE TO BROWSER;
	GRANT SELECT ON SPECTRA TO BROWSER;
	GRANT SELECT ON STRUCTURE_MIXTURE TO BROWSER;
	GRANT SELECT ON STRUCTURES TO BROWSER;
	GRANT SELECT ON MOLFILES TO BROWSER;
	GRANT SELECT ON EXPERIMENTS TO BROWSER;
	GRANT SELECT ON EXPERIMENTTYPE TO BROWSER;
	GRANT SELECT ON RESULTS TO BROWSER;
	GRANT SELECT ON RESULTTYPE TO BROWSER;
	GRANT SELECT ON PARAMETERS TO BROWSER;
	GRANT SELECT ON PARAMETERTYPE TO BROWSER;
	GRANT SELECT ON EXPERIMENTTYPEPARAMETERS TO BROWSER;
	GRANT SELECT ON EXPERIMENTTYPERESULTS TO BROWSER;
	GRANT SELECT ON BATCH_PROJECTS TO BROWSER;
	GRANT SELECT ON BATCH_PROJ_UTILIZATIONS TO BROWSER;
	GRANT SELECT ON UTILIZATIONS TO BROWSER;
	GRANT SELECT ON CMPD_MOL_UTILIZATIONS TO BROWSER;
	
-- 	SUBMITTER	
	GRANT SELECT ON TEMPORARY_STRUCTURES TO SUBMITTER;	
	GRANT SELECT ON NOTEBOOKS TO SUBMITTER;
	GRANT SELECT ON PROJECTS TO SUBMITTER;
	GRANT SELECT ON SALTS TO SUBMITTER;
	GRANT SELECT ON SOLVATES TO SUBMITTER;
	GRANT SELECT ON COMPOUND_TYPE TO SUBMITTER;
	GRANT SELECT ON ALT_IDS TO SUBMITTER;
	GRANT SELECT ON BATCHES TO SUBMITTER;
	GRANT SELECT ON COMMIT_TYPES TO SUBMITTER;
	GRANT SELECT ON COMPOUND_MOLECULE TO SUBMITTER;
	GRANT SELECT ON COMPOUND_PROJECT TO SUBMITTER;
	GRANT SELECT ON COMPOUND_SALT TO SUBMITTER;
	GRANT SELECT ON COMPOUND_TYPE TO SUBMITTER;
	GRANT SELECT ON DUPLICATES TO SUBMITTER;
	GRANT SELECT ON IDENTIFIERS TO SUBMITTER;
	GRANT SELECT ON MIXTURES TO SUBMITTER;
	GRANT SELECT ON NOTEBOOKS TO SUBMITTER;
	GRANT SELECT ON PROJECTS TO SUBMITTER;
	GRANT SELECT ON REG_APPROVED TO SUBMITTER;
	GRANT SELECT ON REG_NUMBERS TO SUBMITTER;
	GRANT SELECT ON REG_QUALITY_CHECKED TO SUBMITTER;
	GRANT SELECT ON SALTS TO SUBMITTER;
	GRANT SELECT ON SEQUENCE TO SUBMITTER;
	GRANT SELECT ON SPECTRA TO SUBMITTER;
	GRANT SELECT ON STRUCTURE_MIXTURE TO SUBMITTER;
	GRANT SELECT ON STRUCTURES TO SUBMITTER;
	GRANT SELECT ON MOLFILES TO SUBMITTER;
	GRANT SELECT ON TEST_SAMPLES TO SUBMITTER;	
	GRANT INSERT ON ALT_IDS TO SUBMITTER;
	GRANT INSERT ON BATCHES TO SUBMITTER;
	GRANT INSERT ON COMPOUND_PROJECT TO SUBMITTER;
	GRANT INSERT ON COMPOUND_MOLECULE TO SUBMITTER;
	GRANT INSERT ON COMPOUND_SALT TO SUBMITTER;
	GRANT INSERT ON DUPLICATES TO SUBMITTER;
	GRANT INSERT ON MIXTURES TO SUBMITTER;
	GRANT INSERT ON REG_APPROVED TO SUBMITTER;
	GRANT INSERT ON REG_NUMBERS TO SUBMITTER;
	GRANT INSERT ON REG_QUALITY_CHECKED TO SUBMITTER;	
	GRANT INSERT ON SPECTRA TO SUBMITTER;
	GRANT INSERT ON STRUCTURE_MIXTURE TO SUBMITTER;
	GRANT INSERT ON STRUCTURES TO SUBMITTER;
	GRANT INSERT ON MOLFILES TO SUBMITTER;
	GRANT INSERT ON TEST_SAMPLES TO SUBMITTER;
	GRANT INSERT ON TEMPORARY_STRUCTURES TO SUBMITTER;
	GRANT DELETE ON TEMPORARY_STRUCTURES TO SUBMITTER;
	GRANT UPDATE ON TEMPORARY_STRUCTURES TO SUBMITTER;
	GRANT UPDATE ON SEQUENCE TO SUBMITTER;
	GRANT UPDATE ON TEMPORARY_STRUCTURES TO SUBMITTER;
	GRANT UPDATE ON BATCHES TO SUBMITTER;
	GRANT UPDATE ON COMPOUND_MOLECULE TO SUBMITTER;
	GRANT UPDATE ON STRUCTURES TO SUBMITTER;
	GRANT UPDATE ON MOLFILES TO SUBMITTER;
	GRANT UPDATE ON COMPOUND_SALT TO SUBMITTER;
	GRANT UPDATE ON COMPOUND_PROJECT TO SUBMITTER;
	GRANT UPDATE ON ALT_IDS TO SUBMITTER;
	GRANT UPDATE ON REG_NUMBERS TO SUBMITTER;
	GRANT SELECT,INSERT,UPDATE ON EXPERIMENTS TO SUBMITTER;
	GRANT SELECT,INSERT,UPDATE  ON EXPERIMENTTYPE TO SUBMITTER;
	GRANT SELECT,INSERT,UPDATE  ON RESULTS TO SUBMITTER;
	GRANT SELECT,INSERT,UPDATE  ON RESULTTYPE TO SUBMITTER;
	GRANT SELECT,INSERT,UPDATE  ON PARAMETERS TO SUBMITTER;
	GRANT SELECT,INSERT,UPDATE  ON PARAMETERTYPE TO SUBMITTER;
	GRANT SELECT,INSERT,UPDATE  ON EXPERIMENTTYPEPARAMETERS TO SUBMITTER;
	GRANT SELECT,INSERT,UPDATE  ON EXPERIMENTTYPERESULTS TO SUBMITTER;
	GRANT SELECT ON BATCH_PROJECTS TO SUBMITTER;
	GRANT SELECT ON BATCH_PROJ_UTILIZATIONS TO SUBMITTER;
	GRANT SELECT ON UTILIZATIONS TO SUBMITTER;
	GRANT SELECT, INSERT ON CMPD_MOL_UTILIZATIONS TO SUBMITTER;

-- SUPERVISING_SCIENTIST	
	GRANT SELECT ON TEMPORARY_STRUCTURES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON NOTEBOOKS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON PROJECTS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON SALTS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON SOLVATES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON COMPOUND_TYPE TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON ALT_IDS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON BATCHES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON COMMIT_TYPES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON COMPOUND_MOLECULE TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON COMPOUND_PROJECT TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON COMPOUND_SALT TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON COMPOUND_TYPE TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON DUPLICATES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON IDENTIFIERS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON MIXTURES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON NOTEBOOKS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON PROJECTS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON REG_APPROVED TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON REG_NUMBERS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON REG_QUALITY_CHECKED TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON SALTS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON SOLVATES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON SEQUENCE TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON SPECTRA TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON STRUCTURE_MIXTURE TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON STRUCTURES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON MOLFILES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON TEST_SAMPLES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON REG_APPROVED TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON ALT_IDS TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON BATCHES TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON COMPOUND_PROJECT TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON COMPOUND_MOLECULE TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON COMPOUND_SALT TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON DUPLICATES TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON MIXTURES TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON REG_NUMBERS TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON SPECTRA TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON STRUCTURE_MIXTURE TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON STRUCTURES TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON MOLFILES TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON TEST_SAMPLES TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON TEMPORARY_STRUCTURES TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON TEMPORARY_STRUCTURES TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON TEMPORARY_STRUCTURES TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON SEQUENCE TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON TEMPORARY_STRUCTURES TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON BATCHES TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON COMPOUND_MOLECULE TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON STRUCTURES TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON MOLFILES TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON COMPOUND_SALT TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON COMPOUND_PROJECT TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON ALT_IDS TO SUPERVISING_SCIENTIST;
	GRANT UPDATE ON REG_NUMBERS TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON ALT_IDS TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON BATCHES TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON COMPOUND_MOLECULE TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON COMPOUND_PROJECT TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON COMPOUND_SALT TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON DUPLICATES TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON MIXTURES TO SUPERVISING_SCIENTIST;	
	GRANT DELETE ON SPECTRA TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON STRUCTURE_MIXTURE TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON STRUCTURES TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON MOLFILES TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON TEST_SAMPLES TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON REG_NUMBERS TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON REG_APPROVED TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON REG_QUALITY_CHECKED TO SUPERVISING_SCIENTIST;
	GRANT INSERT ON REG_APPROVED TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON REG_APPROVED TO SUPERVISING_SCIENTIST;
	GRANT DELETE ON REG_QUALITY_CHECKED TO SUPERVISING_SCIENTIST;
	GRANT SELECT,INSERT,UPDATE ON EXPERIMENTS TO SUPERVISING_SCIENTIST;
	GRANT SELECT,INSERT,UPDATE  ON EXPERIMENTTYPE TO SUPERVISING_SCIENTIST;
	GRANT SELECT,INSERT,UPDATE  ON RESULTS TO SUPERVISING_SCIENTIST;
	GRANT SELECT,INSERT,UPDATE  ON RESULTTYPE TO SUPERVISING_SCIENTIST;
	GRANT SELECT,INSERT,UPDATE  ON PARAMETERS TO SUPERVISING_SCIENTIST;
	GRANT SELECT,INSERT,UPDATE  ON PARAMETERTYPE TO SUPERVISING_SCIENTIST;
	GRANT SELECT,INSERT,UPDATE  ON EXPERIMENTTYPEPARAMETERS TO SUPERVISING_SCIENTIST;
	GRANT SELECT,INSERT,UPDATE  ON EXPERIMENTTYPERESULTS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON BATCH_PROJECTS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON BATCH_PROJ_UTILIZATIONS TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON UTILIZATIONS TO SUPERVISING_SCIENTIST;
	GRANT SELECT, INSERT, UPDATE  ON CMPD_MOL_UTILIZATIONS TO SUPERVISING_SCIENTIST;
		
-- CHEMICAL_ADMINISTRATOR
	GRANT SELECT,INSERT,DELETE,UPDATE ON TEMPORARY_STRUCTURES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON NOTEBOOKS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON PROJECTS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON SALTS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON SOLVATES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON COMPOUND_TYPE TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON ALT_IDS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON BATCHES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON COMMIT_TYPES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON COMPOUND_MOLECULE TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON COMPOUND_PROJECT TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON COMPOUND_SALT TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON COMPOUND_TYPE TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON DUPLICATES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON IDENTIFIERS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON MIXTURES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON NOTEBOOKS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON PROJECTS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON REG_APPROVED TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON REG_NUMBERS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON REG_QUALITY_CHECKED TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON SALTS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON SEQUENCE TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON SPECTRA TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON STRUCTURE_MIXTURE TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON STRUCTURES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON MOLFILES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON TEST_SAMPLES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON REG_APPROVED TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON EXPERIMENTS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON EXPERIMENTTYPE TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON RESULTS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON RESULTTYPE TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON PARAMETERS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON PARAMETERTYPE TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON EXPERIMENTTYPEPARAMETERS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON EXPERIMENTTYPERESULTS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON SALTS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON SOLVATES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON SEQUENCE TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON NOTEBOOKS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON COMPOUND_TYPE TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE,UPDATE ON PROJECTS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,UPDATE ON BATCH_PROJECTS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,UPDATE ON BATCH_PROJ_UTILIZATIONS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,UPDATE ON UTILIZATIONS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,UPDATE ON CMPD_MOL_UTILIZATIONS TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE ON REG_APPROVED TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT,INSERT,DELETE ON REG_QUALITY_CHECKED TO CHEMICAL_ADMINISTRATOR;
	
-- SUPERVISING_CHEMICAL_ADMIN
	GRANT SELECT,UPDATE,INSERT,DELETE ON TEMPORARY_STRUCTURES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON NOTEBOOKS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON PROJECTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON COMPOUND_TYPE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON ALT_IDS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON BATCHES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON COMMIT_TYPES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON COMPOUND_MOLECULE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON COMPOUND_PROJECT TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON COMPOUND_SALT TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON COMPOUND_TYPE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON DUPLICATES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON IDENTIFIERS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON MIXTURES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON NOTEBOOKS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON REG_APPROVED TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON REG_NUMBERS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON REG_QUALITY_CHECKED TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON SEQUENCE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON SPECTRA TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON STRUCTURE_MIXTURE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON STRUCTURES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON MOLFILES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON TEST_SAMPLES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,DELETE,UPDATE ON EXPERIMENTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,DELETE,UPDATE ON EXPERIMENTTYPE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,DELETE,UPDATE ON RESULTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,DELETE,UPDATE ON RESULTTYPE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,DELETE,UPDATE ON PARAMETERS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,DELETE,UPDATE ON PARAMETERTYPE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,DELETE,UPDATE ON EXPERIMENTTYPEPARAMETERS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,DELETE,UPDATE ON EXPERIMENTTYPERESULTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON SALTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON SOLVATES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON SEQUENCE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON NOTEBOOKS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON COMPOUND_TYPE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,UPDATE,INSERT,DELETE ON PROJECTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON BATCH_PROJECTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON BATCH_PROJ_UTILIZATIONS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON UTILIZATIONS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON CMPD_MOL_UTILIZATIONS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT ON REG_APPROVED TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT INSERT ON REG_APPROVED TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT DELETE ON REG_APPROVED TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT ON REG_QUALITY_CHECKED TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT INSERT ON REG_QUALITY_CHECKED TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT DELETE ON REG_QUALITY_CHECKED TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON EXPERIMENTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON EXPERIMENTTYPE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON RESULTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON RESULTTYPE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON PARAMETERS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON PARAMETERTYPE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON EXPERIMENTTYPEPARAMETERS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON EXPERIMENTTYPERESULTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON BATCH_PROJECTS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON BATCH_PROJ_UTILIZATIONS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON UTILIZATIONS TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON CMPD_MOL_UTILIZATIONS TO SUPERVISING_CHEMICAL_ADMIN;
	
-- PERFUME_CHEMIST
	GRANT SELECT ON NOTEBOOKS TO PERFUME_CHEMIST;
	GRANT SELECT ON PROJECTS TO PERFUME_CHEMIST;
	GRANT SELECT ON SALTS TO PERFUME_CHEMIST;
	GRANT SELECT ON SOLVATES TO PERFUME_CHEMIST;
	GRANT SELECT ON COMPOUND_TYPE TO PERFUME_CHEMIST;
	GRANT SELECT ON NOTEBOOKS TO PERFUME_CHEMIST;
	GRANT SELECT ON PROJECTS TO PERFUME_CHEMIST;
	GRANT SELECT ON SALTS TO PERFUME_CHEMIST;
	GRANT SELECT ON COMPOUND_TYPE TO PERFUME_CHEMIST;
	GRANT SELECT ON ALT_IDS TO PERFUME_CHEMIST;
	GRANT SELECT ON BATCHES TO PERFUME_CHEMIST;
	GRANT SELECT ON COMMIT_TYPES TO PERFUME_CHEMIST;
	GRANT SELECT ON COMPOUND_MOLECULE TO PERFUME_CHEMIST;
	GRANT SELECT ON COMPOUND_PROJECT TO PERFUME_CHEMIST;
	GRANT SELECT ON COMPOUND_SALT TO PERFUME_CHEMIST;
	GRANT SELECT ON COMPOUND_TYPE TO PERFUME_CHEMIST;
	GRANT SELECT ON DUPLICATES TO PERFUME_CHEMIST;
	GRANT SELECT ON IDENTIFIERS TO PERFUME_CHEMIST;
	GRANT SELECT ON MIXTURES TO PERFUME_CHEMIST;
	GRANT SELECT ON REG_APPROVED TO PERFUME_CHEMIST;
	GRANT SELECT ON REG_NUMBERS TO PERFUME_CHEMIST;
	GRANT SELECT ON REG_QUALITY_CHECKED TO PERFUME_CHEMIST;
	GRANT SELECT ON SALTS TO PERFUME_CHEMIST;
	GRANT SELECT ON SEQUENCE TO PERFUME_CHEMIST;
	GRANT SELECT ON SPECTRA TO PERFUME_CHEMIST;
	GRANT SELECT ON STRUCTURE_MIXTURE TO PERFUME_CHEMIST;
	GRANT SELECT ON STRUCTURES TO PERFUME_CHEMIST;	
	GRANT SELECT ON MOLFILES TO PERFUME_CHEMIST;	
	GRANT SELECT,INSERT,UPDATE ON BATCH_PROJECTS TO PERFUME_CHEMIST;
	GRANT SELECT ON BATCH_PROJ_UTILIZATIONS TO PERFUME_CHEMIST;
	GRANT SELECT ON UTILIZATIONS TO PERFUME_CHEMIST;
	GRANT SELECT ON CMPD_MOL_UTILIZATIONS TO PERFUME_CHEMIST;
	GRANT SELECT,INSERT,UPDATE,DELETE ON EXPERIMENTS TO PERFUME_CHEMIST;
	GRANT SELECT,INSERT,UPDATE,DELETE ON EXPERIMENTTYPE TO PERFUME_CHEMIST;
	GRANT SELECT,INSERT,UPDATE,DELETE ON RESULTS TO PERFUME_CHEMIST;
	GRANT SELECT,INSERT,UPDATE,DELETE ON RESULTTYPE TO PERFUME_CHEMIST;
	GRANT SELECT,INSERT,UPDATE,DELETE ON PARAMETERS TO PERFUME_CHEMIST;
	GRANT SELECT,INSERT,UPDATE,DELETE ON PARAMETERTYPE TO PERFUME_CHEMIST;
	GRANT SELECT,INSERT,UPDATE,DELETE ON EXPERIMENTTYPEPARAMETERS TO PERFUME_CHEMIST;
	GRANT SELECT,INSERT,UPDATE,DELETE ON EXPERIMENTTYPERESULTS TO PERFUME_CHEMIST;
	


Connect &&securitySchemaName/&&securitySchemaPass@&&serverName

-- BROWSER 
	GRANT SELECT ON SECURITY_ROLES TO BROWSER;
	GRANT SELECT ON PRIVILEGE_TABLES TO BROWSER;
	GRANT SELECT ON CHEM_REG_PRIVILEGES TO BROWSER;
-- SUBMITTER
	GRANT SELECT ON SECURITY_ROLES TO SUBMITTER;
	GRANT SELECT ON PRIVILEGE_TABLES TO SUBMITTER;
	GRANT SELECT ON CHEM_REG_PRIVILEGES TO SUBMITTER;
-- SUPERVISING_SCIENTIST
	GRANT UPDATE ON PEOPLE TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON SECURITY_ROLES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON PRIVILEGE_TABLES TO SUPERVISING_SCIENTIST;
	GRANT SELECT ON CHEM_REG_PRIVILEGES TO SUPERVISING_SCIENTIST;
-- CHEMICAL_ADMINISTRATOR
	GRANT SELECT ON SECURITY_ROLES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT ON PRIVILEGE_TABLES TO CHEMICAL_ADMINISTRATOR;
	GRANT SELECT ON CHEM_REG_PRIVILEGES TO CHEMICAL_ADMINISTRATOR;
	GRANT INSERT,UPDATE  ON PEOPLE TO CHEMICAL_ADMINISTRATOR;
	GRANT INSERT, UPDATE ON SITES TO CHEMICAL_ADMINISTRATOR;
-- SUPERVISING_CHEMICAL_ADMIN
	GRANT INSERT,UPDATE,DELETE ON SITES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT INSERT,UPDATE,DELETE ON PEOPLE TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON SECURITY_ROLES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT,INSERT,UPDATE,DELETE ON CHEM_REG_PRIVILEGES TO SUPERVISING_CHEMICAL_ADMIN;
	GRANT SELECT ON PRIVILEGE_TABLES TO SUPERVISING_CHEMICAL_ADMIN;
-- PERFUME_CHEMIST
	GRANT SELECT ON SECURITY_ROLES TO PERFUME_CHEMIST;
	GRANT SELECT ON PRIVILEGE_TABLES TO PERFUME_CHEMIST;
	GRANT SELECT ON CHEM_REG_PRIVILEGES TO PERFUME_CHEMIST;


-- Data Inserts

--PRIVELEGE_TABLES
delete from security_roles where Privilege_Table_Int_ID IN(select privilege_table_id from privilege_tables where TABLE_SPACE = 'T_REGDB');
delete from privilege_tables where TABLE_SPACE = 'T_REGDB';
commit;

delete from security_roles where ROLE_NAME Like 'BROWSER';
delete from security_roles where ROLE_NAME Like 'SUBMITTER';
delete from security_roles where ROLE_NAME Like 'SUPERVISING_SCIENTIST';
delete from security_roles where ROLE_NAME Like 'CHEMICAL_ADMINISTRATOR';
delete from security_roles where ROLE_NAME Like 'SUPERVISING_CHEMICAL_ADMIN';
delete from security_roles where ROLE_NAME Like 'PERFUME_CHEMIST';
commit;

INSERT INTO PRIVILEGE_TABLES (PRIVILEGE_TABLE_ID,APP_NAME, APP_URL,PRIVILEGE_TABLE_NAME,TABLE_SPACE) values(PRIVILEGE_TABLES_seq.NextVal,'Chemical Registration', '', 'CHEM_REG_PRIVILEGES', 'T_REGDB');

--Browser
INSERT INTO SECURITY_ROLES (ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME)values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'BROWSER');
INSERT INTO CHEM_REG_PRIVILEGES(ROLE_INTERNAL_ID,CAMSOFT_LOG_ON,SEARCH_TEMP,SEARCH_REG,ADD_COMPOUND_TEMP,ADD_BATCH_TEMP,ADD_SALT_TEMP,ADD_IDENTIFIER_TEMP,EDIT_COMPOUND_TEMP,EDIT_BATCH_TEMP,EDIT_SALT_TEMP,EDIT_IDENTIFIERS_TEMP,DELETE_TEMP,REGISTER_TEMP,EDIT_COMPOUND_REG,EDIT_BATCH_REG,EDIT_SALT_REG,EDIT_IDENTIFIERS_REG,DELETE_REG,DELETE_BATCH_REG,EDIT_SCOPE_SELF,EDIT_SCOPE_SUPERVISOR,EDIT_SCOPE_ALL,SET_APPROVED_FLAG,TOGGLE_APPROVED_FLAG,SET_QUALITY_CHECK_FLAG,TOGGLE_QUALITY_CHECK_FLAG,EDIT_SALT_TABLE,ADD_SALT_TABLE,DELETE_SALT_TABLE,EDIT_SEQUENCES_TABLE,ADD_SEQUENCES_TABLE,DELETE_SEQUENCES_TABLE,EDIT_NOTEBOOKS_TABLE,ADD_NOTEBOOKS_TABLE,DELETE_NOTEBOOKS_TABLE,EDIT_PROJECTS_TABLE,ADD_PROJECTS_TABLE,DELETE_PROJECTS_TABLE,EDIT_SOLVATES_TABLE,ADD_SOLVATES_TABLE,DELETE_SOLVATES_TABLE,EDIT_COMPOUND_TYPE_TABLE,ADD_COMPOUND_TYPE_TABLE,DELETE_COMPOUND_TYPE_TABLE,EDIT_UTILIZATIONS_TABLE,ADD_UTILIZATIONS_TABLE,DELETE_UTILIZATIONS_TABLE,EDIT_BATCH_PROJECTS_TABLE,ADD_BATCH_PROJECTS_TABLE,DELETE_BATCH_PROJECTS_TABLE,EDIT_USERS_TABLE,EDIT_PEOPLE_TABLE,ADD_PEOPLE_TABLE,DELETE_PEOPLE_TABLE,EDIT_WORKGROUP,ADD_WORKGROUP,DELETE_WORKGROUP,EDIT_EVAL_DATA,ADD_EVAL_DATA,SEARCH_EVAL_DATA,EDIT_SITES_TABLE,ADD_ANALYTICS_TABLES,DELETE_ANALYTICS_TABLES,EDIT_ANALYTICS_TABLES,DELETE_SITES_TABLE,ADD_SITES_TABLE,DELETE_EVAL_DATA,SITE_ACCESS_ALL)values(SECURITY_ROLES_SEQ.CURRVAL,'1','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0');

--Submitter
INSERT INTO SECURITY_ROLES (ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME)values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'SUBMITTER');
INSERT INTO CHEM_REG_PRIVILEGES(ROLE_INTERNAL_ID,CAMSOFT_LOG_ON,SEARCH_TEMP,SEARCH_REG,ADD_COMPOUND_TEMP,ADD_BATCH_TEMP,ADD_SALT_TEMP,ADD_IDENTIFIER_TEMP,EDIT_COMPOUND_TEMP,EDIT_BATCH_TEMP,EDIT_SALT_TEMP,EDIT_IDENTIFIERS_TEMP,DELETE_TEMP,REGISTER_TEMP,EDIT_COMPOUND_REG,EDIT_BATCH_REG,EDIT_SALT_REG,EDIT_IDENTIFIERS_REG,DELETE_REG,DELETE_BATCH_REG,EDIT_SCOPE_SELF,EDIT_SCOPE_SUPERVISOR,EDIT_SCOPE_ALL,SET_APPROVED_FLAG,TOGGLE_APPROVED_FLAG,SET_QUALITY_CHECK_FLAG,TOGGLE_QUALITY_CHECK_FLAG,EDIT_SALT_TABLE,ADD_SALT_TABLE,DELETE_SALT_TABLE,EDIT_SEQUENCES_TABLE,ADD_SEQUENCES_TABLE,DELETE_SEQUENCES_TABLE,EDIT_NOTEBOOKS_TABLE,ADD_NOTEBOOKS_TABLE,DELETE_NOTEBOOKS_TABLE,EDIT_PROJECTS_TABLE,ADD_PROJECTS_TABLE,DELETE_PROJECTS_TABLE,EDIT_SOLVATES_TABLE,ADD_SOLVATES_TABLE,DELETE_SOLVATES_TABLE,EDIT_COMPOUND_TYPE_TABLE,ADD_COMPOUND_TYPE_TABLE,DELETE_COMPOUND_TYPE_TABLE,EDIT_UTILIZATIONS_TABLE,ADD_UTILIZATIONS_TABLE,DELETE_UTILIZATIONS_TABLE,EDIT_BATCH_PROJECTS_TABLE,ADD_BATCH_PROJECTS_TABLE,DELETE_BATCH_PROJECTS_TABLE,EDIT_USERS_TABLE,EDIT_PEOPLE_TABLE,ADD_PEOPLE_TABLE,DELETE_PEOPLE_TABLE,EDIT_WORKGROUP,ADD_WORKGROUP,DELETE_WORKGROUP,EDIT_EVAL_DATA,ADD_EVAL_DATA,SEARCH_EVAL_DATA,EDIT_SITES_TABLE,ADD_ANALYTICS_TABLES,DELETE_ANALYTICS_TABLES,EDIT_ANALYTICS_TABLES,DELETE_SITES_TABLE,ADD_SITES_TABLE,DELETE_EVAL_DATA,SITE_ACCESS_ALL)values(SECURITY_ROLES_SEQ.CURRVAL,'1','1','1','1','1','1','1','1','1','1','1','0','1','1','1','1','1','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','1','0','0','0','0','0','0','0','0');

--Supervising Scientist
INSERT INTO SECURITY_ROLES (ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME)values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'SUPERVISING_SCIENTIST');
INSERT INTO CHEM_REG_PRIVILEGES(ROLE_INTERNAL_ID,CAMSOFT_LOG_ON,SEARCH_TEMP,SEARCH_REG,ADD_COMPOUND_TEMP,ADD_BATCH_TEMP,ADD_SALT_TEMP,ADD_IDENTIFIER_TEMP,EDIT_COMPOUND_TEMP,EDIT_BATCH_TEMP,EDIT_SALT_TEMP,EDIT_IDENTIFIERS_TEMP,DELETE_TEMP,REGISTER_TEMP,EDIT_COMPOUND_REG,EDIT_BATCH_REG,EDIT_SALT_REG,EDIT_IDENTIFIERS_REG,DELETE_REG,DELETE_BATCH_REG,EDIT_SCOPE_SELF,EDIT_SCOPE_SUPERVISOR,EDIT_SCOPE_ALL,SET_APPROVED_FLAG,TOGGLE_APPROVED_FLAG,SET_QUALITY_CHECK_FLAG,TOGGLE_QUALITY_CHECK_FLAG,EDIT_SALT_TABLE,ADD_SALT_TABLE,DELETE_SALT_TABLE,EDIT_SEQUENCES_TABLE,ADD_SEQUENCES_TABLE,DELETE_SEQUENCES_TABLE,EDIT_NOTEBOOKS_TABLE,ADD_NOTEBOOKS_TABLE,DELETE_NOTEBOOKS_TABLE,EDIT_PROJECTS_TABLE,ADD_PROJECTS_TABLE,DELETE_PROJECTS_TABLE,EDIT_SOLVATES_TABLE,ADD_SOLVATES_TABLE,DELETE_SOLVATES_TABLE,EDIT_COMPOUND_TYPE_TABLE,ADD_COMPOUND_TYPE_TABLE,DELETE_COMPOUND_TYPE_TABLE,EDIT_UTILIZATIONS_TABLE,ADD_UTILIZATIONS_TABLE,DELETE_UTILIZATIONS_TABLE,EDIT_BATCH_PROJECTS_TABLE,ADD_BATCH_PROJECTS_TABLE,DELETE_BATCH_PROJECTS_TABLE,EDIT_USERS_TABLE,EDIT_PEOPLE_TABLE,ADD_PEOPLE_TABLE,DELETE_PEOPLE_TABLE,EDIT_WORKGROUP,ADD_WORKGROUP,DELETE_WORKGROUP,EDIT_EVAL_DATA,ADD_EVAL_DATA,SEARCH_EVAL_DATA,EDIT_SITES_TABLE,ADD_ANALYTICS_TABLES,DELETE_ANALYTICS_TABLES,EDIT_ANALYTICS_TABLES,DELETE_SITES_TABLE,ADD_SITES_TABLE,DELETE_EVAL_DATA,SITE_ACCESS_ALL)values(SECURITY_ROLES_SEQ.CURRVAL,'1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','0','0','1','1','0','1','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','1','0','0','1','1','0','0','0','0','0','0','0','0');

--Chemical Admin
INSERT INTO SECURITY_ROLES (ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME)values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'CHEMICAL_ADMINISTRATOR');
INSERT INTO CHEM_REG_PRIVILEGES(ROLE_INTERNAL_ID,CAMSOFT_LOG_ON,SEARCH_TEMP,SEARCH_REG,ADD_COMPOUND_TEMP,ADD_BATCH_TEMP,ADD_SALT_TEMP,ADD_IDENTIFIER_TEMP,EDIT_COMPOUND_TEMP,EDIT_BATCH_TEMP,EDIT_SALT_TEMP,EDIT_IDENTIFIERS_TEMP,DELETE_TEMP,REGISTER_TEMP,EDIT_COMPOUND_REG,EDIT_BATCH_REG,EDIT_SALT_REG,EDIT_IDENTIFIERS_REG,DELETE_REG,DELETE_BATCH_REG,EDIT_SCOPE_SELF,EDIT_SCOPE_SUPERVISOR,EDIT_SCOPE_ALL,SET_APPROVED_FLAG,TOGGLE_APPROVED_FLAG,SET_QUALITY_CHECK_FLAG,TOGGLE_QUALITY_CHECK_FLAG,EDIT_SALT_TABLE,ADD_SALT_TABLE,DELETE_SALT_TABLE,EDIT_SEQUENCES_TABLE,ADD_SEQUENCES_TABLE,DELETE_SEQUENCES_TABLE,EDIT_NOTEBOOKS_TABLE,ADD_NOTEBOOKS_TABLE,DELETE_NOTEBOOKS_TABLE,EDIT_PROJECTS_TABLE,ADD_PROJECTS_TABLE,DELETE_PROJECTS_TABLE,EDIT_SOLVATES_TABLE,ADD_SOLVATES_TABLE,DELETE_SOLVATES_TABLE,EDIT_COMPOUND_TYPE_TABLE,ADD_COMPOUND_TYPE_TABLE,DELETE_COMPOUND_TYPE_TABLE,EDIT_UTILIZATIONS_TABLE,ADD_UTILIZATIONS_TABLE,DELETE_UTILIZATIONS_TABLE,EDIT_BATCH_PROJECTS_TABLE,ADD_BATCH_PROJECTS_TABLE,DELETE_BATCH_PROJECTS_TABLE,EDIT_USERS_TABLE,EDIT_PEOPLE_TABLE,ADD_PEOPLE_TABLE,DELETE_PEOPLE_TABLE,EDIT_WORKGROUP,ADD_WORKGROUP,DELETE_WORKGROUP,EDIT_EVAL_DATA,ADD_EVAL_DATA,SEARCH_EVAL_DATA,EDIT_SITES_TABLE,ADD_ANALYTICS_TABLES,DELETE_ANALYTICS_TABLES,EDIT_ANALYTICS_TABLES,DELETE_SITES_TABLE,ADD_SITES_TABLE,DELETE_EVAL_DATA,SITE_ACCESS_ALL)values(SECURITY_ROLES_SEQ.CURRVAL,'1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','0','0','1','1','1','1','1','1','1','1','1','0','1','0','0','1','1','0','1','1','0','1','1','0','1','1','0','1','1','0','1','1','0','0','1','1','0','1','1','1','1','1','1','1','1','0','1','0','1','0','0');

--Supervising Chemical Admin
INSERT INTO SECURITY_ROLES (ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME)values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'SUPERVISING_CHEMICAL_ADMIN');
INSERT INTO CHEM_REG_PRIVILEGES(ROLE_INTERNAL_ID,CAMSOFT_LOG_ON,SEARCH_TEMP,SEARCH_REG,ADD_COMPOUND_TEMP,ADD_BATCH_TEMP,ADD_SALT_TEMP,ADD_IDENTIFIER_TEMP,EDIT_COMPOUND_TEMP,EDIT_BATCH_TEMP,EDIT_SALT_TEMP,EDIT_IDENTIFIERS_TEMP,DELETE_TEMP,REGISTER_TEMP,EDIT_COMPOUND_REG,EDIT_BATCH_REG,EDIT_SALT_REG,EDIT_IDENTIFIERS_REG,DELETE_REG,DELETE_BATCH_REG,EDIT_SCOPE_SELF,EDIT_SCOPE_SUPERVISOR,EDIT_SCOPE_ALL,SET_APPROVED_FLAG,TOGGLE_APPROVED_FLAG,SET_QUALITY_CHECK_FLAG,TOGGLE_QUALITY_CHECK_FLAG,EDIT_SALT_TABLE,ADD_SALT_TABLE,DELETE_SALT_TABLE,EDIT_SEQUENCES_TABLE,ADD_SEQUENCES_TABLE,DELETE_SEQUENCES_TABLE,EDIT_NOTEBOOKS_TABLE,ADD_NOTEBOOKS_TABLE,DELETE_NOTEBOOKS_TABLE,EDIT_PROJECTS_TABLE,ADD_PROJECTS_TABLE,DELETE_PROJECTS_TABLE,EDIT_SOLVATES_TABLE,ADD_SOLVATES_TABLE,DELETE_SOLVATES_TABLE,EDIT_COMPOUND_TYPE_TABLE,ADD_COMPOUND_TYPE_TABLE,DELETE_COMPOUND_TYPE_TABLE,EDIT_UTILIZATIONS_TABLE,ADD_UTILIZATIONS_TABLE,DELETE_UTILIZATIONS_TABLE,EDIT_BATCH_PROJECTS_TABLE,ADD_BATCH_PROJECTS_TABLE,DELETE_BATCH_PROJECTS_TABLE,EDIT_USERS_TABLE,EDIT_PEOPLE_TABLE,ADD_PEOPLE_TABLE,DELETE_PEOPLE_TABLE,EDIT_WORKGROUP,ADD_WORKGROUP,DELETE_WORKGROUP,EDIT_EVAL_DATA,ADD_EVAL_DATA,SEARCH_EVAL_DATA,EDIT_SITES_TABLE,ADD_ANALYTICS_TABLES,DELETE_ANALYTICS_TABLES,EDIT_ANALYTICS_TABLES,DELETE_SITES_TABLE,ADD_SITES_TABLE,DELETE_EVAL_DATA,SITE_ACCESS_ALL)values(SECURITY_ROLES_SEQ.CURRVAL,'1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1','1');

--Perfume Chemist
INSERT INTO SECURITY_ROLES (ROLE_ID,PRIVILEGE_TABLE_INT_ID,ROLE_NAME)values(SECURITY_ROLES_SEQ.NEXTVAL,PRIVILEGE_TABLES_seq.CURRVAL,'PERFUME_CHEMIST');
INSERT INTO CHEM_REG_PRIVILEGES(ROLE_INTERNAL_ID,CAMSOFT_LOG_ON,SEARCH_TEMP,SEARCH_REG,ADD_COMPOUND_TEMP,ADD_BATCH_TEMP,ADD_SALT_TEMP,ADD_IDENTIFIER_TEMP,EDIT_COMPOUND_TEMP,EDIT_BATCH_TEMP,EDIT_SALT_TEMP,EDIT_IDENTIFIERS_TEMP,DELETE_TEMP,REGISTER_TEMP,EDIT_COMPOUND_REG,EDIT_BATCH_REG,EDIT_SALT_REG,EDIT_IDENTIFIERS_REG,DELETE_REG,DELETE_BATCH_REG,EDIT_SCOPE_SELF,EDIT_SCOPE_SUPERVISOR,EDIT_SCOPE_ALL,SET_APPROVED_FLAG,TOGGLE_APPROVED_FLAG,SET_QUALITY_CHECK_FLAG,TOGGLE_QUALITY_CHECK_FLAG,EDIT_SALT_TABLE,ADD_SALT_TABLE,DELETE_SALT_TABLE,EDIT_SEQUENCES_TABLE,ADD_SEQUENCES_TABLE,DELETE_SEQUENCES_TABLE,EDIT_NOTEBOOKS_TABLE,ADD_NOTEBOOKS_TABLE,DELETE_NOTEBOOKS_TABLE,EDIT_PROJECTS_TABLE,ADD_PROJECTS_TABLE,DELETE_PROJECTS_TABLE,EDIT_SOLVATES_TABLE,ADD_SOLVATES_TABLE,DELETE_SOLVATES_TABLE,EDIT_COMPOUND_TYPE_TABLE,ADD_COMPOUND_TYPE_TABLE,DELETE_COMPOUND_TYPE_TABLE,EDIT_UTILIZATIONS_TABLE,ADD_UTILIZATIONS_TABLE,DELETE_UTILIZATIONS_TABLE,EDIT_BATCH_PROJECTS_TABLE,ADD_BATCH_PROJECTS_TABLE,DELETE_BATCH_PROJECTS_TABLE,EDIT_USERS_TABLE,EDIT_PEOPLE_TABLE,ADD_PEOPLE_TABLE,DELETE_PEOPLE_TABLE,EDIT_WORKGROUP,ADD_WORKGROUP,DELETE_WORKGROUP,EDIT_EVAL_DATA,ADD_EVAL_DATA,SEARCH_EVAL_DATA,EDIT_SITES_TABLE,ADD_ANALYTICS_TABLES,DELETE_ANALYTICS_TABLES,EDIT_ANALYTICS_TABLES,DELETE_SITES_TABLE,ADD_SITES_TABLE,DELETE_EVAL_DATA,SITE_ACCESS_ALL)values(SECURITY_ROLES_SEQ.CURRVAL,'1','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','1','0','0','1','1','0','1','0','0');

Commit;
