create or replace PACKAGE "CSCHEMREG"
AS
Procedure GetPermregFromTempId(
--TempId in Batches.TEMP_ID%Type,
BatchN OUT Batches.BATCH_NUMBER%Type,
RegN out reg_numbers.reg_number%type);

Function strreplace(str varchar2)return varchar2;

Procedure TranslateIds(
paramValue in out varchar2,
paramName in varchar2
);
Procedure UpdateBatch(
pBatchNumber in Batches.BATCH_NUMBER%Type,
pREG_NUMBER in Reg_Numbers.REG_NUMBER%Type,
pSCIENTIST_ID in CS_SECURITY.PEOPLE.USER_ID%Type default null,
nSCIENTIST_ID in Batches.SCIENTIST_ID%Type default null,
pBP in Batches.BP%Type default null,
pMP in Batches.MP%Type default null,
pH1NMR in Batches.H1NMR%Type default null,
pC13NMR in Batches.C13NMR%Type default null,
pMS in Batches.MS%Type default null,
pIR in Batches.IR%Type default null,
pGC in Batches.GC%Type default null,
pPHYSICAL_FORM in Batches.PHYSICAL_FORM%Type default null,
pCOLOR in Batches.COLOR%Type default null,
pFLASHPOINT in Batches.FLASHPOINT%Type default null,
pHPLC in Batches.HPLC%Type default null,
pOPTICAL_ROTATION in Batches.OPTICAL_ROTATION%Type default null,
pREFRACTIVE_INDEX in Batches.REFRACTIVE_INDEX%Type default null,
pSALT_CODE in Salts.SALT_CODE%Type default null,
pSALT_NAME in Batches.SALT_NAME%Type default null,
pSALT_EQUIVALENTS in Batches.SALT_EQUIVALENTS%Type default null,
pSOLVATE_NAME in Batches.SOLVATE_NAME%Type default null,
pSOLVATE_EQUIVALENTS in Batches.SOLVATE_EQUIVALENTS%Type default null,
pSOURCE in Batches.Source%Type default null,
pVENDOR_NAME in Batches.VENDOR_NAME%Type default null,
pVENDOR_ID in Batches.VENDOR_ID%Type default null,
pPERCENT_ACTIVE in Batches.PERCENT_ACTIVE%Type default null,
pAMOUNT_UNITS in Batches.AMOUNT_UNITS%Type default null,
pPURITY in BATCHES.PURITY%Type default null,
pLC_UV_MS in Batches.LC_UV_MS%Type default null,
pCHN_COMBUSTION in Batches.CHN_COMBUSTION%Type default null,
pUV_SPECTRUM in Batches.UV_SPECTRUM%Type default null,
pAPPEARANCE in Batches.APPEARANCE%Type default null,
pLOGD in Batches.LOGD%Type default null,
pSOLUBILITY in Batches.SOLUBILITY%Type default null,
pLAST_MOD_PERSON_ID in Batches.LAST_MOD_PERSON_ID%Type default null,
pAMOUNT in Batches.AMOUNT%Type default null,
pFIELD_1 in Batches.FIELD_1%Type default null,
pFIELD_2 in Batches.FIELD_2%Type default null,
pFIELD_3 in Batches.FIELD_3%Type default null,
pFIELD_4 in Batches.FIELD_4%Type default null,
pFIELD_5 in Batches.FIELD_5%Type default null,
pFIELD_6 in Batches.FIELD_6%Type default null,
pFIELD_7 in Batches.FIELD_7%Type default null,
pFIELD_8 in Batches.FIELD_8%Type default null,
pFIELD_9 in Batches.FIELD_9%Type default null,
pFIELD_10 in Batches.FIELD_10%Type default null,
pLOAD_ID in Batches.LOAD_ID%Type default null,
--pDATETIME_STAMP in Batches.DATETIME_STAMP%Type default null,
pINT_BATCH_FIELD_1 in Batches.INT_BATCH_FIELD_1%Type default null,
pINT_BATCH_FIELD_2 in Batches.INT_BATCH_FIELD_2%Type default null,
pINT_BATCH_FIELD_3 in Batches.INT_BATCH_FIELD_3%Type default null,
pINT_BATCH_FIELD_4 in Batches.INT_BATCH_FIELD_4%Type default null,
pINT_BATCH_FIELD_5 in Batches.INT_BATCH_FIELD_5%Type default null,
pINT_BATCH_FIELD_6 in Batches.INT_BATCH_FIELD_6%Type default null,
pREAL_BATCH_FIELD_1 in Batches.REAL_BATCH_FIELD_1%Type default null,
pREAL_BATCH_FIELD_2 in Batches.REAL_BATCH_FIELD_2%Type default null,
pREAL_BATCH_FIELD_3 in Batches.REAL_BATCH_FIELD_3%Type default null,
pREAL_BATCH_FIELD_4 in Batches.REAL_BATCH_FIELD_4%Type default null,
pREAL_BATCH_FIELD_5 in Batches.REAL_BATCH_FIELD_5%Type default null,
pREAL_BATCH_FIELD_6 in Batches.REAL_BATCH_FIELD_6%Type default null,
--pDATE_BATCH_FIELD_1 in Batches.DATE_BATCH_FIELD_1%Type default null,
pDATE_BATCH_FIELD_1 in varchar2 default null,
pDATE_BATCH_FIELD_2 in varchar2 default null,
pDATE_BATCH_FIELD_3 in varchar2 default null,
pDATE_BATCH_FIELD_4 in varchar2 default null,
pDATE_BATCH_FIELD_5 in varchar2 default null,
pDATE_BATCH_FIELD_6 in varchar2 default null,
pREAL_CMPD_FIELD_1 in Compound_Molecule.REAL_CMPD_FIELD_1%Type default null,
pREAL_CMPD_FIELD_2 in Compound_Molecule.REAL_CMPD_FIELD_2%Type default null,
pREAL_CMPD_FIELD_3 in Compound_Molecule.REAL_CMPD_FIELD_3%Type default null,
pREAL_CMPD_FIELD_4 in Compound_Molecule.REAL_CMPD_FIELD_4%Type default null,
pPRODUCT_TYPE in COMPOUND_MOLECULE.PRODUCT_TYPE%Type default null,
pCHIRAL in COMPOUND_MOLECULE.CHIRAL%Type default null,
pCLOGP in COMPOUND_MOLECULE.CLOGP%Type default null,
pH_BOND_DONORS in COMPOUND_MOLECULE.H_BOND_DONORS%Type default null,
pH_BOND_ACCEPTORS in COMPOUND_MOLECULE.H_BOND_ACCEPTORS%Type default null,
pMW_TEXT in COMPOUND_MOLECULE.MW_TEXT%Type default null,
pMF_TEXT in COMPOUND_MOLECULE.MF_TEXT%Type default null,
pCOMPOUND_TYPE in COMPOUND_TYPE.DESCRIPTION%Type default null,
nCOMPOUND_TYPE in COMPOUND_MOLECULE.COMPOUND_TYPE%Type default null,
pSTRUCTURE_COMMENTS_TXT in COMPOUND_MOLECULE.STRUCTURE_COMMENTS_TXT%Type default null,
pTXT_CMPD_FIELD_1 in COMPOUND_MOLECULE.TXT_CMPD_FIELD_1%Type default null,
pTXT_CMPD_FIELD_2 in COMPOUND_MOLECULE.TXT_CMPD_FIELD_2%Type default null,
pTXT_CMPD_FIELD_3 in COMPOUND_MOLECULE.TXT_CMPD_FIELD_3%Type default null,
pTXT_CMPD_FIELD_4 in COMPOUND_MOLECULE.TXT_CMPD_FIELD_4%Type default null,
pINT_CMPD_FIELD_1 in COMPOUND_MOLECULE.INT_CMPD_FIELD_1%Type default null,
pINT_CMPD_FIELD_2 in COMPOUND_MOLECULE.INT_CMPD_FIELD_2%Type default null,
pINT_CMPD_FIELD_3 in COMPOUND_MOLECULE.INT_CMPD_FIELD_3%Type default null,
pINT_CMPD_FIELD_4 in COMPOUND_MOLECULE.INT_CMPD_FIELD_4%Type default null,
pDATE_CMPD_FIELD_1 in varchar2 default null,
pDATE_CMPD_FIELD_2 in varchar2 default null,
pDATE_CMPD_FIELD_3 in varchar2 default null,
pDATE_CMPD_FIELD_4 in varchar2 default null,
pAPPROVED in REG_APPROVED.APPROVED%Type default null,
pSOLVATE_ID in Solvates.SOLVATE_ID%Type default null,
pCompound_PROJECT_ID in PROJECTS.PROJECT_NAME%Type default null,
nCompound_PROJECT_ID in TEMPORARY_STRUCTURES.PROJECT_ID%Type default null,
pAPPROVED_TIME in REG_APPROVED.DATETIME_STAMP%Type default null,
pAPPROVED_DATE in REG_APPROVED.DATETIME_STAMP%Type default null,
pFORMULA_WEIGHT in Batches.FORMULA_WEIGHT%Type default null,
pBATCH_PROJECT_ID in Batch_Projects.PROJECT_NAME%Type default null,
nBATCH_PROJECT_ID in Batches.BATCH_PROJECT_ID%Type default null,
fCHEMICAL_NAME in TEMPORARY_STRUCTURES.CHEMICAL_NAME%Type default null,
fCHEM_NAME_AUTOGEN in TEMPORARY_STRUCTURES.CHEM_NAME_AUTOGEN%Type default null,
fSYNONYM_R in TEMPORARY_STRUCTURES.SYNONYM_R%Type default null,
fCAS_NUMBER in TEMPORARY_STRUCTURES.CAS_NUMBER%Type default null,
fRNO_NUMBER in TEMPORARY_STRUCTURES.RNO_NUMBER%Type default null,
fFEMA_GRAS_NUMBER in TEMPORARY_STRUCTURES.FEMA_GRAS_NUMBER%Type default null,
fGROUP_CODE in TEMPORARY_STRUCTURES.GROUP_CODE%Type default null,
pNOTEBOOK_PAGE in BATCHES.NOTEBOOK_PAGE%Type default null,
pNOTEBOOK_TEXT in BATCHES.NOTEBOOK_TEXT%Type default null,
pNOTEBOOK_INTERNAL_ID in NOTEBOOKS.NOTEBOOK_NAME%Type default null,
nNOTEBOOK_INTERNAL_ID in BATCHES.NOTEBOOK_INTERNAL_ID%Type default null,
pProducer in BATCHES.PRODUCER%Type default null,
pLit_Ref in BATCHES.LIT_REF%Type default null,
pBatch_Comment in BATCHES.BATCH_COMMENT%Type default null,
pDateFormat in varchar2,
pSTORAGE_REQ_AND_WARNINGS in BATCHES.STORAGE_REQ_AND_WARNINGS%Type default null,
pPreparation in BATCHES.PREPARATION%Type default null,
pBATCH_INTERNAL_ID out BATCHES.BATCH_INTERNAL_ID%Type
);
Procedure CreateBatch(
pReg_Internal_Id in Varchar,
batchN out Batches.BATCH_NUMBER%Type);
/*Procedure CreateBatch(
pBatch_Internal_Id in Batches.BATCH_INTERNAL_ID%TYPE,
pGiv_Batch_Id in BATCHES.GIV_BATCH_ID%TYPE default null,
pBatch_Number in Batches.BATCH_NUMBER%TYPE default null,
pMol_Id in BATCHES.MOL_ID%TYPE default null,
pCpd_Internal_Id in BATCHES.CPD_INTERNAL_ID%TYPE default null,
pProducer in BATCHES.PRODUCER%TYPE default null,
pScientist_Id in BATCHES.SCIENTIST_ID%TYPE default null,
pReg_Internal_Id in BATCHES.REG_INTERNAL_ID%TYPE default null,
pLast_Mod_Person_Id in BATCHES.LAST_MOD_PERSON_ID%TYPE default null,
pEntry_Person_Id in BATCHES.ENTRY_PERSON_ID%TYPE default null,
pBatch_Reg_Person_Id in BATCHES.BATCH_REG_PERSON_ID%TYPE default null,
pBatch_Reg_Date in BATCHES.BATCH_REG_DATE%TYPE default null,
pLast_Mod_Date in BATCHES.LAST_MOD_DATE%TYPE default null,
pBatch_Comment in BATCHES.BATCH_COMMENT%TYPE default null,
pNotebook_Page in Batches.NOTEBOOK_PAGE%TYPE default null,
pNotebook_Text in BATCHES.NOTEBOOK_TEXT%TYPE default null,
pNotebook_Internal_Id in BATCHES.NOTEBOOK_INTERNAL_ID%TYPE default null,
pSalt_Internal_Id in BATCHES.SALT_INTERNAL_ID%TYPE default null,
pSalt_Name in BATCHES.SALT_NAME%TYPE default null,
pSalt_Mw in BATCHES.SALT_MW%TYPE default null,
pSalt_Equivalents in BATCHES.SALT_EQUIVALENTS%TYPE default null,
pSolvate_Id in BATCHES.SOLVATE_ID%TYPE default null,
pSolvate_Name in BATCHES.SOLVATE_NAME%TYPE default null,
pSolvate_Mw in BATCHES.SOLVATE_MW%TYPE default null,
pSolvate_Equivalents in BATCHES.SOLVATE_EQUIVALENTS%TYPE default null,
pFormula_Weight in BATCHES.FORMULA_WEIGHT%TYPE default null,
pBatch_Formula in BATCHES.BATCH_FORMULA%TYPE default null,
pBatch_Project_Id in BATCHES.BATCH_PROJECT_ID%TYPE default null,
pSource in BATCHES.SOURCE%TYPE default null,
pVendor_Name in BATCHES.VENDOR_NAME%TYPE default null,
pVendor_Id in BATCHES.VENDOR_ID%TYPE default null,
pPercent_Active in BATCHES.PERCENT_ACTIVE%TYPE default null,
pAmount_Units in BATCHES.AMOUNT_UNITS%TYPE default null,
pPurity in BATCHES.PURITY%TYPE default null,
pLC_UV_MS in BATCHES.LC_UV_MS%TYPE default null,
pChn_Combustion in BATCHES.CHN_COMBUSTION%TYPE default null,
pUv_Spectrum in BATCHES.UV_SPECTRUM%TYPE default null,
pAppearance in BATCHES.APPEARANCE%TYPE default null,
pH1NMR in BATCHES.H1NMR%TYPE default null,
pC13NMR in BATCHES.C13NMR%TYPE default null,
pLogD in BATCHES.LOGD%TYPE default null,
pSolubility in BATCHES.SOLUBILITY%TYPE default null,
pMS in BATCHES.MS%TYPE default null,
pIR in BATCHES.IR%TYPE default null,
pGC in BATCHES.GC%TYPE default null,
pBP in BATCHES.BP%TYPE default null,
pMP in BATCHES.MP%TYPE default null,
pFlashPoint in BATCHES.FLASHPOINT%TYPE default null,
pPhysical_Form in BATCHES.PHYSICAL_FORM%TYPE default null,
pColor in BATCHES.COLOR%TYPE default null,
pHPLC in BATCHES.HPLC%TYPE default null,
pOptical_Rotation in BATCHES.OPTICAL_ROTATION%TYPE default null,
pRefractive_Index in BATCHES.REFRACTIVE_INDEX%TYPE default null,
pPreparation in BATCHES.PREPARATION%TYPE default null,
pStorage_Req_And_Warnings in BATCHES.STORAGE_REQ_AND_WARNINGS%TYPE default null,
pLit_Ref in BATCHES.LIT_REF%TYPE default null,
pCreation_Date in BATCHES.CREATION_DATE%TYPE default null,
pAmount in BATCHES.AMOUNT%TYPE default null,
pField_1 in BATCHES.FIELD_1%TYPE default null,
pField_2 in BATCHES.FIELD_2%TYPE default null,
pField_3 in BATCHES.FIELD_3%TYPE default null,
pField_4 in BATCHES.FIELD_4%TYPE default null,
pField_5 in BATCHES.FIELD_5%TYPE default null,
pField_6 in BATCHES.FIELD_6%TYPE default null,
pField_7 in BATCHES.FIELD_7%TYPE default null,
pField_8 in BATCHES.FIELD_8%TYPE default null,
pField_9 in BATCHES.FIELD_9%TYPE default null,
pField_10 in BATCHES.FIELD_10%TYPE default null,
pLoad_Id in BATCHES.LOAD_ID%TYPE default null,
pDateTime_Stamp in BATCHES.DATETIME_STAMP%TYPE default null,
pInt_Batch_Field_1 in BATCHES.INT_BATCH_FIELD_1%TYPE default null,
pInt_Batch_Field_2 in BATCHES.INT_BATCH_FIELD_2%TYPE default null,
pInt_Batch_Field_3 in BATCHES.INT_BATCH_FIELD_3%TYPE default null,
pInt_Batch_Field_4 in BATCHES.INT_BATCH_FIELD_4%TYPE default null,
pInt_Batch_Field_5 in BATCHES.INT_BATCH_FIELD_5%TYPE default null,
pInt_Batch_Field_6 in BATCHES.INT_BATCH_FIELD_6%TYPE default null,
pReal_Batch_Field_1 in BATCHES.REAL_BATCH_FIELD_1%TYPE default null,
pReal_Batch_Field_2 in BATCHES.REAL_BATCH_FIELD_2%TYPE default null,
pReal_Batch_Field_3 in BATCHES.REAL_BATCH_FIELD_3%TYPE default null,
pReal_Batch_Field_4 in BATCHES.REAL_BATCH_FIELD_4%TYPE default null,
pReal_Batch_Field_5 in BATCHES.REAL_BATCH_FIELD_5%TYPE default null,
pReal_Batch_Field_6 in BATCHES.REAL_BATCH_FIELD_6%TYPE default null,
pDate_Batch_Field_1 in BATCHES.DATE_BATCH_FIELD_1%TYPE default null,
pDate_Batch_Field_2 in BATCHES.DATE_BATCH_FIELD_2%TYPE default null,
pDate_Batch_Field_3 in BATCHES.DATE_BATCH_FIELD_3%TYPE default null,
pDate_Batch_Field_4 in BATCHES.DATE_BATCH_FIELD_4%TYPE default null,
pDate_Batch_Field_5 in BATCHES.DATE_BATCH_FIELD_5%TYPE default null,
pDate_Batch_Field_6 in BATCHES.DATE_BATCH_FIELD_6%TYPE default null,
pTemp_Id in BATCHES.TEMP_ID%Type default null
);*/
End;
/