//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerkinElmer.CBOE.Registration.Client.Forms.RegistrationAdmin.ContentArea {
    
    
    public partial class Compound {
        
        /// <summary>
        /// PropertiesPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PerkinElmer.CBOE.Registration.Client.Forms.RegistrationAdmin.UserControls.NavigationPanel PropertiesPanel;
        
        /// <summary>
        /// PropertyList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PerkinElmer.CBOE.Registration.Client.Forms.RegistrationAdmin.UserControls.PropertyListUC PropertyList1;
    }
}
