CREATE TABLE "INV_DOC_TYPES"(
   	"DOC_TYPE_ID" NUMBER(4) NOT NULL, 
	"TYPE_NAME" VARCHAR2(100), 
	CONSTRAINT "INV_DOC_TYPE_PK" 
		PRIMARY KEY("DOC_TYPE_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	);
	
CREATE SEQUENCE SEQ_DOC_TYPE_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER "TRG_INV_DOC_TYPES_ID"
    BEFORE INSERT
    ON "INV_DOC_TYPES"
    FOR EACH ROW
BEGIN
	if :new.doc_type_id is null then
		select SEQ_DOC_TYPE_ID.nextval into :new.doc_type_id from dual;
	end if;
END;
/
	