CREATE TABLE "INV_ESET_TYPE"(
	"ESET_TYPE_ID" NUMBER(9) NOT NULL, 
	"ESET_TYPE_NAME" VARCHAR2(255) NOT NULL, 
    "IS_USER_VISIBLE" VARCHAR2(1) NOT NULL, 
    CONSTRAINT "INV_ESET_TYPE_PK" 
		PRIMARY KEY("ESET_TYPE_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;  

create sequence SEQ_INV_ESET_TYPE INCREMENT BY 1 START WITH 1000;

create or replace trigger TRG_ESET_TYPE_ID BEFORE INSERT ON INV_ESET_TYPE FOR EACH ROW 
begin
if :new.ESET_TYPE_ID is null then
  select SEQ_INV_ESET_TYPE.nextval into :new.ESET_TYPE_ID from dual;
end if;
end;
/

