CREATE TABLE "INV_STATES"(
	"STATE_ID" NUMBER(4) NOT NULL,
	"COUNTRY_ID_FK" NUMBER(4),
	"STATE_NAME" VARCHAR2(255),
	"STATE_ABBREVIATION" VARCHAR2(20),
	CONSTRAINT "INV_STATES_COUNTRY_ID_FK" 
		FOREIGN KEY("COUNTRY_ID_FK") 
		REFERENCES "INV_COUNTRY"("COUNTRY_ID"),	
    CONSTRAINT "INV_STATES_PK"
		PRIMARY KEY("STATE_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

CREATE SEQUENCE SEQ_INV_STATES INCREMENT BY 1 START WITH 1000 MAXVALUE 99999 MINVALUE 1 NOCYCLE NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "TRG_INV_STATES_ID"
    BEFORE INSERT
    ON "INV_STATES"
    FOR EACH ROW
    begin
		if :new.State_ID is null then
			select seq_Inv_States.nextval into :new.State_id from dual;
		end if;
end;
/