CREATE TABLE "INV_EHS_SUBSTANCES"(
    "EHS_SUBSTANCE_ID" NUMBER(5) NOT NULL, 
    "SUBSTANCE_NAME" VARCHAR2(1000), 
    "CAS" VARCHAR2(15), 
    "CAS_INTERNAL" VARCHAR2(15), 
    "IS_OSHA_CARCINOGEN" NUMBER(1) DEFAULT 0 NOT NULL, 
    "OSHA_THRESHOLD_PLANNING_QUAN" NUMBER(5), 
    "INTERNAL_MAX_QUANTITY_POUNDS" NUMBER(5), 
    "INTERNAL_MAX_QUAN_CUBIC_FEET" NUMBER(5), 
    "EPA_THRESHOLD_PLANNING_QUAN" NUMBER(5), 
    "EPA_NOTIFICATION_RQMT_QUAN" NUMBER(5), 
    "ACGIH_CARCINOGEN_CATEGORY" VARCHAR2(2), 
    "IS_DEA_CONTROLLED" NUMBER(1) DEFAULT 0 NOT NULL, 
    CONSTRAINT "EHS_SUBSTANCES_ACGIH_CHK" 
		CHECK(ACGIH_Carcinogen_Category IN ('A1', 'A2')), 
    CONSTRAINT "EHS_SUBSTANCES_CASNAME_CHK" 
		CHECK(NOT(substance_Name IS NULL AND CAS IS NULL)), 
    CONSTRAINT "EHS_SUBSTANCES_PK" 
		PRIMARY KEY("EHS_SUBSTANCE_ID") USING INDEX  TABLESPACE &&indexTableSpaceName
	); 

CREATE OR REPLACE TRIGGER TRG_INV_EHS_Substances_bi0 BEFORE INSERT
ON inv_EHS_Substances
FOR EACH ROW
BEGIN
    :NEW.CAS_Internal := TRANSLATE(UPPER(:NEW.CAS), 
                                   Constants.cCASTranslation1, Constants.cCASTranslation2);
END;
/

CREATE OR REPLACE TRIGGER TRG_INV_EHS_Substances_bu0 BEFORE UPDATE
ON INV_EHS_Substances
FOR EACH ROW
WHEN (new.CAS <> old.CAS)
BEGIN
    :NEW.CAS_Internal := TRANSLATE(UPPER(:NEW.CAS), 
                                   Constants.cCASTranslation1, Constants.cCASTranslation2);
END;
/

