CREATE TABLE "INV_BARCODE_DESC"(
	"BARCODE_DESC_ID" NUMBER(4) NOT NULL, 
	"BARCODE_DESC_NAME" VARCHAR2(50), 
	"PREFIX" VARCHAR2(10), 
	"PFX_SEPARATOR" varchar2(3),
	"SUFFIX" VARCHAR2(10), 
	"SFX_SEPARATOR" varchar2(3),
	"RUN_START" NUMBER(16), 
	"RUN_INCREMENT" number(15,0),
    	"RUN_END" NUMBER(16), 
	"NUMBER_SIZE" NUMBER(3), 
	"PAD_CHARACTER" CHAR(1),
    CONSTRAINT "INV_BARCODE_DESC_PK" 
		PRIMARY KEY("BARCODE_DESC_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;  

create sequence SEQ_INV_BARCODE_DESC INCREMENT BY 1 START WITH 1000;

create or replace trigger TRG_BARCODE_DESC BEFORE INSERT ON INV_BARCODE_DESC FOR EACH ROW 
begin
if :new.BARCODE_DESC_ID is null then
  select SEQ_INV_BARCODE_DESC.nextval into :new.BARCODE_DESC_ID from dual;
end if;
end;
/

