CREATE TABLE "INV_ENUM_VALUES"(
	"ENUM_ID_FK" NUMBER(9) NOT NULL, 
	"VALUE" VARCHAR2(255), 
	"LOOKUPSQL" VARCHAR2(4000),
	CONSTRAINT ENUM_VALUES_ENUM_FK
		FOREIGN KEY (ENUM_ID_FK)
		REFERENCES INV_ENUMERATION (ENUM_ID)
		ON DELETE CASCADE
	)
;

CREATE INDEX ENUM_ID_FK_IDX ON INV_ENUM_VALUES(ENUM_ID_FK) TABLESPACE &&indexTableSpaceName;

