CREATE TABLE "INV_USER_PROPERTIES"(
	"USER_ID_FK" VARCHAR2(30) NOT NULL, 
	"PROPERTYNAME" VARCHAR2(50) NOT NULL, 
  "PROPERTYVALUE" VARCHAR2(4000),
  "TIME_STAMP" DATE DEFAULT sysdate NOT NULL,  
  CONSTRAINT "INV_USER_PROPERTIES_PK" 
		PRIMARY KEY("USER_ID_FK", "PROPERTYNAME") USING INDEX TABLESPACE &&indexTableSpaceName);     
