CREATE TABLE "INV_CONTAINER_ORDER_REASON"(
    "CONTAINER_ORDER_REASON_ID" NUMBER(1) NOT NULL, 
    "NAME" VARCHAR2(30) NOT NULL, 
    "SORT_ORDER" NUMBER(1) NOT NULL, 
    CONSTRAINT "ORDER_REASON_PK" 
		PRIMARY KEY("CONTAINER_ORDER_REASON_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;
