CREATE TABLE "INV_URL"(
    "URL_ID" NUMBER(9) NOT NULL, 
    "FK_VALUE" VARCHAR2(30) NOT NULL, 
    "TABLE_NAME" VARCHAR2(30) NOT NULL,
    "FK_NAME" VARCHAR2(30) NOT NULL, 
    "URL" VARCHAR2(2000), 
    "LINK_TXT" VARCHAR2(2000), 
    "IMAGE_SRC" VARCHAR2(2000), 
    "IMAGE" BLOB, 
    "SORT_ORDER" NUMBER(4), 
    "URL_TYPE" VARCHAR2(50),
    "RID" NUMBER(10) NOT NULL, 
	"CREATOR" VARCHAR2(30) DEFAULT RTRIM(user) NOT NULL, 
	"TIMESTAMP" DATE DEFAULT sysdate NOT NULL
	)
; 

create sequence SEQ_URL INCREMENT BY 1 START WITH 1;
CREATE OR REPLACE TRIGGER "TRG_INV_URL" BEFORE INSERT ON "INV_URL" FOR EACH ROW begin
if :new.URL_ID is null then
	select seq_URL.nextval into :new.URL_id from dual;
end if;
end;
/