CREATE TABLE "INV_ORDER_STATUS"(
	"ORDER_STATUS_ID" NUMBER(4) NOT NULL,
	"ORDER_STATUS_NAME" VARCHAR2(50) NOT NULL,
    CONSTRAINT "INV_ORDER_STATUS_PK"
		PRIMARY KEY("ORDER_STATUS_ID") USING INDEX TABLESPACE &&indexTableSpaceName);

CREATE SEQUENCE SEQ_INV_ORDER_STATUS INCREMENT BY 1 START WITH 1000 MAXVALUE 999999 MINVALUE 1 NOCYCLE NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "TRG_INV_ORDER_STATUS_ORDRSTSID"
    BEFORE INSERT
    ON "INV_ORDER_STATUS"
    FOR EACH ROW
    begin
		if :new.ORDER_STATUS_ID is null then
			select seq_INV_ORDER_STATUS.nextval into :new.ORDER_STATUS_ID from dual;
		end if;
end;
/
