CREATE TABLE "INV_GRID_ELEMENT"(
	"GRID_ELEMENT_ID" NUMBER(9) NOT NULL, 
	"GRID_POSITION_ID_FK" NUMBER(9) NOT NULL, 
  "GRID_STORAGE_ID_FK" NUMBER(9) NOT NULL, 
  "BARCODE_ID" NUMBER(16), 
  "LOCATION_ID_FK" NUMBER(16), 
  "CONTAINER_ID_FK" NUMBER(16), 
  "PLATE_ID_FK" NUMBER(16), 
  "WELL_ID_FK" NUMBER(16), 
  CONSTRAINT "INV_GRIDELM_GRIDPOS" 
		FOREIGN KEY("GRID_POSITION_ID_FK") 
		REFERENCES "INV_GRID_POSITION"("GRID_POSITION_ID")
		ON DELETE CASCADE, 
  CONSTRAINT "INV_GRIDELM_LOCATIONID_FK" 
		FOREIGN KEY("LOCATION_ID_FK") 
		REFERENCES "INV_LOCATIONS"("LOCATION_ID")
		ON DELETE CASCADE, 
  CONSTRAINT "INV_GRIDELM_PLATEID_FK" 
		FOREIGN KEY("PLATE_ID_FK") 
		REFERENCES "INV_PLATES"("PLATE_ID")
    ON DELETE CASCADE, 
  CONSTRAINT "INV_GRIDELM_WELLID_FK" 
		FOREIGN KEY("WELL_ID_FK") 
		REFERENCES "INV_WELLS"("WELL_ID")
    ON DELETE CASCADE, 
  CONSTRAINT "INV_GRID_ELM_STOTAGE" 
		FOREIGN KEY("GRID_STORAGE_ID_FK") 
		REFERENCES "INV_GRID_STORAGE"("GRID_STORAGE_ID") 
		ON DELETE CASCADE,
  CONSTRAINT "INV_GRID_ELEMENT_PK" 
  	PRIMARY KEY("GRID_ELEMENT_ID") USING INDEX TABLESPACE &&indexTableSpaceName  
	)
; 

create sequence SEQ_INV_GRID_ELEMENT INCREMENT BY 1 START WITH 1000;

CREATE INDEX GRID_POSITION_ID_FK_IDX ON INV_GRID_ELEMENT(GRID_POSITION_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX GRID_LOCATION_ID_FK_IDX ON INV_GRID_ELEMENT(LOCATION_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX GRID_PLATE_ID_FK_IDX ON INV_GRID_ELEMENT(PLATE_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX WELL_ID_FK_IDX ON INV_GRID_ELEMENT(WELL_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX GRID_STORAGE_ID_FK_IDX ON INV_GRID_ELEMENT(GRID_STORAGE_ID_FK) TABLESPACE &&indexTableSpaceName;

create or replace trigger TRG_GRID_ELEMENT_ID BEFORE INSERT ON INV_GRID_ELEMENT FOR EACH ROW 
begin
if :new.GRID_ELEMENT_ID is null then
  select SEQ_INV_GRID_ELEMENT.nextval into :new.GRID_ELEMENT_ID from dual;
end if;
end;
/


