CREATE TABLE "INV_CONTAINER_STATUS"(
    "CONTAINER_STATUS_ID" NUMBER(4) NOT NULL, 
    "CONTAINER_STATUS_NAME" VARCHAR2(50), 
    "CONTAINER_STATUS_DESC" VARCHAR2(255), 
    CONSTRAINT "INV_CONTAINER_STATUS_PK" 
		PRIMARY KEY("CONTAINER_STATUS_ID") USING INDEX TABLESPACE &&indexTableSpaceName  
	)
; 

CREATE SEQUENCE SEQ_INV_CONTAINER_STATUS INCREMENT BY 1 START WITH 1000 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE ;

CREATE OR REPLACE TRIGGER "TRG_INV_CONTAINER_STATUS" 
    BEFORE INSERT 
    ON "INV_CONTAINER_STATUS" 
    FOR EACH ROW 
    begin
		if :new.Container_Status_ID is null then
			select seq_Inv_Container_Status.nextval into :new.Container_Status_ID from dual;
		end if;
	end;
/

