CREATE TABLE "INV_XMLDOCS"(
    	"XMLDOC_ID" NUMBER(4) NOT NULL, 
    	"XMLDOC" CLOB, "NAME" VARCHAR2(200),
    	"XMLDOC_TYPE_ID_FK" NUMBER(4),
    	CONSTRAINT "INV_XMLDOCS_PK" 
		PRIMARY KEY("XMLDOC_ID") USING INDEX TABLESPACE &&indexTableSpaceName,
    	CONSTRAINT "INV_XMLDOCS_XMLDOCTYPEID_FK" 
		FOREIGN KEY("XMLDOC_TYPE_ID_FK") 
	    	REFERENCES "INV_XMLDOC_TYPES"("XMLDOC_TYPE_ID")) 
		LOB (XMLDOC) STORE AS(
		DISABLE STORAGE IN ROW
		TABLESPACE &&lobsTableSpaceName
		NOCACHE
		CHUNK 2K
		PCTVERSION 10
		STORAGE(INITIAL &&lobXML NEXT &&lobXML));

CREATE SEQUENCE SEQ_INV_XMLDOCS INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;

CREATE INDEX XMLDOCS_XMLDOCTYPEID_FK_IDX ON INV_XMLDOCS(XMLDOC_TYPE_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE OR REPLACE TRIGGER TRG_XMLDOCS
    BEFORE INSERT
    ON "INV_XMLDOCS"
    FOR EACH ROW 
begin
  if :new.XMLDOC_ID is null then
    select SEQ_INV_XMLDOCS.nextval into :new.XMLDOC_ID from dual;
  end if;
end;                                                      
/
