CREATE TABLE "INV_REQUESTS"(
	"REQUEST_ID" NUMBER(9) NOT NULL, 
	"CONTAINER_ID_FK" NUMBER(9), 
	"USER_ID_FK" VARCHAR2(30), 
	"DATE_REQUIRED" DATE, 
	"DATE_DELIVERED" DATE, 
	"DELIVERED_BY_ID_FK" VARCHAR2(10), 
	"QTY_REQUIRED" NUMBER NOT NULL, 
	"DELIVERY_LOCATION_ID_FK" NUMBER(9) NOT NULL, 
  "REQUEST_COMMENTS" VARCHAR2(4000), 
	"REQUEST_TYPE_ID_FK" NUMBER(4) NOT NULL,
	"REQUEST_STATUS_ID_FK" NUMBER(4) NOT NULL,
	"CONTAINER_TYPE_ID_FK" NUMBER(4),
	"NUMBER_CONTAINERS" NUMBER(4),
	"QUANTITY_LIST" VARCHAR2(1000),
	"SHIP_TO_NAME" VARCHAR2(255),
	"DECLINE_REASON" VARCHAR2(1000),
  "EXPENSE_CENTER" VARCHAR2(255),
	"BATCH_ID_FK" NUMBER(4),
	"ORG_UNIT_ID_FK" NUMBER(4),
	"ASSIGNED_USER_ID_FK" VARCHAR2(100),	
	"QTY_DELIVERED" NUMBER,
	"REQUIRED_UNIT_ID_FK" number(4,0),
	"FIELD_1" VARCHAR2(2000),
	"FIELD_2" VARCHAR2(2000),
	"FIELD_3" VARCHAR2(2000),
	"FIELD_4" VARCHAR2(2000),
	"FIELD_5" VARCHAR2(2000),
	"DATE_1" DATE,
	"DATE_2" DATE,
  "RID" NUMBER(10) NOT NULL, 
  "CREATOR" VARCHAR2(30) DEFAULT RTRIM(user) NOT NULL, 
  "TIMESTAMP" DATE DEFAULT sysdate NOT NULL, 
  CONSTRAINT "INV_REQUESTS_REQUESTTYPE_FK"
		FOREIGN KEY("REQUEST_TYPE_ID_FK")
		REFERENCES "INV_REQUEST_TYPES"("REQUEST_TYPE_ID"),
--	CONSTRAINT "INV_REQUESTS_USERID_FK"
--  	FOREIGN KEY("USER_ID_FK")
--    REFERENCES "PEOPLE"("USER_ID"),
  CONSTRAINT "INV_REQUESTS_REQUESTSTATUS_FK"
		FOREIGN KEY("REQUEST_STATUS_ID_FK")
		REFERENCES "INV_REQUEST_STATUS"("REQUEST_STATUS_ID"),
  CONSTRAINT "INV_REQUESTS_LOC_ID_FK" 
		FOREIGN KEY("DELIVERY_LOCATION_ID_FK") 
		REFERENCES "INV_LOCATIONS"("LOCATION_ID")
    ON DELETE SET NULL, 
	CONSTRAINT "INV_REQUESTS_PK" 
		PRIMARY KEY("REQUEST_ID") USING INDEX TABLESPACE &&indexTableSpaceName,  
  CONSTRAINT "INV_REQUESTS_CONTAINER_ID_FK" 
		FOREIGN KEY("CONTAINER_ID_FK") 
		REFERENCES "INV_CONTAINERS"("CONTAINER_ID") 
		ON DELETE CASCADE,
	CONSTRAINT "INV_REQUESTS_BATCH_ID_FK" 
		FOREIGN KEY ("BATCH_ID_FK")
		REFERENCES "INV_CONTAINER_BATCHES" ("BATCH_ID") on delete cascade,
--	CONSTRAINT "ORG_UNIT_ID_FK"
--		FOREIGN KEY ("ORG_UNIT_ID_FK")
--		REFERENCES "INV_ORG_UNIT" ("ORG_UNIT_ID"),
	CONSTRAINT "INV_REQ_ASSIGNED_USER_ID_FK" 
		FOREIGN KEY ("ASSIGNED_USER_ID_FK")
		REFERENCES "PEOPLE" ("USER_ID")
	)
;

create sequence SEQ_INV_REQUESTS INCREMENT BY 1 START WITH 1; 	 

CREATE OR REPLACE TRIGGER TRG_INV_REQUESTS
    BEFORE INSERT 
    ON INV_REQUESTS
    FOR EACH ROW 
begin
  if :new.REQUEST_ID is null then
    select SEQ_INV_REQUESTS.nextval into :new.REQUEST_ID from dual;
  end if;
end;  
/


CREATE INDEX DELIVERY_LOCATION_ID_FK_IDX ON INV_REQUESTS(DELIVERY_LOCATION_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX REQUEST_TYPE_ID_FK_IDX ON INV_REQUESTS(REQUEST_TYPE_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX REQUEST_STATUS_ID_FK_IDX ON INV_REQUESTS(REQUEST_STATUS_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX IREQUESTS_CONTAINER_ID_FK_IDX ON INV_REQUESTS(CONTAINER_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX INV_REQUESTS_USERID_IDX ON INV_REQUESTS(USER_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX REQUESTS_BATCH_ID_FK_IDX ON INV_REQUESTS(BATCH_ID_FK) TABLESPACE &&indexTableSpaceName;
