CREATE TABLE "INV_COMPOUNDS"(
	"COMPOUND_ID" NUMBER(9) NOT NULL, 
	"MOL_ID" NUMBER(9), 
	"CAS" VARCHAR2(15), 
	"ACX_ID" VARCHAR2(15), 
	"SUBSTANCE_NAME" VARCHAR2(2000) NOT NULL,
	"BASE64_CDX" CLOB,
	"MOLECULAR_WEIGHT" NUMBER, 
	"DENSITY" NUMBER DEFAULT 1 NOT NULL,
	"CLOGP" NUMBER,
    	"ROTATABLE_BONDS" NUMBER(9,0),
    	"TOT_POL_SURF_AREA" NUMBER,
    	"HBOND_ACCEPTORS" NUMBER(9,0),
    	"HBOND_DONORS" NUMBER(9,0),
	"ALT_ID_1" VARCHAR2(255),
	"ALT_ID_2" VARCHAR2(255),
	"ALT_ID_3" VARCHAR2(255),
	"ALT_ID_4" VARCHAR2(255), 
    "ALT_ID_5" VARCHAR2(255),
    "CONFLICTING_FIELDS"  VARCHAR2(2000),
    "RID" NUMBER(12) NOT NULL,
    "CREATOR" VARCHAR2(30) DEFAULT RTRIM(user) NOT NULL,
    "TIMESTAMP" DATE DEFAULT sysdate NOT NULL,  
    CONSTRAINT "INV_COMPOUNDS_PK" 
		PRIMARY KEY("COMPOUND_ID") USING INDEX TABLESPACE &&indexTableSpaceName  
	)
	LOB (BASE64_CDX) STORE AS(
		DISABLE STORAGE IN ROW NOCACHE PCTVERSION 10
		TABLESPACE &&lobsTableSpaceName
		STORAGE (INITIAL &&lobB64cdx NEXT &&lobB64cdx)
	)		
; 

create sequence SEQ_INV_Compounds INCREMENT BY 1 START WITH 1;
create sequence MOLID_SEQ INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER "TRG_INV_COMPOUNDS_ID" 
    BEFORE INSERT 
    ON "INV_COMPOUNDS" 
    FOR EACH ROW 
    begin
		if :new.Compound_ID is null then
			select seq_Inv_Compounds.nextval into :new.compound_id from dual;
		end if;
		if :new.MOL_ID is null then
			SELECT MOLID_SEQ.NEXTVAL INTO :NEW.MOL_ID FROM DUAL;
		end if;
end;
/

CREATE INDEX INV_COMPOUNDS_CAS_IDX ON INV_COMPOUNDS(CAS ASC) TABLESPACE &&indexTableSpaceName;
CREATE INDEX INV_COMPOUNDS_ACXID_IDX ON INV_COMPOUNDS(ACX_ID ASC) TABLESPACE &&indexTableSpaceName;
CREATE INDEX INV_COMPOUNDS_SN_IDX ON INV_COMPOUNDS(SUBSTANCE_NAME ASC) TABLESPACE &&indexTableSpaceName;
CREATE INDEX MX ON inv_compounds(base64_cdx) indexType is cscartridge.moleculeindextype PARAMETERS('&&cscartIndexOptions');

