CREATE TABLE "INV_PLATE_HISTORY"(
	"PLATE_HISTORY_ID" NUMBER(9) NOT NULL, 
	"PLATE_ID_FK" NUMBER(9) NOT NULL, 
    "PLATE_HISTORY_DATE" DATE NOT NULL, 
    "PLATE_ACTION_ID_FK" NUMBER(9) NOT NULL, 
    "FROM_LOCATION_ID_FK" NUMBER(9,0),
	"TO_LOCATION_ID_FK" NUMBER(9,0),
	"IS_FT_INCREMENTED" NUMBER(1,0), 
    "DESCRIPTION" VARCHAR2(255), 
    CONSTRAINT "INV_PHISTORY_PACTION_FK" 
		FOREIGN KEY("PLATE_ACTION_ID_FK") 
			REFERENCES "INV_PLATE_ACTIONS"("PLATE_ACTION_ID"), 
    CONSTRAINT "INV_PHISTORY_PLATEID_FK" 
		FOREIGN KEY("PLATE_ID_FK") 
			REFERENCES "INV_PLATES"("PLATE_ID")
			ON DELETE CASCADE,
	CONSTRAINT PHIST_FROM_LOC_FK
		FOREIGN KEY (FROM_LOCATION_ID_FK)
		REFERENCES INV_LOCATIONS (LOCATION_ID)
		ON DELETE CASCADE,
	CONSTRAINT PHIST_TO_LOC_FK
		FOREIGN KEY (TO_LOCATION_ID_FK)
		REFERENCES INV_LOCATIONS (LOCATION_ID)
		ON DELETE CASCADE,
    CONSTRAINT "INV_PLATE_HISTORY_PK" 
		PRIMARY KEY("PLATE_HISTORY_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

create sequence SEQ_INV_PLATE_HISTORY INCREMENT BY 1 START WITH 1000;

create or replace trigger TRG_PLATE_HISTORY_ID BEFORE INSERT ON INV_PLATE_HISTORY FOR EACH ROW 
begin
if :new.PLATE_HISTORY_ID is null then
  select SEQ_INV_PLATE_HISTORY.nextval into :new.PLATE_HISTORY_ID from dual;
end if;
end;
/

CREATE INDEX HISTORY_PLATE_ACTION_ID_FK_IDX ON INV_PLATE_HISTORY(PLATE_ACTION_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX HISTORY_PLATE_ID_FK_IDX ON INV_PLATE_HISTORY(PLATE_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX HISTORY_FROM_LOC_FK_IDX ON INV_PLATE_HISTORY(FROM_LOCATION_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX HISTORY_TO_LOC_FK_IDX ON INV_PLATE_HISTORY(TO_LOCATION_ID_FK) TABLESPACE &&indexTableSpaceName;