CREATE TABLE "INV_UNITS"(
	"UNIT_ID" NUMBER(4) NOT NULL,
	"UNIT_TYPE_ID_FK" NUMBER(4),
	"CONVERSION_RATIO" NUMBER, 
  "UNIT_ABREVIATION" VARCHAR2(50),
  "UNIT_NAME" VARCHAR2(50), 
  CONSTRAINT "INV_UNITS_PK" 
		PRIMARY KEY("UNIT_ID") USING INDEX TABLESPACE &&indexTableSpaceName, 
  CONSTRAINT "INV_UNIT_TYPES_UNITS_FK" 
		FOREIGN KEY("UNIT_TYPE_ID_FK") 
		REFERENCES "INV_UNIT_TYPES"("UNIT_TYPE_ID")
	)
; 

CREATE INDEX UNIT_TYPE_ID_FK_IDX ON INV_UNITS(UNIT_TYPE_ID_FK) TABLESPACE &&indexTableSpaceName;    
CREATE SEQUENCE SEQ_INV_UNITS INCREMENT BY 1 START WITH 1000;

CREATE OR REPLACE TRIGGER "TRG_INV_UNITS" BEFORE 
    INSERT 
    ON "INV_UNITS" 
    FOR EACH ROW 
    begin
		if :new.unit_ID is null then
			select seq_Inv_units.nextval into :new.unit_id from dual;
		end if;
end;

/
