CREATE TABLE INV_REQUEST_SAMPLES(
	REQUEST_ID_FK NUMBER(16),
	CONTAINER_ID_FK NUMBER(16),
	PRIMARY KEY(REQUEST_ID_FK, CONTAINER_ID_FK),
	CONSTRAINT "INV_REQSAMPLES_REQUESTID_FK"
		FOREIGN KEY("REQUEST_ID_FK")
	  REFERENCES "INV_REQUESTS"("REQUEST_ID")
    ON DELETE CASCADE,
	CONSTRAINT "INV_REQSAMPLES_CONTAINERID_FK"
		FOREIGN KEY("CONTAINER_ID_FK")
	  REFERENCES "INV_CONTAINERS"("CONTAINER_ID")
    ON DELETE CASCADE)
  ORGANIZATION INDEX;    

CREATE INDEX INV_REQSAMPLES_CONTAINERID_IDX ON INV_REQUEST_SAMPLES(CONTAINER_ID_FK) TABLESPACE &&indexTableSpaceName;
