CREATE TABLE "INV_SOLVENTS"(
	"SOLVENT_ID" NUMBER(10) NOT NULL, 
    	"SOLVENT_NAME" VARCHAR2(200) NOT NULL, 
	"COMPOUND_ID_FK" NUMBER(10), 
	CONSTRAINT "INV_SOLVENTS_COMPOUND_ID_FK" 
		FOREIGN KEY("COMPOUND_ID_FK") 
		REFERENCES "INV_COMPOUNDS"("COMPOUND_ID"), 
	CONSTRAINT "INV_SOLVENTS_PK" 
		PRIMARY KEY("SOLVENT_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;  


CREATE INDEX INV_SOLVENTS_COMPOUNDID_IDX ON INV_SOLVENTS(COMPOUND_ID_FK) TABLESPACE &&indexTableSpaceName;

CREATE SEQUENCE SEQ_INV_SOLVENTS INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;

CREATE OR REPLACE TRIGGER TRG_SOLVENTS 
    BEFORE INSERT 
    ON INV_SOLVENTS 
    FOR EACH ROW 
begin
  if :new.SOLVENT_ID is null then
    select SEQ_INV_SOLVENTS.nextval into :new.SOLVENT_ID from dual;
  end if;
end;  
/
