CREATE TABLE "INV_FORECAST" (
	"COMPOUND_ID_FK" NUMBER(10),
	"LOCATION_ID_FK" NUMBER(4),
	"AMOUNT" NUMBER(10),
		  CONSTRAINT "INV_USE_LOCATION_ID_FK"
		FOREIGN KEY("LOCATION_ID_FK")
		REFERENCES "INV_LOCATIONS"("LOCATION_ID"),
	CONSTRAINT "INV_USE_COMPOUND_ID_FK"
		FOREIGN KEY("COMPOUND_ID_FK")
		REFERENCES "INV_COMPOUNDS"("COMPOUND_ID")
	);
	
create sequence SEQ_INV_FORECAST_ID INCREMENT BY 1 START WITH 1;


CREATE UNIQUE INDEX INV_FORECAST_IDX ON INV_FORECAST (COMPOUND_ID_FK ASC,LOCATION_ID_FK ASC) TABLESPACE &&indexTableSpaceName;

