CREATE TABLE "INV_ENUMERATION"(
	"ENUM_ID" NUMBER(9) NOT NULL, 
	"ENUM_VALUE" VARCHAR2(255) NOT NULL, 
	"ESET_ID_FK" NUMBER(9) NOT NULL,
	CONSTRAINT ENUM_ESET_FK
		FOREIGN KEY (ESET_ID_FK)
		REFERENCES INV_ENUMERATION_SET (ESET_ID)
		ON DELETE CASCADE, 
    CONSTRAINT "INV_ENUMERATION_PK" 
		PRIMARY KEY("ENUM_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;
CREATE INDEX INV_ENUMERATION_ESETID_IDX ON INV_ENUMERATION(ESET_ID_FK) TABLESPACE &&indexTableSpaceName;

create sequence SEQ_INV_ENUMERATION INCREMENT BY 1 START WITH 1000;

create or replace trigger TRG_ENUM_ID BEFORE INSERT ON INV_ENUMERATION FOR EACH ROW 
begin
if :new.ENUM_ID is null then
  select SEQ_INV_ENUMERATION.nextval into :new.ENUM_ID from dual;
end if;
end;
/