CREATE TABLE "INV_GRID_POSITION"(
	"GRID_POSITION_ID" NUMBER(9) NOT NULL, 
	"GRID_FORMAT_ID_FK" NUMBER(9) NOT NULL, 
    "GRID_FILL_TEMPLATE_ID_FK" NUMBER(9), 
    "ROW_INDEX" NUMBER(6) NOT NULL, 
    "COL_INDEX" NUMBER(6) NOT NULL, 
    "ROW_NAME" VARCHAR2(50), 
    "COL_NAME" VARCHAR2(50), 
    "SORT_ORDER" NUMBER(6) NOT NULL, 
    "NAME" VARCHAR2(50),
    CONSTRAINT GRID_POSITION_FORMAT_FK
		FOREIGN KEY (GRID_FORMAT_ID_FK)
		REFERENCES INV_GRID_FORMAT (GRID_FORMAT_ID)
		ON DELETE CASCADE, 
    CONSTRAINT "INV_GRID_POSITION_PK" 
		PRIMARY KEY("GRID_POSITION_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

CREATE INDEX GP_GRID_FORMAT_ID_FK ON INV_GRID_POSITION(GRID_FORMAT_ID_FK) TABLESPACE &&indexTableSpaceName;

create sequence SEQ_INV_GRID_POSITION INCREMENT BY 1 START WITH 1000;

create or replace trigger TRG_GRID_POSITION_ID BEFORE INSERT ON INV_GRID_POSITION FOR EACH ROW 
begin
if :new.GRID_POSITION_ID is null then
  select SEQ_INV_GRID_POSITION.nextval into :new.GRID_POSITION_ID from dual;
end if;
end;
/

