CREATE TABLE "INV_COUNTRY"(
	"COUNTRY_ID" NUMBER(4) NOT NULL,
	"COUNTRY_NAME" VARCHAR2(255),
    CONSTRAINT "INV_COUNTRIES_PK"
		PRIMARY KEY("COUNTRY_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

CREATE SEQUENCE SEQ_INV_COUNTRY INCREMENT BY 1 START WITH 1000 MAXVALUE 99999 MINVALUE 1 NOCYCLE NOCACHE ORDER;

CREATE OR REPLACE TRIGGER "TRG_INV_COUNTRY_ID"
    BEFORE INSERT
    ON "INV_COUNTRY"
    FOR EACH ROW
    begin
		if :new.Country_ID is null then
			select seq_Inv_Country.nextval into :new.Country_ID from dual;
		end if;
end;
/