CREATE TABLE "INV_DOCS"(
   	"DOC_ID" NUMBER(4) NOT NULL, 
   	"TABLE_NAME" VARCHAR2(200),
   	"FIELD_NAME" VARCHAR2(200),
   	"FIELD_VALUE" VARCHAR2(200),
   	"DOC_TYPE_ID_FK" NUMBER(4),
   	"DOC" CLOB, 
   	"DATE_CREATED" DATE,
   	CONSTRAINT "INV_DOCS_PK" 
		PRIMARY KEY("DOC_ID") USING INDEX TABLESPACE &&indexTableSpaceName,
    CONSTRAINT "INV_DOCS_DOCTYPEID_FK" 
	FOREIGN KEY("DOC_TYPE_ID_FK") 
	   	REFERENCES "INV_DOC_TYPES"("DOC_TYPE_ID")) 
	LOB (DOC) STORE AS(
	DISABLE STORAGE IN ROW
	TABLESPACE &&lobsTableSpaceName
	NOCACHE
	CHUNK 2K
	PCTVERSION 10
	STORAGE(INITIAL &&lobXML NEXT &&lobXML)
	);

CREATE INDEX DOC_TYPE_ID_FK_IDX ON INV_DOCS(DOC_TYPE_ID_FK) TABLESPACE &&indexTableSpaceName;

CREATE SEQUENCE SEQ_DOC_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER "TRG_INV_DOCS_ID"
    BEFORE INSERT
    ON "INV_DOCS"
    FOR EACH ROW
BEGIN
	if :new.doc_id is null then
		select SEQ_DOC_ID.nextval into :new.doc_id from dual;
	end if;
END;
/
