CREATE TABLE "INV_CONTAINER_BATCH_FIELDS"(
	"FIELD_ID" NUMBER(4) NOT NULL, 
	"FIELD_NAME" VARCHAR2(50) NOT NULL, 
	"DISPLAY_NAME" VARCHAR2(50) NOT NULL, 
	"SORT_ORDER" NUMBER(4) NOT NULL,
    CONSTRAINT "INV_CONBATCHFIELDS_PK" 
		PRIMARY KEY("FIELD_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;  

CREATE SEQUENCE SEQ_INV_CON_BATCH_FIELDS INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 100 ORDER;

 
create or replace trigger TRG_CON_BATCH_FIELDS  BEFORE INSERT ON INV_CONTAINER_BATCH_FIELDS FOR EACH ROW 
begin
if :new.FIELD_ID is null then
  select SEQ_INV_CON_BATCH_FIELDS.nextval into :new.FIELD_ID from dual;
end if;
end;
/

