CREATE TABLE "INV_WELLS"(
	"WELL_ID" NUMBER(16) NOT NULL, 
	"WELL_FORMAT_ID_FK" NUMBER(9), 
	"PLATE_ID_FK" NUMBER(9), 
	"PLATE_FORMAT_ID_FK" NUMBER(9), 
 	"GRID_POSITION_ID_FK" NUMBER(9), 
 	"WEIGHT" NUMBER, 
 	"WEIGHT_UNIT_FK" NUMBER(9), 
 	"QTY_INITIAL" NUMBER, 
 	"QTY_REMAINING" NUMBER, 
 	"QTY_UNIT_FK" NUMBER(9), 
 	"SOLVENT_ID_FK" NUMBER(9), 
	"SOLVENT_VOLUME" NUMBER, 
	"SOLVENT_VOLUME_INITIAL" NUMBER,
 	"SOLVENT_VOLUME_UNIT_ID_FK" NUMBER(9), 
  "SOLUTION_VOLUME" NUMBER,
 	"CONCENTRATION" NUMBER, 
 	"CONC_UNIT_FK" NUMBER(9),
 	"MOLAR_AMOUNT" NUMBER,
 	"MOLAR_UNIT_FK" NUMBER(9,0),
 	"MOLAR_CONC" NUMBER,
	"FIELD_1" VARCHAR2(2000), 
	"FIELD_2" VARCHAR2(2000),
	"FIELD_3" VARCHAR2(2000), 
	"FIELD_4" VARCHAR2(2000), 
	"FIELD_5" VARCHAR2(2000), 
	"DATE_1" DATE, 
	"DATE_2" DATE,
  CONSTRAINT "INV_WELLS_GRIDPOS_FK" 
		FOREIGN KEY("GRID_POSITION_ID_FK") 
		REFERENCES "INV_GRID_POSITION"("GRID_POSITION_ID"), 
  CONSTRAINT "INV_WELLS_PFORMAT_FK" 
		FOREIGN KEY("PLATE_FORMAT_ID_FK") 
		REFERENCES "INV_PLATE_FORMAT"("PLATE_FORMAT_ID"), 
  CONSTRAINT "WELLS_PLATES_FK"
		FOREIGN KEY (PLATE_ID_FK)
		REFERENCES "INV_PLATES"("PLATE_ID")
		ON DELETE CASCADE,
  CONSTRAINT "WELLS_CONC_UNIT_FK"
		FOREIGN KEY ("CONC_UNIT_FK")
		REFERENCES "INV_UNITS"("UNIT_ID"),
  CONSTRAINT "WELLS_MOLAR_UNIT_FK"
		FOREIGN KEY ("MOLAR_UNIT_FK")
		REFERENCES "INV_UNITS"("UNIT_ID"),
  CONSTRAINT "WELLS_QTY_UNIT_FK"
		FOREIGN KEY ("QTY_UNIT_FK")
		REFERENCES "INV_UNITS"("UNIT_ID"),
  CONSTRAINT "WELLS_WEIGHT_UNIT_FK"
		FOREIGN KEY ("WEIGHT_UNIT_FK")
		REFERENCES "INV_UNITS"("UNIT_ID"),		
  CONSTRAINT "WELLS_SOLVENTUNITID_FK" 
		FOREIGN KEY("SOLVENT_VOLUME_UNIT_ID_FK")
	 	REFERENCES "INV_UNITS"("UNIT_ID"),
  CONSTRAINT "WELLS_SOLVENTID_FK" 
		FOREIGN KEY("SOLVENT_ID_FK") 
		REFERENCES "INV_SOLVENTS"("SOLVENT_ID"),
  CONSTRAINT "INV_WELLS_PK" 
		PRIMARY KEY("WELL_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;

create sequence SEQ_INV_WELLS INCREMENT BY 1 START WITH 1000;

CREATE INDEX WELLS_GRID_POSITION_ID_FK_IDX ON INV_WELLS(GRID_POSITION_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX WELLS_WELLS_PLATES_FK_IDX ON INV_WELLS(PLATE_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX WELLS_CONC_UNIT_FK_IDX ON INV_WELLS(CONC_UNIT_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX WELLS_MOLAR_UNIT_FK_IDX ON INV_WELLS(MOLAR_UNIT_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX WELLS_QTY_UNIT_FK_IDX ON INV_WELLS(QTY_UNIT_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX WELLS_WEIGHT_UNIT_FK_IDX ON INV_WELLS(WEIGHT_UNIT_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX WELLS_PLATE_FORMAT_FK_IDX ON INV_WELLS (PLATE_FORMAT_ID_FK) TABLESPACE &&indexTableSpaceName; 
CREATE INDEX WELLS_WELL_FORMAT_ID_FK_IDX ON INV_WELLS (WELL_FORMAT_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX WELLS_SOLVENTID_FK_IDX ON INV_WELLS(SOLVENT_ID_FK) TABLESPACE &&indexTableSpaceName;
CREATE INDEX SOLVENT_VOLUME_UNIT_ID_FK_IDX ON INV_WELLS(SOLVENT_VOLUME_UNIT_ID_FK) TABLESPACE &&indexTableSpaceName;

create or replace trigger TRG_WELL_ID BEFORE INSERT ON INV_WELLS FOR EACH ROW 
begin
if :new.WELL_ID is null then
  select SEQ_INV_WELLS.nextval into :new.WELL_ID from dual;
end if;
end;
/

