CREATE TABLE INV_PROJECT_JOB_INFO (
  PROJECT_NO VARCHAR2(8) NOT NULL,
  PROJECT_DESCRIPTION VARCHAR2(50) NOT NULL,
  JOB_NO VARCHAR2(4) NOT NULL,
  JOB_DESCRIPTION VARCHAR2(50) NOT NULL,
  PRIMARY KEY(PROJECT_NO, JOB_NO) USING INDEX TABLESPACE &&indexTableSpaceName
  );