CREATE TABLE "INV_GRID_FILL_TEMPLATE"(
    "GRID_FILL_TEMPLATE_ID" NUMBER(9) NOT NULL, 
    "FILL_START_CORNER" NUMBER(9) NOT NULL, 
    "FILL_DIRECTION" NUMBER(9) NOT NULL, 
    "FILL_ALTERNATING" NUMBER(1) NOT NULL, 
    CONSTRAINT "INV_GRID_FILL_TEMPLATE_PK" 
    PRIMARY KEY("GRID_FILL_TEMPLATE_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	)
;  

create sequence SEQ_INV_GRID_FILL_TEMPLATE INCREMENT BY 1 START WITH 1000;

create or replace trigger TRG_GRID_FILL_TEMPLATE BEFORE INSERT ON INV_GRID_FILL_TEMPLATE FOR EACH ROW 
begin
if :new.GRID_FILL_TEMPLATE_ID is null then
  select SEQ_INV_GRID_FILL_TEMPLATE.nextval into :new.GRID_FILL_TEMPLATE_ID from dual;
end if;
end;
/

