CREATE TABLE "INV_XMLDOC_TYPES"(
    	"XMLDOC_TYPE_ID" NUMBER(4) NOT NULL, 
	"TYPE_NAME" VARCHAR2(100), 
	CONSTRAINT "INV_XMLDOC_TYPE_PK" 
		PRIMARY KEY("XMLDOC_TYPE_ID") USING INDEX TABLESPACE &&indexTableSpaceName
	);

CREATE SEQUENCE SEQ_INV_XMLDOC_TYPE INCREMENT BY 1 START WITH 1 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;

CREATE OR REPLACE TRIGGER TRG_XMLDOC_TYPE
    BEFORE INSERT
    ON "INV_XMLDOC_TYPES"
    FOR EACH ROW 
begin
  if :new.XMLDOC_TYPE_ID is null then
    select SEQ_INV_XMLDOC_TYPE.nextval into :new.XMLDOC_TYPE_ID from dual;
  end if;
end;    
/

