CREATE TABLE "INV_PICKLIST_TYPES"(
    "PICKLIST_TYPE_ID" NUMBER(4) NOT NULL,
    "PICKLIST_TYPE_NAME" VARCHAR2(30) NOT NULL,
    "PICKLIST_TYPE_STYLE" VARCHAR2(30) NOT NULL,
    CONSTRAINT "PICKLIST_TYPES_PK"
        PRIMARY KEY("PICKLIST_TYPE_ID") USING INDEX TABLESPACE &&indexTableSpaceName
)
;

ALTER TABLE INV_PICKLIST_TYPES ADD CONSTRAINT PicklistTypes_U UNIQUE (PICKLIST_TYPE_NAME);

CREATE SEQUENCE SEQ_INV_PICKLIST_TYPES INCREMENT BY 1 START WITH 1000 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE;

CREATE OR REPLACE TRIGGER "TRG_INV_PICKLIST_TYPES"
    BEFORE INSERT
    ON "INV_PICKLIST_TYPES"
    FOR EACH ROW
    begin
        if :new.Picklist_Type_ID is null then
            select seq_Inv_Picklist_Types.nextval into :new.Picklist_Type_ID from dual;
        end if;
    end;
/
