CREATE TABLE "INV_CUSTOM_CPD_FIELD_VALUES"(
    "CUSTOM_CPD_FIELD_VALUE_ID" NUMBER(9) NOT NULL,
    "PICKLIST_ID_FK" NUMBER(8) NOT NULL,
    "CUSTOM_FIELD_ID_FK" NUMBER(4) NOT NULL,
    "COMPOUND_ID_FK" NUMBER(9) NOT NULL,
    CONSTRAINT "INV_CUSTOM_CPD_FIELD_VALUES_PK"
        PRIMARY KEY("CUSTOM_CPD_FIELD_VALUE_ID") USING INDEX TABLESPACE &&indexTableSpaceName
)
;

ALTER TABLE "INV_CUSTOM_CPD_FIELD_VALUES" ADD CONSTRAINT INV_CUSTOM_CPD_FLD_VAL_FK1 FOREIGN KEY(PICKLIST_ID_FK) REFERENCES &&schemaName..INV_PICKLISTS(PICKLIST_ID);
ALTER TABLE "INV_CUSTOM_CPD_FIELD_VALUES" ADD CONSTRAINT INV_CUSTOM_CPD_FLD_VAL_FK2 FOREIGN KEY(CUSTOM_FIELD_ID_FK) REFERENCES &&schemaName..INV_CUSTOM_FIELDS(CUSTOM_FIELD_ID);

CREATE SEQUENCE SEQ_INV_CTM_CPD_FIELD_VALUES INCREMENT BY 1 START WITH 1000 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE;

CREATE OR REPLACE TRIGGER "TRG_INV_CTM_CPD_FIELD_VALUES"
    BEFORE INSERT
    ON "INV_CUSTOM_CPD_FIELD_VALUES"
    FOR EACH ROW
    begin
        if :new.Custom_Cpd_Field_Value_ID is null then
            select seq_Inv_Ctm_Cpd_Field_Values.nextval into :new.Custom_Cpd_Field_Value_ID from dual;
        end if;
    end;
/
